### ISSUE TITLE
Set up build workflow

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#1]
We will move a static commit of @dberlow and @sannorozco's sources to the `build-the-build` branch so that we can begin the GH Actions remote build workflow work as development continues in the upstream repository.

Source state at repository transfer time: https://github.com/FontBureau/fb-GoogleSansFlex/commit/0d18f71aa89224910bdf32020cd70ec9f58f127e

Upstream FontBureau/fb-GoogleSansFlex branch: `latin-european-round`

@MariannaPaszkowska

**Comment by belluzj** [comment]
Thanks Chris, we'll start looking into this this week.

**Comment by belluzj** [comment]
For any branch on this repository, make sure that we compile fonts with fontmake and serve a ZIP that FontBureau can download.

**Comment by chrissimpkins** [comment]
I have an open question for the Font Bureau team on their upstream repo re the latest source push site that you can see the recent sparse master updates.  Will push here once we understand where to obtain the sources.
