### ISSUE TITLE
Is Python 3.8 dependency mandatory?

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#10]
Is the Python 3.8 version used in the .github/workflows/build.yaml configuration an actual max cPython version or is this just not updated in the auto-gen tooling?  It would be nice to push this to the most recently released cPy version that is supported in the pipeline.

**Comment by madig** [comment]
It wasn't updated probably, using 3.10 (and 3.11 when it's ready) would be preferable.

**Comment by chrissimpkins** [comment]
Ty!  I'm going to update the workflow to our new multi-CPU, more RAM envs and will attempt a Py update with those changes.

**Comment by chrissimpkins** [comment]
Can confirm that cPy 3.10 works (#15)

**Comment by chrissimpkins** [comment]
I missed this instance https://github.com/googlefonts/googlesans-flex/blob/d8815f817d263873d3b5aedca6437deaf5242b1e/Makefile#L28

Do we need that @madig? (https://github.com/googlefonts/googlesans-flex/commit/0c6c97b5df8798346242bad139cf907b69532937)

**Comment by madig** [comment]
No, I just wanted to match what the CI was doing. You can remove it.
