### ISSUE TITLE
opsz 144, wdth 25, wght 400 Review

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#100]
**opsz 144, wdth 25, wght 400 **
Here's the review of GSF Roman, GRAD0 and ROND0, ascii set. Font GoogleSansFlex-Alpha1.0[ROND,opsz,wdth,wght]-VF.ttf from [here.](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/fonts/GoogleSansFlex-Alpha1.0%5BROND%2Copsz%2Cwdth%2Cwght%5D-VF.ttf)

**Feedback**

- [x] `@` - please double-check the contrast in the ring.
<img width="130" alt="Screenshot 2022-12-08 at 5 24 54 PM" src="https://user-images.githubusercontent.com/22956348/206485477-f1a32abc-7e83-44dc-abdf-9329617d2d92.png">

- [x] `f` - please revise the bar on the left side, is appears slightly too short. 

<img width="238" alt="Screenshot 2022-12-08 at 5 26 53 PM" src="https://user-images.githubusercontent.com/22956348/206485978-8a42820e-1233-4e81-a99b-d7b4e8072463.png">

**Comment by dberlow** [comment]
All reviewed, edited and committed FB repo, (NOT FB-wip).

**Comment by MariannaPaszkowska** [comment]
- `@` - approved, thank you!

<img width="660" alt="Screenshot 2022-12-15 at 2 56 19 PM" src="https://user-images.githubusercontent.com/22956348/207864638-00f2c376-fc3d-43b8-93f5-1dd68fc03bad.png">

- `f` `t` - please double-check the horizontal bar. In relationship with the `t`, the bar in the `f` looks slightly longer.

- [x] `t` - please double-check the spacing.

**Comment by tiroj** [comment]
Can someone explain why this is designated ‘wdth 25’?

**Comment by dberlow** [comment]
At Google’s request, we use the width of opsz 144.The initial opsz144, wdth25, wght100 design was made about 1/4 the width of the opsz wdth100 wght100.Then it was determined that that was not condensed enough, but the value was left the same.

**Comment by tiroj** [comment]
Ah, it’s the **wght 100** aspect that I was missing. I assumed that the wdth scale would be related to the ‘Regular’ wght 400 design, not to the lightest weight. Thanks.

**Comment by dberlow** [comment]
My mistake! The wght value we calculated on was 400! Not 100!On Dec 15, 2022, at 1:03 PM, John Hudson ***@***.***> wrote:﻿
Ah, it’s the wght 100 aspect that I was missing. I assumed that the wdth scale would be related to the ‘Regular’ wght 400 design, not to the lightest weight. Thanks.

**Comment by tiroj** [comment]
Oh, that makes more sense in terms of the approach, but are these really 25% (or even narrower?) of the width of the opsz 144 wdth 100 wght 400 design? Based on typical ‘normal’ proportions, I would have guessed these are somewhere around 50%.
<img width="667" alt="image" src="https://user-images.githubusercontent.com/5614500/207982295-7f642b06-c567-4621-b679-03c853be83e6.png">

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates!
