### ISSUE TITLE
Where would check/no-open-corners fit among public fontbakery profiles?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/googlesans-flex#1014]
https://github.com/googlefonts/googlesans-flex/blob/8fdf84be01338ef3888925cd4ceeb1805dee0c50/qa/checks/sources.py#L235

I am opening this issue here because the font is under NDA, so I should not mention it on the public fontbakery issue tracker. (see https://github.com/fonttools/fontbakery/pull/4809#discussion_r1707258249)

I have initially placed the check in the UFO "profile" (which will soon not exist anymore, according to the plan outlined at https://github.com/fonttools/fontbakery/issues/4801). Most of it will be included in the Universal profile. This specific case of the no-open-corners check, though, illustrates one of the main reasons why I proposed reorganizing the profiles. It would have to be placed on a separate repo as it typically does not apply to all projects.

One caveat though is that it does not seem to be "vendor-specific" as well. If I understood it correctly, it would be better described as project specific instead.

I'm considering the idea of placing it in Universal, but flagged as "optional", so it would not run by default, but would be listed to users as optional and would require using "-c checkid" to run it. Does it make sense?

**Comment by RickyDaMa** [comment]
Related to #983 

Yes, this check should definitely be optional and **opt-in** one way or another. Even if that means it's not included in any profiles, the fact that it's in upstream Fontbakery means people can use it (granted it's probably not very discoverable).

Any mechanism on top of that to aid discovery would be a bonus, though that's not particularly relevant for GS Flex specifically, as adding the open source replacement to our `check-sources` profile is easy and we already know the check exists
