### ISSUE TITLE
Language coverage: new errors about Igbo & Yoruba

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#1016]
From [here](https://github.com/googlefonts/googlesans-flex/actions/runs/10183450341/job/28815724080#step:10:1118):

```
Igbo:
    PASS: All base glyphs were present in the font
    PASS: All mark glyphs were present in the font
    PASS: All auxiliary glyphs were present in the font
    PASS: No unattached mark glyphs were produced shaping the text 'A Ụ T SH ṅ N NW L m ẹ ch sh nw Ị GH i H M z ụ gb d KW f ny g w o E P B I kw u r K p gh gw kp GB v U ọ j k W l t Y J KP a n R S e G h D b y ị s V Ṅ Ẹ F NY CH Ọ GW O Z'
    PASS: No unattached mark glyphs were produced shaping the text 'ị́Ị́ị̀Ị̀m̀M̀ọ́Ọ́ọ̀Ọ̀ụ́Ụ́ụ̀Ụ̀'
    WARN: No variant glyphs were found for .notdef
  PASS Hausa
  PASS Vietnamese
  Yoruba:
    FAIL: Some base glyphs were missing: Ɔ̀, Ɔ́, Ɛ, Ɛ̀, Ɛ́, ɔ̀, ɔ́, ɛ, ɛ̀, ɛ́
    PASS: All mark glyphs were present in the font
    WARN: Some auxiliary glyphs were missing: Ɔ̀, Ɔ́, Ɛ, Ɛ̀, Ɛ́, ɔ̀, ɔ́, ɛ, ɛ̀, ɛ́
    FAIL: Shaper produced a .notdef
    FAIL: Shaper produced a .notdef
```

Currently unsure what's changed to cause the regression here (no source changes; no dependency changes that should matter), but Octavio's confirmed that the flagged problems are present in the sources, so we should probably work on fixing them.

**Comment by RickyDaMa** [comment]
From Octavio:

> the problem is that those glyphs were not requested for v2.3, and I'm not 100% sure if they will be requested for 3.0 so there is no way for me to fix that. Are you sure that in the previous round shaperglot was checking them?? Maybe it was just checking a partial set of Yoruba?

**Comment by chrissimpkins** [comment]
**Igbo**: _WARN no variant glyphs were found for .notdef_

what does this mean?

**Comment by chrissimpkins** [comment]
**Yoruba**: _Some base glyphs were missing:_ Ɔ̀, Ɔ́, Ɛ, Ɛ̀, Ɛ́, ɔ̀, ɔ́, ɛ, ɛ̀, ɛ́

My understanding of the required and auxilary glyphs in Yoruba:

Exemplars: a á à b d e é è ẹ {ẹ́} {ẹ̀} f g {gb} h i í ì j k l m ḿ {m̀} n ń ǹ o ó ò ọ {ọ́} {ọ̀} p r s ṣ t u ú ù w y
Auxilary: c q v x z

Perhaps we have a bug in the shaperglot check?

I reached out to @simoncozens about it.

**Comment by chrissimpkins** [comment]
@NeilSureshPatel possible to confirm the above Yoruba exemplars list? This is coming from the SSA lang support Doc that I drafted and you reviewed last year.

**Comment by chrissimpkins** [comment]
Simon told me that we have two Yoruba exemplar definitions.  

There is a default for Yoruba that is used in Nigeria: 

https://github.com/googlefonts/lang/blob/main/Lib/gflanguages/data/languages/yo_Latn.textproto

and a second definition for Yoruba that is used in Benin:

https://github.com/googlefonts/lang/blob/main/Lib/gflanguages/data/languages/yo_Latn_BJ.textproto

Something must have changed to force the tool to use the Benin version rather than the Nigeria version.  I've asked if it is possible to selectively test against the `yo_Latn.textproto` definition.  The original Yoruba lang support goal was to support Nigerian users.

**Comment by NeilSureshPatel** [comment]
@chrissimpkins that looks correct. Yes, Benin orthography is different, though I am not sure why the tool is checking yo_Latn_BJ. has that tag been added to the run command? It should only check the tags that are listed.

**Comment by chrissimpkins** [comment]
Here are additional diagnostics from Simon:

Whoa. I see the problem. Not only do `yo_Latn` and `yo_Latn_BJ` have the same name they also have the same language ID (yo_Latn) in those sources. So they're colliding within the gflanguages model as soon as they are loaded; we're basically doing:

```
lang["yo_Latn"] = { ... }  # Nigerian
lang["yo_Latn"] = { ... }  # Beninformat_text_overflowformat_text_wrap
```

So shaperglot isn't even seeing the Nigerian Yoruba. And that's probably why our test for duplicated language names aren't seeing them either, because the Nigerian is completely overwritten.

**Comment by NeilSureshPatel** [comment]
Oh wow, so it overwrites the first with the second listing. Looks like the head of the textproto might have been copy and pasted to make the BJ entry. Looks like an easy fix though.

**Comment by chrissimpkins** [comment]
> @chrissimpkins that looks correct. Yes, Benin orthography is different, though I am not sure why the tool is checking yo_Latn_BJ. has that tag been added to the run command? It should only check the tags that are listed.

Thanks Neil!  Is Yoruba widely used in Benin?

**Comment by NeilSureshPatel** [comment]
Benin has the second largest Yoruba speaking population about 1.6 million people. It is a small fraction of the population in Nigeria which is about 42 million people.

**Comment by chrissimpkins** [comment]
> Here are additional diagnostics from Simon:
> 
> Whoa. I see the problem. Not only do `yo_Latn` and `yo_Latn_BJ` have the same name they also have the same language ID (yo_Latn) in those sources. So they're colliding within the gflanguages model as soon as they are loaded; we're basically doing:
> 
> ```
> lang["yo_Latn"] = { ... }  # Nigerian
> lang["yo_Latn"] = { ... }  # Beninformat_text_overflowformat_text_wrap
> ```
> 
> So shaperglot isn't even seeing the Nigerian Yoruba. And that's probably why our test for duplicated language names aren't seeing them either, because the Nigerian is completely overwritten.

This issue should be addressed by https://github.com/googlefonts/lang/pull/156

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa it seems that there is a new release with a fix already: https://github.com/googlefonts/lang/releases/tag/v0.6.3

**Comment by belluzj** [comment]
Needed to allow Octavio to branch off and keep working (also the other PR to update the Glyphs.app sources)

For now, Marianna has already prepared a branch with the updated Glyphs.app sources.

**Comment by schriftgestalt** [comment]
It might be useful to build a language sidebar file for Glyphs.app. That way the designers can see/add missing glyphs. 
It would be good if that file would be in sync with the shaperglot requirement.

**Comment by Hoolean** [comment]
This [has appeared again](https://github.com/googlefonts/googlesans-flex/actions/runs/10700211106/job/29663693888) for Igbo on `main`, @RickyDaMa and I are taking a look

**Comment by RickyDaMa** [comment]
Looks like the shaperglot v0.6.0 has updated its requirements for Igbo, here's the full report for just that language:

```
$ shaperglot check fonts/variable/GoogleSansFlex\[GRAD\,ROND\,opsz\,slnt\,wdth\,wght\].ttf ig_Latn
Font nearly supports language 'ig_Latn'
 * FAIL: Shaper produced a .notdef

To add full support to nearly-supported languages:
 * Add codepoint: Ŋ
```

**Comment by RickyDaMa** [comment]
Igbo was reported supported by shaperglot v0.5.1 on the same TTF

**Comment by chrissimpkins** [comment]
> It might be useful to build a language sidebar file for Glyphs.app. That way the designers can see/add missing glyphs. It would be good if that file would be in sync with the shaperglot requirement.

I really like this idea.  We could design this to support the prioritized languages in the brand font program. We already support this for the expressive catalog with e.g., Latin Core, Plus, Pro I believe.

**Comment by chrissimpkins** [comment]
Do we currently believe that we are missing anything to support Igbo or Yoruba? Or this is about fixing the shaperglot checks because they are reporting incorrect results?

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins Shaperglot v0.6.4 reports Ŋ s an auxiliary character in Igbo [ig_Latn] and not required for Yoruba. 
Related #234
