### ISSUE TITLE
Avoid automatic decomposition for more components

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#1018]
As part of [our experiments with GS Flex file size](https://docs.google.com/document/d/1DBDuozATfJwrU3iD5TQFMQckab8MdCfclu6sGlMMCd4/edit?usp=sharing), we identified [some glyphs that are automatically decomposed by the pipeline](https://docs.google.com/spreadsheets/d/1hn46LgquIAnpYQ8s-PacGnAFv0ikveBwKqAPPP0VcSQ/edit?usp=sharing) but which could be left as composed to shrink the size of the final font.

In general, we suspect that any glyph containing a component used in at least one other glyph should be compiled as composed, given Flex's large 'point data' to 'rest-of-data' ratio for glyphs.

For most glyphs on the list, this can be implemented by marking their constituent component glyphs as exportable in Glyphs, and re-importing 🚀

**Comment by chrissimpkins** [comment]
> For most glyphs on the list, this can be implemented by marking their constituent component glyphs as exportable in Glyphs, and re-importing 

So, a task for @octaviopardo and team? Who would handle this fix @MariannaPaszkowska?

**Comment by chrissimpkins** [comment]
Adding as a sub-issue of our general file size reduction tracker

**Comment by MariannaPaszkowska** [comment]
Status: automatic checks are added. Only type design work left here, if anything
