### ISSUE TITLE
Add automatic checks for automatic decomposition

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#1019]
This is a production/QA companion issue for #1018 to brainstorm how we can use Font Bakery to catch any automatic decomposition that may sneak into the project.

## Ideas

Source checks:

 * Check for any glyphs that are on the 'skip' list but which are referenced by unskipped glyphs as a component more than once
   * Would catch: /f_f_j, /f_f_b, etc
 * Check for any glyphs that apply near-identity transforms to their components
   * Would catch: /sterling.tf, etc

TTF checks:

 * Check for any glyph that has been automatically decomposed and is not in a configurable list of 'allowed' glyphs
   * Would catch: anything else, but not /questiondown and other necessary decompositions

**Comment by chrissimpkins** [comment]
The Android fallback stack is a higher priority through EOY.  IMO DaMa can work on this as time allows around that work.  Or we can reach out to Felipe or Simon to see if they have time for this.
