### ISSUE TITLE
Update the sources

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1021]
It seems that the sources in the main are not v 2.003. Let's update that and see if we can automate that process.

**Comment by RickyDaMa** [comment]
Would you have it be part of the import workflow? So that the design sources that are being imported from are updated as part of the PR

I've been wanting this for a while and it shouldn't be that bad to add

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa yes, that would be great!

**Comment by RickyDaMa** [comment]
See #1023 :)
