### ISSUE TITLE
Address new shaperglot fail on Igbo

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1030]
We passed the tests for Igbo earlier and now we have a new fail, as it seems. This is the latest shaperglot report:

"  Igbo:
    PASS: All base glyphs were present in the font
    PASS: All mark glyphs were present in the font
    PASS: All auxiliary glyphs were present in the font
    PASS: No unattached mark glyphs were produced shaping the text 't ṅ b v ọ O ẹ Ẹ A Z r gw s K H NY m F n P B GH ch h SH T gh f ny L KP E S M u gb V CH w Ọ J e o Ị U G D i ụ p R GB g kw NW N l kp W Y z GW d Ụ Ṅ KW I ị k j nw a y sh'
    PASS: No unattached mark glyphs were produced shaping the text 'ị́Ị́ị̀Ị̀m̀M̀ọ́Ọ́ọ̀Ọ̀ụ́Ụ́ụ̀Ụ̀'
    FAIL: Shaper produced a .notdef
    FIX: Add codepoint Ŋ
"
See: https://github.com/googlefonts/googlesans-flex/actions/runs/10791331937/job/29929116054#step:10:1135 

We need to check if it is mandatory to add those code glyphs:
0x014A (LATIN CAPITAL LETTER ENG) | Ŋ
0x014B (LATIN SMALL LETTER ENG) | ŋ

or if the new test is too strict.

**Comment by MariannaPaszkowska** [comment]
response from @NeilSureshPatel 
_The Eng is not one of the exemplars for Igbo. It is one of the auxiliary characters through. I thought these were not supposed to be a hard fail in shaperglot. Interestingly it didn't produce the same error for the lowercase eng. It makes me think there is something wrong with the either the test or setup._

@simoncozens Are shaperglot's Igbo definitions too strict now?
cc @RickyDaMa

**Comment by simoncozens** [comment]
Shaperglot is currently checking for unencoded variations for both base and auxiliary glyphs. I'll alter the UnencodedVariants check to only do the test if the glyph is in the font, and rely on the orthographies check to tell us if it should be present.

**Comment by simoncozens** [comment]
Done it, new version 0.6.1 released yesterday. :-)

**Comment by Hoolean** [comment]
Super, thanks Simon :)

**Comment by Hoolean** [comment]
I'll re-run Shaperglot on `main` and see how it looks

**Comment by Hoolean** [comment]
[We're green!](https://github.com/googlefonts/googlesans-flex/actions/runs/10795765289/job/30055973648#step:12:1103) ✅ Thanks all

![image](https://github.com/user-attachments/assets/3adc19cb-fadc-49e2-ac76-8e9b9ae64ddc)
*(or grey, but it's a tick at least)*
