### ISSUE TITLE
Contour bug in the "p" in the workspace slices, in ExtraExpanded font (not in Italic). 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1034]
<img width="1036" alt="Screenshot 2024-09-10 at 6 05 29 PM" src="https://github.com/user-attachments/assets/c1b16724-5cbb-4635-8915-8d6258da0168">

<img width="693" alt="Screenshot 2024-09-10 at 6 09 02 PM" src="https://github.com/user-attachments/assets/4412d3c9-5716-4455-a88f-39b9045694c8">

Seems like something when wrong when we were slicing the design space.

**Comment by Hoolean** [comment]
Very strange; potentially a bug in the varLib instancer (or the way that we're holding it)

**Comment by Hoolean** [comment]
I think we instance the workspace fonts at slightly different coordinates to those in the above screenshot, but examining the full VF at these corrected positions made no difference:

| Axis | Above | → Corrected |
|-|-:|-:|
|Optical Size|144|
|Width|151|150|
|Weight|1000|900|
|Grade|0|
|Roundness|0|
|Slant|0|

**Comment by Hoolean** [comment]
(i.e. same issue, still only in workspace, but the counter size now matches)

**Comment by Hoolean** [comment]
I just reviewed our instancing code and notice that we remove overlaps:

https://github.com/googlefonts/googlesans-flex/blob/fdfa453dc0a6bb1dfaef8440ab6c511d8ee38fd9/scripts/cut_instances.py#L148-L160

As we are instancing partial VFs instead of statics, we should consider removing this; it could be where the bug is too.

Let's try instancing with and without the flag, and see if the issue is still present. If this resolves the issue, _and_ we can reproduce by feeding the raw outlines into the overlap removal code in isolation, then we know that this is where the bug is, and that the varLib instancer is not at fault :)

**Comment by Hoolean** [comment]
I cut instances from the v2.003 release with our normal build process but without `--remove-overlaps`, and the issue is still present:

![P with bug](https://github.com/user-attachments/assets/a6ec40bf-f257-4f78-944f-96a0f7743935)

Looks like the issue may be in `varLib.instancer` after all...

**Comment by Hoolean** [comment]
I've managed to isolate it a bit further: the issue disappears for `p` and `đ` when running `varLib.instancer` with `--no-optimize`.

This flag disables IUP optimisation, which means that IUP optimisation is causing this issue. This could be happening:
- Directly, through a bug in the optimisation code itself; or
- Indirectly, through triggering a separate bug in `varLib` with the deltas it produces or the way in which it is invoked.

**NOTE:** This is separate to the IUP tolerance testing we have been doing in #1029; our current release process uses gftools/fontmake's default.

**Comment by Hoolean** [comment]
Okay, I think I now have the root problem! I need to confirm it in a debugger, but assuming I do then I will begin preparing a fontTools patch tomorrow.

## Bug

To produce inferred deltas that will be correct given [OpenType's `gvar` semantics](https://learn.microsoft.com/en-us/typography/opentype/spec/gvar#inferred-deltas-for-un-referenced-point-numbers), fontTool's IUP optimisation module [checks the equality of some points](https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/iup.py#L57). Unfortunately, this happens **before** the points are rounded, whereas the point comparison that happens at runtime will occur **after** the points are rounded (as is necessary to serialise `glyf`), which leads to diverging semantics and so diverging and incorrect implied deltas.

I suspect this has gone undetected as the subsetter normally works with rounded points; in the rarer case that partial VF instancing is occurring with a different default position, however, `varLib.instancer` will calculate and [apply the relevant deltas to the font's original coordinates](https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/instancer/__init__.py#L881) to effect the new default position, which leads to unrounded points in memory.

**Comment by Hoolean** [comment]
Reported at fonttools/fonttools#3634, draft PR incoming
