### ISSUE TITLE
Visually review the interpolation of the workspace fonts

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1035]
Fonts to review:

- [x] GoogleSansFlexUltraCondensed[wght].ttf
- [x] GoogleSansFlexUltraCondensed-Italic[wght].ttf
- [x] GoogleSansFlexText[wght].ttf
z (and composed glyphs with z), ™, 

<img width="104" alt="Screenshot 2024-09-10 at 11 53 51 PM" src="https://github.com/user-attachments/assets/cae7acec-4501-4d65-a76c-8e5761b073d9">

<img width="115" alt="Screenshot 2024-09-10 at 11 49 14 PM" src="https://github.com/user-attachments/assets/83f08cd6-7eef-4a2c-a8ec-cc461fc9ac9a">

- [x] GoogleSansFlexText-Italic[wght].ttf
- [x] GoogleSansFlexSuperCondensed[wght].ttf
7 

<img width="139" alt="Screenshot 2024-09-10 at 11 56 49 PM" src="https://github.com/user-attachments/assets/325fff47-8dd0-4b83-9123-73a556afce3c">

- [x] GoogleSansFlexSuperCondensed-Italic[wght].ttf
7

<img width="437" alt="Captura de pantalla 2024-09-10 a las 18 17 44" src="https://github.com/user-attachments/assets/7f3cc71d-ec93-43e9-a3b2-a168f3240a76">

- [x] GoogleSansFlexRounded[wght].ttf
- [x] GoogleSansFlexRounded-Italic[wght].ttf
- [x] GoogleSansFlexNormal[wght].ttf
- [x] GoogleSansFlexNormal-Italic[wght].ttf
- [x] GoogleSansFlexExtraExpanded[wght].ttf
Issues found in: p đ 

<img width="198" alt="Screenshot 2024-09-10 at 7 18 43 PM" src="https://github.com/user-attachments/assets/25b98c83-752c-402d-80cd-bf1f5beb9f68">

<img width="210" alt="Screenshot 2024-09-11 at 12 06 32 AM" src="https://github.com/user-attachments/assets/8d1e25cb-e448-49a1-b516-37bd25891583">

- [x] GoogleSansFlexExtraExpanded-Italic[wght].ttf

Related #1034

**Comment by Hoolean** [comment]
@MariannaPaszkowska

Hi Marianna! We have isolated the interpolation issues that we have seen so far to an upstream bug in fontTool's instancer, and so I would suggest we pause any further manual review until this is fixed.

(after we have fixed the bug and produced fully correct instances then we may even be able to use diffenator2 to assess the full impact :)

**Comment by MariannaPaszkowska** [comment]
Thank you! Has this been reported already?

**Comment by Hoolean** [comment]
Now filed at fonttools/fonttools#3634 - I have a patch that appears to fix the issue, so will open a PR upstream to start discussion on whether it is a suitable approach too

**Comment by MariannaPaszkowska** [comment]
Release with the fix https://github.com/fonttools/fonttools/releases/tag/4.54.0 
And there is even one more recent https://github.com/fonttools/fonttools/releases/tag/4.54.1
