### ISSUE TITLE
Consider keeping overlaps for workspace partial VFs

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#1036]
> I just reviewed our instancing code and notice that we remove overlaps:
>
> https://github.com/googlefonts/googlesans-flex/blob/fdfa453dc0a6bb1dfaef8440ab6c511d8ee38fd9/scripts/cut_instances.py#L148-L160
>
> As we are instancing partial VFs instead of statics, we should consider removing this

_Originally posted by @Hoolean in https://github.com/googlefonts/googlesans-flex/issues/1034#issuecomment-2341446902_

**Comment by Hoolean** [comment]
(against this, it might save some file size from removing points used for `ROND`, which isn't used in every workspace font)

**Comment by MariannaPaszkowska** [comment]
Many thanks for your hard work on this! Fixed upstream in https://github.com/fonttools/fonttools/releases/tag/4.54.0
