### ISSUE TITLE
U+0070 LATIN SMALL LETTER P - artifact in the Google Sans Flex ExtraExpanded builds for Workspace

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#1037]
We identified an artifact in the `p` design in the ExtraExpanded Workspace family

![5qW8JjeAF9FbMBR](https://github.com/user-attachments/assets/1a56cf42-9075-4203-9aee-b011b7a2e78c)

Repro in Slides: https://docs.google.com/presentation/d/1JZZojvhNGOY5kWbyxQC5WHsCgnSZoU6csJvT1XX0Lgg/edit#slide=id.p

**Comment by MariannaPaszkowska** [comment]
Closing as it is a duplicate of #1034 related #1035
