### ISSUE TITLE
Fix bug in Oslash 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1039]
![oslash-bug](https://github.com/user-attachments/assets/cee31fd2-6be3-4a0e-bf77-1efb834d1197)

**Comment by chrissimpkins** [comment]
Seems mandatory :) 

What languages are involved here?

**Comment by octaviopardo** [comment]
around 10. Danish, Faroese, Finnish, a couple of Greenlandic dialects, norwegian, icelandic…

This is fixed already and I d say already implemented since 2.004

**Comment by MariannaPaszkowska** [comment]
duplicate of #1053
