### ISSUE TITLE
Update terminal of mu in opsz144

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#1049]
We have identified certain inconsistencies in the outstroke of /mu glyph in the opsz144. We would like to update those

**Change of metrics?** 
We could resolve it without changing the metrics. Ideally we might want to adjust slightly a few masters

**TIme required**
1 day, is basically prepared, except for the spacing adjustments, if we accept them

![Captura de pantalla 2024-09-27 a las 9 59 39](https://github.com/user-attachments/assets/73d8790d-e6c1-4e5b-a771-280082ff3ab0)

![Captura de pantalla 2024-09-27 a las 9 59 46](https://github.com/user-attachments/assets/4b5a1e05-f12f-453f-bc5c-94633b9949a2)

![Captura de pantalla 2024-09-27 a las 9 59 50](https://github.com/user-attachments/assets/dd69d7e7-aae3-49c1-a356-89ac886573aa)

![Captura de pantalla 2024-09-27 a las 9 59 54](https://github.com/user-attachments/assets/a482a087-279b-41fc-9d46-d46d80617531)

**Comment by MariannaPaszkowska** [comment]
Hi @octaviopardo side question: why at opsz6 the terminals in t and f are angled?

**Comment by octaviopardo** [comment]
well the design was already like that, I assume is a way to make the letters wider in that opsz. Enlarging the stroke and curving it you avoid having to do the turn too large, or start too low, specially in heavier and wider weights

**Comment by MariannaPaszkowska** [comment]
CC @chrissimpkins

**Comment by chrissimpkins** [comment]
LGTM, ok to include in v3.0 if time allows.
