### ISSUE TITLE
Interpolation issue in the GS Flex v2.3 `2` 

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#1050]
Report from Ryan Kiley:

![gsf-bug](https://github.com/user-attachments/assets/a67601c2-b2c8-4f07-9a84-c4b84b9c433b)

Design space location:

- slant: 0
- width: 25
- weight: 1
- GRAD: 100
- ROND: 100

**Comment by MariannaPaszkowska** [comment]
Which glyph it is? `2`?

**Comment by chrissimpkins** [comment]
Yep, `2`.  See title.  I should have been more clear in the body of the report.  Thanks for looking into it!

**Comment by MariannaPaszkowska** [comment]
will be closed by #1102 
![Image](https://github.com/user-attachments/assets/346004e7-b1b7-4170-a5ea-1de6a935c15a)
