### ISSUE TITLE
Adjustments 6 & 9

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#1052]
We have adjusted the inktrap  in the large styles of 6 and 9 after an observation of Megan in one of our meetings

Change of metrics?
no

TIme required
ready

(on the left current, on the right, adjustments)

![6-03](https://github.com/user-attachments/assets/ca8b4524-b2a1-463a-9eb0-b767ffbe9073)
![6-02](https://github.com/user-attachments/assets/42ba5c94-fd2f-48b2-a8c5-9923f077b343)
![6-01](https://github.com/user-attachments/assets/1333a7ca-91e3-45d7-866c-e8ea91db3445)

**Comment by MariannaPaszkowska** [comment]
@octaviopardo is that 144opsz? Do I recall correctly?

**Comment by octaviopardo** [comment]
That is correct

**Comment by chrissimpkins** [comment]
And the change will only be in the 144pt opsz 1000 weight masters?  Are you demonstrating changes in the 400 and 1 weight masters in the top image?  I don't immediately see them if so.

**Comment by chrissimpkins** [comment]
Agree that we should include opsz=144 weight=1000 changes here in v3.0.  Please document if this will impact any other area of the design space and provide some additional visuals to demo what we are doing in other design space areas across the numbers `6` and `9`.  Ty!

**Comment by MariannaPaszkowska** [comment]
will be closed by #1102 
![Image](https://github.com/user-attachments/assets/ede7184e-651b-41ab-a14a-9ec0a6700ce8)
