### ISSUE TITLE
Oslash, seven, hbar, dcroat, eth fixes

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#1053]
**fix of the Oslash bug detected in the review of workspace fonts**
Change of metrics? No
Time required? Ready

![Captura de pantalla 2024-10-01 a las 16 37 16](https://github.com/user-attachments/assets/323c9d33-e120-4618-8fc3-f296f2ad918e)

**Correction of top bar in 7 (144-151-400). It is too long in the italic**
Change of metrics? No
TIme required? Ready

https://github.com/user-attachments/assets/ebd5482d-26f9-4507-96fd-b813317bbd0a

turn hbar, dcroat, eth into components structure
Change of metrics? Theorethically no, potential rounding issues (changes of 0,00X units)
Time required? Ready

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans-flex/issues/1039 seems to be a duplicate of part of this issue?

**Comment by chrissimpkins** [comment]
I don't grasp what the problems are beyond the Oslash.  Will you please describe what we are fixing, particulary in the seven. And in what area of the design space?

**Comment by octaviopardo** [comment]
sorry, u r totally right. The top bar becomes too long in the slanted version, like if the right part slanted but the left part remained in the same spot. The rest (hbar, dcroat and eth) is basically addressed to reduce file size by increasing the use of components. No design changes
