### ISSUE TITLE
Add/update ccmp feature

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1060]
add missing anchors for mkmk feature. More details to follow...

![Image](https://github.com/user-attachments/assets/09dfcb68-7128-4082-a176-9ed112b8f53e)

**Comment by schriftgestalt** [comment]
To avoid clipping it might be better to make a "ringacute" glyph (and add substitution in camp) that is shorter than "ring"+"acute".

**Comment by chrissimpkins** [comment]
Please follow with the additional details so that we understand the impact here.  What languages are involved, what is the bug, and how do we intend to fix it?

**Comment by MariannaPaszkowska** [comment]
it impacts auxiliary combinations for Danish.

**Comment by octaviopardo** [comment]
All the combining accents are properly placed, so this is not a font problem but a production problem.

Apparently, when using combining marks, the font replaces automatically the combined mark by an existing glyph. Then, the precomposed glyphs do not apply the combining marks. 

Here in this image you can see several letters with the ringcomb applied and you can see the different behaviour. When the resulting glyph is not precomposed in the font, the accents stack; when the glyph is present in the font, the combo letter + combining mark gets replaced by the precomposed glyph (check the left column) and the accents do not stack

![Image](https://github.com/user-attachments/assets/1f8f66fa-955e-4d05-8784-c1fb869eb8f4)

**Comment by MariannaPaszkowska** [comment]
cc @belluzj

**Comment by Hoolean** [comment]
Interesting! We'll investigate 🔎

Automatic anchor propagation is disabled to ensure that we are not using file size on anchors that are not explicitly requested by the sources, so we should look to see:
- [x] Are anchors included in aring.glif in the DS+UFOs sources?
  - They are not:
https://github.com/googlefonts/googlesans-flex/blob/eadbc8d70536d99c279899720098b44dc9edfced/sources/GoogleSansFlex-wg1-wd100-oz144-GD0-RD0-sl-10.ufo/glyphs/aring.glif#L1-L9
- [x] Are anchors included in aring.glyph in the Glyphs sources?
  - Confirmed they are not in Glyphs

**Comment by schriftgestalt** [comment]
I think we have two options: 
1) add anchors to all precomposed glyphs. This will add quite a bit of file size
2) decompose the normalized glyphs. This should be only a few lines in ccmp and should work in most places (except in Adobes basic composer)

**Comment by Hoolean** [comment]
I can now confirm that /aring does not contain anchors in the latest .glyphspackage on `main`, so we will indeed need to implement one of the options that Georg suggests

**Comment by Hoolean** [comment]
If helpful, we could implement a svelter version of (1) that would propagate anchors selectively. Pros/cons:

- :x: Need to maintain a list of scenarios in which anchor propagation is required (e.g. /ring in /aring)
- ✔ Avoids manual copying and maintainence of anchor positions
- ✔ Avoids introducing potentially redundant anchors, and their associated file size costs

(2) is interesting, as there may be file size savings from eliminating `glyf` data for precomposed glyphs too.

**Comment by MariannaPaszkowska** [comment]
From the team meeting:
Q: Let's investigating how much files size we are saving by disabling the anchor propagation here. 
Georg suggests to enable the glyph decomposition. 
Jany: we can write a ccmp features.

**Comment by belluzj** [comment]
Georg says: only do the decomposition if followed by yet another accent

```
sub aring' @top by a ringcomb;
```

@schriftgestalt is that what you meant?

**Comment by schriftgestalt** [comment]
some notes for decomposition: 
- check if there is a .case variant of the accent
- the default ccmp for dot removal on i and j+combining mark can be used as an example.
