### ISSUE TITLE
Minor - ss01 single-storey /a doesn't work for /adotbelow

### ISSUE THREAD

**Issue by belluzj** [googlefonts/googlesans-flex#1061]
![Image](https://github.com/user-attachments/assets/f6f0ee26-6645-482e-bbb3-8ae91b6895b7)

**Comment by octaviopardo** [comment]
Seen and fixed for next release. Great catch!

**Comment by chrissimpkins** [comment]
It sounds like it is already addressed. If so, it can be included in v3.0.  If not, please document the language(s) involved and we can discuss priority.

**Comment by octaviopardo** [comment]
it s already implemented for 3.0 indeed

**Comment by MariannaPaszkowska** [comment]
confirming that this is in the latest import #1102 

![Image](https://github.com/user-attachments/assets/9b2771e5-a635-426d-a1db-eb1690a8ca2b)

**Comment by MariannaPaszkowska** [comment]
will be closed by #1103 

![Image](https://github.com/user-attachments/assets/eacea9c6-4066-44b0-aa0c-2809d5d9c1b2)
