### ISSUE TITLE
removing two useless anchors of n?

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1065]

**Comment by octaviopardo** [comment]
So I put this anchors preparing the path for the extended Latin. Name of the anchors are nhookleft and eng, quite self-explanatory. I m calling to remove them for the sake of cleanness but if there is a plan to extend the latin soon, they can/should remain

![Image](https://github.com/user-attachments/assets/362a17a3-b924-40f2-a60b-064f82d7b24f)
