### ISSUE TITLE
1 units shakes in the slanted in 3.0

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#1071]
We are registering many 1 unit variations in the slanted masters in between the 2.005 and the 3.0 versions. The main reason is the new point structure. The 2.5 point structure had 4 points in the extreme of a stem (offcurve point - on curve point - on curve point - off curve point), while the 3.0 only have 2 on curve points. As a result, the stems are varying slightly across the design in a way that cannot be fixed. 

The way to proceed here are two
Keep glyph width consistent with 2.005
1) break sidebearings relationship. This means that left n and left m might vary in a unit but glyph width stays consistent in between 2.005 and 3.0

TO not keep glyph width consistency with 2.005
2) break glyph width consistency: left n and left m have the same value but glyhp-widht might change in one unit

(See in the image the 3.0 in the foreground vs the 2.4 in the background)

![Image](https://github.com/user-attachments/assets/6e381363-7a89-4ae7-bf3e-25703e045eb6)

**Comment by chrissimpkins** [comment]
Are there any user-facing perceptible consequences of the decision that we make across your two proposals here?

**Comment by octaviopardo** [comment]
I have not checked things in Diffenator yet, but I wouldn't be surprised if there are some minimal "shakes", BUT The kind that nobody will ever notice unless looking at a before/after in diffenator

**Comment by MariannaPaszkowska** [comment]
This issue is related to the rounding refactor. There is nothing actionable here. This issue is open for documentation purposes and QA definitions.
