### ISSUE TITLE
Add shaping test for new `tnum` behaviour

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#1077]

**Comment by MariannaPaszkowska** [comment]
Changes in `tnum` and `calt` as reported by @octaviopardo 


![Image](https://github.com/user-attachments/assets/a8c068e2-392f-4d72-8753-db5d2f0bf255)

**Comment by Hoolean** [comment]
Super, thanks Marianna! Which glyphs have changed advance width too? We could test these at the same time

**Comment by Hoolean** [comment]
cc @RickyDaMa

**Comment by MariannaPaszkowska** [comment]
those should be at half tabular width now: `colon.tf`, `comma.tf`, `period.tf`, `semicolon.tf`

cc @octaviopardo
