### ISSUE TITLE
Add narrow non-breaking space (U+202F)

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1083]
The width of the space is up to discussion.
Requested by one of the internal teams. 

The use case is localising the traditional horizontal digital time displays as the space between the final number and the am/pm designator. `9:19 am`  ICU-based localization tests failed on this missing in the brand fonts when they attempted to implement their clock design.

**Comment by MariannaPaszkowska** [comment]
Suggestion from @octaviopardo: The width of this character can be based on the percentage of the width of the `space` instead of the unit-based widths.

**Comment by MariannaPaszkowska** [comment]
Decision: let's add this character, as a percentage of the width of the space and create a beta file to ship to the team. @octaviopardo will also add some visuals here.

**Comment by octaviopardo** [comment]
ready. This is how it looks with 1/2 of regular space. I think it looks fine

![Image](https://github.com/user-attachments/assets/ccd37c96-a932-415e-8c13-bda9aacc363d)
![Image](https://github.com/user-attachments/assets/9bb60a22-6d72-4fb8-a888-dc9e85fc1f8a)
![Image](https://github.com/user-attachments/assets/145a5719-9fb2-4fa0-b5ce-59df68ab78a7)

**Comment by chrissimpkins** [comment]
Thank you very much Octavio!  Will you please point me to a commit build where I can find a file with this support to share it with the team?  No rush.

**Comment by chrissimpkins** [comment]
> Thank you very much Octavio! Will you please point me to a commit build where I can find a file with this support to share it with the team? No rush.

Octavio told me that we can test with the build in this run: https://github.com/googlefonts/googlesans-flex/actions/runs/11769327102

**Comment by chrissimpkins** [comment]
Test build shared with the product team. I'll let you know when I hear back from them. Let's leave this tracker open until we have their green light. Ty!

**Comment by chrissimpkins** [comment]
Approved by product team.  OK to merge.

**Comment by chrissimpkins** [comment]
I shared the release file with the product team that requested this.  Thanks for addressing it!
