### ISSUE TITLE
Google Sans Flex v2.6 Fonts CSS API subset definitions

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#1096]
Based on the report in https://github.com/googlefonts/googlesans-flex/issues/1092#issuecomment-2491437916, I proposed the following subset definitions in the GSF v2.6 that is in sandbox before we move it to production.  Please let me know if you identify any other subset definition requirements before the push. Thanks!

```
subsets: "canadian-aboriginal"
subsets: "cherokee"
subsets: "latin"
subsets: "latin-ext"
subsets: "math"
subsets: "menu"
subsets: "nushu"
subsets: "symbols"
subsets: "syriac"
subsets: "tifinagh"
subsets: "vietnamese"
```

**Comment by MariannaPaszkowska** [comment]
#1095

**Comment by MariannaPaszkowska** [comment]
https://gist.github.com/m4rc1e/8fe31c10352a23cb8974cf25d1bcdca0

@m4rc1e reported that _his tool reports that there are exactly 38 unaccounted for glyphs. So the results of my manual edit and his tool are basically the same._
