### ISSUE TITLE
Build #211 (6 and 9 redo) failed 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#110]
It seems that the fb-wip needs the same CI improvements as @RickyDaMa introduced in the main branch. (thanks, @madig!)

**Comment by madig** [comment]
I merged the build scripting into fb-wip, building now fails due to source incompatibilities: https://github.com/googlefonts/googlesans-flex/actions/runs/3695475671/jobs/6257908769#step:8:396

**Comment by MariannaPaszkowska** [comment]
Thanks for the quick fix! 🚀  Incompatibility in the sources is another issue.
