### ISSUE TITLE
ROND axis avar1 mapping

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#1105]
Tracker for mapping of the new v3.0 semi-rounds with an avar1 definition

**Comment by chrissimpkins** [comment]
Dave requests that we remap ROND=70 to the ROND=75 location

**Comment by chrissimpkins** [comment]
Waiting for input from Material UX team

**Comment by MariannaPaszkowska** [comment]
#1109

**Comment by chrissimpkins** [comment]
Confirming that this was closed as not implemented?  We did not add the avar1 table, correct?

**Comment by davelab6** [comment]
Correct, we decided to keep the axis simple and unattuned by avar1
