### ISSUE TITLE
Issues in the component order in slanted `ư` and `u`

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1108]
Spotted at 
opsz-144_0, wght-1000_0, wdth-100_0, GRAD-0_0, ROND-0_0, slnt 10_0 

 <img width="1159" alt="Image" src="https://github.com/user-attachments/assets/285d7509-7310-448f-9208-456dc6804738" />

<img width="985" alt="Image" src="https://github.com/user-attachments/assets/5c958c1e-6d16-4713-9458-d96fa0e26a4a" />

BTW, @behdad this wasn't reported by the fonttools/varLib.interpolatable test I run.

`u`
opsz-144_0, wght-700_0, wdth-100_0, GRAD-0_0, ROND-0_0, slnt 10_0 

<img width="1563" alt="Image" src="https://github.com/user-attachments/assets/b863f95a-158e-40ad-944d-56338545e909" />

**Comment by simoncozens** [comment]
This is not just `uhorn`, but is a problem in `u` itself. The path direction in sources/GoogleSansFlex-wg1000-wd100-oz144-GD0-RD0-sl0.ufo/ and sources/GoogleSansFlex-wg1000-wd100-oz144-GD0-RD0-sl-10.ufo is reversed.

A fontbakery source check for consistent path direction across masters might be a good idea.

**Comment by simoncozens** [comment]
<img width="1082" alt="Image" src="https://github.com/user-attachments/assets/3beb6b93-96ec-46dc-9031-d196ab9de71d" />

**Comment by octaviopardo** [comment]
Yes, thanks SImon. It s already fixed and I m building the font to confirm the fix :) Ur script was very useful as always
