### ISSUE TITLE
Glyph names in sources - automatic renaming process

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#117]
Let's create an automatic renaming process to make the glyph names from the FB sources consistent with https://github.com/googlefonts/googlesans-flex/blob/main/.github/actions/import/glyph-list.txt

Font Bakery fail: [Glyph names are all valid?](https://github.com/googlefonts/googlesans-flex/actions/runs/3707745278/jobs/6284525053#step:9:284)
@belluzj @madig 
CC @chrissimpkins

**Comment by madig** [comment]
Hm, it's easy to fix that fail by writing explicit production names into the UFOs, which is easy and can be managed with https://github.com/googlefonts/googlesans-flex/pull/67. Renaming the glyphs is a separate issue and can also be done by script.

**Comment by MariannaPaszkowska** [comment]
@madig sgtm, let's add a renaming script to our toolbox :)

**Comment by anthrotype** [comment]
Why a postprocessing script to rename glyphs? What's wrong with public.postscriptNames inside UFO lib?

**Comment by madig** [comment]
I think this is about 1. renaming design names so what we have matches the glyph list at https://github.com/googlefonts/googlesans-flex/blob/main/.github/actions/import/glyph-list.txt and relatedly, 2. setting correct production names in postscriptNames.

**Comment by RickyDaMa** [comment]
#67 now handles setting valid production names for glyphs which otherwise didn't have a production name and their design name wasn't permitted. The way it does so isn't massively intelligent, but because only 7 glyphs are affected (and they're all components), there shouldn't be anything to worry about

```
INFO: automatically to specified postscript name for exclam-top by removing dashes
INFO: automatically to specified postscript name for question-top by removing dashes       
INFO: automatically to specified postscript name for dot-composite by removing dashes      
INFO: automatically to specified postscript name for Eth-bar by removing dashes
INFO: automatically to specified postscript name for Oslash-bar by removing dashes
INFO: automatically to specified postscript name for oslash-bar by removing dashes
```

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa @madig  I tested font from this [build](https://github.com/googlefonts/googlesans-flex/actions/runs/3894379712) and I still am getting a Fontbakery fail: 

<img width="690" alt="Screenshot 2023-01-12 at 5 54 26 PM" src="https://user-images.githubusercontent.com/22956348/212115410-df15ed26-fd5b-4b1e-b1d1-a6ec74077fd4.png">

**Comment by RickyDaMa** [comment]
Hey @MariannaPaszkowska, the fix is in and should be working as intended, however it's only run on import. A new import hasn't been run since #214 was merged so the sources on `main` are still not fixed. If you'd like, I can run the script and open a PR to change the sources on `main`? Alternatively, a new import from `fb-wip` would also include the change

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa Can I run the import workflow on a specific commit? Many changes happened in the fb-wip, and we don't want to import them for this release. Otherwise, changes to the sources (including OS/2 WinAdcent/Descent recalculation) and a new PR is how we would like to approach it.

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska I can't guarantee it'll work, there's no harm in trying. Put the commit reference in the "The name of the branch to import from" and see if the pipeline fails. I may have to do more work to the workflow to make it support this though

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa It seems that the pipeline fails if I try a specific commit. Let's work on supporting it, if it can be done today. If not let's prepare the sources. What does it sound?

**Comment by RickyDaMa** [comment]
Sounds good to me! 🔍

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska could you please provide me a link to the commit you're trying to use so I can test with it? Thanks!

**Comment by MariannaPaszkowska** [comment]
Here it is: https://github.com/googlefonts/googlesans-flex/commit/227d8d1aa538a4d24ee5bacd67a59b6bab44adfc
