### ISSUE TITLE
Ensure VFs with the GRAD axis do not vary horizontal advance.

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#118]
Font Bakery fail: The following glyphs have variation in horizontal advance due to the GRAD axis:
• seven.tf
• equal.tf 

Please double-check those glyphs. 

The report is [here](https://github.com/googlefonts/googlesans-flex/actions/runs/3707745278/jobs/6284525053#step:9:284)
CC @chrissimpkins

**Comment by dberlow** [comment]
Tabular figures do not count right now?On Dec 16, 2022, at 9:43 AM, Marianna Paszkowska ***@***.***> wrote:﻿
Font Bakery fail: The following glyphs have variation in horizontal advance due to the GRAD axis:
• seven.tf
• equal.tf
Please double-check those glyphs.
Report is here
CC @chrissimpkins

**Comment by sannorozco** [comment]
Yup, they don’t count right now, bu we will be fixing this in the next build.

**Comment by sannorozco** [comment]
This has been fixed.
