### ISSUE TITLE
fix family and style max length

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#120]
Font Bakery check fails here:

>> Check:   com.google.fonts/check/name/family_and_style_max_length
    Desc:    Combined length of family and style must not exceed 27 characters.
    Files:   GoogleSansFlex[GRAD,ROND,opsz,wdth,wght].ttf

     WARN The combined length of family and style exceeds 27                    
          chars in the following 'WINDOWS' entries: FONT_FAMILY_NAME =          
          'GoogleSansFlex opsz18-wdth100-wght400-ROND0' / SUBFAMILY_NAME =      
          'Regular'                                                             
                                                                                
          Please take a look at the conversation at                             
          https://github.com/googlefonts/fontbakery/issues/2179 in order to     
          understand the reasoning behind these name table records max-length   
          criteria. [code: too-long]                                            
    Result: WARN

The report is [here](https://github.com/googlefonts/googlesans-flex/actions/runs/3707745278/jobs/6284525053#step:9:284)
CC @chrissimpkins

**Comment by chrissimpkins** [comment]
I don't believe that any of the environments that Stephen indicated are high priority for us at this stage.  Is anyone aware of other areas where this is important?

**Comment by chrissimpkins** [comment]
The fix should also include a production style name.  The current name is a UFO master location.

**Comment by MariannaPaszkowska** [comment]
#125
