### ISSUE TITLE
Differing number of anchors in H and h

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#122]
Please review and fix the differing number of anchors in H and h:

Fonts had differing anchors in glyph H:
 * 67 fonts had "bottom, center, top"
 * GoogleSansFlex opsz144-wdth151-wght1000-ROND100 had "center, top"

Fonts had differing anchors in glyph h:
 * 67 fonts had "bottom, center, top"
 * GoogleSansFlex opsz144-wdth151-wght1000-ROND100 had "bottom, bottom, center, top, top"

**Comment by sannorozco** [comment]
I üst compiled and there was no output about this, sources from the repo.

**Comment by sannorozco** [comment]
This incompatibilities are because of our WIP on ROND100 sources, should be fixed in the following days.
