### ISSUE TITLE
interpolation issues on opsz axis

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#159]
Here are some interpolation issues I noticed today during a [review of this font](https://github.com/googlefonts/googlesans-flex/actions/runs/3836960312):
axis positions: wght 700 (visible also in positions 50-1000), wdth 151 (visible also in positions 30-151), opsz 80 (visible also in positions 30-151):
- [x]  « » (tips are breaking)
<img width="329" alt="Screenshot 2023-01-04 at 1 05 09 PM" src="https://user-images.githubusercontent.com/22956348/210541875-32e3fb26-1576-4899-ab6b-c7a374095551.png">

- [x]   ‹ › (tips are breaking)
<img width="278" alt="Screenshot 2023-01-04 at 1 05 18 PM" src="https://user-images.githubusercontent.com/22956348/210541897-7c2517c7-aeaf-4dca-a70a-a5216bca8e25.png">

- [x] Œ 
<img width="317" alt="Screenshot 2023-01-04 at 1 05 27 PM" src="https://user-images.githubusercontent.com/22956348/210541922-981e404e-915b-493f-951a-47dcf9643ed9.png">

axis positions: wght 700 (visible also in positions 500-1000), wdth 151, opsz 80 (visible also in positions 19-143):

- [ ] diaeresis (slanted):
<img width="415" alt="Screenshot 2023-01-04 at 1 08 18 PM" src="https://user-images.githubusercontent.com/22956348/210542473-948ebee7-4033-4002-b4f0-641ec70a1808.png">

- [x] diaeresis also gets rapidly smaller and then bigger again opsz 6-18 (wght 700-1000)

- [ ] double acute (diagonals are breaking)
<img width="326" alt="Screenshot 2023-01-04 at 1 08 29 PM" src="https://user-images.githubusercontent.com/22956348/210542499-3bd93062-8bc8-40f7-9148-2743a4b3a472.png">

- [ ] acute  (diagonals are breaking)
<img width="342" alt="Screenshot 2023-01-04 at 1 06 09 PM" src="https://user-images.githubusercontent.com/22956348/210542085-8e750c02-0bbc-451e-a7d0-ee888e182527.png">

- [ ] circumflex (diagonals are breaking)
<img width="243" alt="Screenshot 2023-01-04 at 1 09 02 PM" src="https://user-images.githubusercontent.com/22956348/210542582-f3d3d123-675a-4719-8619-a203774c4fd2.png">

- [ ] ẞ (outstroke outline, a bottom curve is breaking)
<img width="187" alt="Screenshot 2023-01-04 at 1 08 42 PM" src="https://user-images.githubusercontent.com/22956348/210542545-17fa45e2-7dd9-47e5-af9c-4e45f56abe89.png">

**Comment by dberlow** [comment]
Thanks Marianna!

SO, Ive fixed the French quotes.
The OE must not have any junctions top or bottom like this:
<img width="525" alt="Screen Shot 2023-01-04 at 7 15 43 AM" src="https://user-images.githubusercontent.com/1956494/210553427-16a4fac0-0054-4512-86ec-b4ade554cd54.png">
All the junctions in the design space must be like this:
<img width="611" alt="Screen Shot 2023-01-04 at 7 15 27 AM" src="https://user-images.githubusercontent.com/1956494/210553508-6bacd99c-17d8-4159-a39b-d825c499ad4f.png">

I have done only GoogleSansFlex-opsz144-wdth151-wght400-ROND0 in the course of this illustration.

**Comment by MariannaPaszkowska** [comment]
Review today on this font: https://github.com/googlefonts/googlesans-flex/actions/runs/3872234545

- [ ] «» - tips are still breaking

- [ ] ‹› - tips are still breaking

 <img width="915" alt="Screenshot 2023-01-09 at 8 29 10 PM" src="https://user-images.githubusercontent.com/22956348/211381194-306a0656-f4c9-4a12-a80e-9166f6c086ca.png">

**Comment by MariannaPaszkowska** [comment]
@sannorozco Many issues still remain: <img width="815" alt="Screenshot 2023-01-30 at 3 05 14 PM" src="https://user-images.githubusercontent.com/22956348/215485526-f83ad3b7-7b00-4bf7-a249-b48bfd838481.png">
Tested font: https://github.com/googlefonts/googlesans-flex/actions/runs/4024665128

**Comment by MariannaPaszkowska** [comment]
@sannorozco: Accents in gravecomb, acutecomb, circumflexcomb, and ẞ still have issues in GRAD -50 (test string: À Ő Â Á ẞ): <img width="897" alt="Screenshot 2023-02-06 at 3 48 28 PM" src="https://user-images.githubusercontent.com/22956348/216988077-13192228-06e9-4a38-881f-ac7b22c9a215.png">
Tested today on this build: https://github.com/googlefonts/googlesans-flex/actions/runs/4103075184
