### ISSUE TITLE
ROND 100: opsz 144, wdth 25, wght 1

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#170]
Dots (dot, diaeresis, ÷, ? ! ¿ ¡ ) are too heavy and inconsistent with ROND=0

<img width="244" alt="Screenshot 2023-01-04 at 8 14 29 PM" src="https://user-images.githubusercontent.com/22956348/210622079-b508a023-fa6b-4f81-945a-ef55fbf674e5.png">

<img width="235" alt="Screenshot 2023-01-04 at 8 18 25 PM" src="https://user-images.githubusercontent.com/22956348/210622700-3dc249b4-5160-4c4b-9a57-691e334d7e31.png">

**Comment by dberlow** [comment]
I do not know how you are proofing this style.

But it does not look like that in RF. 
<img width="416" alt="Screen Shot 2023-01-04 at 5 05 25 PM" src="https://user-images.githubusercontent.com/1956494/210658960-c0bdc1e6-9268-4eab-9bc2-d805b675696f.png">

or Chrome
<img width="422" alt="image" src="https://user-images.githubusercontent.com/1956494/210659765-d896a855-e418-4bd0-846a-5e1d775ca04d.png">

**Comment by MariannaPaszkowska** [comment]
I tested in Videoproof/Chrome. This was only visible in ROND=100, not in ROND=0.

**Comment by sannorozco** [comment]
We updated it on ROND100, VF soon.
