### ISSUE TITLE
ROND100: no roundness in opsz between 6-18pt

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#174]
The font reviewed is [here](https://github.com/googlefonts/googlesans-flex/actions/runs/3846821926). 

<img width="540" alt="Screenshot 2023-01-05 at 3 26 55 PM" src="https://user-images.githubusercontent.com/22956348/210790909-bc248797-1c1f-486c-a090-370f8ac911b8.png">

**Comment by dberlow** [comment]
This is by design. There is no ROND between opsz6 and 17.9990.

For discussion.

**Comment by MariannaPaszkowska** [comment]
Thank you @dberlow!

**Comment by dberlow** [comment]
Closing for P1
