### ISSUE TITLE
PANOSE value

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans-flex#181]
I see that no PANOSE value has been specified. Any wishes? Google Sans Regular uses 2, 11, 5, 3, 3, 5, 2, 4, 2, 4. Since we don't produce statics yet, one value for the default source (18pt Regular) should do for now.

**Comment by MariannaPaszkowska** [comment]
Hi @madig, yes, let's take those values: 
   <panose>
      <bFamilyType value="2"/> # Latin Text 
      <bSerifStyle value="11"/> # Normal Sans
      <bWeight value="5"/> # Book
      <bProportion value="3"/> # Modern
      <bContrast value="3"/> # Very Low
      <bStrokeVariation value="5"/> # Gradual/Vertical
      <bArmStyle value="2"/> # Straight Arms/Horizontal
      <bLetterForm value="4"/> # Normal/Boxed
      <bMidline value="2"/> # Standard/Trimmed
      <bXHeight value="4"/> # Constant/Large
    </panose>
