### ISSUE TITLE
GRAD axis: variation in horizontal advance due in some glyphs

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#182]
The following glyphs have variation in horizontal advance due to the GRAD axis: 
`onehalf`
`greaterequal.tf`
`lessequal.tf `

Reported here: https://github.com/googlefonts/googlesans-flex/actions/runs/3846821926/jobs/6552559918#step:11:120

**Comment by ghost** [comment]
DONE

**Comment by chrissimpkins** [comment]
Does fontbakery support checks on this?

**Comment by RickyDaMa** [comment]
@chrissimpkins yes, that's what led Marianna to find this issue. The link she provides is to Fontbakery's output

**Comment by dberlow** [comment]
Please also add width checks to *-ROND0 to matching *-ROND100, as I have requested that check to be run on our commits as well.E.g. GoogleSansFlex-opsz18-wdth100-wght400-GRAD0-ROND0 must match        GoogleSansFlex-opsz18-wdth100-wght400-GRAD0-ROND100On Jan 13, 2023, at 4:59 AM, Ricky ***@***.***> wrote:﻿
@chrissimpkins yes, that's what led Marianna to find this issue. The link she provides is to Fontbakery's output

**Comment by chrissimpkins** [comment]
> @chrissimpkins yes, that's what led Marianna to find this issue. The link she provides is to Fontbakery's output

That's great.  Didn't realize that it was added to fontbakery.

We have a SHA hash check on the kerning.plist files across GRAD masters if kerning diffs are not picked up by fontbakery yet.  Let's consider this after the kerning is imported into the production source files.

**Comment by chrissimpkins** [comment]
> Please also add width checks to *-ROND0 to matching *-ROND100, as I have requested that check to be run on our commits as well.E.g. GoogleSansFlex-opsz18-wdth100-wght400-GRAD0-ROND0 must match        GoogleSansFlex-opsz18-wdth100-wght400-GRAD0-ROND100On Jan 13, 2023, at 4:59 AM, Ricky ***@***.***> wrote:﻿ @chrissimpkins yes, that's what led Marianna to find this issue. The link she provides is to Fontbakery's output —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Will open this as a new repo issue. Thanks David

**Comment by chrissimpkins** [comment]
> > Please also add width checks to _-ROND0 to matching _-ROND100, as I have requested that check to be run on our commits as well.E.g. GoogleSansFlex-opsz18-wdth100-wght400-GRAD0-ROND0 must match        GoogleSansFlex-opsz18-wdth100-wght400-GRAD0-ROND100On Jan 13, 2023, at 4:59 AM, Ricky _**@**_.___> wrote:﻿ @chrissimpkins yes, that's what led Marianna to find this issue. The link she provides is to Fontbakery's output —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: _**@**_._**>
> 
> Will open this as a new repo issue. Thanks David

https://github.com/googlefonts/googlesans-flex/issues/238
