### ISSUE TITLE
Test git tag push release workflow

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#192]
Confirm that the push of a git tag formatted as `vX.XXX*` prepares a GitHub release with the appropriate release version, and a zip archive with the release files that includes the release version in the zip archive file path.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans-flex/releases/tag/v1.000-Alpha.2

**Comment by chrissimpkins** [comment]
@RickyDaMa @madig the release part of the workflow was not triggered

https://github.com/googlefonts/googlesans-flex/actions/runs/3858458652

cc @MariannaPaszkowska

**Comment by madig** [comment]
The release is triggered by a GitHub release, not a tag. I created one at https://github.com/googlefonts/googlesans-flex/releases/tag/v1.000-Alpha.2, let's see.

**Comment by chrissimpkins** [comment]
Got it!  Thank you!
