### ISSUE TITLE
interpolation issues: wdth50-95, wght 100-1000, ROND100, opsz144

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#197]
<img width="845" alt="Screenshot 2023-01-09 at 12 18 27 PM" src="https://user-images.githubusercontent.com/22956348/211285933-c291ac78-2d24-466d-ae23-3dc4f2ce1210.png">

<img width="763" alt="Screenshot 2023-01-09 at 12 19 24 PM" src="https://user-images.githubusercontent.com/22956348/211286106-827e1401-b602-4bed-a29d-4fd94f5be6de.png">

<img width="950" alt="Screenshot 2023-01-09 at 12 20 56 PM" src="https://user-images.githubusercontent.com/22956348/211286350-4801c7c8-aa02-4de5-9b79-63705898937e.png">

**Comment by dberlow** [comment]
ROND wdth intermediates of these are done, awaiting next designspace and build.

**Comment by MariannaPaszkowska** [comment]
Thank you for the update, the interpolation looks better. There are some issues remaining in the heavier weights, width 25-90, ROND 100:
<img width="1420" alt="Screenshot 2023-01-26 at 4 47 11 PM" src="https://user-images.githubusercontent.com/22956348/214866165-f3ef821a-64e0-4d55-8ec7-5fa7dd7dd47d.png">
<img width="1422" alt="Screenshot 2023-01-26 at 4 47 40 PM" src="https://user-images.githubusercontent.com/22956348/214866310-560b4b9d-916c-485e-b8da-05d2b2b91124.png">
