### ISSUE TITLE
Add kerning 2 Priority masters

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#210]
Priority masters: 
wght=400, wdth=100, opsz=18, ROND=0, GRAD=0
wght=1000, wdth=100, opsz=18, ROND=0, GRAD=0
Copy values to ROND = 100

**Comment by sannorozco** [comment]
@MariannaPaszkowska kerning was added to all sources ROND0 & ROND100, and compiled. Kerning on:

- GoogleSansFlex-opsz18-wdth100-wght400-ROND0.ufo
- GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD50.ufo
- GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD-50.ufo
- GoogleSansFlex-opsz18-wdth100-wght1000-ROND0.ufo
- ROND100/GoogleSansFlex-opsz18-wdth100-wght400-ROND100.ufo
- ROND100/GoogleSansFlex-opsz18-wdth100-wght1000-ROND100.ufo

All other locations have 0s.

**Comment by MariannaPaszkowska** [comment]
Thanks for the delivery. I had a look and it seems that some important pairs are missing. Example `T.` `Y.` `Þ.` `W.` `V.` `WAW` `ST`, `ey` `fa`, `of` `mv`, `mw`,  . Kerning for `Æ` is missing. 
Those were present in GSv10. 
Are `EA` `KZ` pairs intentional?

**Comment by sannorozco** [comment]
@MariannaPaszkowska this was updated in yesterday’s build.
