### ISSUE TITLE
opsz 6pt interpolation issues

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#212]
Please also check all related glyphs. 

- [ ] 3:
<img width="527" alt="Screenshot 2023-01-09 at 5 54 14 PM" src="https://user-images.githubusercontent.com/22956348/211350816-0064b74f-72e5-4cf7-b199-05202c788dec.png">

- [ ] c
<img width="379" alt="Screenshot 2023-01-09 at 5 56 24 PM" src="https://user-images.githubusercontent.com/22956348/211351216-193a8c5f-4649-4907-960d-80e26edda9ec.png">

- [ ] g
<img width="738" alt="Screenshot 2023-01-09 at 6 00 31 PM" src="https://user-images.githubusercontent.com/22956348/211352189-94e8493d-e4af-4216-b67a-145a6a723cbb.png">

- [ ] s
<img width="627" alt="Screenshot 2023-01-09 at 5 56 52 PM" src="https://user-images.githubusercontent.com/22956348/211351317-2df1efcb-d726-4385-a037-1d0eaec1a284.png">

- [ ] $
<img width="498" alt="Screenshot 2023-01-09 at 5 57 27 PM" src="https://user-images.githubusercontent.com/22956348/211351454-1ba77278-1642-43ef-878b-e45168b72c78.png">

- [ ] £
<img width="459" alt="Screenshot 2023-01-09 at 5 58 52 PM" src="https://user-images.githubusercontent.com/22956348/211351790-e66ed9e8-a989-458b-8a0a-08c09e755526.png">

- [ ] c g e:
<img width="1311" alt="Screenshot 2023-01-09 at 4 13 44 PM" src="https://user-images.githubusercontent.com/22956348/211350891-715b1082-ec76-4721-be36-171395f35dce.png">
<img width="567" alt="Screenshot 2023-01-12 at 5 32 25 PM" src="https://user-images.githubusercontent.com/22956348/212109939-780879e0-3583-46f4-a1b1-0f56d8661b33.png">

- [ ] a, caron, cent, ae, oe
<img width="1022" alt="Screenshot 2023-01-12 at 5 28 37 PM" src="https://user-images.githubusercontent.com/22956348/212109035-63e99315-75ab-403d-accb-c4b942bc589d.png">

**Comment by MariannaPaszkowska** [comment]
@sannorozco Can you give us an update on this issue?

**Comment by MariannaPaszkowska** [comment]
Tested [this build](https://github.com/googlefonts/googlesans-flex/actions/runs/4103075184) today: <img width="1029" alt="Screenshot 2023-02-06 at 3 57 09 PM" src="https://user-images.githubusercontent.com/22956348/216990228-26bc77bf-5476-447f-a514-d6eff6c7ab30.png">

**Comment by MariannaPaszkowska** [comment]
@dberlow as we discussed yesterday, here is a full list of glyphs with issues:

a. list for sharp:

```
acgsG33Rẞ§

Accents: circumflex, caron, dieresiscomb(ÂǍ ï)  

```
b. for ROND
```
2 3 a C G J R S &
Accents: circumflex, caron, dieresiscomb(ÂǍ ï)  
Ligatures: (the first component has outline issues, open corners) ﬀ ﬁ ﬂ ﬃ ﬄ
```
Sharp:
<img width="1268" alt="Screenshot 2023-02-07 at 4 17 22 PM" src="https://user-images.githubusercontent.com/22956348/217269636-4b48e160-fc1f-4e12-9943-1b2e56cff2cb.png">

ROND:
<img width="1190" alt="Screenshot 2023-02-07 at 4 06 32 PM" src="https://user-images.githubusercontent.com/22956348/217269553-159cdea7-775d-4a65-bf58-2e215711f4f6.png">

**Comment by dberlow** [comment]
thank you. almost there.

**Comment by MariannaPaszkowska** [comment]
related open issue #224
