### ISSUE TITLE
Adjust Bold Instance

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#215]
Interpolation value for Bold Instance: 657 (all rest of the axis at their defaults).
@chrissimpkins We can adjust the interpolation value or use avar1.

**Comment by chrissimpkins** [comment]
The Google Sans weight avar1 is documented in https://github.com/googlefonts/googlesans/discussions/278.  

The source definition is @ https://github.com/googlefonts/googlesans/blob/e20bd20082e09ff2a700af5d60a9fb63afb5ffea/source/GoogleSans/GoogleSans.designspace#L9-L12

#### Google Sans (not Flex) weight axis avar1

| User  |  Internal  |
|-------|------------|
|  400  |   380      |
|  500  |   555      |
|  700  |   734      |




Let's not add any changes to support this until we decide on how to approach avar1 across the entire weight axis range.

**Comment by chrissimpkins** [comment]
@dberlow What are the stem widths of the GS Flex 700 masters vs. the Google Sans 734 masters where they have overlapping master support across the Flex design space?

**Comment by MariannaPaszkowska** [comment]
Design avar1 for opsz and wght: #108

**Comment by dberlow** [comment]
wdth and ROND do not overlap. GRAD I will leave aside.

Google Sans has opsz17 to 18, and wght 380-734 , and Google Sans Flex has opsz17 and 18, and 380-734 too, but I think you want what's below?

Flex values are provided at each size in consideration of the overlap of size range by use.

GSF, stem width (H)
BOLD
opsz6 wght 700 152/1000 (306/2000)
opsz18 wght 700. 162.5/1000 (325/2000)
opsz144 opsz700  183.5/1000 (367/2000)
vs. 
GS,  stem width (H)
opsz17 wght 734 134/1000
opsz18 wght 734 135/1000

Regular
GSF,  stem width (H)
opsz6 wght 400 95/1000 (190/2000)
opsz18 wght 400. 85/1000 (170/2000)
opsz144 opsz 400  73.5/1000 (147/2000)
vs. 
GS,  stem width (H)
opsz17 wght 380 85/1000
opsz18 wght 380 85/1000

**Comment by dberlow** [comment]
These are OS/2 values vs the measured values.
18,100,1 16/1000 (32/2000) @18, from 1 to 400 = 300/69 = .23/1000 per os/2 value
18,100,400 85/1000 (170/2000)  @18, from 400 to 1000 = 600/155 = .2583/1000 per os/2 value
18,100,1000 240/1000 (480/2000)

**Comment by MariannaPaszkowska** [comment]
This was related to: #108 (closed)
