### ISSUE TITLE
Add MVAR table

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#221]
It will be needed because we will cut instances from the VFs.

Reference: https://github.com/googlefonts/googlesans/pull/493/files#diff-03a30f87ff87febbe403fb59cac9338d00c19d62dea4d8a9ac56e8d8d56a4301

**Comment by madig** [comment]
I don't think we're dropping it? Unless gftools does, otherwise it would appear if has reason to exist. I'll check gftools tomorrow.

**Comment by madig** [comment]
It does indeed remove it and there seems to be no easy way to make it stop. There's this issue upstream: https://github.com/googlefonts/gftools/issues/580. Not sure how to proceed here. I can try to change gftools or we just drop it and use fontmake instead?

**Comment by madig** [comment]
FWIW, I made https://github.com/googlefonts/gftools/pull/648.

**Comment by m4rc1e** [comment]
You folks couldn't have made this PR at a better time. We've finally dropped Browserstack in our google/fonts ci so we no longer need to drop the MVAR, since we can now use the latest browsers.

**Comment by chrissimpkins** [comment]
Marc, let's chat about how this impacts the rest of the catalog.  I'll connect with you off repository

**Comment by chrissimpkins** [comment]
We should be gtg with the gftools MVAR table PR merge.

@madig @RickyDaMa  When this update is released, do you recommend that we run a full dependency update with pip-tools on the requirements.in or just bump the version on gftools in the requirements.txt file?

**Comment by m4rc1e** [comment]
It isn't on pip atm since I need to update the ci which builds the package. Issue here, https://github.com/googlefonts/gftools/actions/runs/3912606577/jobs/6687455671.

**Comment by m4rc1e** [comment]
I'm going to solve this next week since dropping the setup.py file has caused some other issues with pypi.

If you desperately need to install the latest gftools, do `pip install git+https://github.com/googlefonts/gftools@v0.9.22` which will install from the git tag.

**Comment by belluzj** [comment]
Thanks Marc! @chrissimpkins @MariannaPaszkowska are you OK for us to use the git+... package URL for requirements.txt, or should we wait for a PyPI release? We could maybe check that it indeed solves the MVAR issue with the git URL, and swap with the PyPI release as soon as available?

**Comment by m4rc1e** [comment]
I reckon I'll have pypi fix by EOD Monday

**Comment by chrissimpkins** [comment]
Thank you very much for reviewing, merging, and releasing this Marc. And thanks for the PR Nikolaus!

@belluzj OK to use the git+ URL for now.  Marianna would like to include MVAR in the test builds that we distribute to Android.  Are you able to update requirements today?  If not, I can open a PR with the changes.  We'd like to have as final as possible RC files by the end of the day today.

**Comment by chrissimpkins** [comment]
When we add the git+ dependency URL, let's open a new issue report to move to the PyPI release as soon as it is available.  No rush on it Marc.  Ty

**Comment by madig** [comment]
MVAR in https://github.com/googlefonts/googlesans-flex/suites/10360739410/artifacts/510739818.

**Comment by chrissimpkins** [comment]
tyvm!

**Comment by chrissimpkins** [comment]
I think that this can be closed following the merge of #241?

**Comment by madig** [comment]
I think so.
