### ISSUE TITLE
Add unhinted TT font gasp and prep table definitions

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#222]
We use the gftools fix-nonhinting script to define the gasp and prep tables in TTF families without instruction sets.  Let's use the same approach in GS Flex.

Standalone script is available in the GS project at https://github.com/googlefonts/googlesans/blob/main/scripts/gftools-fix-nonhinting.py if needed.

**Comment by madig** [comment]
Need to look into whether gftools offers this somehow.

**Comment by chrissimpkins** [comment]
> Need to look into whether gftools offers this somehow.

https://github.com/googlefonts/gftools/blob/main/Lib/gftools/scripts/fix_nonhinting.py

**Comment by RickyDaMa** [comment]
I've run this locally, and currently the tool isn't changing anything:

```
> gftools fix-nonhinting fonts/variable/GoogleSansFlex\[GRAD\,ROND\,opsz\,wdth\,wght\].ttf fonts/variable/GoogleSansFlex\[GRAD\,ROND\,opsz\,wdth\,wght\]-fixed.ttf
GASP was:  {65535: 15}
PREP was:
        PUSHW[ ]        /* 1 value pushed */
        511
        SCANCTRL[ ]     /* ScanConversionControl */
        PUSHB[ ]        /* 1 value pushed */
        4
        SCANTYPE[ ]     /* ScanType */
GASP now:  {65535: 15}
PREP now:
        PUSHW[]
        511
        SCANCTRL[]
        PUSHB[]
        4
        SCANTYPE[]
```

Nevertheless, I can add this into the build pipeline if you'd like @chrissimpkins? Since we already use gftools it should be easy to add

Maybe since we're using gftools to build, this fix is run as part of the process anyway?

**Comment by RickyDaMa** [comment]
As I suspected, looks like it's included/run by default. Closing this issue :)

**Comment by dberlow** [comment]
@chrissimpkins, i think these values, along with an instruction to change them at opsz144 below wght 20 or so, could be researched to prevent disappearance of the lightest weights, as seen in Chrome.See issue #115.Thanks.On Jan 11, 2023, at 7:50 AM, Ricky ***@***.***> wrote:﻿
As I suspected, looks like it's included/run by default. Closing this issue :)

**Comment by MariannaPaszkowska** [comment]
It's ok to close this issue; we can keep working on the gasp in #115, targeting the v1.1 release. Thanks for the updates, everyone!

**Comment by chrissimpkins** [comment]
> As I suspected, looks like it's included/run by default. Closing this issue :)

Thanks for having a look at this Ricky.  That's great if it is already included in the build.  OK to close.

**Comment by chrissimpkins** [comment]
> @chrissimpkins, i think these values, along with an instruction to change them at opsz144 below wght 20 or so, could be researched to prevent disappearance of the lightest weights, as seen in Chrome.See issue #115.Thanks.

Agree David. I'll open a new issue so that we can follow up on this.

**Comment by chrissimpkins** [comment]
> > @chrissimpkins, i think these values, along with an instruction to change them at opsz144 below wght 20 or so, could be researched to prevent disappearance of the lightest weights, as seen in Chrome.See issue #115.Thanks.
> 
> Agree David. I'll open a new issue so that we can follow up on this.

https://github.com/googlefonts/googlesans-flex/issues/229
