### ISSUE TITLE
Fix regressions opsz6 ROND

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#224]
There seem to be a few regressions between the delivery from Monday and today:
 
Previous font (on the left): https://github.com/googlefonts/googlesans-flex/actions/runs/3872234545
Latest font  (on the right): https://github.com/googlefonts/googlesans-flex/actions/runs/3891030087
<img width="1509" alt="Screenshot 2023-01-11 at 7 50 11 PM" src="https://user-images.githubusercontent.com/22956348/211880745-d25b82d4-cd28-4316-8f4d-e6c864ce8425.png">
<img width="1509" alt="Screenshot 2023-01-11 at 7 52 35 PM" src="https://user-images.githubusercontent.com/22956348/211881196-ffe666c7-172e-4227-be40-240af8f7ef12.png">

**Comment by sannorozco** [comment]
I can confirm this is caused by the intermediates added to ROND100, I fixed the bars.

All the intermediates for ROND100 are being woking on.

**Comment by MariannaPaszkowska** [comment]
@sannorozco Thanks for the updates so far! The ¢ looks better, but the rest of the glyphs still need some work:

<img width="1119" alt="Screenshot 2023-01-26 at 6 20 32 PM" src="https://user-images.githubusercontent.com/22956348/214890164-4fa6f6f8-7f96-4076-8be3-e5dad41ed748.png">

<img width="1033" alt="Screenshot 2023-01-26 at 6 20 51 PM" src="https://user-images.githubusercontent.com/22956348/214890224-9a815e63-6351-43b5-85b0-da43062eff7a.png">

<img width="1171" alt="Screenshot 2023-01-26 at 6 21 27 PM" src="https://user-images.githubusercontent.com/22956348/214890372-e24eb708-e38f-46ce-be29-4565ce383a60.png">

**Comment by MariannaPaszkowska** [comment]
<img width="896" alt="Screenshot 2023-02-14 at 5 23 09 PM" src="https://user-images.githubusercontent.com/22956348/218781197-6402905f-75a9-45ea-a32e-d16c158a3191.png">

**Comment by MariannaPaszkowska** [comment]
@cecidcd @sannorozco 
ROND100 - issues that still need addressing:
<img width="1205" alt="Screenshot 2023-02-24 at 3 15 36 PM" src="https://user-images.githubusercontent.com/22956348/221187751-fd5bca8c-07c2-4651-afcb-19a462354d57.png">

for comparison ROND0 (G and $ have small issues)
<img width="1189" alt="Screenshot 2023-02-24 at 3 15 52 PM" src="https://user-images.githubusercontent.com/22956348/221187777-8407c4f1-81cc-44e5-92a9-e9f7881c007b.png">

**Comment by MariannaPaszkowska** [comment]
@sannorozco <img width="994" alt="Screenshot 2023-02-27 at 10 37 04 AM" src="https://user-images.githubusercontent.com/22956348/221514049-1301dfb8-53ac-4a49-87c7-6dbbeab43048.png">

**Comment by sannorozco** [comment]
This has been fixed.

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates. I confirm that this is fixed. Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4303113101)
