### ISSUE TITLE
interpolation design - Q

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#225]
Add sparse masters to adjust the interpolation of the Q to avoid:

<img width="490" alt="Screenshot 2023-01-11 at 8 39 13 PM" src="https://user-images.githubusercontent.com/22956348/211891259-725ff6db-ad26-498f-8d61-b887416a27a0.png">
<img width="602" alt="Screenshot 2023-01-11 at 7 33 40 PM" src="https://user-images.githubusercontent.com/22956348/211891276-318a8a04-3280-4a6f-845f-e40280d19541.png">
<img width="674" alt="Screenshot 2023-01-11 at 7 31 11 PM" src="https://user-images.githubusercontent.com/22956348/211891296-682c8651-cb77-45de-b71b-a2d1701231e6.png">
<img width="565" alt="Screenshot 2023-01-11 at 7 30 53 PM" src="https://user-images.githubusercontent.com/22956348/211891312-a9cb649a-e3f1-4ec0-a3ab-b10f11f13752.png">
<img width="163" alt="Screenshot 2023-01-11 at 7 29 46 PM" src="https://user-images.githubusercontent.com/22956348/211891386-9a8e79e6-972f-4685-ab2d-6ee44b2bbad2.png">

**Comment by sannorozco** [comment]
Added SPARSE for Q, might need to add another at 18 25.

**Comment by MariannaPaszkowska** [comment]
@Santiago The interpolation of the Q looks much better, but there are still places where it needs warping: <img width="529" alt="Screenshot 2023-01-26 at 6 14 23 PM" src="https://user-images.githubusercontent.com/22956348/214888615-d3a57bcb-9beb-4d7b-90bf-4783735963d6.png">
<img width="492" alt="Screenshot 2023-01-26 at 6 15 42 PM" src="https://user-images.githubusercontent.com/22956348/214888928-1b0a0928-0972-4797-86a5-94bf37959c43.png">
