### ISSUE TITLE
Add full kerning (all masters)

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#226]
**Left to-do:**
- [x] copy kern to ROND
- [x] copy kern to GRAD
- [x] add wdth 85 masters
- [x] add wdth 50 masters 
related #422 

**Priorities:** 
- Axes: opsz, weight, width, GRAD, ROND

- Priority pairs: Kerning with priority suggestions can be found [here](https://github.com/googlefonts/googlesans-flex/blob/main/list-prioritykernsGSF.txt).

**Masters to be kerned:**

- [x] opsz 6, wdth 100, wght 400
- [x] opsz 6, wdth 100, wght 1
- [x] opsz 6, wdth 100, wght 1000
- [x] opsz 6, wdth 25, wght 400
- [x] opsz 6, wdth 25, wght 1
- [x] opsz 6, wdth 25, wght 1000
- [x] opsz 6, wdth 151, wght 400
- [x] opsz 6, wdth 151, wght 1
- [x] opsz 6, wdth 151, wght 1000
- [x] opsz 18, wdth 100, wght 400 - characters from https://github.com/googlefonts/googlesans-flex/issues/72 need kerning
- [x] opsz 18, wdth 100, wght 1
- [x] opsz 18, wdth 100, wght 1000 - characters from https://github.com/googlefonts/googlesans-flex/issues/72 need kerning
- [x] opsz 18, wdth 25, wght 400
- [x] opsz 18, wdth 25, wght 1
- [x] opsz 18, wdth 25, wght 1000
- [x] opsz 18, wdth 151, wght 400
- [x] opsz 18, wdth 151, wght 1
- [x] opsz 18, wdth 151, wght 1000
- [x] opsz 144, wdth 100, wght 400
- [x] opsz 144, wdth 100, wght 1
- [x] opsz 144, wdth 100, wght 1000
- [x] opsz 144, wdth 25, wght 400
- [x] opsz 144, wdth 25, wght 1
- [x] opsz 144, wdth 25, wght 1000
- [x] opsz 144, wdth 151, wght 400
- [x] opsz 144, wdth 151, wght 1
- [x] opsz 144, wdth 151, wght 1000

**Comment by MariannaPaszkowska** [comment]
@dberlow @sannorozco This is really great; thank you, I can confirm that we received kerning. The reviews are in progress; I'll keep you updated. 
CC @chrissimpkins https://github.com/googlefonts/googlesans-flex/actions/runs/4261168369

**Comment by sannorozco** [comment]
@MariannaPaszkowska , I’ll make another update later today, I need to make another pass.
I’ll keep you updated.

**Comment by sannorozco** [comment]
@MariannaPaszkowska Yesterday I added the interpolated kerning to the width intermediates.

**Comment by MariannaPaszkowska** [comment]
@sannorozco Those sources have no kerning:

- GoogleSansFlex-opsz17.999-wdth25-wght1-ROND0.ufo:                     
- GoogleSansFlex-opsz17.999-wdth25-wght400-ROND0.ufo:                   
- GoogleSansFlex-opsz17.999-wdth25-wght1000-ROND0.ufo:    

Is this intentional?

**Comment by sannorozco** [comment]
These are updated now.
