### ISSUE TITLE
Add subsetter step in build pipeline

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#228]
Thoughts about adding a subsetter step to the build pipeline?  We include the fonttools subsetter in Google Sans builds.  Should we keep this approach consistent in GS Flex?  This will remove everything that is unencoded and unreachable.  We can also address issues like #227 at this stage of the build process.

Let's discuss and decide.  Not urgent.  This is part of the March targeted work.

**Comment by madig** [comment]
I think it's a good idea, paired with feedbacking dropped glyphs to whoever put them in, so we can ideally clean the sources.

**Comment by chrissimpkins** [comment]
added in https://github.com/googlefonts/googlesans-flex/pull/369
