### ISSUE TITLE
Review gasp and prep table definitions for unhinted TTF variable fonts

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#229]
@chrissimpkins, i think these values, along with an instruction to change them at opsz144 below wght 20 or so, could be researched to prevent disappearance of the lightest weights, as seen in Chrome.See issue #115.Thanks.

_Originally posted by @dberlow in https://github.com/googlefonts/googlesans-flex/issues/222#issuecomment-1378715734_

**Comment by MariannaPaszkowska** [comment]
#115

**Comment by chrissimpkins** [comment]
Apologies, it looks like this is a duplicate of #115.  I wasn't aware that was open when David commented yesterday.  Closing.

**Comment by MariannaPaszkowska** [comment]
np @chrissimpkins! It's better to have a double issue than miss out on something. Thank you! :)
