### ISSUE TITLE
Fix interpolation: øØ

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#230]
<img width="772" alt="Screenshot 2023-01-12 at 5 01 15 PM" src="https://user-images.githubusercontent.com/22956348/212102179-b975d44b-95cc-442f-a679-56e92516299a.png">
<img width="876" alt="Screenshot 2023-01-12 at 5 02 08 PM" src="https://user-images.githubusercontent.com/22956348/212102195-4dcb52b0-f44b-4562-90b8-9c38d4645f3b.png">

<img width="751" alt="Screenshot 2023-01-12 at 5 03 15 PM" src="https://user-images.githubusercontent.com/22956348/212102132-6eec5471-282d-41c8-bd10-2f3baa25c0dc.png">
<img width="720" alt="Screenshot 2023-01-12 at 5 02 47 PM" src="https://user-images.githubusercontent.com/22956348/212102151-76b6d49f-0ef9-4eab-8f0f-fed380313006.png">

<img width="539" alt="Screenshot 2023-01-12 at 5 07 43 PM" src="https://user-images.githubusercontent.com/22956348/212102983-f3a54b12-15d2-4098-89d4-390159fe24e3.png">

**Comment by MariannaPaszkowska** [comment]
This is still an issue, Reviewed today, [this ](https://github.com/googlefonts/googlesans-flex/actions/runs/4103075184) build <img width="559" alt="Screenshot 2023-02-06 at 6 51 00 PM" src="https://user-images.githubusercontent.com/22956348/217033486-31b4d340-076c-440e-8be6-fbddfe40c505.png">
@sannorozco is this still in progress? I am trying to understand if we're not losing anything during the import.

**Comment by sannorozco** [comment]
@MariannaPaszkowska, we just updated the bars on all sources a couple of hours ago, first we did all of them on all 80 sources so there are no gaps. What I’ll be doing is re interpolate the SPARSE where we open the bars.

I’ll let you know when is ready for review.

Cheers!

**Comment by chrissimpkins** [comment]
Miguel is working on this.  In progress.

**Comment by MariannaPaszkowska** [comment]
@sannorozco This is still to-do: <img width="673" alt="Screenshot 2023-02-20 at 4 10 20 PM" src="https://user-images.githubusercontent.com/22956348/220130033-d56fb830-119b-4f42-a4a3-e7bcd90832fb.png">

**Comment by MariannaPaszkowska** [comment]
We decided to keep the glyph without the intermediate masters for the next release and come back to this later.

**Comment by dberlow** [comment]
Close this?

**Comment by MariannaPaszkowska** [comment]
We were targeting this release to improve this: <img width="698" alt="Screenshot 2023-05-18 at 4 13 52 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/e269423e-2c46-4700-ac4b-c061629dc4d1">

**Comment by MariannaPaszkowska** [comment]
@sannorozco what's the status on this one?

**Comment by sannorozco** [comment]
@MariannaPaszkowska I’ll be pushing a solution later today, gimme a couple of hours.

**Comment by sannorozco** [comment]
Hallo @MariannaPaszkowska, this was updated.
