### ISSUE TITLE
Performance improving ideas

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#24]
By the very nature of Google Sans Flex, there are going to be a lot of masters, and an incredibly high number of glyph instances. We have produced a spreadsheet that estimates the number of glyphs based on scripts, axes, etc.

  |   | Flex (production notes estimate) |   |   |   |  
-- | -- | -- | -- | -- | -- | --
  | Masters | 150 |   |   |   |  
  | Glyphs | 340 |   |   |   |  
  | Uprights/Italics | 2 |   |   |   |  
  | Total glyph instances | 102,000 |   |   |   |  
  |   |   |   |   |   |  
  |   | Google Sans Flex (per-axis estimate) |   |   |   | Google Sans
Masters | Weight | 3 | 3 |   | Masters | 8
Width | 3 | 9 |   | Glyphs | 6,871
Opsz | 3 | 27 |   | Uprights/Italics | 2
Grade | 3 | 81 |   | Total glyph instances | 109,936
Round | 2 | 162 |   |   |  
Uprights/Italics | 2 | 324 |   |   |  
  | Glyphs | 340 |   |   |   |  
  | Total glyph instances | 110,160 |   |   |   |  
  |   |   |   |   |   |  
  |   | Google Sans Flex simulation with same glyph set as Google Sans |   |   |   |  
Masters | Weight | 3 |   |   |   |  
Width | 3 |   |   |   |  
Opsz | 3 |   |   |   |  
Grade | 3 |   |   |   |  
Round | 2 |   |   |   |  
Uprights/Italics | 2 |   |   |   |  
  | Glyphs | 6,871 |   |   |   |  
  | Total glyph instances | 2,226,204 | 20.25 | times Google Sans |   |  

For the first release of GS Flex, we will sit incredibly close to the glyph instance count of Google Sans, so performance work is not urgent for this quarter.

However, this will scale rapidly with the addition of new scripts, and thus we are considering what can be done to help keep build times manageable.

Ideas:
- [ ] Set up pypy (keep separate/optional, but always use on CI)
- [x] Use `uharfbuzz` for packing, pruning, and 
- [ ] `uharfbuzz` for cutting instances (once stable)
- [ ] Use the `ufo2ft` kern splitter
- [ ] Slice static fonts from the big VF

**Comment by madig** [comment]
I'm looking at using Pypy, but the build setup makes this hard. We want to avoid depending on lxml, because it actually makes source loading slower than when using CPython, but gftools pulls in several deps that hardcode a dependency on it (nanoemoji, fontfeatures, picosvg). Maybe one solution would be to change fontTools to not use lxml if not running on CPython...
