### ISSUE TITLE
Review MVAR table

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#246]
Are the included metrics and data in the Google Sans Flex RC.2 build MVAR table as expected?  

[GS-Flex-MVAR.ttx.zip](https://github.com/googlefonts/googlesans-flex/files/10427096/GS-Flex-MVAR.ttx.zip)

cc @MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
I checked MVAR in [this font](https://github.com/googlefonts/googlesans-flex/releases/tag/v1.000-RC.2). I think it needs revisiting, and here are my findings:

Tags included in the MVAR table:
'hasc'	horizontal ascender	OS/2.sTypoAscender
'hcrs'	horizontal caret rise	hhea.caretSlopeRise
'hdsc'	horizontal descender	OS/2.sTypoDescender
'sbxs'	subscript em x size	OS/2.ySubscriptXSize
'sbyo'	subscript em y offset	OS/2.ySubscriptYOffset
'spxs'	superscript em x size	OS/2.ySuperscriptXSize
'spyo'	superscript em y offset	OS/2.ySuperscriptYOffset
'spys'	superscript em y size	OS/2.ySuperscriptYSize
'stro'	strikeout offset	OS/2.yStrikeoutPosition
'strs'	strikeout size	OS/2.yStrikeoutSize 
'undo'	underline offset	post.underlinePosition
'unds'	underline size	post.underlineThickness
'xhgt'	x height	OS/2.sxHeight

included, but don't seem to vary: 
'undo'	underline offset	post.underlinePosition
'unds'	underline size	post.underlineThickness
'xhgt'	x height	OS/2.sxHeight

Vary along the ROND in opsz18+ and shouldn't: 
'hdsc'	horizontal descender	OS/2.sTypoDescender
'hasc'	horizontal ascender	OS/2.sTypoAscender
'strs'	strikeout size	OS/2.yStrikeoutSize 

In opsz 6-18 MVAR values seem incorrect. Example: x-height doesn't align with x.
I was testing with Samsa.
