### ISSUE TITLE
Release GitHub Actions workflow runs multiple times on the same git tag

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#253]
@RickyDaMa @madig Any idea why this might be happening when I attempt the release on a commit in the git history?

![hgPJszmzdk6ZVTs](https://user-images.githubusercontent.com/4249591/213298620-73d6e8f6-dbc6-4693-bc37-ec93e9db91ff.png)

It looks like it fired off four different actions at the `v1.000` git tag based release generation.

**Comment by madig** [comment]
Heh :) It fired one for each 1) created, 2) released, 3) published and 4) edited :)
