### ISSUE TITLE
Use fontbakery exit status codes in the GitHub Actions CI tests

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#254]
The non-zero fontbakery exit status code [is currently defined as acceptable](https://github.com/googlefonts/googlesans-flex/actions/runs/3953017972) and CI passes despite failing tests to allow the completion of the workflows.  Let's confirm that we toggle the non-zero exit status code back on so that the CI fails in advance of our March release when we are comfortable that we have either addressed the failing issues or ignore the fontbakery check as not relevant in this project.

**Comment by madig** [comment]
Note to self: see if warnings cause an error exit code; if so, we might need to prune more checks.

**Comment by chrissimpkins** [comment]
I don't believe that warnings use non-zero exit status codes.

**Comment by madig** [comment]
Warnings won't stop the test run, yes. I suppose that's what we want.

@MariannaPaszkowska there is a PR for this: #257
