### ISSUE TITLE
import workflow fails 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#258]
https://github.com/googlefonts/googlesans-flex/actions/runs/3957847338/jobs/6778708605#step:9:534
```
Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation:
GDEF.table.Version

The problem is likely to be in Google Sans Flex opsz18-wdth100-wght579-ROND0-SPARSE:
Expected to see .Version==65538, instead saw 65536
```

**Comment by madig** [comment]
Aside, /a, /nine, /fiv, /cent, /r and /six have inconsistent Unicode values across masters. It seems to be missing in places. https://github.com/googlefonts/googlesans-flex/pull/67 would fix it.

**Comment by madig** [comment]
The problem here is that the various "SPARSE" UFOs only contain a couple of glyphs, but are treated as "full UFOs" by the compiler, leading to a mismatch of feature code to be merged. The fix is to go to the Designspace file and add `layer="public.default"` to sparse sources, like so:

```xml
<source filename="GoogleSansFlex-opsz18-wdth100-wght699-ROND0-SPARSE.ufo" familyname="GoogleSansFlex" stylename="opsz18-wdth100-wght699-ROND0-SPARSE" layer="public.default">
```

**Comment by MariannaPaszkowska** [comment]
Hi @sannorozco, have you had a chance to work on this? I tried to import sources today and had the same issue: https://github.com/googlefonts/googlesans-flex/actions/runs/3966507980 
If you can get to it, it would be very helpful. I'd like to review the build to close some of the open issues.

**Comment by sannorozco** [comment]
Hi @MariannaPaszkowska , not yet, it’s gonna be worked over the weekend, since I need to change layer name on all sources. Will be ready by Monday.

**Comment by sannorozco** [comment]
Hi @MariannaPaszkowska, this was updated.

**Comment by MariannaPaszkowska** [comment]
Thank you! I can confirm it
