### ISSUE TITLE
Add some punctuation and space characters 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#259]
0x2022 (BULLET)
0x2013 (EN DASH)
0x2014 (EM DASH)
0x2212 (MINUS SIGN)
0x2026 (HORIZONTAL ELLIPSIS)
0x2122 (TRADE MARK SIGN)

Space characters:
Em Space U+2003
En Space U+2002
Thin Space U+2009
Hair Space U+200A
Figure Space U+2007 (optional)

The full character set can be found [here](https://github.com/googlefonts/googlesans-flex/issues/41)

@RickyDaMa @madig, we should also add those to our production lists.

**Comment by dberlow** [comment]
I have added these except I already included a "space.tf", for tabular,use, If that's okay. 

The regular space is fine with proportional figures, and in tabular use the space must be the same as the figures.

**Comment by tiroj** [comment]
/space.tf could be encoded as U+2007 FIGURE SPACE, which is intended to be the same width as tabular numerals.

**Comment by MariannaPaszkowska** [comment]
Thank you, @tiroj! This is what we will do.
