### ISSUE TITLE
Set up diffenator2

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#26]
[diffenator2](https://github.com/m4rc1e/diffenator2) ([GitHub action](https://github.com/f-actions/diffenator2))

Potential use cases (feedback/ideas welcome!):
1. Regression testing source updates / new scripts (ensuring nothing that wasn’t supposed to be changed has been changed)
1. Regression testing after build/pipeline dependency updates
1. Regression testing any changes in workflow/repo (i.e. migrating to Font Gardener #25)

Our understanding of future work/functionality of diffenator2 and how it related to Google Sans Flex:
1. [ ] Inclusion of AOSP word list
2. [ ] Inclusion of Google products / custom word lists
3. [ ] Inclusion of strings from Kalapi's web tester documents, see https://github.com/googlefonts/googlesans/pull/520#issuecomment-1304805162 

Integration with Google Sans Flex:
- [ ] Add GitHub action to CI workflow (as a manually triggered step/workflow?)

**Comment by MariannaPaszkowska** [comment]
Hi @m4rc1e, we think now is a great time to include the diffenator2 in our workflow. Are there any issues we should be aware of?

**Comment by m4rc1e** [comment]
My only concern is that it can only compare fvar instances atm. imo, it would be nice if we could also compare arbitrary coords.

**Comment by madig** [comment]
Hum... The action would need access to the GSF repo, right? Which would mean personal access tokens? I think @chrissimpkins said Google is currently skittish around those...

**Comment by m4rc1e** [comment]
No PATs needed. Each github actions run creates a PAT which lasts the lifetime of the job. We may be able to use this like we do in google/fonts, https://github.com/google/fonts/blob/main/.github/workflows/test.yaml#L23

**Comment by madig** [comment]
@m4rc1e kthx! Good to know. I'm running into a wall though: https://github.com/googlefonts/googlesans-flex/actions/runs/4065559440/jobs/7000430937#step:6:2175. Like what?

**Comment by m4rc1e** [comment]
@madig apologies, the diffenator2 action hadn't been updated in a while. I've rerun the job so let's see what happens.

**Comment by madig** [comment]
@m4rc1e @MariannaPaszkowska what is left to do here?

**Comment by m4rc1e** [comment]
I'm sure it's done. Same as the other project, push a branch with the prefix `push-` to trigger the diffenator2 action.
