### ISSUE TITLE
Check and fix GRAD reflow

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#261]
The following glyphs have variation in horizontal advance due to the GRAD axis: `onesuperior`, `twosuperior` and `threesuperior`. Please check and fix, this will cause the build to fail (it's one of the fontbakery checks).

**Comment by sannorozco** [comment]
Hallo Marianna,

This morning I checked the my local and repository’s branch sources and these have the same width between the default, GRAD-50, & GRAD50. Also checked the compiled VFs and I don’t see any width advance.

https://user-images.githubusercontent.com/1184152/213831123-6ba71e8e-2d7f-4603-a739-8febe02ce987.mov

**Comment by chrissimpkins** [comment]
Following the addition of fea code support we are seeing these new fontbakery advance width check flags:

- zeroslash.tf
- a.alt

```
FAIL The following glyphs have variation in horizontal                     
          advance due to the GRAD axis: zeroslash.tf and a.alt [code:           
          grad-causes-reflow]  
```

**Comment by chrissimpkins** [comment]
How was this resolved? All fixed?

**Comment by MariannaPaszkowska** [comment]
All fixed, FontBakery is not reporting variation in horizontal advance due to the GRAD axis anymore.
