### ISSUE TITLE
New glyph repertoire

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#265]
In FB-wip/source/exeperiments/ is a font
GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD0-A

This font’s glyph set contains all the glyphs I’m aware of the need to add for the upcoming product.

The set was gathered from:
#72, (without most of the ligatures at the top). It includes glyphs for issues [#243](https://github.com/googlefonts/googlesans-flex/issues/243) [#223](https://github.com/googlefonts/googlesans-flex/issues/223) [#259](https://github.com/googlefonts/googlesans-flex/issues/259) [#234](https://github.com/googlefonts/googlesans-flex/issues/234) referenced in #72.
#33 where all the features that require glyphs have been checked off except for “lnums”. this includes ss01 and ss02, alt /a and /g, with their accented accompaniment and the /ae also required.
Three glyphs have been allotted for a future squiggle and its initial and finial

Next steps: We recommend 
1. adding the feature code required for this product
2. building a ttf 
3. Testing and verifying it for language support
4. Testing and verifying it for feature support

**Comment by chrissimpkins** [comment]
We are prepared to review the OpenType feature support in builds as soon as the Font Bureau team implements the OpenType feature shaping source in Adobe format fea files.

**Comment by sannorozco** [comment]
@chrissimpkins @MariannaPaszkowska @dberlow Updated features and generated static ttf on fb-wip branch at [googlesans-flex/sources/experiments/Full Charset Features/GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD0.ttf](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/sources/experiments/Full%20Charset%20Features/GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD0.ttf)

**Comment by MariannaPaszkowska** [comment]
https://github.com/googlefonts/googlesans-flex/blob/fb-wip/fonts/GoogleSansFlex-Alpha1.0%5BGRAD%2CROND%2Copsz%2Cwdth%2Cwght%5D-VF.ttf

Missing glyphs (some could be missing Unicodes): 
```
-ligatures:
f_b
f_f
f_f_b
f_f_h
f_f_i
f_f_j
f_f_k
f_f_l
f_f_t
f_h
f_j
f_k
f_t
t_f
t_t

aeacute.alt
gcircumflex.alt

uni0123.alt ģ.alt

zero.slash

wiggle.init
wiggle.medium
wiggle.final

- to import (please import unchanged from Google Sans, it should stay identical across masters):
G.super 
Gsuper u+E005
G.logo
e.logo
g.logo
l.logo
o.logo
Google.logo
```


Can we also add those to the character set? I realized that I missed those in my previous list. I'll add them also to #72 
```
- no-outlines:
CR u+000D
figurespace u+2007
fourperemspace u+2005 
sixperemspace u+2006
threeperemspace u+2004
zerowidthspace u+200B

- composed:
zeroinferior u+2080
oneinferior u+2081
twoinferior u+2082
threeinferior u+2083
fourinferior u+2084
fiveinferior u+2085
sixinferior u+2086
seveninferior u+2087
eightinferior u+2088
nineinferior u+2089

zerosuperior u+2070
fivesuperior u+2075
sixsuperior u+2076
sevensuperior u+2077
eightsuperior u+2078
ninesuperior u+2079
```

**Comment by dberlow** [comment]
These are included already:
- composed:
zeroinferior u+2080
oneinferior u+2081
twoinferior u+2082
threeinferior u+2083
fourinferior u+2084
fiveinferior u+2085
sixinferior u+2086
seveninferior u+2087
eightinferior u+2088
nineinferior u+2089

These should have been included, my mistake.
zerosuperior u+2070
fivesuperior u+2075
sixsuperior u+2076
sevensuperior u+2077
eightsuperior u+2078
ninesuperior u+2079

This is included in the font already
"zero.slash

this is the third glyph in the font"
u+000D
Do you want it renamed?

This;
figurespace u+2007
...is included as as "space.tf" so when figures are used with a space, and then changed to tabular, the user doesn't. have to search and replace space for figurespace. or we rename and add the space/figurespace replacement. 

These are included, named "squiggle". Do you want name change to:
wiggle.init
wiggle.medium
wiggle.final

Are these part of this release?
-ligatures:
f_b
f_f
f_f_b
f_f_h
f_f_i
f_f_j
f_f_k
f_f_l
f_f_t
f_h
f_j
f_k
f_t
t_f
t_t
...and 
G.super 
Gsuper u+E005
G.logo
e.logo
g.logo
l.logo
o.logo
Google.logo
?

**Comment by dberlow** [comment]
The Google logo glyphs have now been added.

**Comment by MariannaPaszkowska** [comment]
Notes from the discussion today: yes, we should add the ligatures and import Google logo symbols. Logo symbols will require refinement after rescaling and conversion from cubic outlines to quadratic. They should be visually identical to what is in GS v10. There won't be design edits to the logos.

**Comment by MariannaPaszkowska** [comment]
Thank you for adding the logos @dberlow. That was faster than my comments :)

**Comment by dberlow** [comment]
No problem.On Jan 25, 2023, at 3:56 PM, Marianna Paszkowska ***@***.***> wrote:﻿
Thank you for adding the logos @dberlow. That was faster than my comments :)

**Comment by sannorozco** [comment]
This was updated with all glyphs now, including ligatures and Google logo.

**Comment by sannorozco** [comment]
@chrissimpkins @MariannaPaszkowska @dberlow Updated features and generated static ttf on fb-wip branch at [googlesans-flex/sources/experiments/Full Charset Features/GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD0.ttf](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/sources/experiments/Full%20Charset%20Features/GoogleSansFlex-opsz18-wdth100-wght400-ROND0-GRAD0.ttf)
