### ISSUE TITLE
Collidoscope's fontbakery integration

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#276]

**Comment by chrissimpkins** [comment]
Has this been addressed?

**Comment by madig** [comment]
It's my interpretation that the integration of the new collidoscope is probably postponed to after fontbakery 0.8.11, because the dep updates are in this PR: https://github.com/googlefonts/fontbakery/pull/3981#issuecomment-1448030156.

**Comment by felipesanches** [comment]
yes. But that will happen very soon, since I am about to cut the stable release this week

**Comment by chrissimpkins** [comment]
Thanks! Let's please not update any *compiler* dependencies this close to the release. If the fontbakery update does not touch those then we should be OK.  Else, let's find a way to run it outside of the pipeline until after we push the release files.

**Comment by madig** [comment]
It's relatively easy to put fontbakery and its deps into an isolated venv away from other dependencies if need be.

**Comment by madig** [comment]
Is not updating compiler deps still a concern? I could also implement a separate venv with an ever up to date fontbakery.

**Comment by MariannaPaszkowska** [comment]
We need to rebase #282 and move it to a standalone script.

**Comment by MariannaPaszkowska** [comment]
closed by #282
