### ISSUE TITLE
Import and review feature code from fb-wip

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#277]
https://github.com/googlefonts/googlesans-flex/issues/265#issuecomment-1404525428 

Feature code: https://github.com/googlefonts/googlesans-flex/tree/fb-wip/sources/experiments/Full%20Charset%20Features/features

**Comment by MariannaPaszkowska** [comment]
https://github.com/googlefonts/googlesans-flex/issues/33

**Comment by madig** [comment]
All the referenced glyphs need to be imported into main first before most of the feature code works. See https://github.com/googlefonts/googlesans-flex/pull/273.
