### ISSUE TITLE
Wiggle glyph

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#287]
Left to do:
- [x] remove/replace all wdth masters. 

Done:
- [x] Add wiggle design to the regular master and copy to all masters
<img width="329" alt="Screenshot 2023-01-31 at 3 38 20 PM" src="https://user-images.githubusercontent.com/22956348/216131507-944d5053-5861-40d5-b6ae-4c94df9dfc59.png">

- [x] Design weight masters wiggle 
- [x] Add width opsz for the wiggle
- [x] add to the liga feature. 
In calt and triggered by `:~`:
```
sub colon asciitilde colon by wiggle;
sub wiggle asciitilde' by wiggle; #optionally 
```

**Comment by MariannaPaszkowska** [comment]
Comment from @dberlow (Daily stand-up meeting): We can add opsz with 2 additional masters.

**Comment by dberlow** [comment]
SO,
This wiggle glyph is complete up to the sparse masters of ROND0 below. 
<img width="436" alt="Screen Shot 2023-02-04 at 10 52 15 AM" src="https://user-images.githubusercontent.com/1956494/216777146-dd4dfa3e-6841-4ff5-9924-064ddbe71938.png">

I began grade, but the realized that was not required so it is unchanged. 

Once this is approved and or edited, and a decision is made on ROND100, we can update the remainder of the sources. 

The next build can show all of ROND0.

**Comment by dberlow** [comment]
The near-future state is that shutting off the width axes over the design space for that glyph will take a bit of time without sparse masters.

E.g., we could just delete a bunch of contours in the wdth axes and be done, but instead we must replace the wiggles on the wdth axes with wiggles from elsewhere, to stop width changes on that glyph.Same is true of logo characters and sparse masters. 

There would be just one set of contours in the default, and nothing else to do for those glyphs in the rest of the design space.

**Comment by chrissimpkins** [comment]
The width master definitions are being replaced with default master definitions

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates to wiggle @dberlow! 
I can confirm no width changes anymore.

**Comment by MariannaPaszkowska** [comment]
Reopening because Rond masters need to be updated.
