### ISSUE TITLE
Our importer appears to remove main branch defined fea files

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#292]
... but our importer is deleting some master feature files (that import the main fea file) that are defined in the main branch. 

_Originally posted by @chrissimpkins in https://github.com/googlefonts/googlesans-flex/issues/291#issuecomment-1413051544_

Occurred during attempt to perform a git commit SHA defined import with our importer workflow in #291

**Comment by chrissimpkins** [comment]
#294 added Python script to replace the files as a workaround for now so that we can use the importer

**Comment by madig** [comment]
Fixed by #329, UFOs should always point to a shared family.fea where all feature development should take place.

**Comment by chrissimpkins** [comment]
Confirmed fix. Thanks Nikolaus!
