### ISSUE TITLE
Add avar1 for opsz

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#293]
Values from GSF CJK: 
```
opsz_map = {
    6: 0,
    8: 0.004,
    14: 10,
    17.999: 35.1988,
    18: 35.2,
    24: 73,
    92: 93,
    144: 100
}
```

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans-flex/pull/320
https://github.com/googlefonts/googlesans-flex/pull/335

**Comment by dberlow** [comment]
I've shared a comparison that's so far got no other information.

For now. 
1. each column is labeled for a different variable font
2. the widths of the columns showing each sample, and length of the sample string is constrained to the 24" width of my monitor. 
3. the images come from https://variable-type-tools.appspot.com/ (waterfall layout)
4. They are pasted together in the ".Sketch" file
5. that file is output to the ".pdf"
6. there are tiny numbers along the left of each column that indicate the size of each line

**Comment by MariannaPaszkowska** [comment]
We decided not to include it. Rationale: https://github.com/googlefonts/googlesans-flex/pull/335#issuecomment-1433125770
