### ISSUE TITLE
Missing ss01 and ss02 alternate glyphs

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#298]
Fontmake raises an error about the following missing glyphs when I attempted to implement the extended alternate-a and alternate-g feature code defined for `ss01` and `ss02`:

- acaron.alt
- gcommaaccent.alt

```
fontmake.errors.FontmakeError: In 'regular/GoogleSansFlex.designspace': Generating fonts from Designspace failed: The following glyph names are referenced but are missing from the glyph set:
 acaron.alt (first found at /Users/chris/code/google/googlesans-flex/sources/regular/family.fea:219:135)
 gcommaaccent.alt (first found at /Users/chris/code/google/googlesans-flex/sources/regular/family.fea:222:21)
```

@MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
I can see [acaron.alt.glif](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/sources/roman/GoogleSansFlex-opsz6-wdth151-wght1000-ROND0.ufo/glyphs/acaron.alt.glif) and [gcommaaccent.alt.glif](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/sources/roman/GoogleSansFlex-opsz6-wdth151-wght1000-ROND0.ufo/glyphs/gcommaaccent.alt.glif) in the sources. 
They're not building, I'm looking into that.

**Comment by chrissimpkins** [comment]
The glyphs will be available in the next import following the merge of https://github.com/googlefonts/googlesans-flex/pull/303
