### ISSUE TITLE
using Github desktop...

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#3]
I downloaded the "code" 

I get No Branches and No Sources.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1956494/189673004-4970d8d2-cc7f-43d2-9d83-e4696229caeb.png">

Where do I commit?

Thanks.

**Comment by belluzj** [comment]
Hello David, you're not supposed to look into the .git folder yourself, you should use a Git client, for example on Mac you could use Fork: https://git-fork.com/ (that's what designers like to use at Dalton Maag).

The git tool or the Fork UI for it will manage the contents the project's folder for you, detect changes after you edit the files, and propose to you a way to commit.

**Comment by chrissimpkins** [comment]
I spoke with David and Santiago about this issue over the last couple weeks and again today.

Santiago will commit the changes in a non-main branch of this repository to take advantage of the new build process that was added in #2 and follow the traditional PR review workflow to propose changes intended for the main branch. @dberlow, I am happy to help get you set up with a GUI tool to manage git branch work if you are interested to push to a branch yourself. We can create the branch for you or you are welcome to create and manage your own branches.  Will close this issue.
