### ISSUE TITLE
Comparison testing between Google Sans & Google Sans Flex

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#30]
Google Sans will be used as a fallback font for Flex, so ensuring there aren't jarring differences between them would be useful

**Comment by belluzj** [comment]
Copy the fontbakery profile from GS https://github.com/googlefonts/googlesans/blob/main/qa/check-googlesans.py

Comment all checks and progressively uncomment, starting with the vertical metrics, to match GS v10.

Also, add a .highdef glyph to GSFlex so that the yMin yMax are the same as GS v10

**Comment by MariannaPaszkowska** [comment]
@belluzj Thank you for the preview today! It looks great, here are more ideas from today's meeting: 

- [x] Add the tool to the repository
- [x] Add kern on/of function
- [x] Feature legend: Show full file names of the fonts (or name table names) that are loaded and mark them with colors

**Comment by belluzj** [comment]
@MariannaPaszkowska I added the tool to the repository, and you'll find [in the PR description](https://github.com/googlefonts/googlesans-flex/pull/43) a link to the index.html (as a ZIP file) of the app, so you can test it locally. Let me know if it works for you and what else I can add.

You mentioned adding known instances, which I haven't done yet. What did you have in mind? A dropdown with the instances of Google Sans?

**Comment by MariannaPaszkowska** [comment]
Fantastic, thank you! 
Yes, let's add the instance lists:
- [x] Add drop-down lists with font instances. 

I think it should be two lists, one for each font. They should work independently, just like the sliders. 
What do you think, @belluzj @chrissimpkins?

**Comment by madig** [comment]
Some attributes can be checked by #45.

**Comment by belluzj** [comment]
> I think it should be two lists, one for each font. They should work independently, just like the sliders.

@MariannaPaszkowska To clarify: currently the sliders act on both fonts. Do you mean that you would prefer a set of sliders for each font, that can behave independently from each other? That would be a pre-requisite to having 2 dropdown menus.

**Comment by MariannaPaszkowska** [comment]
Ok, thanks for clarifying that. Then it makes more sense to keep just one list.

**Comment by belluzj** [comment]
I will add one list then, pre-filled with the Google Sans instances. That way the app can be used to check how close the two fonts are in the scenario where designers currently using Google Sans would swap in Google Sans Flex with the same axis configuration.

**Comment by dberlow** [comment]
This was not the plan, please chat with Dave

**Comment by belluzj** [comment]
Thanks @dberlow, I don't know the exact plan, I'll let @MariannaPaszkowska confirm how she plans to use this tester/what she intends to check.

**Comment by MariannaPaszkowska** [comment]
@dberlow This is a tool I requested. It will be used to gather data on the differences between GS and GS Flex. I will need this data to support communication with our teams. This will help us successfully land the project.

**Comment by dberlow** [comment]
“Google Sans will be used as a fallback font for Flex”

We are not looking for the differences we are looking for the matches. And using Google Sans as fall back for google sans flex, The vast design space of google sans flex is almost entirely outside the design space of google sans.

The default should work :-)
