### ISSUE TITLE
add scientific inferiors feature

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#302]
```
feature sinf {
    # automatic
    sub zero by zeroinferior;
    sub one by oneinferior;
    sub two by twoinferior;
    sub three by threeinferior;
    sub four by fourinferior;
    sub five by fiveinferior;
    sub six by sixinferior;
    sub seven by seveninferior;
    sub eight by eightinferior;
    sub nine by nineinferior;
} sinf;
```

**Comment by chrissimpkins** [comment]
The goal is to change our current commented out sinf fea code:

https://github.com/googlefonts/googlesans-flex/blob/f1209a51749f813ecc76cd271255afc63d443e32/sources/regular/family.fea#L169-L181

to the glyph names you listed above?  This is how they are in fb-wip or we will need a rename?

**Comment by tiroj** [comment]
The `sinf` feature only existed because of a misunderstanding by Adobe in the early phase of OpenType. The output of the `sinf` feature should not differ from that of `subs`, presuming the latter is conventionally implemented, i.e. with the `subs` variants descending below the baseline.
