### ISSUE TITLE
Slash in zeroslash does not extend across the glyph over range wdth > 100

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#309]
Occurs across the full weight, opsz, grade, roundness range

![zero-slash](https://user-images.githubusercontent.com/4249591/216482789-b14390a3-eb15-40de-ae93-de43a0e5cd64.gif)

cc @MariannaPaszkowska @sannorozco @dberlow

**Comment by sannorozco** [comment]
Yes, this is being worked on at the moment.

**Comment by MariannaPaszkowska** [comment]
Confirming this is now fixed.
