### ISSUE TITLE
Automation for interpolation artifacts

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#31]
Because the designspace is so big with so many axes, some amount of computer help is going to be needed for this.

It may helps to have list(s) of designspace locations that need reviewing. Exhaustive testing will scale poorly as more axes are added.

Ideas *(tags don't indicate responsibility, just whose idea it was)*:
- video diffenator (@m4rc1e)
- Fontbakery outline tests (these rely on heuristics and thus aren't foolproof) (@madig)
- checking for smooth/harmonious nodes across the designspace (@belluzj)
- automated specimen generation (some prior work already done) (@chrissimpkins)

**Comment by belluzj** [comment]
We can start looking into this as well.

**Comment by belluzj** [comment]
The point is to support reviewers to know where to look for the problems (find the glyph + designspace location)

**Comment by MariannaPaszkowska** [comment]
Ideas from this issue were out into separate issues.
