### ISSUE TITLE
Fix tail of the Q 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#325]
<img width="536" alt="Screenshot 2023-02-06 at 4 00 51 PM" src="https://user-images.githubusercontent.com/22956348/216991371-527292ca-eaa2-4b94-a4b3-e5695c0871d4.png">
<img width="521" alt="Screenshot 2023-02-06 at 4 00 40 PM" src="https://user-images.githubusercontent.com/22956348/216991378-e987b0e3-ac1e-44b9-ab47-1c22dd2c9e38.png">

**Comment by MariannaPaszkowska** [comment]
<img width="708" alt="Screenshot 2023-02-14 at 6 46 21 PM" src="https://user-images.githubusercontent.com/22956348/218802266-ee4052e8-fbad-411a-a49e-b91d6818ae5b.png">
@dberlow @sannorozco This issue persists in the latest builds.

**Comment by chrissimpkins** [comment]
Miguel and Hector are working on this.  In progress.

**Comment by MariannaPaszkowska** [comment]
@sannorozco This is still To-Do: <img width="516" alt="Screenshot 2023-02-20 at 4 09 19 PM" src="https://user-images.githubusercontent.com/22956348/220129714-7a7e6f7d-001d-48de-962e-97fd401afb58.png">

**Comment by sannorozco** [comment]
@MariannaPaszkowska Added SPARSE sources to fix this.

**Comment by MariannaPaszkowska** [comment]
<img width="534" alt="Screenshot 2023-02-27 at 10 48 03 AM" src="https://user-images.githubusercontent.com/22956348/221516394-927b89f4-23cf-4ea2-81c0-c0b9370638af.png">

<img width="524" alt="Screenshot 2023-02-27 at 10 48 13 AM" src="https://user-images.githubusercontent.com/22956348/221516427-f7c81ca0-1b50-4715-a969-833a7f2b2130.png">
