### ISSUE TITLE
OpenType feature support: v1.1

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#33]
This is the set of OpenType feature support requirements for the first production release of Google Sans Flex.

- [x] calt - includes figure height centered colon between figure forms for horizontal time displays
- [x] liga - default f- and t-ligature forms
  - [x] wiggle ligature form composed with two asciitilde glyphs input (*we might need to move it to calt)
- [x] locl (Latin: Catalan, Romanian, Moldovan, Dutch, Lithuanian)
- [x] mark - mark positioning
- [x] mkmk - mark to mark positioning (as required by glyph repertoire)
- [x] frac - fractions
- [x] numr - numerator forms
- [x] dnom - denominators
- [x] tnum - tabular figures
- [x] pnum - proportional figures
- [x] lnum - lining figures
- [x] ordn - ordinals
- [x] sinf - scientific inferiors
- [x] subs - subscripts
- [x] sups - superscripts
- [x] stylistic set .ss01 for the alternate lowercase `a` form; friendly name: `single-story 'a'`
- [x] zero - an alternate slashed zero figure form
- [x] stylistic set .ss02 for the alternate lowercase `g` form 1 (two-story); friendly name: `two-story 'g' form 1`

Edit 17 Jan: added tags and user-friendly names of the stylistic sets 01 and 02.
Edit 6 Feb: removed "case - case-sensitive forms" out of scope

**Comment by davelab6** [comment]
`pnum` and `lnum` are non-operations unless `tnum` was set higher up in a CSS stylesheet and they are used to reset to default?

**Comment by tiroj** [comment]
If the fonts support dynamic mark positioning for composing diacritics, consider adding

- [ ] locl (Latin: Catalan, Romanian, Moldovan, Dutch, **Lithuanian**)

The convention in Lithuanian is not to suppress the dot on _i_ (and by extension _j_) when marks are added above, as may occur in dictionaries.

**Comment by chrissimpkins** [comment]
Thanks John!  

Lithuanian support is in scope for v1.  @sannorozco is John's recommendation something that you've come across in your lang support shaping review?

**Comment by chrissimpkins** [comment]
> `pnum` and `lnum` are non-operations unless `tnum` was set higher up in a CSS stylesheet and they are used to reset to default?

@davelab6 carry over from production Google Sans.  We can eliminate them if you do not feel that they are necessary

**Comment by MariannaPaszkowska** [comment]
@dberlow @sannorozco Here is a list of features we'd like to support in version 1.000.

**Comment by madig** [comment]
In GS, single-storey `a` is in ss08 and there is no single-storey g. For compatibility with GS, I suppose ss08 should stay; which one to use for the `g`? :)

**Comment by dberlow** [comment]
The Default g is one story.  There was a two-story g in GS. 

We are happy to name them anything that Google decides, but stylistic sets are best reserved for glyphs of an alternate desgn set, not an alternate glyph.

Both alternate g that we are working on and the alternate a are not part of any set, and are intended to be used individually.

**Comment by MariannaPaszkowska** [comment]
@madig Good question! We decided not to keep the names of Stylistic Set features backward compatible. 
In v.1.1 we aim to include two-story `g` and an alternate `a`. We probably will create stylistic sets with friendly names for both glyphs. I need to confirm that with the team. 
Also: I moved the two-story `g` feature to v.1.1 #48 - there was a change of scope recently.
CC @chrissimpkins @davelab6

**Comment by davelab6** [comment]
> > `pnum` and `lnum` are non-operations unless `tnum` was set higher up in a CSS stylesheet and they are used to reset to default?
> 
> @davelab6 carry over from production Google Sans. We can eliminate them if you do not feel that they are necessary

No no, just asking

Thanks for the Lithuanian tip John

**Comment by dberlow** [comment]
tnum - tabular figures are now being added. 

Along with the list given:
zero.tf one.tf two.tf three.tf four.tf five.tf six.tf seven.tf eight.tf nine.tf period.tf comma.tf colon.tf semicolon.tf numbersign.tf space.tf cent.tf currency.tf dollar.tf sterling.tf plus.tf multiply.tf divide.tf equal.tf greater.tf less.tf plusminus.tf logicalnot.tf percent.tf section.tf Euro.tf minus.tf notequal.tf

We recommend adding these glyphs:
Euro 
minus 
notequal 
approxequal 
...which are proportional counterparts to the tabular list above. 

And for compression, FB is adding these. 
notequal-slash 
equal-stroke 
percentbar.tf

Let us know here, thanks.

**Comment by moyogo** [comment]
@tiroj For Lithuanian, the future proof approach is to use the COMBINING DOT ABOVE between the i or the j and the accent. For example as used on this Lithuanian dictionary entry http://www.lkz.lt/Index_m.asp?zodis=ija&lns=-1&les=-1 where the characters are 0069, 0307, 0300.

The characters without combining dot may occur in pre-Unicode data, but users should be encouraged to use combining dot as that is non ambiguous and doesn't depend on what font, application or language tagging is used.

Not to sound like a broken record but such a feature also breaks any non-Lithuanian person or place name that does have an accented i (or j) when used in Lithuanian text and should not be used in a font with this scope.

**Comment by moyogo** [comment]
For example, these would be broken with a font that changes i and j with accents in Lithuanian: "Třeštíkova" in ["Herojus dešimtmečius stebinčią dokumentininkę vienas apiplėšė" on Lrytas.lt](https://www.lrytas.lt/kultura/kinas/2016/09/15/news/herojus-desimtmecius-stebincia-dokumentininke-vienas-apiplese-1121951), "Bolívarą" in ["Paslaptingieji masonai: mitai, faktai ir istorija" on Lrytas.lt](https://www.lrytas.lt/it/ismanyk/2022/02/16/news/paslaptingieji-masonai-mitai-faktai-ir-istorija-22246166), "Aníbalo" in ["Patirtis: dvidešimt vieneri Portugalijos metai su euru" on IQ.lt](https://iq.lt/finansai-ir-investavimas/patirtis-dvidesimt-vieneri-portugalijos-metai-su-euru/207107), or even "Dalí" in ["Salvador Dalí" on VLE.lt](https://www.vle.lt/straipsnis/salvador-dali/) where a PUA character is used for the i dot grave so clearly the authors did not want a dot in there or they would have used a PUA character as well in Dalí’s name.

**Comment by moyogo** [comment]
@tiroj  and of course the Unicode Standard adresses this:

![](https://forum.glyphsapp.com/uploads/default/original/2X/0/09a785ab2f242daa86c9e26237e6fb72d7188144.png)

![](https://forum.glyphsapp.com/uploads/default/original/2X/7/7baed2acda482f9299fdfda93e3bdb3c73422e92.png)

**Comment by tiroj** [comment]
I don’t recall seeing that figure before. Do you know when this text was added to Unicode?

I see the reasoning, and agree it is more robust. It is also kinda funny: we’re going to take away your dot, and then you can put your dot back, if you can figure out how to do that.

**Comment by moyogo** [comment]
> I don’t recall seeing that figure before. Do you know when this text was added to Unicode?

No. But it's in every version I checked since at least Unicode version 3.0 from 1999.

> I see the reasoning, and agree it is more robust. It is also kinda funny: we’re going to take away your dot, and then you can put your dot back, if you can figure out how to do that.

I believe the Lithuanian standardization body tried to encode all the accented characters used in their dictionaries because using i with acute and the others was inadequate and fonts and applications didn't support Unicode’s solution back in the early 2000s. A lot has changed since then. But yeah, softdottedness is peculiar.

**Comment by moyogo** [comment]
@chrissimpkins @MariannaPaszkowska @davelab6 @tiroj 
> The convention in Lithuanian is not to suppress the dot on i (and by extension j) when marks are added above, as may occur in dictionaries.

If there’s a consensus on supporting Lithuanian dictionary phonetic notation with the mark and mkmk features, with the COMBINING DOT ABOVE as recommended by the Unicode Standard and used in Lithuanian dictionaries, rather than locl feature glyph substituion then Lithuanian can be removed from

>  locl (Latin: Catalan, Romanian, Moldovan, Dutch, Lithuanian)

**Comment by moyogo** [comment]
For what it’s worth, I opened an issue https://github.com/googlefonts/googlesans/issues/563 on the Dutch locl feature breaking Dutch text.

**Comment by chrissimpkins** [comment]
@dberlow @sannorozco A build for testing of OpenType feature shaping and outline support as of your fb-wip branch commit https://github.com/googlefonts/googlesans-flex/commit/d43724ed3c6076bfb1cd49bc300e26c75de33da3, as supported by [the feature code defined here](https://github.com/googlefonts/googlesans-flex/blob/77a4787aae1677663c0004ec5b5339b0debf28ed/sources/regular/family.fea) is available in the zip archive linked below:

https://github.com/googlefonts/googlesans-flex/suites/10751538780/artifacts/539583560

cc @MariannaPaszkowska

**Comment by chrissimpkins** [comment]
🎉
