### ISSUE TITLE
ogonek separates from the base glyph in: Ą ę 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#331]
It's most important to fix this in 144:
<img width="712" alt="Screenshot 2023-02-06 at 7 55 02 PM" src="https://user-images.githubusercontent.com/22956348/217048380-78d6dd36-c06e-4c06-9376-81253b628628.png">
<img width="731" alt="Screenshot 2023-02-06 at 7 53 26 PM" src="https://user-images.githubusercontent.com/22956348/217048390-360e5394-cc93-4358-93bd-8b7c9f8ffd00.png">
<img width="506" alt="Screenshot 2023-02-06 at 7 51 08 PM" src="https://user-images.githubusercontent.com/22956348/217048408-96a13ceb-77c7-4604-a25a-fb5b0a9ae2c5.png">

**Comment by sannorozco** [comment]
This has been updated, ready for check @MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
<img width="821" alt="Screenshot 2023-05-16 at 1 19 04 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/3c8df057-1084-47c2-ac56-e3593715c683">
@sannorozco
