### ISSUE TITLE
Design space: v1

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#34]
The design space at the first Latin release will include the following axes:

| axis   | min | default | max  |
|:-------|----:|--------:|-----:|
| `wght` | 1   | 400     | 1000 |
| `wdth` | 25  | 100     |  151 | 
| `opsz` | 6   |  18     |  144 |
| `GRAD` | -50 |   0     |   50 |
| `ROND` | 0   |   0     |  100 |

**Comment by madig** [comment]
So, no italics?

**Comment by chrissimpkins** [comment]
Not as an axis.  Will remain a separate font as we currently have in GS for now

**Comment by dberlow** [comment]
Roman and Italic
weight (1 to 1000, default: 400)
width (25 to 151, default: 100)
opsz (6 to 144, default: 18)
GRAD (-50 to +50, default: 0)
ROND (0 to 100, default: 0)

**Comment by dberlow** [comment]
Outlined all current options issue 50
