### ISSUE TITLE
Improve ordn feature

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#341]
Currently:
```
feature ordn {
    sub [A a a.alt] by ordfeminine;
    sub [O o] by ordmasculine;
} ordn;
```
We could consider targeting better:
```
[anynumber] a' by ordfeminine
[anynumber] o' by ordmasculine
[anynumber] period a' by ordfeminine
[anynumber] period o' by ordmasculine
```

<img width="997" alt="Screenshot 2023-02-07 at 2 51 27 PM" src="https://user-images.githubusercontent.com/22956348/217249825-82e2bab1-3786-4758-8241-e798267d3a95.png">

**Comment by chrissimpkins** [comment]
@MariannaPaszkowska Do you aim to address this by next week?

**Comment by MariannaPaszkowska** [comment]
#413 @chrissimpkins, done!
