### ISSUE TITLE
edit colon.time glyph

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#342]
Please 

- [x] change the vertical positioning to match the figures
- [x] make the character width the same as in the default colon. 
- [x] add contex zero.slash to the calt

Regular: Top Google Sans, bottom Google Sans Flex. Colon.time is used with figures through calt feature:
<img width="1043" alt="Screenshot 2023-02-07 at 3 10 46 PM" src="https://user-images.githubusercontent.com/22956348/217254678-cdd9cd02-d97b-4375-b36d-abd5da8ddef4.png">

Bold: Top Google Sans, bottom Google Sans Flex:
<img width="1136" alt="Screenshot 2023-02-07 at 3 11 50 PM" src="https://user-images.githubusercontent.com/22956348/217254702-0a7047a3-1bad-4754-b496-91492a3e93c0.png">

**Comment by dberlow** [comment]
Santiago, 
6,100,400
18,100,400
144, 100,400
are now updated.

**Comment by MariannaPaszkowska** [comment]
@sannorozco, do you know if there's any progress on this? When do you plan to deliver this? 
CC @chrissimpkins

**Comment by sannorozco** [comment]
@MariannaPaszkowska this will be updated later today.

**Comment by chrissimpkins** [comment]
Is this addressed?

**Comment by dberlow** [comment]
This is addressed. There are design issues represented in the solution where the dots are positioned vertically depending on wght and wdth, to appear like a clock.E.g., at wght1, it’s not good to have them as far apart as the /:, and at wght1000, the dots do not need to be as tight as the /: that needs to fit in the xht.On Feb 13, 2023, at 4:07 PM, Chris Simpkins ***@***.***> wrote:﻿
Is this addressed?
