### ISSUE TITLE
Revise axis names with the display name strings defined in the Fonts axis registry

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#350]
In the following source block:

https://github.com/googlefonts/googlesans-flex/blob/5169cbd6a86c0b0b8c013cdb4cb71911673e32d9/sources/regular/GoogleSansFlex.designspace#L3-L19

let's update the axis names so that they use the string and casing defined in our axis registry:

- [Weight](https://github.com/googlefonts/axisregistry/blob/12b2364e7c179fcc00a1f0fe6422d9eea4f74788/Lib/axisregistry/data/weight.textproto#L3)
- [Width](https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/width.textproto#L3)
- [Optical Size](https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/optical_size.textproto#L5)
- [Roundness](https://github.com/googlefonts/axisregistry/blob/12b2364e7c179fcc00a1f0fe6422d9eea4f74788/Lib/axisregistry/data/roundness.textproto#L3)
- [Grade](https://github.com/googlefonts/axisregistry/blob/12b2364e7c179fcc00a1f0fe6422d9eea4f74788/Lib/axisregistry/data/grade.textproto#L3)

**Comment by MariannaPaszkowska** [comment]
@madig are we testing for that?

**Comment by madig** [comment]
You mean ensuring that the names we give the axis are in the font? No.
