### ISSUE TITLE
Create a simple tool for checking too-small and suspiciously large kerning pairs. 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#351]
Create a simple tool for checking for too-large and too-small kerning pairs. 

User story:
As a reviewer, I want to be able to quickly check the font sources (all masters) for:
1. Kerning pairs that cannot be seen with a bare eye and can safely be deleted. 
2. Suspiciously large kerning pairs that need to be reviewed. 
I want to understand the output fast and be able to share the feedback with the designer/font developer easily. 

Details: 
- The output should be easily copied to another reviewing tool (string). It should be divided into convenient categories and sorted by the most problematic first. 
- The tool should adapt to the UPM set in the sources.

A tip from @simoncozens: maybe the function `fontTools.ufoLib.kerning.lookupKerningValue` from the https://github.com/daltonmaag/kerning-validator would be useful here.

**Comment by madig** [comment]
Hm. Sounds like a modification of https://github.com/googlefonts/googlesans-flex/pull/340 where I instead warn about pairs with values outside a range. No need for `lookupKerningValue` because you just loop over the per-UFO kerning as it is defined.
