### ISSUE TITLE
Make <wdth 50 glyphs narrower

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#358]
CGOQS too wide
<img width="901" alt="Screen Shot 2023-02-13 at 10 19 12 AM" src="https://user-images.githubusercontent.com/1956494/218497959-4ab1b166-1fad-4d3e-9679-1efd1101c0f1.png">

**Comment by dberlow** [comment]
completed and ready for review

**Comment by MariannaPaszkowska** [comment]
Approved for this release. We might want to come back to round glyphs on wght=80.
