### ISSUE TITLE
Some glyphs have variation in horizontal advance in axes GRAD and ROND

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#362]
Fontbakery FAIL on the [latest import](https://github.com/googlefonts/googlesans-flex/commit/9053960530e150a2d2f600193d147987bc3ed57d): 

1. The following glyphs have variation in horizontal advance due to the GRAD axis: 
`a.alt` `threequarters` `onehalf` `onequarter` `Ldot` `zeroslash.tf`

2. The following glyphs have variation in horizontal advance due to the ROND axis: 
 `t` `Hbar.1` `colon.time` and `zero.slash` `trademark` `zeroslash.tf` `percent.tf` `percentbar.tf`

Please review and fix.

**Comment by dberlow** [comment]
1. today
3. are all corrected.
