### ISSUE TITLE
Please improve 

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#366]
I recently saw that messages from the build script DO include what Specific Glyph is incompatible or missing in a commit. 

Instead of that timely information being immediately passed on to the designer, I get this message on Every Commit, compatible or not. 
<img width="880" alt="Screen Shot 2023-02-14 at 6 10 54 AM" src="https://user-images.githubusercontent.com/1956494/218720843-ae481416-9a82-494c-a690-dfc12c009a5a.png">

100's and 100's and I asked for a change several times.

**Comment by MariannaPaszkowska** [comment]
Hi @dberlow, I had the same problem! In the main view on the repository, you can change the notifications settings by clicking on "Watch". I shared with you a new doc with a guide. I also included there instructions on how to find which glyphs fail the build workflow.

<img width="1336" alt="Screenshot 2023-02-14 at 2 45 44 PM" src="https://user-images.githubusercontent.com/22956348/218742395-1e1f2aea-3fdf-44cd-846e-b43258932cf0.png">

**Comment by chrissimpkins** [comment]
You should no longer receives notices about the failed regression checks in the fb-wip branch following the merge of https://github.com/googlefonts/googlesans-flex/pull/376 to the fb-wip branch.  Please let me know if this remains a problem with future commits.

cc @MariannaPaszkowska

**Comment by dberlow** [comment]
I cleaned up some preview interpolations and work files associated with making the opsz17.999 sources and committed this a.m. 

I got email as usual to tell me the build failed. (a build that had nothing to do with the files removed.)

I followed the error as you see in this movie. (Tracking an Error- Scene I, Take 1.mov)...
to the designspace file, and the error appears to be path names . https://drive.google.com/file/d/1fx_AvR2H7fRd6n7Zvq2YulkqWqCEwn6E/view?usp=share_link
No path names were changed in the making of this movie. 

On my local machine, using the same designspace file, I can build a VF in memory and preview an instance as you can see in the movie's next scene. (Tracking an Error-Scene II, Take I.mov).https://drive.google.com/file/d/1uHo200ysj79j3a1VVWuXUJc3bQKhwQmC/view?usp=share_link

I, and others, need to know for certain when our work does not build, per commit. 

Is there anything I can do differently to make that possible, or is this software on the Repo that's just not progressed to the point where it's possible, but it can do so?

Cheers.

**Comment by chrissimpkins** [comment]
The messages coming out of the compiler aren't entirely meant for humans :) 

Here is the relevant section in the latest commit in your branch:

```
Fonts had differing number of contours in glyph four.tf:
 * 82 fonts had 2
 * GoogleSansFlex opsz17.999-wdth25-wght1000-ROND0 had 0
Fonts had differing number of components in glyph four.tf:
 * 82 fonts had 0
 * GoogleSansFlex opsz17.999-wdth25-wght1000-ROND0 had 1
```

**Comment by chrissimpkins** [comment]
you introduced something that began failing the build in https://github.com/googlefonts/googlesans-flex/commit/12c1bb508158cb73075fa50a7b85d7c7022f3596

**Comment by chrissimpkins** [comment]
This this URL to view your fb-wip branch commit history and understand if the build works or fails. 

https://github.com/googlefonts/googlesans-flex/commits/fb-wip

Now that we removed the "regression" check that was being performed on each commit the CI output summary will be useful to you.  If you see a red `x`, the build did not work.  If you see a green check mark, the build worked.

You can click on the red `x` to view the reason for the fail.  Use the "Details" link next to the build workflow name.  The reason for the fail is buried within the terminal output in the GitHub UI.  Don't hesitate to reach out if you have difficulty locating or deciphering it.

![C2QPXeejVdcXcSi](https://user-images.githubusercontent.com/4249591/219038074-174cbacf-2364-492b-b012-0d3f62a6c1e7.png)

**Comment by chrissimpkins** [comment]
![BXUzvSr9RZnBsCp](https://user-images.githubusercontent.com/4249591/219039895-83c4f0e7-48b6-4656-a3ee-7183a66f83f3.png)

**Comment by dberlow** [comment]
Thanks so much!
