### ISSUE TITLE
add caret anchors to the ligature glyphs

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#367]
This can be edited at a later stage. 
Font Bakery warning: "WARN This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos] "

We should add caret anchors to the ligature glyphs. Anchors should be called in this manner: "caret_1"

**Comment by dberlow** [comment]
These can be scripted in at any time, I believe, with no manual editing.

The ligatures that need to grow carats are all components added together on
the widths of their source glyphs.
So if the /f is 200 units and the /i 180, we can automate the addition of a
mark 200 units from the origin in /fi's 380 width.

Same works for three-letter ligatures.
/IJ and /ij do no need a mark in the middle, I think, it's a glyph like /AE

Do you have a list?

**Comment by octaviopardo** [comment]
this one should be fixed in tomorrow's build

**Comment by MariannaPaszkowska** [comment]
many thanks! fixed in #844
