### ISSUE TITLE
$¢ fix interpolation 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#374]
<img width="618" alt="Screenshot 2023-02-14 at 7 18 41 PM" src="https://user-images.githubusercontent.com/22956348/218815197-8f718aa2-37c9-423d-84a2-75c73646b80a.png">

**Comment by MariannaPaszkowska** [comment]
<img width="550" alt="Screenshot 2023-02-14 at 8 23 56 PM" src="https://user-images.githubusercontent.com/22956348/218824634-b23bd63f-e4d6-4613-877a-5573ffca5b77.png">

**Comment by chrissimpkins** [comment]
Miguel is working on this.  In progress.

**Comment by MariannaPaszkowska** [comment]
@mmmaiqo @sannorozco @dberlow This is still To-Do: 
<img width="438" alt="Screenshot 2023-02-20 at 2 17 02 PM" src="https://user-images.githubusercontent.com/22956348/220104581-ff2ee1b2-1390-47b0-852c-32d9b0c5f1be.png">
<img width="456" alt="Screenshot 2023-02-20 at 2 16 57 PM" src="https://user-images.githubusercontent.com/22956348/220104630-ac6e8484-2cd8-4fc0-afed-2f41f07342f2.png">

**Comment by MariannaPaszkowska** [comment]
@sannorozco I checked the previously reported issues in today's [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4261168369), and here is the current state: 


<img width="453" alt="Screenshot 2023-02-24 at 2 53 41 PM" src="https://user-images.githubusercontent.com/22956348/221183732-e78db574-3693-41e6-bff6-8e51dfccc2f9.png">

<img width="493" alt="Screenshot 2023-02-24 at 2 53 05 PM" src="https://user-images.githubusercontent.com/22956348/221183840-84a79fa4-2ac3-4ee9-b132-1d73c37a7b6f.png">
<img width="468" alt="Screenshot 2023-02-24 at 2 52 55 PM" src="https://user-images.githubusercontent.com/22956348/221183851-ec5cef4b-829f-4807-877d-739d16002c27.png">
<img width="473" alt="Screenshot 2023-02-24 at 2 52 37 PM" src="https://user-images.githubusercontent.com/22956348/221183874-d7f88b8c-862b-4ebd-bcc9-21e0d0f5e624.png">

**Comment by sannorozco** [comment]
@MariannaPaszkowska Added SPARSE sources to fix this.

**Comment by MariannaPaszkowska** [comment]
Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4280209987) 
**Current state:**
<img width="458" alt="Screenshot 2023-02-27 at 10 47 29 AM" src="https://user-images.githubusercontent.com/22956348/221516622-39000959-7b68-4c57-8d7a-d81cde74a7af.png">
<img width="464" alt="Screenshot 2023-02-27 at 10 47 23 AM" src="https://user-images.githubusercontent.com/22956348/221516628-46f91d70-c441-4f1f-8213-110e6bfee997.png">
<img width="472" alt="Screenshot 2023-02-27 at 10 46 59 AM" src="https://user-images.githubusercontent.com/22956348/221516631-f3f26514-0f45-4953-be0d-ae3697defb5d.png">
<img width="413" alt="Screenshot 2023-02-27 at 10 46 54 AM" src="https://user-images.githubusercontent.com/22956348/221516637-623bd202-005d-4d22-8c0d-dbccef709b97.png">
<img width="438" alt="Screenshot 2023-02-27 at 10 46 45 AM" src="https://user-images.githubusercontent.com/22956348/221516638-6c4be2c1-74d1-42db-bb17-e4e53eca3641.png">
<img width="419" alt="Screenshot 2023-02-27 at 10 46 40 AM" src="https://user-images.githubusercontent.com/22956348/221516642-f298a294-b895-40b7-94bb-56098926174b.png">
<img width="416" alt="Screenshot 2023-02-27 at 10 46 30 AM" src="https://user-images.githubusercontent.com/22956348/221516646-48953ff4-83fe-46bd-87a1-62f51ea83cf8.png">
<img width="503" alt="Screenshot 2023-02-27 at 10 46 24 AM" src="https://user-images.githubusercontent.com/22956348/221516652-6f1ac87c-5cc3-4059-bd1c-22626d6cf9e8.png">

**Comment by chrissimpkins** [comment]
Status @sannorozco @dberlow ?

**Comment by sannorozco** [comment]
@chrissimpkins I’m reviewing this right now, it’s on the width between 40–50, might need to add another sparse in between.

**Comment by sannorozco** [comment]
@MariannaPaszkowska I added an additional sparse, so it fixes all in between wdth 40–50.

**Comment by chrissimpkins** [comment]
Thank you very much Santiago.  I'll take a look at these today.

**Comment by sannorozco** [comment]
@chrissimpkins Yes, we added many SPARSE sources for this, I didn’t see any gap, let me know if we need more.

**Comment by chrissimpkins** [comment]
@sannorozco All of the design space locations that Marianna posted in https://github.com/googlefonts/googlesans-flex/issues/374#issuecomment-1445928396 LGTM.  I identified one new area between 500 - 700 weight when GRAD = +50, wdth=50, opsz=144.  Shown in video below.

![dollar-cent-1](https://user-images.githubusercontent.com/4249591/221999333-52c7a634-e482-4f0a-98a7-bbd7a8bce069.gif)

**Comment by chrissimpkins** [comment]
Marianna will run a more thorough review and be back in touch with any other findings.  Thanks for your work here!  This looks much better.

**Comment by sannorozco** [comment]
@chrissimpkins Changing opening bars at 50 instead of 40 will be best, will have to regenerate them for width 50.

**Comment by MariannaPaszkowska** [comment]
@sannorozco I checked the latest build, and the issue still persists. Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4303113101)
Please also fix  cent.tf and dollar.tf

CC @chrissimpkins 

<img width="586" alt="Screenshot 2023-03-01 at 2 17 27 PM" src="https://user-images.githubusercontent.com/22956348/222137215-3f70103d-8653-42a3-9015-a077f9de1b97.png">
<img width="519" alt="Screenshot 2023-03-01 at 2 17 14 PM" src="https://user-images.githubusercontent.com/22956348/222137217-df02880f-5eaf-4ecc-957a-188c2cfcb2c6.png">
<img width="572" alt="Screenshot 2023-03-01 at 2 17 07 PM" src="https://user-images.githubusercontent.com/22956348/222137219-e273cb7a-33ee-45d3-bb5c-7fa2b475e6f4.png">
<img width="506" alt="Screenshot 2023-03-01 at 2 18 00 PM" src="https://user-images.githubusercontent.com/22956348/222137207-67c0d192-7427-4d7f-b5a5-29c274717ab6.png">
<img width="587" alt="Screenshot 2023-03-01 at 2 17 50 PM" src="https://user-images.githubusercontent.com/22956348/222137212-354a87f2-6bf8-47c7-b9db-126d57d31e50.png">
<img width="522" alt="Screenshot 2023-03-01 at 2 17 42 PM" src="https://user-images.githubusercontent.com/22956348/222137213-fda0f4b4-29d5-4bf6-9963-1eb9e1662555.png">
<img width="558" alt="Screenshot 2023-03-01 at 2 19 14 PM" src="https://user-images.githubusercontent.com/22956348/222137427-fdafa590-19e7-4584-a6e6-6b4d255ddd8f.png">

**Comment by MariannaPaszkowska** [comment]
I confirm that the bars are not breaking now. I noticed that the switch is happening later now. 

The latest build:
<img width="426" alt="Screenshot 2023-03-02 at 11 44 05 AM" src="https://user-images.githubusercontent.com/22956348/222391787-99358a79-ef00-4164-81bc-85fbe010fa59.png">

Earlier builds:
<img width="514" alt="Screenshot 2023-03-02 at 11 44 32 AM" src="https://user-images.githubusercontent.com/22956348/222391938-4146359e-0853-4234-b686-55f7b33ac255.png">

**Comment by sannorozco** [comment]
@MariannaPaszkowska Yup, in the latest build if you go to 699 41 144 the bars will be there because in the designspace it’s specified 699.999, it was at 699 before as you said. BUT if we leave it at 699, and move the sliders you’ll see the bars moving between 699.001–700.

So do we want the glitch?

**Comment by MariannaPaszkowska** [comment]
As discussed in the meeting yesterday, the switch should happen earlier:
<img width="471" alt="Screenshot 2023-03-03 at 1 31 37 PM" src="https://user-images.githubusercontent.com/22956348/222709840-f067631e-1229-47d3-9226-96d86f6a38f7.png">
<img width="482" alt="Screenshot 2023-03-03 at 1 31 30 PM" src="https://user-images.githubusercontent.com/22956348/222709844-afd29131-c20b-4e6f-b17a-4c80f1548a5b.png">
<img width="475" alt="Screenshot 2023-03-03 at 1 31 17 PM" src="https://user-images.githubusercontent.com/22956348/222709846-9ed1d9c9-8659-472e-b03b-2f5fb42560aa.png">
