### ISSUE TITLE
Solutions for Į į 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#375]
MIlestone: v1.2

**Comment by MariannaPaszkowska** [comment]
<img width="574" alt="Screenshot 2023-02-14 at 8 04 33 PM" src="https://user-images.githubusercontent.com/22956348/218820565-54048e76-df91-4af4-b99a-0d9c76f7621f.png">

<img width="575" alt="Screenshot 2023-02-14 at 8 04 45 PM" src="https://user-images.githubusercontent.com/22956348/218820601-1b3fc2f0-8419-434d-9e94-8b059d15e615.png">

**Comment by MariannaPaszkowska** [comment]
Some problematic combinations (įį are known in Lithuanian)

<img width="938" alt="Screenshot 2023-02-14 at 8 06 26 PM" src="https://user-images.githubusercontent.com/22956348/218821409-aafaaa72-2dfb-445e-83e7-daa6dbdf6d3d.png">
<img width="943" alt="Screenshot 2023-02-14 at 8 09 13 PM" src="https://user-images.githubusercontent.com/22956348/218821485-2f404a5d-3496-4dba-987c-c2e14c530930.png">

**Comment by dberlow** [comment]
Suggestions?

**Comment by tiroj** [comment]
The optical relationship of the weight of the ogonek to the weight of the stem looks good in this case, which can be used as a model for the other combinations.
<img width="56" alt="image" src="https://user-images.githubusercontent.com/5614500/219082961-1c19b6da-4aac-4ed1-932b-6e2a76cee36a.png">
The rounded style might well benefit from being handled as a decomposed glyph with the connection refined to flow from the lower right of the rounded stem terminal. I’m guessing that would also have implications for how you handle the glyph in the rest of the design space.

Then add positive kerning on the right for various descenders and adjacent below marks.

**Comment by dberlow** [comment]
That's fine, thanks John.
 
Regarding /iogonek /j combo I have an investigator looking at the functioning wght max using the default glyphs for /iogonek /j combo, and we propose subbing via RVRN above that wght max to include a different /j.

**Comment by tiroj** [comment]
FYI the įj sequence is rare: I think it does not occur in Polish, and in Lithuanian only in a few words, mostly at the beginning of a word, but where it occurs elsewhere it is part of the ending –įjį as in kairįjį and mirusįjį.

**Comment by dberlow** [comment]
Wonderful, thanks. Will wait about it on Google’s decision to fix that way, or any other.On Feb 15, 2023, at 12:04 PM, John Hudson ***@***.***> wrote:﻿
FYI the įj sequence is rare: I think it does not occur in Polish, and in Lithuanian only in a few words, mostly at the beginning of a word, but where it occurs elsewhere it is part of the ending –įjį as in kairįjį and mirusįjį.
