### ISSUE TITLE
Google logo letters reflow on weight and width

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#379]
Google logo letters sidebearings change along wght and wdth. They should keep the same glyph width across masters. Please update. 
Affected glyphs: `G.logo` `o.logo` `g.logo` `l.logo` `e.logo`

**Comment by MariannaPaszkowska** [comment]
Triggers :Google_G_logo :Google_o_logo :Google_g_logo :Google_l_logo :Google_e_logo

**Comment by chrissimpkins** [comment]
@MariannaPaszkowska Can we help by reproducing the opsz 18 default master outlines to all other masters?
