### ISSUE TITLE
Compare GS to GS Flex opsz 17 and 18 Regular Grad0 to evaluate reflow

### ISSUE THREAD

**Issue by belluzj** [googlefonts/googlesans-flex#38]
Make it part of the pipeline but only as a warning kind of thing, not error. The point is to have ready answers for designers asking how much their designs will reflow when switching to GS Flex. Understand how hard it is to switch from GS to GS Flex in existing designs; so we're only interested in checking the common designspace (don't care about width axis). Something simple and fast to perform. The output could be a comparison PDF or HTML documents (visual output and easily shareable) with GS and flex overlaid with different colours. Use shaping text or UDHR as source for text. Automated so it can be done for many languages e.g. Arabic.

**Comment by madig** [comment]
@MariannaPaszkowska does https://github.com/daltonmaag/overlay-font-tester do what you need?
