### ISSUE TITLE
Set glyf table OVERLAP_SIMPLE and OVERLAP_COMPOUND bit flags

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#382]
Teams are seeing overlaps in Android environment-specific stroked outlines with this family.  We introduced the overlap bit flag change to address it in Google Sans around v8.001 and I think that we may be able to address it here with the same script if we are not currently doing so?

Google Sans Issue: https://github.com/googlefonts/googlesans/issues/478
@madig PR to add script in the GS build workflow: https://github.com/googlefonts/googlesans/pull/494

Let's plan to include this in the production build workflow for the v1.1 release.

**Comment by chrissimpkins** [comment]
Are we appropriately labeling glyphs with overlaps using the new script?  IIRC there is a performance impact associated with over-labeling and teams will have problems with stroking if we are under-labeling.

**Comment by madig** [comment]
The script is somewhat overeager I think. @m4rc1e once talked about tackling this somehow, but I don't know the status.

**Comment by m4rc1e** [comment]
I neer got round to implementing anything. Our convo ended up on this solution, https://github.com/google/fonts/issues/4405#issuecomment-1104867714

**Comment by chrissimpkins** [comment]
I spoke with Marianna about it today. Let's confirm that all default figures are appopriately labeled as having overlaps, and at the very least spot check other areas of the glyph repertoire so that we understand if the script is functioning.

**Comment by MariannaPaszkowska** [comment]
@madig could you check if `0-9` figures and `A, C, I, V, X, R, S, Q, a, e, fi, g, ł, i, ó, s, …, &` are appropriately labeled?

**Comment by madig** [comment]
Here is the full list of glyphs with the overlap bit set:

* .notdef
* a
* A
* a.alt
* aacute
* Aacute
* aacute.alt
* abreve
* Abreve
* abreve.alt
* acaron
* Acaron
* acaron.alt
* acircumflex
* Acircumflex
* acircumflex.alt
* acute
* acutecomb
* adieresis
* Adieresis
* adieresis.alt
* ae
* AE
* ae.alt
* agrave
* Agrave
* agrave.alt
* amacron
* Amacron
* amacron.alt
* ampersand
* aogonek
* Aogonek
* aogonek.alt
* approxequal
* approxequal.tf
* aring
* Aring
* aring.alt
* asciicircum
* asciitilde
* asterisk
* at
* atilde
* Atilde
* atilde.alt
* b
* B
* backslash
* braceleft
* braceright
* bracketleft
* bracketright
* breve
* brevecomb
* brokenbar
* c
* C
* cacute
* Cacute
* caron
* caroncomb
* ccaron
* Ccaron
* ccedilla
* Ccedilla
* cdotaccent
* Cdotaccent
* cedilla
* cedillacomb
* cent
* cent.tf
* circumflex
* circumflexcomb
* comma
* comma.tf
* commaaccentcomb
* commaturnedabovecomb
* copyright
* currency
* currency.tf
* d
* D
* dcaron
* Dcaron
* dcroat
* Dcroat
* degree
* diagonalbarl
* dieresis
* dieresiscomb
* divide
* divide.tf
* dollar
* dollar.tf
* e
* E
* e.logo
* eacute
* Eacute
* ecaron
* Ecaron
* ecircumflex
* Ecircumflex
* edieresis
* Edieresis
* edotaccent
* Edotaccent
* egrave
* Egrave
* eight
* eight.denominator
* eight.numerator
* eight.tf
* eightsubscript
* eightsuperscript
* emacron
* Emacron
* eng
* Eng
* Engeng
* eogonek
* Eogonek
* equal
* equal.tf
* eth
* Eth
* Euro
* Euro.tf
* exclam
* exclambottom
* exclamdown
* exclamtop
* f
* F
* f_b
* f_f
* f_f_b
* f_f_h
* f_f_i
* f_f_j
* f_f_k
* f_f_l
* f_f_t
* f_h
* f_i
* f_j
* f_k
* f_l
* f_t
* five
* five.denominator
* five.numerator
* five.tf
* fivesubscript
* fivesuperscript
* flig1
* flig2
* four
* four.denominator
* four.numerator
* four.tf
* foursubscript
* foursuperior
* foursuperscript
* fraction
* g
* G
* g.alt
* gbreve
* Gbreve
* gbreve.alt
* gcommaaccent
* Gcommaaccent
* gcommaaccent.alt
* gdotaccent
* Gdotaccent
* gdotaccent.alt
* germandbls
* Germandbls
* Google.logo
* grave
* gravecomb
* greater
* greater.tf
* greaterequal
* greaterequal.tf
* guillemetleft
* guillemetright
* guilsinglleft
* guilsinglright
* h
* H
* hbar
* Hbar
* horizontalelipsis
* hungarumlaut
* hungarumlautcomb
* i
* iacute
* Iacute
* icircumflex
* Icircumflex
* idieresis
* Idieresis
* Idotaccent
* igrave
* Igrave
* ij
* IJ
* imacron
* Imacron
* iogonek
* Iogonek
* j
* J
* jdotless
* k
* K
* kcommaaccent
* Kcommaaccent
* L
* lacute
* Lacute
* lcaron
* Lcaron
* lcommaaccent
* Lcommaaccent
* ldot
* Ldot
* less
* less.tf
* lessequal
* lessequal.tf
* logicalnot
* logicalnot.tf
* lslash
* Lslash
* m
* M
* micro
* mu
* multiply
* multiply.tf
* n
* N
* nacute
* Nacute
* ncaron
* Ncaron
* ncommaaccent
* Ncommaaccent
* nine
* nine.denominator
* nine.numerator
* nine.tf
* ninesubscript
* ninesuperscript
* notequal
* notequal.tf
* notequalslash
* ntilde
* Ntilde
* numbersign
* numbersign.tf
* o
* O
* oacute
* Oacute
* ocircumflex
* Ocircumflex
* odieresis
* Odieresis
* oe
* OE
* ogonek
* ogonekcomb
* ograve
* Ograve
* ohungarumlaut
* Ohungarumlaut
* omacron
* Omacron
* one
* one.denominator
* one.numerator
* one.tf
* onehalf
* onequarter
* onesubscript
* onesuperior
* onesuperscript
* ordfeminine
* ordmasculine
* oslash
* Oslash
* oslashbar
* Oslashbar
* otilde
* Otilde
* p
* P
* paragraph
* parenleft
* parenright
* percent
* percent.tf
* percentbar
* percentbar.tf
* plus
* plus.tf
* plusminus
* plusminus.tf
* q
* Q
* question
* questionbottom
* questiondown
* questiontop
* quotedbl
* quotedblbase
* quotedblleft
* quotedblright
* quoteleft
* quoteright
* quotesinglbase
* r
* R
* racute
* Racute
* rcaron
* Rcaron
* rcommaaccent
* Rcommaaccent
* registered
* s
* S
* sacute
* Sacute
* scaron
* Scaron
* scedilla
* Scedilla
* scommaaccent
* Scommaaccent
* section
* section.tf
* semicolon
* semicolon.tf
* seven
* seven.denominator
* seven.numerator
* seven.tf
* sevensubscript
* sevensuperscript
* six
* six.denominator
* six.numerator
* six.tf
* sixsubscript
* sixsuperscript
* slash
* sterling
* sterling.tf
* t
* T
* t_f
* t_t
* tcaron
* Tcaron
* tcedilla
* Tcedilla
* tcommaaccent
* Tcommaaccent
* thorn
* Thorn
* three
* three.denominator
* three.numerator
* three.tf
* threequarters
* threesubscript
* threesuperior
* threesuperscript
* tilde
* tildecomb
* tlig
* trademark
* two
* two.denominator
* two.numerator
* two.tf
* twosubscript
* twosuperior
* twosuperscript
* u
* U
* uacute
* Uacute
* ubreve
* Ubreve
* ucircumflex
* Ucircumflex
* udieresis
* Udieresis
* ugrave
* Ugrave
* uhungarumlaut
* Uhungarumlaut
* umacron
* Umacron
* uni25CC
* uogonek
* Uogonek
* uring
* Uring
* v
* V
* w
* W
* wacute
* Wacute
* wcircumflex
* Wcircumflex
* wdieresis
* Wdieresis
* wgrave
* Wgrave
* x
* X
* y
* Y
* yacute
* Yacute
* ycircumflex
* Ycircumflex
* ydieresis
* Ydieresis
* yen
* ygrave
* Ygrave
* z
* Z
* zacute
* Zacute
* zcaron
* Zcaron
* zdotaccent
* Zdotaccent
* zero
* zero.denominator
* zero.numerator
* zero.tf
* zeropercent
* zeroslash
* zeroslash.tf
* zerosubscript
* zerosuperscript

**Comment by dberlow** [comment]
I think this list is incorrect. I don’t see how either the acute or the fraction could have an overlap e.g.. if this is important to get correct:
Santiago if you could remove overlap on a copy of the default, check compatibility between it and the actual default, the correct answer to overlaps is in the list of incompatible glyphs.

**Comment by MariannaPaszkowska** [comment]
@dberlow It might be our script that is overeager to set the overlap flags. Let us look into that. 

I looked at the font in Samsa. In some cases, this might have to do with overlapping points for the ROND support. 
Zero is labeled, probably because of points 3 and 4, 10 and 11, 17 and 18, 24 and 25. This is for wdth axis support. 
<img width="856" alt="Screenshot 2023-02-22 at 5 23 52 PM" src="https://user-images.githubusercontent.com/22956348/220668490-716e6b43-9b2f-4b93-843a-5258d27b72b7.png">
<img width="1135" alt="Screenshot 2023-02-22 at 5 30 19 PM" src="https://user-images.githubusercontent.com/22956348/220670966-ddd9ba88-8dcf-4c68-8214-adf5441f7ab6.png">

Acute has overlapping points for ROND support, which makes sense, but it shoudn't ne 
<img width="665" alt="Screenshot 2023-02-22 at 5 26 26 PM" src="https://user-images.githubusercontent.com/22956348/220669422-9ca8fe64-9946-48b2-9dc9-837d4d7e349a.png">

@madig My wild guess is that those overlapping points are the reason for the over labeling. I wonder how we can improve. 🤔  We could look for the crossing outlines. Or can we provide the list manually?

**Comment by anthrotype** [comment]
i believe the script uses Skia PathOps to remove overlaps and then check if the paths are the same as before removing overlaps, otherwise if they have changed it assumes they must have had overlaps. It might well be that pathops removes the duplicate overlapping points as Marianna suggest, that would make sense for an operation that is called 'simplify'.
Maybe your script could also check that the total area of the a glyph's paths is the same before/after. I think pathops Path has a method for that too.

**Comment by anthrotype** [comment]
needless to say, overlapping _points_ are totally fine and one should not need to set the 'overlap' glyf flags just for those.

**Comment by dberlow** [comment]
Overlapping  contours is all my suggestion will find, and sounds like Cosimo’s solution as well. We just don’t need to script to do it.
And, with the ROND axis as specified and designed, there are very very few characters in the font do not have points located on the same coordinates that should not be removed.

**Comment by MariannaPaszkowska** [comment]
Thanks for confirming @anthrotype that overlapping points are not an issue.

@madig Here is my list of glyphs that need overlaps:
```
numbersign
dollar
cent
ampersand
plus
four
six
eight
nine
A
B
E
F
G
H
K
P
Q
R
T
X
Y
a
e
f
k
t
s
x
y
sterling
yen
section
Agrave
Aacute
Acircumflex
Atilde
Adieresis
Aring
AE
Ccedilla
Egrave
Eacute
Ecircumflex
Edieresis
Eth
multiply
Oslash
Yacute
Thorn
agrave
aacute
acircumflex
atilde
adieresis
aring
ae
ccedilla
egrave
eacute
ecircumflex
edieresis
eth
divide
oslash
yacute
ydieresis
foursuperior
f_f
f_f_i
f_f_l
OE
oe
Dcroat
dcroat
Emacron
emacron
Edotaccent
edotaccent
Eogonek
eogonek
Ecaron
ecaron
Racute
racute
Rcommaaccent
rcommaaccent
Rcaron
rcaron
sacute
Scedilla
scedilla
scommaaccent
scaron
Tcommaaccent
tcommaaccent
Tcedilla
tcedilla
Tcaron
tcaron
Ycircumflex
ycircumflex
Ydieresis
Ygrave
ygrave
Amacron
amacron
Abreve
abreve
Aogonek
aogonek
Lslash
lslash
Acaron
acaron
Hbar
hbar
Iogonek
iogonek
colon
semicolon
Gbreve
Gdotaccent
Gcommaaccent
Kcommaaccent
kcommaaccent
Uogonek
uogonek
quotedblleft
quotedblright
quotedblbase
section
percent
approxequal
lessequal
greaterequal
plusminus
notequal
multiply
plus
divide
sterling
euro
dollar
currency
cent
colon
numbersign
semicolon
colon
section.tf
percent.tf
approxequal.tf
lessequal.tf
greaterequal.tf
plusminus.tf
notequal.tf
multiply.tf
plus.tf
divide.tf
sterling.tf
Euro.tf
dollar.tf
currency.tf
cent.tf
colon.time
numbersign.tf
semicolon.tf
colon.tf
aogonek.alt
ae.alt
g.alt
gbreve.alt
gcommaaccent.alt
gdotaccent.alt
zeroslash
zeroslash.tf
threesubscript
foursubscript
fivesubscript
sixsubscript
eightsubscript
ninesubscript
threesuperscript
foursuperscript
fivesuperscript
sixsuperscript
eightsuperscript
ninesuperscript
three.numerator
four.numerator
five.numerator
six.numerator
eight.numerator
nine.numerator
three.denominator
four.denominator
five.denominator
six.denominator
eight.denominator
nine.denominator
micro
mu
flig1
flig2
trademark
```

**Comment by dberlow** [comment]
The third glyph from the bottom is some kind of a miscopy

**Comment by MariannaPaszkowska** [comment]
True, thanks @dberlow ! I fixed that.

**Comment by madig** [comment]
I looked at some font rendering of the string "4689ABEFGHKPQRTXYaefktsxy" in:

* InDesign 18.1 (export to PDF) and Safari 15.4 on macOS 12.3.1
* Some FreeType version

and I see no overlap problem with the bits on _or_ off.

**Comment by anthrotype** [comment]
>  I see no overlap problem with the bits on or off.

the problem is when glyph outlines gets "stroked", e.g. https://codepen.io/rs42/pen/yLpYQeg

**Comment by anthrotype** [comment]
Skia now simplifies paths for glyphs that are marked as overlapping to work around that issue, see 
https://skia-review.googlesource.com/c/skia/+/521637

**Comment by dberlow** [comment]
I’m traveling and unable to illustrate this completely. I’ve also written a little bit about the shortcomings of the current overlap flags, and some other issues that we face not covered by the format.Sign-indocs.google.comOn Feb 24, 2023, at 7:32 AM, Cosimo Lupo ***@***.***> wrote:﻿
Skia now simplifies paths for glyphs that are marked as overlapping to work around that issue, see
https://skia-review.googlesource.com/c/skia/+/521637

**Comment by madig** [comment]
Chrome does not currently remove overlaps on stroked glyphs with the bit set, FWIW:

![image](https://user-images.githubusercontent.com/380829/221189455-e6741aa8-0ba2-47cd-a779-e69f5d5a59a3.png)

**Comment by madig** [comment]
I also see no isses in Figma, though I have never used it before and so might be missing something.

**Comment by dberlow** [comment]
Thank you.On Feb 24, 2023, at 8:34 AM, Nikolaus Waxweiler ***@***.***> wrote:﻿
I also see no isses in Figma.

**Comment by anthrotype** [comment]
> Chrome does not currently remove overlaps on stroked glyphs with the bit set

cc @bungeman

**Comment by anthrotype** [comment]
Maybe Skia only does that when it's using freetype as the font host. What platform have you tried this with Chrome?

**Comment by madig** [comment]
Windows 11

**Comment by anthrotype** [comment]
can you try on Linux or Android?

**Comment by madig** [comment]
I don't have a Linux Chrome to hand right now and how do you test on Android?

**Comment by anthrotype** [comment]
put your test .html + font somewhere that you can load from the mobile browser?

this is first search result https://prowe214.medium.com/tip-how-to-view-localhost-web-apps-on-your-phone-ad6b2c883a7c

**Comment by m4rc1e** [comment]
I use python's http server `python -m http.server` + browserstack.

It's Friday eve so I'm probably gonna grab a beer and a burger in a bit but if this isn't done, just ping me on Mon and I'll take a look.

**Comment by MariannaPaszkowska** [comment]
sure @m4rc1e, I'll also keep an eye on that. It would be good to have this done and tested by the end of next week. Until then 🍻!

**Comment by madig** [comment]
I did a test on the Android 13 on a Pixel 4a and the test string above looks fine in the latest Firefox and Chrome. Neither remove overlaps for the stroked variant. Interestingly, Chromium on Linux does:

![grafik](https://user-images.githubusercontent.com/380829/221593438-1e59cbc4-a130-4fa1-b939-1f0e4e6c6f6a.png)

**Comment by anthrotype** [comment]
> the test string above looks fine in the latest Firefox and Chrome. Neither remove overlaps for the stroked variant.

I don't understand what you mean by "looks fine", and "neither remove overlaps.."
Is that screenshot above (which looks fine to me) from Linux or Android?

**Comment by chrissimpkins** [comment]
Where are we with the coverage of bit settings for outlines that we know to have overlaps?  These are all currently being set either by script or with a fixed list of glyph names?

**Comment by madig** [comment]
> I don't understand what you mean by "looks fine", and "neither remove overlaps.."

I don't see holes in outlines. I consider stroked outlines a special case.

> Is that screenshot above (which looks fine to me) from Linux or Android?

Chromium Linux.

**Comment by madig** [comment]
@chrissimpkins I posted https://github.com/googlefonts/googlesans-flex/pull/421

**Comment by anthrotype** [comment]
> I consider stroked outlines a special case.

the problem is exactly about the stroked outlines. I asked for a confirmation that when the overlap bit is set, Chrome Android/Linux (via Skia Freetype font host) simplifies the outlines (ie. removes the overlaps) before stroking. But then I got confused by your statement "neither removes overlap"... If it looks fine (when stroked), it must mean that the overlaps were indeed removed. I will interpret your 'I don't see holes in outlines' to mean that the feature is working as intended on Chrome Android/Linux, as expected. Thanks

**Comment by dberlow** [comment]
We believe that /A construction does not work even in quadratics and we’ve resolved it in RobotoFlex and GSF by splitting the crossbar into two contours.

**Comment by madig** [comment]
I made a mistake, Chrome Android removes overlaps for stroked glyphs:

* Chrome Android 13: ![c](https://user-images.githubusercontent.com/380829/222148639-0507ef16-b3fd-4be9-aa66-26e882bbd5a3.png)
* Chromium Linux: ![cl](https://user-images.githubusercontent.com/380829/222148882-8236f536-9ae1-4afb-9bbe-09e3ae747a93.png)
* Chrome macOS: <img width="967" alt="cm" src="https://user-images.githubusercontent.com/380829/222149254-1436ed35-f126-4113-a2ae-3549bc954484.png">
* Chrome Windows: <img width="663" alt="cw" src="https://user-images.githubusercontent.com/380829/222149304-3c864dbd-eaa3-4cd4-b9f0-21bcbeab55ba.png">
* Edge Windows: <img width="780" alt="ew" src="https://user-images.githubusercontent.com/380829/222149346-fcf11622-3a3f-4a45-916d-a245d6fd777d.png">
* Firefox Android 13: ![ff](https://user-images.githubusercontent.com/380829/222149087-f3869964-8c06-4daf-bdda-305d743452cf.png)
* Firefox Windows: <img width="781" alt="Screenshot_1" src="https://user-images.githubusercontent.com/380829/222150273-ea0d4620-4a35-4a1d-b720-129f09dd692f.png">
* Safari macOS 12.3.1: <img width="1000" alt="sm" src="https://user-images.githubusercontent.com/380829/222149390-b9792c98-3253-4edc-9e84-14dadc8916df.png">

**Comment by madig** [comment]
I suppose "2", "3", "5", "S", "C", "c", "g", "i" and "j" would need a bit, too, if you wanted to support the extreme ends.

Also, "4" disappears at some Roundness coordinates, i.e. wght=1000, wdth=151, opsz=144, ROND=11, GRAD=49. Not sure if Skia bug?

This is at mostly the extreme ends of all axes. I played a bit with Roundness to see how things interact.

![grafik](https://user-images.githubusercontent.com/380829/222445614-ba1b58c5-5188-4f67-b58e-458fca2fc419.png)

**Comment by madig** [comment]
Weird. Doesn't happen when solid, so I guess Skia bug.

wght=900, wdth=100, opsz=144, ROND=100, GRAD=9

![grafik](https://user-images.githubusercontent.com/380829/222448847-177253ab-d5db-4f00-a9ed-a33d82fa5f01.png)

**Comment by anthrotype** [comment]
ouch... a skia pathops bug is possible, yeah. Ideally we'd send a bug report upstream with are small font that reproduces this, but I suppose this font hasn't been released yet.
What do you mean by "solid"?

**Comment by madig** [comment]
Non-stroked, as in, normal rendering; black text on white background.

**Comment by chrissimpkins** [comment]
Distributed a font compiled with the https://github.com/googlefonts/googlesans-flex/pull/421 changes to the requesting team. Ty!

**Comment by MariannaPaszkowska** [comment]
@madig Many thanks for the testing! Let's add "2", "3", "5", "S", "C", "c", "g" (an overlap simple), and  "i" and "j" (an overlap compound) to our list.

**Comment by chrissimpkins** [comment]
We are receiving reports of similar behavior in other Fonts catalog families across other environments.  This review will inform what we do there. Thanks again for deep diving into this!

@m4rc1e @anthrotype I think that we should discuss how we handle the VF families more generally across the catalog.  I don't believe that we check for overlaps without these bit flags set, nor do we attempt to set them globally or detect and set automatically, correct?
