### ISSUE TITLE
Trim Grade (GRAD) axis extremes

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#387]

**Comment by dberlow** [comment]
Sources for first iteration committed.

**Comment by sannorozco** [comment]
@dberlow I added the GRAD trims to the build 😉

@MariannaPaszkowska I updated the designspace to include the sources located (temporary) in roman/Skateboards Previews/, so from now on I live the CI will send us fail message if it’s not updated on route end.

Cheers!
