### ISSUE TITLE
Remove avar1 table on optical size axis

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#389]
We decided not to ship an avar table on the opsz axis as of the March release. Let's remove the definition from our main branch designspace file.

**Comment by chrissimpkins** [comment]
This is still present in our main branch.  Let's leave this open until we merge a change that addresses it.  Thanks!

**Comment by dberlow** [comment]
Sorry, I thought FB has made the change, it's merged and this issue was
changed in priority.

**Comment by chrissimpkins** [comment]
@MariannaPaszkowska It looks like Santiago removed this from the designspace file in their branch.  I think that this is on us to import the change (or simply open a PR to remove it directly from the production designspace file) at this stage.

https://github.com/googlefonts/googlesans-flex/blob/ed785d0c08f68647a40836e2b07aa1c87721f74c/sources/roman/GoogleSansFlex.designspace#L10-L12
