### ISSUE TITLE
GRAD review part 1. Trimming and +50 on hairline

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#391]
GRAD trimming: Most masters are approved; thank you! Here are a couple of issues I found. 

- [x] **GRAD -50 and sizes 6 and 18** Glyphs `6` and `9` have some contour issues

<img width="1246" alt="Screenshot 2023-02-18 at 12 41 24 AM" src="https://user-images.githubusercontent.com/22956348/219811662-b9e86bd9-9ad1-4cde-8291-aa28a59a86d9.png">

<img width="1624" alt="Screenshot 2023-02-18 at 12 40 51 AM" src="https://user-images.githubusercontent.com/22956348/219811664-e8b460cf-a8d1-480d-b6a3-9337a7deae56.png">

- [x] **GRAD +50 on wght** 1 has contrast (opsz 18-144, 25-130 wdth) and 6 and 9 have contour issues

<img width="1563" alt="Screenshot 2023-02-18 at 12 45 23 AM" src="https://user-images.githubusercontent.com/22956348/219811651-aaa46af6-757d-4eba-b909-3d6970f2d1b7.png">

<img width="1592" alt="Screenshot 2023-02-18 at 12 45 10 AM" src="https://user-images.githubusercontent.com/22956348/219811656-5f3237d6-bb55-48e4-83ed-12f9f57a3437.png">

<img width="1596" alt="Screenshot 2023-02-18 at 12 44 50 AM" src="https://user-images.githubusercontent.com/22956348/219811658-dfcad095-cb64-4c13-9ae8-57de393b750d.png">

<img width="1442" alt="Screenshot 2023-02-18 at 12 54 11 AM" src="https://user-images.githubusercontent.com/22956348/219812594-2ec92531-f8d8-4ba7-bb29-65687019b32c.png">

<img width="1578" alt="Screenshot 2023-02-18 at 12 55 20 AM" src="https://user-images.githubusercontent.com/22956348/219812756-7938988c-9b08-4241-a89a-93cdbb22e41e.png">

**Comment by dberlow** [comment]
Do you agree with the trim range we've selected?

**Comment by MariannaPaszkowska** [comment]
The trim range works well.  Many thanks!
