### ISSUE TITLE
GRAD review part2. Glyph positioning issues

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#392]
GRAD review:
Characters that need updates:
- Accents moving horizontally: Ò Ó Ô Õ Ö Ď ŕ ř  Ď ř ŕ ę Ų 
- Glyphs changing vertical position: ¹ ² ³  • 
- Glyphs changing horizontal position: ‹ ›  "Acute Accent"  "Grave Accent"
- Components are not aligned: Ŋ ŋ
- Dot moves vertically: Ŀ
- Outline breaking slightly at -50/+50: \ (1000 wght, 151 wdth, 144opsz)

Full list: ` Ò Ó Ô Õ Ö Ď ŕ ř  Ď ř ŕ ę Ų ¹ ² ³  • ‹ ›  \ Ŋ ŋ Ŀ ŀ `  `Acute Accent`  `Grave Accent`

**Details and master locations**

- [x] **1. Location: 1 weight, 100 width, 6 size**
- Glyphs changing vertical position: ¹ ² ³ • 
- Dot moves vertically: Ŀ
- Accents moving horizontally: Ď ř ŕ ę Ų 

- [x] **2. Location: 1000 weight, 100 width, 6 size**
- Glyphs changing vertical position: •
- Accents moving horizontally: Ď ř ŕ
- Components are not aligned: Ŋ ŋ
<img width="637" alt="Screenshot 2023-02-17 at 11 30 18 PM" src="https://user-images.githubusercontent.com/22956348/219797567-a02584d8-9449-448c-aae0-ec531f125f4a.png">

- [x] **3.  Location: 1000 weight, 151 width, 6 size**
- Accents moving horizontally: ŕ ř 
- dot moves vertically: Ŀ
- Glyphs changing vertical position: •
- Glyphs changing horizontal position: ‹ ›

- [x] **4. Location: 1 weight, 151 width, 6 size**
- Glyphs changing vertical position: ¹ ² ³ • 
 - Accents moving horizontally: ę Ų 
 - Components are not aligned: Ŋ ŋ
 - Glyphs changing horizontal position: ‹ ›

- [x] ** 5. Location: 1 weight, 25 width, 18 size**
- Glyphs changing vertical position: ¹ ² ³ • 
- Accents moving horizontally: ę Ų 
- Components are not aligned: Ŋ ŋ
- Accents moving horizontally: ŕ ř 

- [x] **6. Location: 1 weight, 25 width, 144 size**
- Glyphs changing vertical position: ¹ ² ³  •
- Accents moving horizontally: ę Ų ŕ ř
- Components are not aligned: Ŋ ŋ
- dot moves vertically: ŀ (lowercase ldot)

- [x] **7. Location: 1000 weight, 25 width, 144 size**
- Accents moving horizontally: Ò Ó Ô Õ Ö Ď ŕ ř
- Glyphs changing vertical position: ¹ ² ³  • 
- Glyphs changing horizontal position: ‹ ›
- Components are not aligned: Ŋ ŋ

- [x] **8. Location: 1000 weight, 151 width, 144 size**
- Glyphs moving horizontally: ` ´ 
- Glyphs moving vertically: •
- Accents moving horizontally: Ò Ó Ô Õ Ö	ŕ ř
- Outline breaking slightlu at -50/+50: \

**Comment by dberlow** [comment]
While addressing some grde issues,

   -

   Glyphs changing vertical position: ¹ ² ³ •

...is part of opsz.

**Comment by dberlow** [comment]
All sub issues checked and corrected on GRAD min and max.

   - Outline breaking slightly at -50/+50: \ (1000 wght, 151 wdth, 144opsz)

Will address in other issue.

**Comment by MariannaPaszkowska** [comment]
I still see a lot of the reposted issues in the font from latest import build. 

<img width="654" alt="Screenshot 2023-02-20 at 3 02 24 PM" src="https://user-images.githubusercontent.com/22956348/220116157-ac30597e-9684-4019-afd6-6484d8a8bda8.png">

**Comment by dberlow** [comment]
Yes, changes need to be copied to other glyphs and styles.

6 and 9 still need a hero today.;)

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates!
