### ISSUE TITLE
spacing of "e" at 6pt 151 wdth

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#394]
<img width="677" alt="Screenshot 2023-02-17 at 4 36 43 PM" src="https://user-images.githubusercontent.com/22956348/219813237-71b6171e-7ab1-45a3-b7aa-08ff77f55480.png">
<img width="749" alt="Screenshot 2023-02-17 at 4 38 09 PM" src="https://user-images.githubusercontent.com/22956348/219813260-6101a2f7-4233-4320-8eb0-a70d1b2158cb.png">

**Comment by dberlow** [comment]
Change committed

**Comment by MariannaPaszkowska** [comment]
Thank you @dberlow!
