### ISSUE TITLE
Incorrect style name in source

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#4]
GoogleSansFlex-opsz6-wdth151-wght400-ROND0 has an incorrect style name, 
"opsz6-wdth100-wght400-ROND0" should be "opsz6-wdth151-wght400-ROND0"

**Comment by chrissimpkins** [comment]
@RickyDaMa Was this issue addressed?

**Comment by RickyDaMa** [comment]
I can't see any instances where this is inconsistent in a Designspace at the current HEAD. There were some issues of similar nature before e0c3cb2b04130a35820ac8cce4366f865c663622 I think, but that update fixed them. The only typos I've noticed & corrected from provided files are aafb77835a7638b9b4bfa0d215116dc8bcfd05f1

@dberlow was this issue with a designspace file or the naming of a UFO?
