### ISSUE TITLE
Create Labels in the repository

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#40]
@dberlow, this is an issue tracking progress on creating new labels in this repository. You can request new labels in the comments here. 

Labels with description: 

- [x] `-ready for review`-  ready for discussion/revision
- [x] `---still debating`
- [x] `---needs approval` - extra attention is needed

- [x] `outline bug`  - Something is wrong with the outline of the glyph
- [x] `design-space change` 
- [x] `glyph charset change`
- [x] `feature change`

- [x] `Alpha` - this is about a font version Alpha 
- [x] `Beta`- this is about a font version Beta 

CC @chrissimpkins @belluzj

**Comment by RickyDaMa** [comment]
FYI Jany & I have also created labels for "This quarter", "Next quarter" and various priority ones "P1" "P2" etc.

**Comment by MariannaPaszkowska** [comment]
Update after a meeting: instead of "This quarter" and "Next quarter" we will use Milestones v1.000 and v1.1000. This will need less maintenance. I will remove those labels.

**Comment by RickyDaMa** [comment]
I added the appropriate milestone to all issues using the quarter labels and removed the labels during the meeting 😃

**Comment by MariannaPaszkowska** [comment]
Great, thank you, @RickyDaMa!
