### ISSUE TITLE
GRAD +50 on wght 1 has contrast

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#401]
**GRAD +50 on wght 1** has contrast (opsz 18-144, 25-130 wdth). (moved from #391 ) What can be done about this?

<img width="1563" alt="Screenshot 2023-02-18 at 12 45 23 AM" src="https://user-images.githubusercontent.com/22956348/219811651-aaa46af6-757d-4eba-b909-3d6970f2d1b7.png">

<img width="1592" alt="Screenshot 2023-02-18 at 12 45 10 AM" src="https://user-images.githubusercontent.com/22956348/219811656-5f3237d6-bb55-48e4-83ed-12f9f57a3437.png">

<img width="1596" alt="Screenshot 2023-02-18 at 12 44 50 AM" src="https://user-images.githubusercontent.com/22956348/219811658-dfcad095-cb64-4c13-9ae8-57de393b750d.png">

<img width="1442" alt="Screenshot 2023-02-18 at 12 54 11 AM" src="https://user-images.githubusercontent.com/22956348/219812594-2ec92531-f8d8-4ba7-bb29-65687019b32c.png">

<img width="1578" alt="Screenshot 2023-02-18 at 12 55 20 AM" src="https://user-images.githubusercontent.com/22956348/219812756-7938988c-9b08-4241-a89a-93cdbb22e41e.png">

**Comment by dberlow** [comment]
The grade trims have to be re-instanced after the changes that I’ve made.On Feb 20, 2023, at 9:07 AM, Marianna Paszkowska ***@***.***> wrote:﻿
GRAD +50 on wght 1 has contrast (opsz 18-144, 25-130 wdth). (moved from #391 ) What can be done about this?

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates!

<img width="877" alt="Screenshot 2023-02-22 at 12 02 58 PM" src="https://user-images.githubusercontent.com/22956348/220587471-d5514e76-9fb4-4343-8722-dcbaa94a5074.png">
