### ISSUE TITLE
Kerning review 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#403]
Masters to review:
- [ ] opsz 6, wdth 100, wght 400
- [ ] opsz 6, wdth 100, wght 1
- [ ] opsz 6, wdth 100, wght 1000
- [ ] opsz 6, wdth 25, wght 400
- [ ] opsz 6, wdth 25, wght 1
- [ ] opsz 6, wdth 25, wght 1000
- [ ] opsz 6, wdth 151, wght 400
- [ ] opsz 6, wdth 151, wght 1
- [ ] opsz 6, wdth 151, wght 1000
- [x] opsz 18, wdth 100, wght 400
- [ ] opsz 18, wdth 100, wght 1
- [ ] opsz 18, wdth 100, wght 1000
- [x] opsz 18, wdth 25, wght 400
- [ ] opsz 18, wdth 25, wght 1
- [ ] opsz 18, wdth 25, wght 1000
- [ ] opsz 18, wdth 151, wght 400
- [ ] opsz 18, wdth 151, wght 1
- [ ] opsz 18, wdth 151, wght 1000
- [x] opsz 144, wdth 100, wght 400
- [ ] opsz 144, wdth 100, wght 1
- [x] opsz 144, wdth 100, wght 1000
- [x] opsz 144, wdth 25, wght 400
- [ ] opsz 144, wdth 25, wght 1
- [ ] opsz 144, wdth 25, wght 1000
- [x] opsz 144, wdth 151, wght 400
- [x] opsz 144, wdth 151, wght 1
- [ ] opsz 144, wdth 151, wght 1000

**Comment by chrissimpkins** [comment]
related https://github.com/googlefonts/googlesans-flex/issues/415
