### ISSUE TITLE
Make intermediate masters into true sparse masters

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#416]
We should investigate if this will have an impact on the file-size

**Comment by chrissimpkins** [comment]
Deprioritized for v1.1. We will address this but not this week.

**Comment by sannorozco** [comment]
All widt intermediates were sparsified, filesize decreased.

**Comment by MariannaPaszkowska** [comment]
@sannorozco, thanks for the update! What's the filesize difference?

**Comment by MariannaPaszkowska** [comment]
@sannorozco, thanks for the update! What's the filesize difference?

**Comment by dberlow** [comment]
Hey Marianna,It’s gone to 1.2 from 2.2.Cheers, DavidOn Mar 27, 2023, at 8:25 AM, Marianna Paszkowska ***@***.***> wrote:﻿
@sannorozco, thanks for the update! What's the filesize difference?

**Comment by MariannaPaszkowska** [comment]
closing this as we moved to the glyphspackage format where we use brace layers as sparse masters.
