### ISSUE TITLE
Deliver a keep-list for sparse masters

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#418]
We will need this glyph list to automate the process of creating true sparse masters from our intermediate masters. See #416

**Comment by chrissimpkins** [comment]
I am deprioritizing this.  OK to keep all masters as full for this release.  We'll look into this in a future release.  We will still need the list of sparse glyphs across all masters but it does not need to be collected this week.

**Comment by chrissimpkins** [comment]
David told me today that this involves 34 glyphs across all sparse masters. They are reviewing the file size impact.

**Comment by dberlow** [comment]
36 final count.

The three opsz17.999, and all wdth50 and width85 sources may be sparse to
this list.

dollar
ampersand
two
three
five
six
nine
question
C
G
J
S
a
c
e
g
r
s
cent
sterling
section
ordfeminine
ae
ae.alt
oe
Euro
two.numerator
three.numerator
five.numerator
six.numerator
nine.numerator
two.tf
three.tf
five.tf
question-top
question-bottom

**Comment by sannorozco** [comment]
All the 17.999 & width intermediates were sparsified, filesize decreased.
