### ISSUE TITLE
beta 9 opsz max wght max round max `r` kink

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#424]
<img width="183" alt="Screenshot 2023-02-24 at 5 21 09 PM" src="https://user-images.githubusercontent.com/261579/221324774-ecf1d367-5012-47cd-b850-5506db313707.png">

top of the arm has a kink

**Comment by sannorozco** [comment]
This was fixed on Friday after this.

**Comment by MariannaPaszkowska** [comment]
@sannorozco 
<img width="925" alt="Screenshot 2023-02-27 at 10 56 50 AM" src="https://user-images.githubusercontent.com/22956348/221518341-6448bd5b-a5f7-4c6d-8601-b0a33a56466a.png">

<img width="858" alt="Screenshot 2023-02-27 at 10 57 20 AM" src="https://user-images.githubusercontent.com/22956348/221518458-d0e3f872-c059-4913-9120-f4f4138a175d.png">

<img width="939" alt="Screenshot 2023-02-27 at 10 57 51 AM" src="https://user-images.githubusercontent.com/22956348/221518588-6a655c04-dac1-4443-86b7-0e3e5d9752b2.png">

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates! I confirm that this is fixed. Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4303113101)
