### ISSUE TITLE
OS/2 xAvgCharWidth 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#425]
FontBakery: 
    WARN OS/2 xAvgCharWidth is 1092 but it should be 1102                      
          which corresponds to the average of the widths of all glyphs in the   
          font. [code: xAvgCharWidth-wrong]                                     
    Result: WARN

**Comment by madig** [comment]
I'm not aware of a use for this value. I also tried changing the subsetter to recalc it and to leave out any post-processing after building the fonts, and the value didn't change. I'd ignore this.

**Comment by felipesanches** [comment]
I'd like to figure out which programs do use this value and add a more detailed explanation to the check rationale text.

**Comment by madig** [comment]
Hm, does the fontbakery calculcation differ from what fontTools is calculating, and if so, why?

**Comment by dberlow** [comment]
There are literally a 48 Million correct values  for this in  GSF.﻿I think I was told long ago by MS that this was to work in conjunction with Panose numbers to find a suitable replacement for a missing font. But I’m not seeing any documentation that describes how this value is changed, as MVAR does for alignments, to remain accurate to the variations of the average widths over the design space locations of wght, wdth and size.This leads me to believe that Microsoft isn’t using it and I don’t know anybody who is.On Feb 27, 2023, at 9:12 AM, Felipe Corrêa da Silva Sanches ***@***.***> wrote:﻿
I'd like to figure out which programs do use this value and add a more detailed explanation to the check rationale text.

**Comment by tiroj** [comment]
> Hm, does the fontbakery calculcation differ from what fontTools is calculating, and if so, why?

Possibly relevant: the calculation of xAvgCharWidth depends on the OS/2 table version. Older versions of the table specified an average of all the glyphs in a font; since version 3, it is the average of all _non-zero width_ glyphs.

This can be considered legacy data in a variable font, and should correspond to the default instance in the glyf table.
