### ISSUE TITLE
interpolation issue = 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#427]
Please check the contour order across masters in:

- [x] equal
- [x] equal.tf
- [x] notequal
- [x] notequal.tf

<img width="842" alt="Screenshot 2023-02-27 at 2 13 57 PM" src="https://user-images.githubusercontent.com/22956348/221561204-99f03717-e1f1-44ba-af1f-f00c4af0ed97.png">

<img width="901" alt="Screenshot 2023-02-27 at 2 13 38 PM" src="https://user-images.githubusercontent.com/22956348/221561267-61384ef9-6531-49ff-b107-9025c34575ad.png">

**Comment by MariannaPaszkowska** [comment]
Thank you for the quick updates. I confirm that this is fixed. Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4303113101)

**Comment by MariannaPaszkowska** [comment]
@sannorozco 

<img width="666" alt="Screenshot 2023-03-01 at 6 43 48 PM" src="https://user-images.githubusercontent.com/22956348/222205463-472c118b-9a93-411e-b81d-472f91fa4df3.png">

<img width="682" alt="Screenshot 2023-03-01 at 6 45 01 PM" src="https://user-images.githubusercontent.com/22956348/222205787-8cbba192-6309-460f-b8b5-0525723cac2b.png">
<img width="651" alt="Screenshot 2023-03-01 at 6 44 47 PM" src="https://user-images.githubusercontent.com/22956348/222205790-c4008e8e-a7ed-4a78-9a29-1025c4e7e5b6.png">
<img width="689" alt="Screenshot 2023-03-01 at 6 44 41 PM" src="https://user-images.githubusercontent.com/22956348/222205794-b596e2a4-7e9f-4cfe-9489-11f1d5127385.png">

**Comment by MariannaPaszkowska** [comment]
@sannorozco Please also fix .tf glyph: <img width="708" alt="Screenshot 2023-03-01 at 9 59 08 PM" src="https://user-images.githubusercontent.com/22956348/222252381-ad4d459d-d48e-478f-9a39-16df912e69c4.png">

**Comment by MariannaPaszkowska** [comment]
notequal.tf in ROND=100 still needs updates:

<img width="1212" alt="Screenshot 2023-03-02 at 11 54 38 AM" src="https://user-images.githubusercontent.com/22956348/222394448-5fd4a09f-9420-426d-838a-73cd77a6046d.png">
<img width="1217" alt="Screenshot 2023-03-02 at 11 54 27 AM" src="https://user-images.githubusercontent.com/22956348/222394489-31b19346-0dcc-452b-b33b-97b3a9827228.png">

**Comment by dberlow** [comment]
Appears to be fixed
[image: image.png]

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates!
