### ISSUE TITLE
`y` interpolation issues

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#431]
<img width="754" alt="Screenshot 2023-02-27 at 7 43 33 PM" src="https://user-images.githubusercontent.com/22956348/221654141-d41bc967-8b63-4a4a-971c-b4d73acb6fc7.png">
<img width="634" alt="Screenshot 2023-02-27 at 7 43 48 PM" src="https://user-images.githubusercontent.com/22956348/221654158-0d6ed842-c6f2-47b6-9e78-5a361fafb848.png">

**Comment by sannorozco** [comment]
This was updated yesterday, no kinks.

**Comment by MariannaPaszkowska** [comment]
Thanks for the quick fix.
