### ISSUE TITLE
tabular figures reflow

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#435]
GoogleSansFlex-opsz6-wdth85-wght1000-ROND0-SPARSE.ufo                                              
```                                                                                
           • nine.tf (1373) has different width than zero.tf (1372.8)           
           • percent.tf (1373) has different width than zero.tf (1372.8)        
           • section.tf (1373) has different width than zero.tf (1372.8)        
           • cent.tf (1373) has different width than zero.tf (1372.8)           
           • dollar.tf (1373) has different width than zero.tf (1372.8)         
           • six.tf (1373) has different width than zero.tf (1372.8)            
           • sterling.tf (1373) has different width than zero.tf (1372.8) 
```

**Comment by dberlow** [comment]
The widths of GoogleSansFlex-opsz6-wdth85-wght1000-ROND0-SPARSE according to Robofont:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/1956494/222167852-c2557d1f-96f7-4a9c-82c3-d01a1bcfdadb.png">
Whatever it is that's going wrong here, it is happening beyond our design tools.

**Comment by MariannaPaszkowska** [comment]
Can this be due to a rounding error? @madig @belluzj ?

**Comment by madig** [comment]
I'll have a look tomorrow morning.

**Comment by madig** [comment]
zero.tf has a floating point width: https://github.com/googlefonts/googlesans-flex/blob/cc38ec2b5b4407dfd73eeaa5f8c638a1e2ae9c3d/sources/regular/GoogleSansFlex-opsz6-wdth85-wght1000-ROND0-SPARSE.ufo/glyphs/zero.tf.glif#L3.

A quick look at some othe glif files reveals that many are full of floating point numbers. I suppose that's what interpolation without rounding does. I can write a script to just round everything, but then someone would need to go and check that the results are as intended and that there are no stray off-by-ones...

**Comment by MariannaPaszkowska** [comment]
@madig we can round them; let's discuss that tomorrow.

**Comment by MariannaPaszkowska** [comment]
Related #453 and #459
