### ISSUE TITLE
ROND outline issues  `µ` 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#439]
@sannorozco Interpolation issues in [the latest sources](https://github.com/googlefonts/googlesans-flex/actions/runs/4303113101): 
cc @chrissimpkins @davelab6 
moved from #428  comments in to allow better tracking. 

- [x] `3` `3.tf`
<img width="634" alt="Screenshot 2023-03-01 at 6 36 27 PM" src="https://user-images.githubusercontent.com/22956348/222203673-cc816c63-92a9-4f8c-9da7-52afc8d7fb75.png">

- [x] `C`
<img width="688" alt="Screenshot 2023-03-01 at 6 46 48 PM" src="https://user-images.githubusercontent.com/22956348/222206264-fdcd68ca-7fad-439f-834c-5ad71189cb60.png">

- [x] `G`
<img width="727" alt="Screenshot 2023-03-01 at 6 47 48 PM" src="https://user-images.githubusercontent.com/22956348/222206476-96fe08bc-530c-4a73-80a6-5da7748b81cf.png">

- [x] `J`
<img width="713" alt="Screenshot 2023-03-01 at 6 48 16 PM" src="https://user-images.githubusercontent.com/22956348/222206647-71db53ed-d608-42f6-beda-dcbbca758b8e.png">

- [ ] `S` 
<img width="693" alt="Screenshot 2023-03-01 at 6 48 49 PM" src="https://user-images.githubusercontent.com/22956348/222206753-e11e23d7-f7a7-42d4-adbb-79a07fe07867.png">

- [x] `j` `ĳ`  
- [x]  `ȷ`
<img width="542" alt="Screenshot 2023-03-01 at 3 58 41 PM" src="https://user-images.githubusercontent.com/22956348/222161724-f8e7e8aa-bac7-4716-8152-d073a55fa5b7.png">
<img width="521" alt="Screenshot 2023-03-01 at 3 58 37 PM" src="https://user-images.githubusercontent.com/22956348/222161742-52133e2c-a9e5-4f70-9164-54c6cb234f22.png">

- [x] `s`
<img width="578" alt="Screenshot 2023-03-01 at 3 57 17 PM" src="https://user-images.githubusercontent.com/22956348/222161289-3538556b-4d3a-4a74-ab9e-1ed280f8f5ff.png">

- [x] `r` <img width="650" alt="Screenshot 2023-03-01 at 6 51 57 PM" src="https://user-images.githubusercontent.com/22956348/222207674-2f5508fb-9650-4781-b549-a0d3ef857cac.png">

- [x] `ß`
<img width="422" alt="Screenshot 2023-03-01 at 4 00 29 PM" src="https://user-images.githubusercontent.com/22956348/222162176-f45ea4ee-7b38-47c7-9fb3-c644ebcb080c.png">

<img width="657" alt="Screenshot 2023-03-01 at 6 23 36 PM" src="https://user-images.githubusercontent.com/22956348/222200216-bda5246e-2907-4a58-afd1-16c8bad59fd9.png">

- [x] `§`  `section.tf`
<img width="562" alt="Screenshot 2023-03-01 at 7 02 57 PM" src="https://user-images.githubusercontent.com/22956348/222210215-68c6b1da-e7ad-4551-8d94-573d07792c82.png">

- [ ] `µ`
<img width="615" alt="Screenshot 2023-03-01 at 7 05 54 PM" src="https://user-images.githubusercontent.com/22956348/222211027-26f7ca1d-841e-4d9a-bfef-1e30666937c6.png">

**Comment by MariannaPaszkowska** [comment]
Review of [this build](https://github.com/googlefonts/googlesans-flex/actions/runs/4317174830):
<img width="469" alt="Screenshot 2023-03-02 at 8 58 13 PM" src="https://user-images.githubusercontent.com/22956348/222525448-0fb4d998-d967-4d72-badc-39b4135baaff.png">
<img width="534" alt="Screenshot 2023-03-02 at 9 02 31 PM" src="https://user-images.githubusercontent.com/22956348/222526429-a4f13ff9-f44c-48c6-a47f-63739e9f6003.png">
<img width="616" alt="Screenshot 2023-03-02 at 9 00 17 PM" src="https://user-images.githubusercontent.com/22956348/222526431-20994929-6cae-468b-904e-c1e667142b24.png">
<img width="619" alt="Screenshot 2023-03-02 at 9 00 10 PM" src="https://user-images.githubusercontent.com/22956348/222526432-90f0279a-a035-46da-88de-ad39e02e3f74.png">
<img width="573" alt="Screenshot 2023-03-02 at 8 59 52 PM" src="https://user-images.githubusercontent.com/22956348/222526434-c5843907-78fa-4f61-8eed-ce36af4bf550.png">
<img width="578" alt="Screenshot 2023-03-02 at 8 59 14 PM" src="https://user-images.githubusercontent.com/22956348/222526437-f1de5cd7-e0b2-4b4a-b993-cd354ebaeaef.png">

**Comment by MariannaPaszkowska** [comment]
<img width="630" alt="Screenshot 2023-03-03 at 12 27 44 PM" src="https://user-images.githubusercontent.com/22956348/222696955-6c126470-1f14-4f88-864e-9acf9a7799c2.png">

test string: `3 C G J S j ȷ  r ß § µ`

**Comment by MariannaPaszkowska** [comment]
@sannorozco `S` `C` `s` `r` `ȷ` `§` and `µ` 

<img width="1249" alt="Screenshot 2023-05-16 at 1 32 10 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/05104b43-ace5-4646-b44c-19d61304be3e">

<img width="869" alt="Screenshot 2023-05-16 at 1 34 35 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/c850d824-fa5c-4bee-b889-00fe06db2eca">

<img width="849" alt="Screenshot 2023-05-16 at 1 35 56 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/82614105-c3ff-4a12-89e4-04aed98fec3f">


<img width="848" alt="Screenshot 2023-05-16 at 1 36 08 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/97630d7f-10b2-4ea1-93c6-93992b9c8868">

**Comment by sannorozco** [comment]
I’m still working on this issue.

**Comment by MariannaPaszkowska** [comment]
@sannorozco mi/micro µ is still to-do: <img width="892" alt="Screenshot 2023-05-18 at 4 41 54 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/aa8eb8f7-d813-48d9-ac1f-fcaf4ff943ec">

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates!
