### ISSUE TITLE
The diaeresis - interpolation bug

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#445]
P2: 
The diaeresis seems to become larger and smaller - it looks like a jump in interpolation. 
<img width="533" alt="Screenshot 2023-03-01 at 7 38 54 PM" src="https://user-images.githubusercontent.com/22956348/222254127-fb51fccf-b438-4d84-8b45-a008c4644092.png">
<img width="526" alt="Screenshot 2023-03-01 at 7 38 40 PM" src="https://user-images.githubusercontent.com/22956348/222254133-a3b9e047-427f-4626-bacb-6cb761463bbb.png">
<img width="637" alt="Screenshot 2023-03-01 at 7 38 33 PM" src="https://user-images.githubusercontent.com/22956348/222254137-89655d85-31f9-445e-bcc6-5c79f9fb82aa.png">

**Comment by dberlow** [comment]
committed, ROND0 & ROND100

**Comment by MariannaPaszkowska** [comment]
Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4312104946):

<img width="425" alt="Screenshot 2023-03-02 at 11 20 42 AM" src="https://user-images.githubusercontent.com/22956348/222386149-2cb7162c-d4be-44b7-918c-c4f32e89b805.png">
<img width="457" alt="Screenshot 2023-03-02 at 11 20 25 AM" src="https://user-images.githubusercontent.com/22956348/222386154-3c446bde-3d12-4e4f-95cb-3ead53d1f27b.png">
<img width="400" alt="Screenshot 2023-03-02 at 11 20 48 AM" src="https://user-images.githubusercontent.com/22956348/222386074-8e49d778-0d0e-4a76-806e-9a0557b8a5b9.png">

**Comment by dberlow** [comment]
repairs committed
