### ISSUE TITLE
Outline bug in `6` and `9` on GRAD -50

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#460]
<img width="650" alt="Screenshot 2023-03-03 at 6 11 48 PM" src="https://user-images.githubusercontent.com/22956348/222776930-355e5ab3-75fd-4bba-a2dd-8c44531a3c9b.png">

**Comment by sannorozco** [comment]
@MariannaPaszkowska This has been fixed.

**Comment by MariannaPaszkowska** [comment]
Thank you for the updates. There had been big progress. 
Please also fix this:
<img width="535" alt="Screenshot 2023-03-05 at 12 41 52 PM" src="https://user-images.githubusercontent.com/22956348/222955575-6510bd8e-fce0-449c-ac95-99ac97d3399e.png">
<img width="502" alt="Screenshot 2023-03-05 at 12 41 47 PM" src="https://user-images.githubusercontent.com/22956348/222955582-db27963c-7261-4855-987c-652a2f154fe2.png">

<img width="717" alt="Screenshot 2023-03-05 at 12 44 38 PM" src="https://user-images.githubusercontent.com/22956348/222955721-7bfa7810-2c8f-4153-8c3b-7182a3c0a8a5.png">
<img width="696" alt="Screenshot 2023-03-05 at 12 44 57 PM" src="https://user-images.githubusercontent.com/22956348/222955738-6b21d7bf-32b9-4472-a893-d1850fa260b0.png">

<img width="685" alt="Screenshot 2023-03-05 at 1 01 54 PM" src="https://user-images.githubusercontent.com/22956348/222956564-0cff25b6-205a-4bdb-b30b-62d9edc73aa6.png">
<img width="656" alt="Screenshot 2023-03-05 at 1 02 32 PM" src="https://user-images.githubusercontent.com/22956348/222956583-e7b10bcb-c3ec-4242-ac3f-ed55d0aa0953.png">


Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4335509495) 
CC @dberlow @chrissimpkins @davelab6

**Comment by MariannaPaszkowska** [comment]
I confirm that this is fixed. Thank you! 
Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4341490294)
CC @dberlow @chrissimpkins @davelab6
