### ISSUE TITLE
Outline bug in `G` and `C` 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#461]
<img width="639" alt="Screenshot 2023-03-03 at 4 32 15 PM" src="https://user-images.githubusercontent.com/22956348/222777444-85189cd3-2e97-43f1-abca-a65bbbb0f374.png">
<img width="615" alt="Screenshot 2023-03-03 at 4 32 08 PM" src="https://user-images.githubusercontent.com/22956348/222777450-fa67bff0-db02-4bbd-8b9e-b81bd1535797.png">
<img width="685" alt="Screenshot 2023-03-03 at 4 29 35 PM" src="https://user-images.githubusercontent.com/22956348/222777453-4ebf0e45-6b6f-4140-9710-8e6e3e4a0034.png">
<img width="714" alt="Screenshot 2023-03-03 at 4 28 13 PM" src="https://user-images.githubusercontent.com/22956348/222777457-464e07d7-d070-4c7c-ae0e-853c006702a0.png">

**Comment by sannorozco** [comment]
@MariannaPaszkowska @chrissimpkins @dberlow this has been fixed.

**Comment by MariannaPaszkowska** [comment]
I confirm that this is fixed. Thank you! 
Reviewed [build](https://github.com/googlefonts/googlesans-flex/actions/runs/4335509495) 
CC @dberlow @chrissimpkins @davelab6
