### ISSUE TITLE
interpolation bug in 6 and 9

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#467]
<img width="680" alt="Screenshot 2023-03-06 at 3 08 31 PM" src="https://user-images.githubusercontent.com/22956348/223119169-d7594e78-4965-4f1c-bb66-4fa5f5259533.png">
<img width="657" alt="Screenshot 2023-03-06 at 3 08 24 PM" src="https://user-images.githubusercontent.com/22956348/223119176-71fac932-ddfe-4b22-9bc7-93a61982cd8b.png">
<img width="610" alt="Screenshot 2023-03-06 at 3 08 07 PM" src="https://user-images.githubusercontent.com/22956348/223119180-aab94c9a-558d-4d8d-acba-3643acd48051.png">
<img width="666" alt="Screenshot 2023-03-06 at 3 07 51 PM" src="https://user-images.githubusercontent.com/22956348/223119181-b0a926eb-9666-46b8-b5dc-299f880d5c65.png">
<img width="650" alt="Screenshot 2023-03-06 at 3 07 42 PM" src="https://user-images.githubusercontent.com/22956348/223119184-6903b3c0-7fc3-452c-a566-d897cb8c2941.png">
<img width="648" alt="Screenshot 2023-03-06 at 3 07 34 PM" src="https://user-images.githubusercontent.com/22956348/223119188-76bc22c1-e1be-4ef4-bc6c-55982cfeb2d6.png">

**Comment by MariannaPaszkowska** [comment]
Trimming
<img width="1005" alt="Screenshot 2023-03-07 at 4 53 49 PM" src="https://user-images.githubusercontent.com/22956348/223459391-f88b5efa-d567-4c87-8627-9704e5fa0bed.png">

**Comment by MariannaPaszkowska** [comment]
<img width="767" alt="Screenshot 2023-05-16 at 1 16 28 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a4afa2ca-6e82-4d6b-a55e-0a11ba1c809f">
<img width="728" alt="Screenshot 2023-05-16 at 1 16 23 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/5f11628a-94fc-4191-b630-b0b224a36aa1">
@sannorozco

**Comment by MariannaPaszkowska** [comment]
@dberlow @sannorozco that previous outline bug is now fixed, but I just found this issue: <img width="695" alt="Screenshot 2023-05-22 at 9 28 19 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ac3d736f-b26e-445d-8201-41b047c6af98">

For comparison, this is the release v1.001:

<img width="610" alt="Screenshot 2023-05-22 at 9 30 42 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a75ec9dd-a4a3-433b-ae4e-ebdc79a6dacb">

**Comment by sannorozco** [comment]
Hallo @MariannaPaszkowska, I updated this and it’s ready for review.
