### ISSUE TITLE
Fallback stack info

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#47]
@chrissimpkins explained to me just now that the current plan for the sans-serif fallback stack for Android U is:

1P:

* GS Flex [L] **optional opt-in family**
* GS Classic [LGC + i18n]
* Roboto Classic [LGC-max]
* Noto Sans [i18n]

3P:

* Roboto Flex [LGC-min] **optional opt-in family**
* Roboto Classic [LGC-max]
* Noto Sans [i18n]

**Comment by davelab6** [comment]
@dberlow wrote me,


We all know that the flex’s design spaces are larger than the fallback’s design spaces, that the italics of GSF are separate fonts while the Robotos have slant axes, and that the only compatible design space location, with close appearance between GSF and GS, is opsz18, wght400, I.E. the default.

Since FB have not been asked for advice on how to handle these issues, or told FB how Google will handle them, FB must assume Google has already figured it out.

When this was font stack possibility was first revealed to FB, and discussed with @davelab6  in the early months of 2022, there was contour compatibility between GS and GSF and time for options. 

The first was to borrow a few extrema from GSF, scale them down to 1000 upm and add them to GS to make the breath of the two design spaces equal. That is no longer possible in the time frame available to us, as the contours have diverged with the addition of square-sided condensation and the ROND axis. Stripping the contour points from the GSF extrema to match GS and creating a designspace extension of GS space is a 2-3 week project for a semi-skilled individual.

The second option, one that seems to now be in motion, was to constrain the users of GSF/RF to styles available in GS/R. We’re happy to advise on this as required, but everyone knows our schedule.

**Comment by davelab6** [comment]
> FB must assume Google has already figured it out

Please don't assume anything without stating it in an issue

**Comment by dberlow** [comment]
Sorry about the misspost. It was meant for all. I’m working on phone with very limited connectivity and slow when working.

**Comment by davelab6** [comment]
I think @chrissimpkins should decide how to move this issue forward. We aren't going to touch GS and we aren't going to constrain the usage, either, I don't think. 

Possibly there's nothing actionable here and now this is documented here in the repo we can close this issue and move on.

**Comment by chrissimpkins** [comment]
The plan as defined in the original post is correct and has been discussed across Fonts, Android eng, and Android i18n stakeholders.  I don't think that there is anything actionable here.  Please feel free to reopen if you'd like to discuss further.
