### ISSUE TITLE
outline issue `₈` ROND

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#473]
<img width="410" alt="Screenshot 2023-03-07 at 3 51 03 PM" src="https://user-images.githubusercontent.com/22956348/223442700-7595bf9f-4932-4c4f-bac0-b4f884a4f88d.png">
<img width="400" alt="Screenshot 2023-03-07 at 3 52 51 PM" src="https://user-images.githubusercontent.com/22956348/223442673-6fb8c502-5f23-4b04-bc79-7d2f3ad8bbbd.png">
<img width="370" alt="Screenshot 2023-03-07 at 3 52 31 PM" src="https://user-images.githubusercontent.com/22956348/223442691-b72c9759-ccb2-4e7f-a0df-f09490d4632f.png">

**Comment by dberlow** [comment]
I loaded up the fonts an manually input the three locations as you see. 
This must have either been corrected, or a rendering glitch.
<img width="770" alt="Screen Shot 2023-03-24 at 7 58 53 PM" src="https://user-images.githubusercontent.com/1956494/227664041-f7b9294a-5e2e-4250-96bb-954fbb3a3e0e.png">
Marianna, let me know if it appears on a fresh start.

**Comment by sannorozco** [comment]
This was uodated in ROND100 source.

**Comment by sannorozco** [comment]
This has been updated, ready for check @MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
<img width="474" alt="Screenshot 2023-05-16 at 1 12 46 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/d2db72fa-92a0-4b53-9aed-b05eb2d57284">
@sannorozco This doesn't seem fixed, could you please double check?

**Comment by sannorozco** [comment]
@MariannaPaszkowska Double checked, I built locally from the sources and it seems fixed.

<img width="462" alt="Screen Shot 2023-05-16 at 12 24 11" src="https://github.com/googlefonts/googlesans-flex/assets/1184152/f1b7790c-fb75-4388-af8c-5ec1aece5983">
