### ISSUE TITLE
outline issue `®`

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#474]
<img width="517" alt="Screenshot 2023-03-07 at 3 58 13 PM" src="https://user-images.githubusercontent.com/22956348/223443704-49828128-8816-49a3-9e9c-406eb77b6b88.png">

wght=602, wdth=99, opsz=144 ROND=100 GRAD=50
<img width="220" alt="Screenshot 2023-03-07 at 4 29 35 PM" src="https://user-images.githubusercontent.com/22956348/223452010-56027665-a3c3-4bc4-b4bb-758d293b0b1b.png">

**Comment by sannorozco** [comment]
This has been updated, ready for check @MariannaPaszkowska
