### ISSUE TITLE
ROND outline issue: `æ`

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#476]
`a r µ Œ ẞ æ ﬀ ﬁ ﬂ ﬃ ﬄ`
<img width="799" alt="Screenshot 2023-03-07 at 4 03 47 PM" src="https://user-images.githubusercontent.com/22956348/223445113-177a950e-a1da-45ea-bb90-7ca34a9ae193.png">

`ae` in 144pt:
<img width="512" alt="Screenshot 2023-03-07 at 4 02 38 PM" src="https://user-images.githubusercontent.com/22956348/223445166-065ac8cf-3d5f-4bcb-b90e-e8394b735b15.png">

**Comment by MariannaPaszkowska** [comment]
<img width="1276" alt="Screenshot 2023-05-16 at 1 14 55 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/5edbd77a-4b2d-47a4-95f4-c3c7df994aaf">

**Comment by MariannaPaszkowska** [comment]
@sannorozco thanks for the updates! Most glyphs are fixed, there is a small issue with ae æ glyph <img width="1608" alt="Screenshot 2023-05-18 at 4 03 36 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/da95ffa6-11ca-4bdb-a835-d6aa475a8d9e">

**Comment by dberlow** [comment]
repaired
