### ISSUE TITLE
spacing issue `‘ ’ ‚ “ ” „` 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#477]
<img width="550" alt="Screenshot 2023-03-08 at 2 48 40 PM" src="https://user-images.githubusercontent.com/22956348/223768592-e536c4db-3e0b-4e78-8dea-9a3d1ece27f7.png">

<img width="707" alt="Screenshot 2023-03-07 at 4 13 17 PM" src="https://user-images.githubusercontent.com/22956348/223447641-9c5a260d-6e66-4425-bf7f-0475d6d3c70c.png">
<img width="734" alt="Screenshot 2023-03-07 at 4 13 07 PM" src="https://user-images.githubusercontent.com/22956348/223447647-ee25e999-26b0-4d9e-a321-0bffa2710e1a.png">
<img width="870" alt="Screenshot 2023-03-07 at 4 12 54 PM" src="https://user-images.githubusercontent.com/22956348/223447649-0a3f97cf-8093-4602-9c55-9a60362ce275.png">
<img width="870" alt="Screenshot 2023-03-07 at 4 12 45 PM" src="https://user-images.githubusercontent.com/22956348/223447653-cc362e64-2db6-4127-8f74-5982c3fb4983.png">

**Comment by sannorozco** [comment]
All quotes on all sources were updated.
