### ISSUE TITLE
Outline issue in /circumflex and /caron

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#479]
wght=152 wdth=126 opsz=144 ROND=0 GRAD=50

<img width="852" alt="Screenshot 2023-03-07 at 4 22 00 PM" src="https://user-images.githubusercontent.com/22956348/223449758-c2824ad1-1222-4b5c-8e26-93b079941fb5.png">

GRAD=0
<img width="552" alt="Screenshot 2023-03-08 at 3 11 05 PM" src="https://user-images.githubusercontent.com/22956348/223767617-579f07f6-a63b-417f-8a95-ea5c38f76bac.png">

<img width="478" alt="Screenshot 2023-03-08 at 3 10 21 PM" src="https://user-images.githubusercontent.com/22956348/223767788-95499a82-ad73-4861-9797-672e8fca27fa.png">

<img width="471" alt="Screenshot 2023-03-08 at 3 06 07 PM" src="https://user-images.githubusercontent.com/22956348/223767705-941bf4fa-4827-4a7a-ad05-508a820ceb28.png">

**Comment by sannorozco** [comment]
These were updated.

**Comment by sannorozco** [comment]
This has been updated, ready for check @MariannaPaszkowska
