### ISSUE TITLE
bullet  `•` interpolation issue opsz6

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#480]
bullet  `•` changes size on the width axis
<img width="728" alt="Screenshot 2023-03-07 at 4 24 50 PM" src="https://user-images.githubusercontent.com/22956348/223450750-efc7929c-b70b-4cca-9911-714235a88853.png">
<img width="801" alt="Screenshot 2023-03-07 at 4 23 54 PM" src="https://user-images.githubusercontent.com/22956348/223450768-d5b8a619-ec08-4eb5-b7e1-01bb983859a7.png">
<img width="828" alt="Screenshot 2023-03-07 at 4 24 57 PM" src="https://user-images.githubusercontent.com/22956348/223450782-208d7cec-3a68-4fcf-b42f-d7c214652d5c.png">

**Comment by sannorozco** [comment]
Updated over the weekend.
