### ISSUE TITLE
Check and fix space widths

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#486]

**Comment by madig** [comment]
I ran a script over the sources (excluding Grade) to see what the spacing is in each source. Here's a table. I left out all sparse(?) wght sources (the columns between 400 and 1000) because none of them contained a space.

|  | wght=1.0 | wght=400.0 | wght=1000.0 |
|---|---|---|---|
| rond=0.0, opsz=6.0, wdth=25.0 | 516 | 464 | 468 |
| rond=0.0, opsz=6.0, wdth=85.0 |  |  | 468 |
| rond=0.0, opsz=6.0, wdth=100.0 | 516 | 540 | 468 |
| rond=0.0, opsz=6.0, wdth=151.0 | 752 | 866 | 650 |
| rond=0.0, opsz=17.999, wdth=25.0 | 456 | 440 | 466 |
| rond=0.0, opsz=18.0, wdth=25.0 | 450 | 438 | 466 |
| rond=0.0, opsz=18.0, wdth=50.0 | 478 | 447 | 477 |
| rond=0.0, opsz=18.0, wdth=85.0 | 516 | 459 | 492 |
| rond=0.0, opsz=18.0, wdth=100.0 | 532 | 464 | 499 |
| rond=0.0, opsz=18.0, wdth=151.0 | 823 | 755 | 850 |
| rond=0.0, opsz=144.0, wdth=25.0 | 300 | 300 | 380 |
| rond=0.0, opsz=144.0, wdth=50.0 | 400 | 400 | 410 |
| rond=0.0, opsz=144.0, wdth=85.0 | 450 | 450 | 452 |
| rond=0.0, opsz=144.0, wdth=100.0 | 500 | 500 | 470 |
| rond=0.0, opsz=144.0, wdth=151.0 | 896 | 628 | 725 |
| rond=100.0, opsz=6.0, wdth=25.0 | 516 | 464 | 468 |
| rond=100.0, opsz=6.0, wdth=85.0 |  |  | 468 |
| rond=100.0, opsz=6.0, wdth=100.0 | 516 | 540 | 468 |
| rond=100.0, opsz=6.0, wdth=151.0 | 752 | 866 | 650 |
| rond=100.0, opsz=18.0, wdth=25.0 | 450 | 438 | 466 |
| rond=100.0, opsz=18.0, wdth=50.0 | 478 | 447 | 477 |
| rond=100.0, opsz=18.0, wdth=85.0 | 516 | 459 | 492 |
| rond=100.0, opsz=18.0, wdth=100.0 | 532 | 464 | 499 |
| rond=100.0, opsz=18.0, wdth=151.0 | 823 | 755 | 850 |
| rond=100.0, opsz=144.0, wdth=25.0 | 300 | 300 | 380 |
| rond=100.0, opsz=144.0, wdth=50.0 | 400 | 400 | 410 |
| rond=100.0, opsz=144.0, wdth=85.0 | 450 | 450 | 452 |
| rond=100.0, opsz=144.0, wdth=100.0 | 500 | 500 | 470 |
| rond=100.0, opsz=144.0, wdth=151.0 | 896 | 628 | 725 |

I think the width isn't set for all spaces in the sources (or there is a space glyph for only one source for an axis), which might be messing with variation and leading to the weird behavior we're seeing 🤔 But also note how sometimes the spacing goes e.g. down and then up, when it should be progressively going down or some such.

**Comment by dberlow** [comment]
Santiago,
This changed and committed, along with proper values for all the other spaces and nbspace?

**Comment by MariannaPaszkowska** [comment]
@belluzj @madig, could you please check the spaces on fonts/sources from this work run: https://github.com/googlefonts/googlesans-flex/actions/runs/4989682925 ?

**Comment by madig** [comment]
Here are the space widths across the design space, all values rounded.

| |wght=1.0|wght=400.0|wght=449.0|wght=450.0|wght=579.0|wght=580.0|wght=698.999|wght=699.0|wght=699.999|wght=700.0|wght=1000.0|
|------------------------------------------------|--------|----------|----------|----------|----------|----------|------------|----------|------------|----------|-----------|
|rond=0.0, grad=-50.0, opsz=6.0, wdth=25.0       |440     |440       |442       |442       |446       |446       |450         |450       |450         |450       |460        |
|rond=0.0, grad=-50.0, opsz=6.0, wdth=39.999     |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=0.0, grad=-50.0, opsz=6.0, wdth=40.0       |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=0.0, grad=-50.0, opsz=6.0, wdth=50.0       |471     |479       |478       |478       |476       |476       |474         |474       |474         |474       |470        |
|rond=0.0, grad=-50.0, opsz=6.0, wdth=85.0       |502     |521       |517       |517       |505       |505       |495         |495       |495         |495       |468        |
|rond=0.0, grad=-50.0, opsz=6.0, wdth=100.0      |516     |540       |541       |541       |543       |543       |545         |545       |545         |545       |550        |
|rond=0.0, grad=-50.0, opsz=6.0, wdth=151.0      |752     |866       |869       |869       |876       |876       |883         |883       |883         |883       |900        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=25.0    |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=39.999  |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=40.0    |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=50.0    |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=85.0    |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=100.0   |464     |464       |467       |467       |474       |475       |481         |481       |482         |482       |499        |
|rond=0.0, grad=-50.0, opsz=17.999, wdth=151.0   |755     |755       |763       |763       |783       |784       |802         |802       |803         |803       |850        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=25.0      |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=39.999    |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=40.0      |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=50.0      |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=85.0      |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=100.0     |464     |464       |467       |467       |474       |475       |481         |481       |481         |482       |499        |
|rond=0.0, grad=-50.0, opsz=18.0, wdth=151.0     |755     |755       |763       |763       |783       |784       |802         |802       |802         |803       |850        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=25.0     |300     |300       |307       |307       |324       |324       |340         |340       |340         |340       |380        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=39.999   |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=40.0     |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=50.0     |376     |376       |380       |380       |390       |390       |400         |400       |400         |400       |425        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=85.0     |420     |420       |423       |423       |432       |432       |440         |440       |440         |440       |460        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=100.0    |450     |450       |452       |452       |456       |456       |460         |460       |460         |460       |470        |
|rond=0.0, grad=-50.0, opsz=144.0, wdth=151.0    |628     |628       |636       |636       |657       |657       |676         |676       |676         |677       |725        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=25.0         |440     |440       |442       |442       |446       |446       |450         |450       |450         |450       |460        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=39.999       |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=40.0         |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=50.0         |471     |479       |478       |478       |476       |476       |474         |474       |474         |474       |470        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=85.0         |502     |521       |517       |517       |505       |505       |495         |495       |495         |495       |468        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=100.0        |516     |540       |541       |541       |543       |543       |545         |545       |545         |545       |550        |
|rond=0.0, grad=0.0, opsz=6.0, wdth=151.0        |752     |866       |869       |869       |876       |876       |883         |883       |883         |883       |900        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=25.0      |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=39.999    |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=40.0      |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=50.0      |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=85.0      |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=100.0     |464     |464       |467       |467       |474       |475       |481         |481       |482         |482       |499        |
|rond=0.0, grad=0.0, opsz=17.999, wdth=151.0     |755     |755       |763       |763       |783       |784       |802         |802       |803         |803       |850        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=25.0        |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=39.999      |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=40.0        |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=50.0        |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=85.0        |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=100.0       |464     |464       |467       |467       |474       |475       |481         |481       |481         |482       |499        |
|rond=0.0, grad=0.0, opsz=18.0, wdth=151.0       |755     |755       |763       |763       |783       |784       |802         |802       |802         |803       |850        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=25.0       |300     |300       |307       |307       |324       |324       |340         |340       |340         |340       |380        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=39.999     |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=40.0       |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=50.0       |376     |376       |380       |380       |390       |390       |400         |400       |400         |400       |425        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=85.0       |420     |420       |423       |423       |432       |432       |440         |440       |440         |440       |460        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=100.0      |450     |450       |452       |452       |456       |456       |460         |460       |460         |460       |470        |
|rond=0.0, grad=0.0, opsz=144.0, wdth=151.0      |628     |628       |636       |636       |657       |657       |676         |676       |676         |677       |725        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=25.0        |440     |440       |442       |442       |446       |446       |450         |450       |450         |450       |460        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=39.999      |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=40.0        |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=50.0        |471     |479       |478       |478       |476       |476       |474         |474       |474         |474       |470        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=85.0        |502     |521       |517       |517       |505       |505       |495         |495       |495         |495       |468        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=100.0       |516     |540       |541       |541       |543       |543       |545         |545       |545         |545       |550        |
|rond=0.0, grad=50.0, opsz=6.0, wdth=151.0       |752     |866       |869       |869       |876       |876       |883         |883       |883         |883       |900        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=25.0     |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=39.999   |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=40.0     |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=50.0     |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=85.0     |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=100.0    |464     |464       |467       |467       |474       |475       |481         |481       |482         |482       |499        |
|rond=0.0, grad=50.0, opsz=17.999, wdth=151.0    |755     |755       |763       |763       |783       |784       |802         |802       |803         |803       |850        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=25.0       |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=39.999     |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=40.0       |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=50.0       |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=85.0       |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=100.0      |464     |464       |467       |467       |474       |475       |481         |481       |481         |482       |499        |
|rond=0.0, grad=50.0, opsz=18.0, wdth=151.0      |755     |755       |763       |763       |783       |784       |802         |802       |802         |803       |850        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=25.0      |300     |300       |307       |307       |324       |324       |340         |340       |340         |340       |380        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=39.999    |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=40.0      |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=50.0      |376     |376       |380       |380       |390       |390       |400         |400       |400         |400       |425        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=85.0      |420     |420       |423       |423       |432       |432       |440         |440       |440         |440       |460        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=100.0     |450     |450       |452       |452       |456       |456       |460         |460       |460         |460       |470        |
|rond=0.0, grad=50.0, opsz=144.0, wdth=151.0     |628     |628       |636       |636       |657       |657       |676         |676       |676         |677       |725        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=25.0     |440     |440       |442       |442       |446       |446       |450         |450       |450         |450       |460        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=39.999   |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=40.0     |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=50.0     |471     |479       |478       |478       |476       |476       |474         |474       |474         |474       |470        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=85.0     |502     |521       |517       |517       |505       |505       |495         |495       |495         |495       |468        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=100.0    |516     |540       |541       |541       |543       |543       |545         |545       |545         |545       |550        |
|rond=100.0, grad=-50.0, opsz=6.0, wdth=151.0    |752     |866       |869       |869       |876       |876       |883         |883       |883         |883       |900        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=25.0  |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=39.999|447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=40.0  |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=50.0  |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=85.0  |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=100.0 |464     |464       |467       |467       |474       |475       |481         |481       |482         |482       |499        |
|rond=100.0, grad=-50.0, opsz=17.999, wdth=151.0 |755     |755       |763       |763       |783       |784       |802         |802       |803         |803       |850        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=25.0    |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=39.999  |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=40.0    |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=50.0    |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=85.0    |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=100.0   |464     |464       |467       |467       |474       |475       |481         |481       |481         |482       |499        |
|rond=100.0, grad=-50.0, opsz=18.0, wdth=151.0   |755     |755       |763       |763       |783       |784       |802         |802       |802         |803       |850        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=25.0   |300     |300       |307       |307       |324       |324       |340         |340       |340         |340       |380        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=39.999 |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=40.0   |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=50.0   |376     |376       |380       |380       |390       |390       |400         |400       |400         |400       |425        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=85.0   |420     |420       |423       |423       |432       |432       |440         |440       |440         |440       |460        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=100.0  |450     |450       |452       |452       |456       |456       |460         |460       |460         |460       |470        |
|rond=100.0, grad=-50.0, opsz=144.0, wdth=151.0  |628     |628       |636       |636       |657       |657       |676         |676       |676         |677       |725        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=25.0       |440     |440       |442       |442       |446       |446       |450         |450       |450         |450       |460        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=39.999     |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=40.0       |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=50.0       |471     |479       |478       |478       |476       |476       |474         |474       |474         |474       |470        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=85.0       |502     |521       |517       |517       |505       |505       |495         |495       |495         |495       |468        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=100.0      |516     |540       |541       |541       |543       |543       |545         |545       |545         |545       |550        |
|rond=100.0, grad=0.0, opsz=6.0, wdth=151.0      |752     |866       |869       |869       |876       |876       |883         |883       |883         |883       |900        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=25.0    |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=39.999  |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=40.0    |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=50.0    |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=85.0    |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=100.0   |464     |464       |467       |467       |474       |475       |481         |481       |482         |482       |499        |
|rond=100.0, grad=0.0, opsz=17.999, wdth=151.0   |755     |755       |763       |763       |783       |784       |802         |802       |803         |803       |850        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=25.0      |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=39.999    |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=40.0      |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=50.0      |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=85.0      |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=100.0     |464     |464       |467       |467       |474       |475       |481         |481       |481         |482       |499        |
|rond=100.0, grad=0.0, opsz=18.0, wdth=151.0     |755     |755       |763       |763       |783       |784       |802         |802       |802         |803       |850        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=25.0     |300     |300       |307       |307       |324       |324       |340         |340       |340         |340       |380        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=39.999   |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=40.0     |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=50.0     |376     |376       |380       |380       |390       |390       |400         |400       |400         |400       |425        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=85.0     |420     |420       |423       |423       |432       |432       |440         |440       |440         |440       |460        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=100.0    |450     |450       |452       |452       |456       |456       |460         |460       |460         |460       |470        |
|rond=100.0, grad=0.0, opsz=144.0, wdth=151.0    |628     |628       |636       |636       |657       |657       |676         |676       |676         |677       |725        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=25.0      |440     |440       |442       |442       |446       |446       |450         |450       |450         |450       |460        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=39.999    |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=40.0      |459     |463       |464       |464       |464       |464       |465         |465       |465         |465       |466        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=50.0      |471     |479       |478       |478       |476       |476       |474         |474       |474         |474       |470        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=85.0      |502     |521       |517       |517       |505       |505       |495         |495       |495         |495       |468        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=100.0     |516     |540       |541       |541       |543       |543       |545         |545       |545         |545       |550        |
|rond=100.0, grad=50.0, opsz=6.0, wdth=151.0     |752     |866       |869       |869       |876       |876       |883         |883       |883         |883       |900        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=25.0   |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=39.999 |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=40.0   |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |474        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=50.0   |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=85.0   |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=100.0  |464     |464       |467       |467       |474       |475       |481         |481       |482         |482       |499        |
|rond=100.0, grad=50.0, opsz=17.999, wdth=151.0  |755     |755       |763       |763       |783       |784       |802         |802       |803         |803       |850        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=25.0     |438     |438       |440       |440       |446       |446       |452         |452       |452         |452       |466        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=39.999   |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=40.0     |447     |447       |449       |449       |455       |455       |461         |461       |461         |461       |475        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=50.0     |452     |452       |455       |455       |461       |461       |466         |466       |466         |466       |480        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=85.0     |460     |460       |462       |462       |467       |468       |472         |472       |473         |473       |485        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=100.0    |464     |464       |467       |467       |474       |475       |481         |481       |481         |482       |499        |
|rond=100.0, grad=50.0, opsz=18.0, wdth=151.0    |755     |755       |763       |763       |783       |784       |802         |802       |802         |803       |850        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=25.0    |300     |300       |307       |307       |324       |324       |340         |340       |340         |340       |380        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=39.999  |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=40.0    |345     |345       |350       |350       |364       |364       |376         |376       |376         |376       |407        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=50.0    |376     |376       |380       |380       |390       |390       |400         |400       |400         |400       |425        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=85.0    |420     |420       |423       |423       |432       |432       |440         |440       |440         |440       |460        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=100.0   |450     |450       |452       |452       |456       |456       |460         |460       |460         |460       |470        |
|rond=100.0, grad=50.0, opsz=144.0, wdth=151.0   |628     |628       |636       |636       |657       |657       |676         |676       |676         |677       |725        |

**Comment by MariannaPaszkowska** [comment]
@madig Great work! Can we easily incorporate a plot? It'll make it much easier to comprehend and analyze the information at hand.

**Comment by madig** [comment]
I added a chart 

<img width="712" height="735" alt="Image" src="https://github.com/user-attachments/assets/1c9ce26a-178b-4e5a-97bf-9748fbaaac56" />

**Comment by MariannaPaszkowska** [comment]
Superb, thank you!
