### ISSUE TITLE
outline issue in `Ţ`

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#489]
<img width="443" alt="Screenshot 2023-03-08 at 3 33 09 PM" src="https://user-images.githubusercontent.com/22956348/223768918-f669c5de-3eda-42ae-b54d-c94777cc4eb4.png">

**Comment by sannorozco** [comment]
This was updated.

**Comment by sannorozco** [comment]
This has been updated, ready for check @MariannaPaszkowska
