### ISSUE TITLE
update import process to only import updated glyphs

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#495]
Let's limit which glyphs we import to only those needing reworking. The intention is to prevent regressions. 

That's the list of glyphs that still need updates (55 glyphs): 
```
$
“
”
„
÷
®
¹
⁴
¼
¾
¢
¯
ˆ
ˇ
Â
Č
Ď
Ê
Ě
Î
Ň
Ô
Ø
Ř
Š
Ţ
Ť
Û
Ŵ
Ŷ
Ž
â
æ
č
ď
ê
ě
î
ľ
ł
ň
ô
ø
ř
š
ť
û
ű
ŵ
ŷ
ž
Ǎ
ǎ
₁
₄
```

**Comment by dberlow** [comment]
Is that correct or is importing now  based on a list that you’ve determined and not what the changes are?

**Comment by MariannaPaszkowska** [comment]
@dberlow importing is based on this list. We need to edit it manually if you need to update other glyphs. We can also keep editing this list, removing approved glyphs as we make progress.

**Comment by dberlow** [comment]
Marianna,

We had a conversation together last week, that did not, I think, lead to
this decision.

I then discussed it with Chris in our meeting last week. We have a job to
do before we can start doing it this way, via a list.

There are space characters wrong that are now waiting for approval, there
are glyphs being changed without any width or shape changes and there are
characters we all missed in review that are all fixed or being fixed.

We are also adding GRAD sources to deal with the width axis and removing
ROND100 masters that are not required.

And we need to be able to update, and then freeze by source, and then by
glyph, starting next week.

Cheers,
David

**Comment by dberlow** [comment]
In addition, I assigned Chris to this issue.
