### ISSUE TITLE
FB tasks 2-10/2-16

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#497]
1. Check all 27 primary sharp source, for hinting, for italic
2. Add GRAD intermediates to wdth
3. Complete sharp
4. Check all 27 primary round source for italic, check all Sharp regular kerning
5. Add ROND intermediates to wdth
6. Retrim GRAD
7. Test

**Comment by MariannaPaszkowska** [comment]
@dberlow ok to close this?
