### ISSUE TITLE
Fix GitHub Actions runner Build font and specimen workflow

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#499]
We recognized today that the GitHub Actions commit-level runs in the fb-wip2 branch are taking between 6 - 14 **hours** to complete.  I deactivated the workflows by removing the entire `.github` directory in #498 and merged this to the fb-wip2.  David and Santiago were notified about the issue today.  Let's not create any new branches and not merge anything to main, all of which still have Actions workflows defined, until we have an opportunity to diagnose the problem and watch + cancel the runner if it exceeds the typical ~ 2 min per commit execution time.

Here is the list of commits where this occurred: https://github.com/googlefonts/googlesans-flex/actions/workflows/build.yaml. The latest commit that ran in the expected amount of time was https://github.com/googlefonts/googlesans-flex/actions/runs/4474393360

**Comment by dberlow** [comment]
These should only be run on the FB-wip, I think, as so many changes are
present on wip-2.

**Comment by chrissimpkins** [comment]
It is OK to commit to the wip2 branch.  Let's hold on commits to any other branch until we address this.

**Comment by madig** [comment]
https://github.com/googlefonts/googlesans-flex/pull/500 seems to run fine. Testing the requirements locally showed some conflict between the fontbakery and gftools dependency. The PR also limits the run time to 60 minutes.

**Comment by chrissimpkins** [comment]
This issue should be addressed in main branch following the merge of #500.  We have a large number of other branches that are not based on these changes in main.  I am going to deactivate all CI runs in the fb-wip branch.  Please do not push commits to any branch that is not rebased on main branch as of the #500 commits that landed today.  Let's leave this open until we resolve this issue everywhere.

**Comment by chrissimpkins** [comment]
> I am going to deactivate all CI runs in the fb-wip branch.

https://github.com/googlefonts/googlesans-flex/pull/503
