### ISSUE TITLE
outline issue ` ⁴`

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#501]
separated from an issue #478 

- [x] Outline issue in `⁴`

<img width="490" alt="Screenshot 2023-03-08 at 3 02 38 PM" src="https://user-images.githubusercontent.com/22956348/223768178-ea771893-d39f-4f26-af93-506b3788ee82.png">
<img width="507" alt="Screenshot 2023-03-08 at 3 02 14 PM" src="https://user-images.githubusercontent.com/22956348/223768372-2bd6e5c8-d6c2-4aaf-b3bc-3d8320614d6f.png">

This might have been fixed in https://github.com/googlefonts/googlesans-flex/commit/de9c98ce2c8fe6d69d6813d97ca4ccc8b3831aef - needs review.

**Comment by sannorozco** [comment]
This has been updated, ready for check @MariannaPaszkowska
