### ISSUE TITLE
Metrics & Kerning in the Italic

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#505]
What should the relation of the metrics and kerning be in between the upright and the italic? Should they change?? I would say they should not, so the italic axis does not produce any reflow in text setting @MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
We chatted about that during the meeting yesterday. 
Metrics & kerning don't have to be compatible between upright and italic. 
CC @davelab6 @chrissimpkins
