### ISSUE TITLE
Adjust spacing in the ROND

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#508]
<img width="464" alt="Screenshot 2023-05-16 at 8 22 52 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0990d179-3e01-4717-a8d3-c7ca1f22b622">

**Comment by dberlow** [comment]
A further survey for schedule planning:
GSF-18,151,1000,ROND100 ascii
<img width="1147" alt="GSF-18,151,1000,ROND100ascii" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/10c7cab6-ef54-4144-a66c-a5433d691862">

GSF-144,151,1000,ROND100 uppercase
<img width="1134" alt="GSF-144,151,1000,ROND100" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/6e269164-e51f-4626-bcc9-9f9b2267cea4">

**Comment by MariannaPaszkowska** [comment]
closing because of a duplicate issue #711
