### ISSUE TITLE
Sparsify master opsz6-wdth85-wght1000-ROND0-SPARSE

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#520]
Hi, @sannorozco we noticed that this master is not truly sparse: GoogleSansFlexItalic-opsz6-wdth85-wght1000-ROND0-SPARSE 
Let's fix that :)

**Comment by sannorozco** [comment]
Sparsified!

**Comment by schriftgestalt** [comment]
there is another one: 
opsz6-wdth85-wght1000-ROND100-SPARSE

**Comment by sannorozco** [comment]
Hallo @schriftgestalt, I don’t see that source on my working branch **_fb-wip-v1.002_**.

If needed you can duplicate the same SPARSE ufo and rename it. On opsz6 all outlines are the same between ROND0 & ROND100.

**Comment by schriftgestalt** [comment]
I just saw that that file is scaled "SPARSE" but has all glyphs.

**Comment by octaviopardo** [comment]
Please! Send the updated version of this master to our branch :)

**Comment by MariannaPaszkowska** [comment]
@octaviopardo, has this been imported? Can I close this issue?

**Comment by octaviopardo** [comment]
OK, I found the lost ROND100 sparse master that @schriftgestalt was talking about. It is actually the ROND0. It has ROND0 in the file name, but ROND100 in the font info. One of them should be adjusted @sannorozco

**Comment by schriftgestalt** [comment]
And several source style names in the GoogleSansFlex.designspace do not always contain the "ROND100" (for the round 100 masters).
