### ISSUE TITLE
Invalid Bluezones

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/googlesans-flex#522]
Some files, e.g. GoogleSansFlex-opsz18-wdth100-wght400-ROND0.ufo does contain BlueValues that seems to outdate (not scaled to 2000 UPM?):
```
<key>postscriptBlueValues</key>
    <array>
      <integer>-16</integer>
      <integer>0</integer>
      <integer>510</integer>
      <integer>526</integer>
      <integer>580</integer>
      <integer>596</integer>
      <integer>716</integer>
      <integer>732</integer>
    </array>
```
It is desirable to have proper zones in the fonts as that helps keeping the overshot consistent.

**Comment by MariannaPaszkowska** [comment]
@madig @belluzj are we recalculating those values during import?

**Comment by schriftgestalt** [comment]
They might not be needed for TT. But are useful when designing.

**Comment by madig** [comment]
We don't touch them. I guess they weren't scaled to 2000 upM back in the days and no one noticed. I agree that they're nice to have, especially when using Glyphs.

**Comment by MariannaPaszkowska** [comment]
How can we quickly fix them? Any automated solutions?

**Comment by madig** [comment]
I'll look into it.

**Comment by madig** [comment]
So, actually, if we fix this in main, the next import that replaces the DS (as expected for the italic) is going to undo that. I could write a script that scales them on a repo and then I run it on main and italic? And on Octavio's branch?

**Comment by schriftgestalt** [comment]
Maybe make new ones from the default metrics with a default overshot? Instead of scaling them and risking rounding errors?

**Comment by madig** [comment]
Yes, ideally someone goes through all masters and adjusts them to sensible values. With all the copy-pasting that went on in GSF, I assume many values are wrong, anyway.

**Comment by dberlow** [comment]
Hey all,GSF Paramaroundup, linked below“Index refs” contain glyph id and points to me measured.“Measurements” contain values.Overshoots are included.Google Sheets: Sign-indocs.google.comI will check with Santiago to see why the index refs are not all reporting measures.Cheers, David Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by madig** [comment]
@MariannaPaszkowska Is there something actionable here? I think the blue zones should be checked one by one by a designer, rather than me writing a script that doubles blue zones that may be bogus copy-pasta.
