### ISSUE TITLE
Build font workflow not working on the it-ad-wip-italic-v1.002

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#524]
Can we look into why the fonts are not building there: https://github.com/googlefonts/googlesans-flex/actions/runs/5078110512

CC @joanacorreiatype @octaviopardo

**Comment by madig** [comment]
Looks like a malformed guideline. Maybe try tossing them all out?

**Comment by MariannaPaszkowska** [comment]
This was caused by UFO sources exported from Glyphs App.
Before moving from RoboFont to Glyphs App, we need to ensure all tooling involved in the workflow is updated and tested. 

To start, Glyphs App should be updated, and tested. Then the private UFO plugin should be ready (to facilitate working on multiple UFOs). Testing the round trips from UFO to .glyphs format is crucial, as well as ensuring that fontmake handles everything correctly. Finally, our build and import workflows should be tested and updated as needed.

Unfortunately, these updates may not be completed before v2.0. In the meantime, it's best to continue working in RoboFont.

CC @davelab6 @chrissimpkins @octaviopardo 

@schriftgestalt Just flagging this to you: it seems that after working on the UFO file, a guideline was created that seems malformed. Maybe @joanacorreiatype can connect with you to give you more details and data so that we can fix that.

**Comment by davelab6** [comment]
> Unfortunately, these updates may not be completed before v2.0.

Right, the _plan_ is that we will only expect UFOs from GlyphsApp starting in August, when Octavio's team starts work on v2; until then Font Bureau is working on v2 in RoboFont, and Octavio's team was/is planned/expected to start work in RoboFont too. 

However, if the updates are 100% completed before August 1st - @schriftgestalt said he's already 90-95% of the way on some part of it, but there are many other stake holders who also need to get to 100% - then it may be possible to update Octavio's project plan, get that plan change approved by the Google exec stakeholders, and move to GlyphsApp within the v1.2 phase. 

But its a big deal.

**Comment by schriftgestalt** [comment]
I’m sure we can switch to Glyphs much quicker. But I see that it needs more testing and verification. 

About that specific problem:
from the build error:
> ValueError: if 'x' or 'y' are None, 'angle' must not be present

The guide format rules seem to be relaxed in the UFO3 spec. There was a complicated requirement that it needed certain combinations of `x`, `y`, and `angle`. But they seem to be removed. So any missing value should default to zero. 
I’ll make Glyphs write the guides with the old requirements for now but ufolib might need an update?
