### ISSUE TITLE
Glyphs Italic Offset 

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#529]
Hi Georg, the files I created are the italics with Glyphs. When I open the UFO in Robofont, the spacing is not correct, and it is if I open the UFO in Glyphs. I can correct it in Robofont, but if there is another way. Using Robofont, we set the Italic Slant Offset, which makes the spacing okay for the italics, the same as in the regular. 
One example file of this is: 
GoogleSansFlexItalic-opsz144-wdth151-wght400-ROND0.ufo

**Comment by schriftgestalt** [comment]
Have a look at this post: https://forum.glyphsapp.com/t/guide-x-origin-at-y-260/26045

**Comment by schriftgestalt** [comment]
I would suggest to add `Slant Offset` and shift the outlines by the same amount.

**Comment by joanacorreiatype** [comment]
Thank you. We are good now.
