### ISSUE TITLE
Duplicated UFO

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#530]
Hiya, There is one UFO in the ROND100 folder that is duplicated in both upright and italic, 
GoogleSansFlex-opsz144-wdth151-wght1000-ROND100 copy.ufo ; and GoogleSansFlexItalic-opsz144-wdth151-wght1000-ROND100 copy.ufo

I assume we should ignore it right?

**Comment by dberlow** [comment]
Hey Octavio,

If it's not listed as a source in the designspace file, it shouldn't be
there as far as I'm concerned

So you can ignore and/or delete them.

Cheers,
David

**Comment by octaviopardo** [comment]
Perfect, thanks David
