### ISSUE TITLE
File size estimation: GRAD axis mockup

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#54]
@chrissimpkins Grade axis mockup is available here: https://github.com/googlefonts/googlesans-flex/releases/tag/Alpha-v1.0 

It contains axes:
- Weight
- Width
- Optical Size
- grade

It is missing a round axis.

EDIT from 8 Dec:
- [ ] Add the missing ROND axis to the mockup sources

**Comment by chrissimpkins** [comment]
@dberlow @sannorozco Possible to push the mocked GRAD axis with sources that allow us to build round too?  Ideally, we will project file size estimates with the full set of planned v1 variable axes.  

cc @nyshadhr9

**Comment by dberlow** [comment]
Yes, we’d like to. I wanted make sure that we have status labeling per axis, as a build with opsz, wdth, wght, ROND and GRAD, mock for now, will include a wide range of completion.Also, our local designspace files are using path names to sources from our repo to local directories. So on our FB repo, we build the test from all the sharp sources in the /source/Roman directory, with the mock GRAD sources coming from source/experiments. /ROND sources come from another folder as well.I’m happy to build a designspace file for this, but am not sure what path names are needed for your build process. On the fb repo all the sources are located at these links.Our square terminals are here:github.comRound terminals are here:github.comGRAD mock here:github.comThe sources are named for the designspace locations, as usual. Let me know if a designspace with the pathnames to these locations can be useful.Cheers.On Nov 29, 2022, at 8:27 PM, Chris Simpkins ***@***.***> wrote:﻿
@dberlow @sannorozco Possible to push the mocked GRAD axis with sources that allow us to build round too?  Ideally, we will project file size estimates with the full set of planned v1 variable axes.
cc @nyshadhr9

**Comment by RickyDaMa** [comment]
> I’m happy to build a designspace file for this, but am not sure what path names are needed for your build process

My understanding is that we read the designspace file in order to find the UFOs, so any folder structure & naming scheme that works for you will be fine so long as the Designspace(s) are kept up to date. I believe the import script searches for Designspace files in order to discover UFOs currently, because we understand file structure isn't final, so unless @madig jumps in to correct me you're absolutely fine to make whatever changes you need

If you were to also update the `sources/config.yaml` file to point to any designspaces you wish to be built, the automatic build process on this repository can then run. This will also give you access to any regression checks etc. that are added as we move forward

**Comment by RickyDaMa** [comment]
> If you were to also update the `sources/config.yaml` file to point to any designspaces you wish to be built, the automatic build process on this repository can then run

As a heads up, I've just done this on the `fb-wip` branch as part of #59

**Comment by MariannaPaszkowska** [comment]
I'm capturing this task here so, for easier tracking:
- [ ] Add the missing ROND axis to the mockup sources
@sannorozco @dberlow 

CC @chrissimpkins @davelab6

**Comment by dberlow** [comment]
This GRAD mock started with a request from Chris, discussed in an internal doc. That ended with a request from Dave to make an issue of the doc contents, here: https://github.com/FontBureau/fb-GoogleSansFlex/issues/77

And that ends November 21st, with compatible sources of opsz, wght, wdth, ROND and Mock GRAD being available. Google was invited to take them from our repo and assemble them on their repo. We understood that this was locating a lot of sources in parallel FB/FB-wip repository's directories and authoring a design space file specific to the ufo paths fro an experimental build.

We also tried to help this along from Mexico, but work like that was taking time our connections would not allow. 

If Google still needs this immediately, it's up to them. FB will also be ready with a more accurate build, based on the actual GRAD axis, in the next few days. I expect we'll get the exact day resolved today.

**Comment by MariannaPaszkowska** [comment]
I really appreciate your work on this. However, it is not complete. 
The release of the mockup font that we received was missing the ROND axis: https://github.com/googlefonts/googlesans-flex/blob/fb-wip/fonts/GoogleSansFlex-Alpha1.0%5BGRAD%2Copsz%2Cwdth%2Cwght%5D-VF.ttf 
ROND was described in the referenced spec: https://docs.google.com/document/d/1Ur-MBy-trehuJEuQyWZspPPAVgoZ5IAaaeHKKgmDz4U/edit. 

@chrissimpkins, would waiting a few days for that fix work for you?

**Comment by chrissimpkins** [comment]
> @chrissimpkins, would waiting a few days for that fix work for you?

Works for me.  Thank you
