### ISSUE TITLE
How do we deal with the opsz6R100 masters?

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#540]
In terms of drawing those masters are equal to the R0. However, duplicating them was a mistake, so @madig how would you like us to deal with them? I know you could do the work yourself at some point, but it would be awesome if we could have them at least at the end of each milestone, so we can actually see the interpolation properly in all the designspace. 

CC @casasin

**Comment by MariannaPaszkowska** [comment]
Hi @octaviopardo, you can leave those out for now and duplicate those as works best for you and your team. I think it's a good idea to do it before each milestone. This shouldn’t cause any issues as long as the sources are compatible.
