### ISSUE TITLE
No rounded shape for circumflexcomb and caroncomb on upright master

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#542]
There is no rounded shape for circumflexcomb and caroncomb on the upright master. 

GoogleSansFlexItalic-opsz144-wdth100-wght1000-ROND100

**Comment by sannorozco** [comment]
Updated this on our fb-wip-v1.002branch. Let me know if you need me to update it elsewhere.

**Comment by joanacorreiatype** [comment]
If you could update on our branch it-ad-wip-italic-v1.002
Thank you

**Comment by joanacorreiatype** [comment]
Hi @sannorozco would you mind updating it on our branch it-ad-wip-italic-v1.002? Thank you

**Comment by sannorozco** [comment]
Updated, ready for you to make italic @joanacorreiatype @octaviopardo .

**Comment by MariannaPaszkowska** [comment]
Thanks for taking care of that quickly @sannorozco!

@joanacorreiatype, could you confirm that this is addressed now?
