### ISSUE TITLE
Weight min tittle size?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#543]
The tittle size in minimum weights seems to be disproportionately large compared to the stroke weights. @dberlow was this design decision approved and documented anywhere last year? 

<img width="377" alt="Screenshot 2023-06-06 at 17 00 00" src="https://github.com/googlefonts/googlesans-flex/assets/261579/6cd4780b-f814-466a-8590-5b9eac2dd4c6">

**Comment by dberlow** [comment]
Opsz please...but I guess somewhere between opsz 18 and 144

The topic first came up in Roboto and I did some studies and published some pictures, showing one of them at ATYPI Antwerp. I'll find that stuff. I also wrote about it in "Size Wise". https://docs.google.com/document/d/1GvGgCtaAY0xM7CzesFf71vcR5B1kMzG3pb231WpUx20/edit

Forward, and the work on GSF was more range of wght and opsz so a bigger challenge. The work we did was critiqued and edits were made. 

The resulting opsz size masters of wght1 are, we feel correct. But...
<img width="1117" alt="Screen Shot 2023-06-07 at 7 33 35 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/1dbf4630-2464-4255-a325-6d9e36360032">

...
1. We don't think it's possible to use a single wght on dots when switching to dark mode, as the dot appears to become brighter. as you can see in the two specimens of opsz18 above. 
2. We also think, like the bar of the l.c. "e"'s intermediates,  intermediates are required for dots until avar2. These can be planned as sparse masters for GSF 2.0. 
3. with avar2, we'll want to have separate parametric values for what I call "the little things", the period being one of them. So in the Latin, dot is planned as the control character for little things.  That starts at Index#47 here; https://docs.google.com/spreadsheets/d/1lZcLW7xo39zG3TTv6EK3iLs5t8OjWWPJv0lb9qEnsDE/edit#gid=0

**Comment by MariannaPaszkowska** [comment]
@davelab6 I thought we fixed that. The issues I found it as reported: https://github.com/googlefonts/googlesans-flex/issues/85 https://github.com/googlefonts/googlesans-flex/issues/91

**Comment by davelab6** [comment]
This is very probably an old version

**Comment by davelab6** [comment]
I'll double check that and the opsz

**Comment by MariannaPaszkowska** [comment]
This is only happening at small opsz, which is beneficial to the readability and intentional
