### ISSUE TITLE
Interpolation errors in GSF v Alpha 1.0, broken contours in min opsz

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#55]
Outline review of GS Flex Alpha Round from the release: https://github.com/googlefonts/googlesans-flex/releases/tag/Alpha-v1.0 
Reviewed font: [GoogleSansFlex-Alpha1.0[ROND,opsz,wdth,wght]-VF.ttf](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/fonts/GoogleSansFlex-Alpha1.0%5BROND%2Copsz%2Cwdth%2Cwght%5D-VF.ttf) _"with 6 and 9 straight on all the designspace, not rounded yet."_

Issue: broken contours. 

Axis location:  **opsz 6, wdth 78, wght 749**
https://videoproof.graphicore.de/#2022-11-29T11:02:53Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;opsz6,wdth78,wght749;grid&Latin.Uppercase;0

*Please note that those issues are not visible in the intended optical size to the bare eye. 
Affected glyphs: 

- [ ] `C` (terminals of the in-/outstrokes)
<img width="315" alt="Screenshot 2022-11-29 at 1 03 16 PM" src="https://user-images.githubusercontent.com/22956348/204516651-dd02e129-e4ae-4c57-a1f8-51fe87ce0a60.png">

- [ ] `G` (terminal of the instroke)
<img width="273" alt="Screenshot 2022-11-29 at 1 03 39 PM" src="https://user-images.githubusercontent.com/22956348/204516759-2d18e26e-c5b2-4e4b-afd2-298049c6e3e0.png">

- [ ] `J` *(terminal of the outstroke, see also #56 for another potential issue)

<img width="287" alt="Screenshot 2022-11-29 at 1 00 42 PM" src="https://user-images.githubusercontent.com/22956348/204519395-aec40629-1c18-43d6-9c55-372516e58877.png">

- [ ] `R` (leg)
<img width="223" alt="Screenshot 2022-11-29 at 1 24 47 PM" src="https://user-images.githubusercontent.com/22956348/204516876-68e46750-69bf-4610-8aaa-25f1ede710c4.png">

- [ ] `S` (terminal of the outstroke)
<img width="172" alt="Screenshot 2022-11-29 at 1 04 17 PM" src="https://user-images.githubusercontent.com/22956348/204516934-4aa4a8a3-921b-4592-ac48-a03bf3f3ac7e.png">

- [ ] `a` (terminal of the instroke)
<img width="219" alt="Screenshot 2022-11-29 at 1 04 02 PM" src="https://user-images.githubusercontent.com/22956348/204517189-c45635b5-43d3-4dcc-93a5-222d95e94d1e.png">

- [ ] `c` (terminal of the outstroke)
<img width="259" alt="Screenshot 2022-11-29 at 1 04 06 PM" src="https://user-images.githubusercontent.com/22956348/204517170-0444a1f0-42f3-468f-9d16-6ffc9a42d4c8.png">

- [ ] `e` (terminal of the outstroke)
<img width="297" alt="Screenshot 2022-11-29 at 1 04 10 PM" src="https://user-images.githubusercontent.com/22956348/204517143-8aa77c3d-1a4d-4259-bb20-f9caf52c8c11.png">

- [x] `j` (terminal of the outstroke)
<img width="178" alt="Screenshot 2022-11-29 at 1 40 42 PM" src="https://user-images.githubusercontent.com/22956348/204519902-7fa4c2f9-d008-4dd5-a406-eff0e8e23a11.png">

- [ ] `k` (leg)
<img width="256" alt="Screenshot 2022-11-29 at 1 28 11 PM" src="https://user-images.githubusercontent.com/22956348/204518749-f26478d2-a251-4db2-b832-ff69b2907541.png">

- [ ] `s` (terminal of the outstroke)
<img width="169" alt="Screenshot 2022-11-29 at 1 28 19 PM" src="https://user-images.githubusercontent.com/22956348/204518787-d7ac978f-6483-43c2-8a01-9ac24bfcd30e.png">

- [ ] `3` (terminals of the in-/outstrokes)
<img width="194" alt="Screenshot 2022-11-29 at 1 17 42 PM" src="https://user-images.githubusercontent.com/22956348/204517094-2fa53791-e020-407a-8cdf-35f9ccfe5c30.png">

- [x] `2` (terminal of the instroke)
<img width="323" alt="Screenshot 2022-11-29 at 1 29 06 PM" src="https://user-images.githubusercontent.com/22956348/204517695-49fcf5c9-21bc-447c-aace-7cd5ba1c856e.png">

- [x] `5` (terminal of the outstroke)
<img width="305" alt="Screenshot 2022-11-29 at 1 29 00 PM" src="https://user-images.githubusercontent.com/22956348/204517656-4af35141-a661-4793-962f-6d020284820b.png">

- [ ] `$` (an issue in the terminals, ignoring the broken bar)
<img width="149" alt="Screenshot 2022-11-29 at 1 08 07 PM" src="https://user-images.githubusercontent.com/22956348/204517048-c26deb36-f0b6-45b4-933f-d7a4727531e1.png">

- [x] `¢` (terminals of the in-/outstrokes)
<img width="150" alt="Screenshot 2022-11-29 at 1 19 01 PM" src="https://user-images.githubusercontent.com/22956348/204517346-06e907d0-afe6-4f99-8e9a-a573629e9355.png">

- [x] `£` (terminal of the instroke)
<img width="375" alt="Screenshot 2022-11-29 at 1 31 14 PM" src="https://user-images.githubusercontent.com/22956348/204519343-dfb3e462-bd75-4371-b8b9-e8a0e26d6d00.png">

- [x] `§` (terminal of the instroke)

<img width="201" alt="Screenshot 2022-11-29 at 1 19 40 PM" src="https://user-images.githubusercontent.com/22956348/204517280-5e406868-5a45-483b-bb0a-3a65783a96e9.png">

CC @chrissimpkins @davelab6

**Comment by dberlow** [comment]
Awaiting completion of columns "F" and "G" at link below.
https://docs.google.com/spreadsheets/d/1UFj8xekKjUfYhilePT3FFxdmIECTsO3tBpvErjNP0tY/edit#gid=0

**Comment by MariannaPaszkowska** [comment]
Thank you for the update @dberlow!

**Comment by MariannaPaszkowska** [comment]
Update: 6 issues are fixed 12 issues are left.
<img width="1294" alt="Screenshot 2023-01-26 at 4 39 44 PM" src="https://user-images.githubusercontent.com/22956348/214864283-445d9acd-162e-4456-a56b-f0c93f08a3e3.png">

**Comment by dberlow** [comment]
I believe this is the lack or an intermediate at opsz17.99, preventing the intermediates at opsz18 <wdth100 from effecting the shapes < opsz18.

Below, Top you see the glyphs of this issue repeated in Typeroof. 
Below Bottom, are the same glyphs in the same designspace location, generated in Robofont with opsz18 removed from the designspace. Just opsz6 wght and wdth are fine, (aside from lack of the intermediates on the bars of cent and dollar).
<img width="859" alt="Screen Shot 2023-01-26 at 11 41 16 AM" src="https://user-images.githubusercontent.com/1956494/214896425-ce000a8a-8ab2-4bd0-847b-d6ba7299cdae.png">

**Comment by MariannaPaszkowska** [comment]
Review today of [this build](https://github.com/googlefonts/googlesans-flex/actions/runs/4103075184): <img width="922" alt="Screenshot 2023-02-06 at 8 26 22 PM" src="https://user-images.githubusercontent.com/22956348/217054597-2563be25-fd54-49dc-b7cb-8deab0f0ec69.png">
<img width="1031" alt="Screenshot 2023-02-06 at 8 26 56 PM" src="https://user-images.githubusercontent.com/22956348/217054708-68c74bd0-86a3-485f-a2f3-78f6066f8dcd.png">

**Comment by MariannaPaszkowska** [comment]
Closing - multiple issues, this is tracked in https://github.com/googlefonts/googlesans-flex/issues/212
