### ISSUE TITLE
Automatic builds: use separate allow lists for Roman and Italic

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#551]
It would be great if we had more control over what we import to Italic vs Roman; it currently uses the same file for both. It could be done through another solution.

**Comment by RickyDaMa** [comment]
I can make it so that there's a separate import list for each of the `sources` in [`sources/config.yaml`](https://github.com/googlefonts/googlesans-flex/blob/main/sources/config.yaml), falling back on regular if an import list isn't found. Would that work for you @MariannaPaszkowska?

**Comment by MariannaPaszkowska** [comment]
Yes, thanks a lot @RickyDaMa
