### ISSUE TITLE
Unrounded J & ?

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#552]
Master opsz18-wdth50-wght400-ROND100 has a J & ? only partially rounded 
![Captura de pantalla 2023-06-13 a las 9 47 20](https://github.com/googlefonts/googlesans-flex/assets/2181684/4185f5e9-4c70-4e5b-b3cf-5b070e8ab4df)
@sannorozco can you fix it add it to our branch? (you can do it only in the upright and we will take it to the italic)

@Txonliz stay tuned
@MariannaPaszkowska

**Comment by sannorozco** [comment]
Done, updated in Roman so you can move it to Italic @octaviopardo @Txonliz.

**Comment by MariannaPaszkowska** [comment]
@Txonliz @octaviopardo let me know when this is done in your branch, please. :)

**Comment by Txonliz** [comment]
@MariannaPaszkowska @octaviopardo Done!
