### ISSUE TITLE
DIfferent question mark components in 144-100-1000-0

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#553]
Top question mark and bottom question mark components are different. Should they be corrected? If so please let us know and update our branch
![Captura de pantalla 2023-06-13 a las 12 26 24](https://github.com/googlefonts/googlesans-flex/assets/2181684/494f46b5-8314-472d-bfcc-91d72b398993)

Somehow I feel like having two different components for the top and bottom part of question mark looses the sense of using components for those signs.

stay tuned @joanacorreiatype 
@MariannaPaszkowska

**Comment by sannorozco** [comment]
Updated in Roman so you can move it to Italic @octaviopardo @joanacorreiatype.

Having this as a separate component was to re-use it for some African Languages that use glottal stop https://en.wikipedia.org/wiki/Glottal_stop, and for IPA.

**Comment by octaviopardo** [comment]
Ok, @dberlow also mentioned that is made to match better the proportions of the descenders :) SO now we can close it
