### ISSUE TITLE
Keep some glyphs partially of fully not slanted

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#556]
Following a decision from today's meeting we'd like to keep small circular shape rounded and not slanted, some glyphs rotated, and not slanted.

Here is a list of affected glyphs: 

unchanged rounded shape/dot:
```
/exclam
/question
/percent
/semicolon
/i
/j
/exclamdown
/questiondown
/Aring
/aring
/f_f_i
/f_i
/f_j
/Idieresis
/Odieresis
/Udieresis
/adieresis
/edieresis
/idieresis
/odieresis
/udieresis
/ydieresis
/Uring
/uring
/ij
/Ydieresis
/Edotaccent
/edotaccent
/Ldot
/ldot
/Zdotaccent
/zdotaccent
/Wdieresis
/wdieresis
/Idotaccent
/adieresis.alt
/aring.alt
/gdotaccent.alt
/cdotaccent
/Cdotaccent
/gdotaccent
/Gdotaccent
/zeropercent
```
rotate:
```
/asterisk
```

unchanged:
```
/period
/plus
/currency
/colon
/less
/equal
/greater
/bar
/asciitilde
/brokenbar
/dieresis
/copyright
/logicalnot
/registered
/periodcentered
/degree
/plusminus
/multiply
/divide
/greaterequal
/lessequal
/approxequal
/notequal
/dotaccent
/ring
/dotaccentcomb
/dieresiscomb
/ringcomb
/period.tf
/comma.tf
/colon.tf
/semicolon.tf
/colon.time
/currency.tf
/plus.tf
/minus.tf
/multiply.tf
/divide.tf
/equal.tf
/notequal.tf
/greater.tf
/less.tf
/greaterequal.tf
/lessequal.tf
/plusminus.tf
/approxequal.tf
/logicalnot.tf
/percent.tf
/dot-composite
/dot-composite-top
/notequal-slash
/greaterequal-stroke
/bullet
/minus
/horizontalelipsis
/G.logo
/e.logo
/g.logo
/l.logo
/o.logo
/Google.logo
/G.super
/Gsuper
/wiggle.medium
```

edit: removed /section #630 

cc @davelab6 @dberlow @chrissimpkins

**Comment by davelab6** [comment]
Sounds good

**Comment by MariannaPaszkowska** [comment]
@dberlow what is your opinion about the \at sign? It's vertical in this design, should we slant it in Italic?

**Comment by octaviopardo** [comment]
Is /question included intentionally or by mistake? it is a two components glyphs, made out of dot-composite –that should NOT be changed– and question-top –that should be changed I think–
Also cent.tf indeed we do not have to touch it, but it s not part of this specific issue, as it is a component of cent

**Comment by MariannaPaszkowska** [comment]
Hi @octaviopardo, good catch! I included those by mistake. It is fixed now!

**Comment by dberlow** [comment]
> @dberlow what is your opinion about the \at sign? It's vertical in this design, should we slant it in Italic?

I would just slant the "a", not the loop.

**Comment by octaviopardo** [comment]
trademark?

**Comment by dberlow** [comment]
I don’t think so.On Jun 19, 2023, at 5:07 AM, octaviopardo ***@***.***> wrote:﻿
trademark?

**Comment by octaviopardo** [comment]
backslash is on the list, but not the slash?

**Comment by MariannaPaszkowska** [comment]
Both backslash and slash should be slanted. I updated the list.

**Comment by octaviopardo** [comment]
and any thoughts about the comma (and quotes, and comma accents)? slanted? rotated, rotated and slightly slanted? @dberlow @MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
Re: comma, as discussed during the meeting we will keep the sop rounded and the tail slanted. :)

**Comment by Bogidar** [comment]
Hello!
Do we slant the .notdef ?
it is not on the list, but in the 1.2 we didn’t slant it actually. @MariannaPaszkowska ?

Thanks!

**Comment by octaviopardo** [comment]
Add uni25CC (◌) to unchanged

**Comment by MariannaPaszkowska** [comment]
have a look at this issue, @kalapi
