### ISSUE TITLE
Kerning updated target for v1.002

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#557]
`ł Ł Ľ ť ď ľ` spacing - too tight

Kerning pairs that need attention
```
1) (proportional)
av avion
hy hydrangea 
rd arduous 
by baby
sy sync
yc nyc
fï fïka
þy þýdd 
þv þvas 
Cï Cïno 
Æï Æïno
Zï Zïno
Tī Tī 
Ły Łysa
Kw Kwiczący 
Ky Kyle 
Kv Kvæven 
Lv Lvon 
Lw Lwowskiego
Ts Tsatsiki
Tw Tweet 
Tv Tveen 
Ty Tygrys 
Tx Txapela
Tz Tzin  
Tæ Tæt
oY oYo 
nY nYn 
sY sYs 
uY uYu  
cY cYc 
Y,
P‚
Y.
T,
T.
f’
f”
r’
r”
L’
“A
‘A
f“
f‘
Y;
P.
P‚ 
Y„
L‘
’s
Y‚
V„
A“
V,
V.
‚Y
T‚
f) 
f™ 
f} 
¿A ¿ABBA?
¿V ¿VOV?
¿v ¿vamos?
¿W ¿WOW?
¿w ¿wow?
¿Y ¿YAY?
¿T ¿TÍA T?
ďk loďka
ľč topoľčiankach
ľj iľjič
ľk veľkolepým
ľž oceľželezo 
ľt odtiaľto
ľš boľševickej
ťš dvadsaťštyri
ťh štvrťhodiny
ťj päťjazyčný
ľň uvoľňovanými
ųj mažųjų
ąj pirmąjį
Įj Įjaudinam
įj abejojusįjį
DW OBYDWÓCH
OW SOWA
ÞÆ ÓÞÆGILEGA
ĽV ĽVOV
ĽT VOĽTE
ŁO OŁÓWEK
ÞY MISÞYRMA
ÞÆ ÓÞÆGILEGA
TÆ STÆRRI 
VÆ SAMVÆR 
YÆ URBYÆ
“Æ
‘Æ
’Æ
“Æ
‘Æ
’Æ
ï\
/ï 
{ï 
ï} 
[ï 
ï]
ï\ 
/ï 
{ï 
ï} 
[ï 
ï]
ď™ 
ď‘ 
ď’ 
ď' 
ď\ 
ď} 
ď] 
ď)
ď™ 
ď‘ 
ď’ 
ď' 
ď\ 
ď} 
ď] 
ď)
```

<img width="429" alt="Screenshot 2023-07-03 at 5 22 03 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/04b0ee71-ce6a-493b-9b0a-75b2cc7cf796">
<img width="487" alt="Screenshot 2023-07-03 at 5 22 38 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0e36bc7d-4b61-439c-9df8-c1054b43b74c">
<img width="465" alt="Screenshot 2023-07-03 at 5 22 48 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/7f8aa603-af16-4d43-9317-6df47b1b5117">
<img width="477" alt="Screenshot 2023-07-03 at 5 23 00 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/36bf40e3-75ef-4e21-9483-39f316368554">
<img width="460" alt="Screenshot 2023-07-03 at 5 23 08 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/eef977e8-be06-48ce-8817-7209687712ee">
<img width="486" alt="Screenshot 2023-07-03 at 5 23 15 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/eacf2624-fd0b-4767-9c34-5824aea2f85e">

**Comment by dberlow** [comment]
GSF kerning pairs reviewed and revised:
FB-wip2, opsz18 wdth100 wght400 GRAD0 ROND0

Testing with this font: https://github.com/googlefonts/googlesans-flex/actions/runs/5291229190

Pairs noted and comments added where needed.
1) (proportional) -20
av avion -40
hy hydrangea -40
rd arduous -30
by baby -70
sy sync -40
yc nyc -70
fï fïka 3-
þy þýdd This is kerned properly at -70!?
þv þvas This is kerned properly at -70!?
Cï Cïno not seeing anything to kern
Æï Æïno not seeing anything to kern
Zï Zïno +50
Tī Tī +70
Ły Łysa -80
Kw Kwiczący -80
Ky Kyle -80
Kv Kvæven -80
Lv Lvon -100
Lw Lwowskiego -80
Ts Tsatsiki -140
Tw Tweet -90
Tv Tveen -100
Ty Tygrys -100
Tx Txapela -150
Tz Tzin -130
Tæ Tæt -130
oY oYo -170
nY nYn -120
sY sYs -120
uY uYu -140
cY cYc -170
Y, -210 -190
P‚ -280 is plenty
Y. -230
T, -200
T. -200
f’ 60 (tighter)
f” 60 (“)
r’ 60 (“)
r” 60 (“)
L’ -290
“A“ -290
‘A‘ -280
f“ okay “f and ‘f -70
f‘ okay
Y; -120
P. -280 is good
P‚ -280 is good
Y„ -280
L‘ -180?
’s -140
Y‚ -280
V„ -180
A“ -280
V, -200,
V. -200
‚Y -240
T‚ -200
f) 80
f™ 60
f} 70
¿A ¿ABBA? -100
¿V ¿VOV? -230
¿v ¿vamos? -160
¿W ¿WOW? -220
¿w ¿wow? -130
¿Y ¿YAY? -250
¿T ¿TÍA T?-230
ďk loďka 180 (ďi?)
ľč topoľčiankach 25
ľj iľjič 160
ľk veľkolepým 180
ľž oceľželezo 70
ľt odtiaľto 80
ľš boľševickej 45
ťš dvadsaťštyri -20
ťh štvrťhodiny 35
ťj päťjazyčný 45
ľň uvoľňovanými 70
ųj mažųjų 35
ąj pirmąjį 75
Įj Įjaudinam 50
įj abejojusįjį 70
DW OBYDWÓCH -30
OW SOWA okay
ÞÆ ÓÞÆGILEGA -240
ĽV ĽVOV -10
ĽT VOĽTE -160
ŁO OŁÓWEK -80
ÞY MISÞYRMA -120
ÞÆ ÓÞÆGILEGA (repeat)
TÆ STÆRRI -270
VÆ SAMVÆR -270
YÆ URBYÆ -290
“Æ -440
‘Æ -440
’Æ -440?
“Æ -440? ‘ and “ Æ -400
’Æ -440
ï\ 120
/ï 120
{ï 90
ï} 90
[ï 90
ï] 90
ï\ repeat
/ï repeat
{ï repeat
ï} repeat(ï) 90, 90
[ï repeat
ï] repeat kerned(imacron) and {}, []
ď™ 240
ď‘ 180
ď’ 140
ď' 220 dcaron” 220
ď\ 280
ď} 230
ď] 220
ď) 200
ď™ repeat
ď‘ repeat
ď’ repeat
ď' repeat
ď\ repeat
ď} repeat
ď] repeat
ď) repeat

**Comment by dberlow** [comment]
Updates Merged into FB-wip2
https://github.com/googlefonts/googlesans-flex/tree/fb-wip2/sources/regular/GoogleSansFlex-opsz18-wdth100-wght400-ROND0.ufo

**Comment by dberlow** [comment]
Test of Changes
GSF kerning pairs

Testing with this font: https://github.com/googlefonts/googlesans-flex/actions/runs/5291229190

1) (proportional) -20
av avion -40
hy hydrangea -40
rd arduous -30
by baby -70
sy sync -40
yc nyc -70
fï fïka 3-
þy þýdd This is kerned properly at -70!?
þv þvas This is kerned properly at -70!?
Cï Cïno not seeing anything to kern
Æï Æïno not seeing anything to kern
Zï Zïno +50
Tī Tī +70
Ły Łysa -80
Kw Kwiczący -80
Ky Kyle -80
Kv Kvæven -80
Lv Lvon -100
Lw Lwowskiego -80
Ts Tsatsiki -140
Tw Tweet -90
Tv Tveen -100
Ty Tygrys -100
Tx Txapela -150
Tz Tzin -130
Tæ Tæt -130
oY oYo -170
nY nYn -120
sY sYs -120
uY uYu -140
cY cYc -170
Y, -210 -190
P‚ -280 is plenty
Y. -230
T, -200
T. -200
f’ 60 (tighter)
f” 60 (“)
r’ 60 (“)
r” 60 (“)
L’ -290
“A“ -290
‘A‘ -280
f“ okay “f and ‘f -70
f‘ okay
Y; -120
P. -280 is good
P‚ -280 is good
Y„ -280
L‘ -180?
’s -140
Y‚ -280
V„ -180
A“ -280
V, -200,
V. -200
‚Y -240
T‚ -200
f) 80
f™ 60
f} 70
¿A ¿ABBA? -100
¿V ¿VOV? -230
¿v ¿vamos? -160
¿W ¿WOW? -220
¿w ¿wow? -130
¿Y ¿YAY? -250
¿T ¿TÍA T?-230
ďk loďka 180 (ďi?)
ľč topoľčiankach 25
ľj iľjič 160
ľk veľkolepým 180
ľž oceľželezo 70
ľt odtiaľto 80
ľš boľševickej 45
ťš dvadsaťštyri -20
ťh štvrťhodiny 35
ťj päťjazyčný 45
ľň uvoľňovanými 70
ųj mažųjų 35
ąj pirmąjį 75
Įj Įjaudinam 50
įj abejojusįjį 70
DW OBYDWÓCH -30
OW SOWA okay
ÞÆ ÓÞÆGILEGA -240
ĽV ĽVOV -10
ĽT VOĽTE -160
ŁO OŁÓWEK -80
ÞY MISÞYRMA -120
ÞÆ ÓÞÆGILEGA (repeat)
TÆ STÆRRI -270
VÆ SAMVÆR -270
YÆ URBYÆ -290
“Æ -440
‘Æ -440
’Æ -440?
“Æ -440? ‘ and “ Æ -400
’Æ -440
ï\ 120
/ï 120
{ï 90
ï} 90
[ï 90
ï] 90
ï\ repeat
/ï repeat
{ï repeat
ï} repeat(ï) 90, 90
[ï repeat
ï] repeat kerned(imacron) and {}, []
ď™ 240
ď‘ 180
ď’ 140
ď' 220 dcaron” 220
ď\ 280
ď} 230
ď] 220
ď) 200
ď™ repeat
ď‘ repeat
ď’ repeat
ď' repeat
ď\ repeat
ď} repeat
ď] repeat
ď) repeat

**Comment by MariannaPaszkowska** [comment]
@dberlow, I've tested the mentioned build and noticed improvements in some pairs, but there's still work to be done. @octaviopardo and their team will handle the kerning from now on, giving you more time for v2. Thanks! 

Update: @MariannaPaszkowska  tested the wrong data. Kerning still needs to be imported. 

CC @davelab6 @chrissimpkins

**Comment by MariannaPaszkowska** [comment]
I misunderstood your comment @dberlow, and tested the font before your changes. Apologies. @octaviopardo, we need to import kerning data from here: https://github.com/googlefonts/googlesans-flex/blob/fb-wip2/sources/regular/GoogleSansFlex-opsz18-wdth100-wght400-ROND0.ufo/kerning.plist

**Comment by dberlow** [comment]
Hey,﻿Sorry for any confusion. Let me know how that regular kerning works on the italic’s regular.Cheers!On Jul 3, 2023, at 11:19 AM, Marianna Paszkowska ***@***.***> wrote:﻿
I misunderstood your comment @dberlow, and tested the font before your changes. Apologies. @octaviopardo, we need to import kerning data from here: https://github.com/googlefonts/googlesans-flex/blob/fb-wip2/sources/regular/GoogleSansFlex-opsz18-wdth100-wght400-ROND0.ufo/kerning.plist
