### ISSUE TITLE
Build workflow failing when given commit hash instead of branch name

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#558]
Hi @RickyDaMa we are getting this error and we are unsure why is it, can you help us and tell us more?

https://github.com/googlefonts/googlesans-flex/actions/runs/5288386163/jobs/9570022969

**Comment by RickyDaMa** [comment]
Hi @octaviopardo sorry the workflow isn't working for you! It seems to run okay if you give it a branch name, but not a specific commit hash. I'll investigate this, but for now you can run the build process okay if you ask it to build `it-ad-wip-italic-v1.002` instead. See my build of your branch [here](https://github.com/googlefonts/googlesans-flex/actions/runs/5289506916/jobs/9572506006)

**Comment by octaviopardo** [comment]
Hey @RickyDaMa
sorry I did not know it worked like that, then indeed ignore my comments. We do not need this specific built based in commits, using the whole branch is fine. Thanks a lot!
