### ISSUE TITLE
Interpolation issues in uppercase J

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#56]
Review of GS Flex Alpha Round from the release: https://github.com/googlefonts/googlesans-flex/releases/tag/Alpha-v1.0
Reviewed font: [GoogleSansFlex-Alpha1.0[ROND,opsz,wdth,wght]-VF.ttf](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/fonts/GoogleSansFlex-Alpha1.0%5BROND%2Copsz%2Cwdth%2Cwght%5D-VF.ttf) "with 6 and 9 straight on all the designspace, not rounded yet."

Thinning, point placement, curve balance, contrast: 

https://videoproof.graphicore.de/#2022-11-29T10:43:35Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;opsz6,wdth25,wght224;grid&Latin.ASCII;0

<img width="77" alt="Screenshot 2022-11-29 at 12 50 03 PM" src="https://user-images.githubusercontent.com/22956348/204510010-65427427-65a4-4d61-bdf2-0954bfbb110e.png">

https://videoproof.graphicore.de/#2022-11-29T10:49:48Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;opsz6,wdth25,wght1;grid&Latin.ASCII;0 

<img width="74" alt="Screenshot 2022-11-29 at 12 44 36 PM" src="https://user-images.githubusercontent.com/22956348/204508914-78d5baa6-4eae-4c9c-b110-2e18a8375b5e.png">

see also #55 for another interpolation issue in `J`

CC @chrissimpkins @davelab6

**Comment by davelab6** [comment]
@dberlow meta comment, is this the ideal format for filing design review issues?
