### ISSUE TITLE
Numerators and denominators decomposed

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#561]
hi @sannorozco and @dberlow 
why numerators and denominators are both decomposed? why not make one of them components as superiors and inferiors?
Is their design different in any master?

Thanks :)

**Comment by dberlow** [comment]
This was an error. The numerators are to be the only contours, and everything else should be composed from them.On Jun 19, 2023, at 4:56 AM, octaviopardo ***@***.***> wrote:﻿
hi @sannorozco and @dberlow
why numerators and denominators are both decomposed? why not make one of them components as superiors and inferiors?
Is their design different in any master?
Thanks :)

**Comment by octaviopardo** [comment]
Ok, does it make sense to change them at this point or shall we keep them the way they are? It is not only about changing them by components but they would also need to be repositioned, and any issue there might contaminate the fractions. 

Let us know :)

**Comment by sannorozco** [comment]
@octaviopardo yes I think you can change them.

**Comment by dberlow** [comment]
It is totally scriptable with no manual intervention.
I will chat with SO about the script.
1. The numerators are kept and used to compose the denominators with all
the denominators getting a negative vertical shift that equals the
difference between the y min of /1 and the baseline.
2. The denominators of the fractions are recomposed using the numerators as
the fractions are now, the and denominators composed from the numerators
with the same negative shift as the denominators, and the horizontal shift
of the denominators the same as they were composed in the original fraction.

**Comment by octaviopardo** [comment]
Let us know if you develop something that we can reuse ourselves, thanks :D
@casasin

**Comment by octaviopardo** [comment]
Hi Guys, have you done something about this? DO you have any script we can reuse?

**Comment by sannorozco** [comment]
@octaviopardo I’ll send you this soon.
