### ISSUE TITLE
Problem with idotaccent on 144-151-1000

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#562]
On the upright, there is a problem with the dot of the i. It's different from j. 

<img width="286" alt="Screen Shot 2023-06-19 at 12 16 03 PM" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/ca10935c-c0b6-405f-9f9d-5d414247ac43">

**Comment by MariannaPaszkowska** [comment]
CC @dberlow
