### ISSUE TITLE
gcircumflex.alt but no gcircumflex

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#564]
There is gcircumflex.alt in the font but no gcircumflex. How do you want to proceed with this? Will you add the glyph in the upright and we add it in our side automatically?

BTW @RickyDaMa no check to see if the open type features have all the reference glyphs?

**Comment by dberlow** [comment]
I think this has to start with the glyph list that's used to check the
fonts.

**Comment by sannorozco** [comment]
Hey @octaviopardo! In the beginning we had a bigger charset, and I believe it was reduced with a glyph list import into main, so maybe this slipped away?

**Comment by MariannaPaszkowska** [comment]
The gcircumflex wasn't a part of our target character set, and gcircumflex.alt should be excluded too. @octaviopardo  #72 #41
