### ISSUE TITLE
Hbar overlaping

### ISSUE THREAD

**Issue by Bogidar** [googlefonts/googlesans-flex#565]
Hello! 

The Hbar on opsz17.999-wdth25-wght1-ROND0 its overlaping.

<img width="482" alt="Captura de pantalla 2023-06-20 a las 12 03 37" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/fe80c800-ac75-4aa8-918c-54cbbf2759cb">

@octaviopardo 
@sannorozco

**Comment by dberlow** [comment]
Confirmed, thanks.

**Comment by sannorozco** [comment]
Hey @Bogidar, updated in Roman.

**Comment by Bogidar** [comment]
Gracias!
