### ISSUE TITLE
g.alt & a.alt do not have a top anchor

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#568]
g.alt does not have a top anchor. All the diacritics in ģ ğ ġ ĝ are manually aligned. They work as expected but in ĝ the circumflex gets out of place when tested in Fontgoggles
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/e14ce9ab-cbe1-45b1-919a-cc78f9ae5d81)

@sannorozco 
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz! Added top anchor on Roman sources.

**Comment by octaviopardo** [comment]
@sannorozco a.alt neither. We are also adding top and ogonek anchors on that one, oki??

**Comment by mekkablue** [comment]
There’s a mekkablue script for this, called _Replicate Anchors in Sffixed Glyphs._

**Comment by sannorozco** [comment]
@octaviopardo Ok!

**Comment by octaviopardo** [comment]
Hello @sannorozco I ve seen you ve added the anchors in the a.alt and g.alt, please give us a shout when you do so! So no ogonek anchor in a.alt?

**Comment by sannorozco** [comment]
@octaviopardo I’ll add it to the Roman.
