### ISSUE TITLE
Italic sources ROND sources change advance widths

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans-flex#569]
Fontbakery says:

> The following glyphs have variation in horizontal advance due to the ROND axis: K, Wgrave, f_f_j, D, eacute, Edotaccent, Q, plus, Atilde, Umacron and 205 more.

**Comment by octaviopardo** [comment]
in what UFO?

**Comment by MariannaPaszkowska** [comment]
@sannorozco Could you explain what the reason behind this comment is? I speak enough Spanish to understand this. 
I removed Hector's access to the repository before we can clarify this.

**Comment by madig** [comment]
Fontbakery doesn't say, but you'll have to check all ROND UFOs for each glyph anyway. I can't fix this by script because while I could set the width equal to the ROND0 default source of the Designspace, this would only change the RSB, but not LSB.

**Comment by octaviopardo** [comment]
I would like to solve this in the upcoming days. @madig can you give me more data of the meaning of this error? Does it mean that when you activate the ROND axis, the glyph width is superior? We could indeed check every glyph width in the R0 vs R100 and find out divergences

**Comment by madig** [comment]
It means that each glyph and kern pair in a ROND100 source must have the same advance width (spacing and kerning) as the corresponding ROND0 source.

**Comment by octaviopardo** [comment]
Oki, we ve looked at the divergences, and in many cases the differences are 1 unit. We are gonna be fixing everything over 2 units, but can we assume that everything with a difference of 1 unit is acceptable?? In many cases, the difference is provoked by the slant angle of the italic and the rounding of the values that glyphs does. 

We could also round units programmatically…

@madig @MariannaPaszkowska @casasin

**Comment by madig** [comment]
The difference must be zero in all cases, because even 1 font unit can lead to layout changes.

**Comment by MariannaPaszkowska** [comment]
@octaviopardo are there any updates on this?

**Comment by MariannaPaszkowska** [comment]
@madig and @belluzj will look into an automated way which we can apply in the build (logic taken from FontBakery)

**Comment by octaviopardo** [comment]
I think this is fixed. We looked at it specifically, used some scripts to fix it manually and last fontbakery report did not say anything about it

**Comment by MariannaPaszkowska** [comment]
the fontbakery might not catch this as in many cases the widths were consistent. This was a visible shift of outlines. 
I'll review it again.

**Comment by madig** [comment]
There's a mismatch of values for the kerning pair `("asterisk", "public.kern2.A_left")`:

| Source | Kerning Value in Italic ROND0 Counterpart | Kerning Value in Upright ROND0 Counterpart |
| --- | --- | --- |
| GoogleSansFlexItalic-opsz6-wdth25-wght1-ROND100.ufo | -40 | 0 |
| GoogleSansFlexItalic-opsz6-wdth100-wght400-ROND100.ufo | -80 | 0 |
| GoogleSansFlexItalic-opsz6-wdth151-wght400-ROND100.ufo | -30 | -150 |
| GoogleSansFlexItalic-opsz18-wdth25-wght1000-ROND100.ufo | -60 | 0 |
| GoogleSansFlexItalic-opsz18-wdth151-wght1-ROND100.ufo | -120 | -150 |
| GoogleSansFlexItalic-opsz18-wdth151-wght400-ROND100.ufo | -120 | -150 |
| GoogleSansFlexItalic-opsz18-wdth85-wght1000-ROND100.ufo | -80 | 0 |
| GoogleSansFlexItalic-opsz18-wdth50-wght1000-ROND100.ufo | -80 | 0 |

**Comment by casasin** [comment]
This has been fixed together with the kerning issue reflow.
