### ISSUE TITLE
STAT table and instances

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#57]
The issue to track progress on defining instances and to open a discussion. 

Difference from Google Sans:
- Optical size instances will only be defined at the default value on the optical size axis.

Steps:
- [x] Look into the GF's axis registry definitions
- [x] Investigate STAT and fvar instances in Roboto Flex to understand the approach there
- [x] Define STAT instances
- [x] Define fvar instances 
- [x] Take UX to ease into the account
- [x] Create a proposal and consult the team

CC @chrissimpkins @madig

**Comment by MariannaPaszkowska** [comment]
_Draft_ fvar proposal:

fvar instances in Roboto and GS:
wght - only

_Draft_ STAT proposal:

Width:
UltraCondensed, value 50.0
ExtraCondensed, value 62.5
Condensed, value 75.0
SemiCondensed, value 87.5
Normal, value 100.0
SemiExpanded, value 112.5 
Expanded, value 125.0
ExtraExpanded, value 150.0

Weight:
Thin, value 100.0
ExtraLight, value 200.0
Light, value 300.0
Regular, value 400.0 linked to 700.0 (optional, build like this only in Roboto)
Medium, value 500.0
SemiBold, value 600.0
Bold, value 700.0
ExtraBold, value 800.0
Black, value 900.0

Grade: 
Normal

Round: 
Normal

To decide - Optical Size in STAT are built differently in Roboto and Google Sans.
Optical Size in Roboto:
point size names and set values: 8pt, 9pt, 10pt, ..., 144pt. 

Optical Size in Google Sans:
Text + range, values
Max + range, values

CC @chrissimpkins

**Comment by chrissimpkins** [comment]
Weight LGTM. 

For width, @dberlow do you see 25 as a usable end of the range and warranting a STAT instance definition? IMO probably yes if we will include the rest of the range.  

For opsz, should we link sizes to the Material type scale? Pro: would actually be used by designers if they happen to use an application that supports STAT (maybe unlikely?). con: could change across Google Material versions and is a recommendation rather than a mandate.  Maybe it makes most sense to not include opsz instances at all?  In general I see these as much less useful to an end user than weight/width.  The goal should be automation and transparency to the end user IMO.  In the interim they get a slider / programmatic access to a VF axis rather than instance name clutter under assumptions about size milestones of highest importance / widest use.

**Comment by dberlow** [comment]
When we were looking at the productization of Roboto Flex, Dave and I came
up with three sets of styles from basic to advanced.

Something like that may be useful here.
1. coverage of basic Google Sans, two weights (400 and 700) of roman and
italic. (no opsz, or width)
2. include 1 above, + two  more weights, 200 and 500 with italics (no opsz)
and a 1/2 dozen expressive styles, (from larger opsz)
3. included 1 and 2 and widths of four weights + 1/2 dozen more expressive
styles.

>For width, @dberlow <https://github.com/dberlow> do you see 25 as a usable
end of the range and warranting a STAT instance definition?
So for some users, yes.

>For opsz, should we link sizes to the Material type scale?
If opsz is automatic, then you can just let it happen. If you make
instances of them, users might select them and they might not change them
if the size changes later. Not sure what to recommend beyond automatic for
opsz...

> In general I see these as much less useful to an end user than
weight/width.
I think opsz is very useful automatically, while width and weight are more
commonly useful manually;)

With the goal of automation ops allow the material type scale to be
simplified as the weight-switching they were doing to get color right,
between 300, 400 and 500, over their range of sizes, is no longer required
if opsz is used. That's waht we did with Roboto, and an early version of
GSF is shown in a pdf:
https://drive.google.com/file/d/1Aaz8lX4mKPD4x-csxTFyZRT3n6tAtayC/view?usp=sharing

Let me know if there's more I can do here.
Cheers,
David

**Comment by madig** [comment]
What should be the label for wdth=151?

**Comment by dberlow** [comment]
A width word like “Extra-expanded”, you mean?On Dec 2, 2022, at 12:29 PM, Nikolaus Waxweiler ***@***.***> wrote:﻿
What should be the label for wdth=151?

**Comment by madig** [comment]
Yes. Extra-expanded is 150 according to https://learn.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass, but I'm not sure about 151.

**Comment by chrissimpkins** [comment]
IMO wdth=151 needs no label.  150 should be the Extra Expanded width.  It's defined to 151 to maintain an axis range that is the same as Roboto Flex in anticipation of a need for axis range  consistency in Material third party and first party typography guidance.

**Comment by MariannaPaszkowska** [comment]
Sgtm @chrissimpkins!

What if we use flexible ranges for optical sizes in the STAT table?
Proposal:
Micro, range: 6-10 (pt)
Text, range: 10-18 (pt)
Max, range: 18-32767.99998 (pt)

**Comment by MariannaPaszkowska** [comment]
@jany @madig @RickyDaMa @Hoolean 
Decision: use Roboto Flex approach to STAT.
```
8pt,  value: 8
9pt,  value: 9
10pt,  value: 10
11pt,  value: 11
12pt,  value: 12
14pt,  value: 14
16pt,  value: 16
17pt,  value: 17
18pt,  value: 18
20pt,  value: 20
24pt,  value: 24
28pt,  value: 28
36pt,  value: 36
48pt,  value: 48
60pt,  value: 60
72pt,  value: 72
96pt,  value: 96
120pt,  value: 120
144pt,  value: 144
```
CC @chrissimpkins

**Comment by madig** [comment]
I updated the STAT opsz definitions in https://github.com/googlefonts/googlesans-flex/pull/129

**Comment by RickyDaMa** [comment]
Marking this as complete as the most up-to-date STAT entries are included in the `sources/config.yaml` file used to build the font
