### ISSUE TITLE
foursuperior and foursuperscript

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#571]
foursuperior and foursuperscript have the same Unicode, so one of them is actually inaccessible in the font. Want to do something about it?

**Comment by MariannaPaszkowska** [comment]
Let's fix this manually @octaviopardo @casasin.
To prevent this in the future a new check will be added to our tooling when dependencies will be upgraded (ufo2ft).

**Comment by casasin** [comment]
This is already fixed.
