### ISSUE TITLE
ae not rounded

### ISSUE THREAD

**Issue by Bogidar** [googlefonts/googlesans-flex#578]
ae not rounded in master:
opsz18-wdth100-wgth1000-ROND100

<img width="1042" alt="Captura de pantalla 2023-06-21 a las 18 46 33" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/7557e2bf-87e5-41f2-8274-201041447f09">

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Bogidar, updated in Roman.

**Comment by Bogidar** [comment]
Thanks! @sannorozco
