### ISSUE TITLE
four.numerator not rounded

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#579]
four.numerator (and all the glyphs including it as a component) not rounded in master opsz18-wdth25-wght1-ROND100
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/08bbb97c-a85c-45b8-8506-601f0e4b1d88)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
