### ISSUE TITLE
emdash rounded

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#580]
emdash is rounded in master opsz18-wdth25-wght1-ROND0
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/64134724-42e1-4918-a753-aecc490b16ad)
@octaviopardo

**Comment by Txonliz** [comment]
there is also a sharp version in the rounded master (opsz18-wdth25-wght1-ROND100)
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/fa2861a2-46c2-4981-93ef-f3e0c5a03265)

**Comment by schriftgestalt** [comment]
Small reminder that this can be fixed with the Fit Curve set to 55 or 56.

**Comment by Txonliz** [comment]
Good tip!

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco

**Comment by Txonliz** [comment]
Closed
