### ISSUE TITLE
oe significantly smaller than the rest of the rounded letters in opsz6-wdth25-wght1-ROND0

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#581]
in opsz6-wdth25-wght1-ROND0, oe is significantly smaller than the rest of the rounded letters. Let us know if you want to fix it for v1.2 or we ssave it for 2.0 @MariannaPaszkowska 
![Captura de pantalla 2023-06-22 a las 18 19 56](https://github.com/googlefonts/googlesans-flex/assets/2181684/ed848d33-1869-4268-bf3a-8be22b97f4ab)

**Comment by sannorozco** [comment]
Hey @octaviopardo, updated in Roman ROND0 ROND100.
