### ISSUE TITLE
quotes not rounded

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#582]
quoteright, quoteleft, quotesinglbase, quotedblbase, quotedblleft and quotedblright are not rounded in opsz18-wdth25-wght1-ROND100 master

![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/db9efff1-c43d-420b-b37d-13f5a61b56a1)

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
