### ISSUE TITLE
slash in ø?

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#583]
Hello! We've seen some divergences in design and thickness in between our UFOs (the italics) and the upright ones, for example, some ø & Ø that had the slash too thick and obviously needed adjustments. 

I m not sure if these updates have been reported somewhere and I missed them, if so please let me know where and apologize for the spam!
If they haven't please keep us in the loop of any change you introduce in the design of 1.2 so we can properly harmonize it. Even small ones, we are fine with them :)

Thanks!

**Comment by sannorozco** [comment]
Hey @octaviopardo, This was updated in the roman a while ago https://github.com/googlefonts/googlesans-flex/issues/230

The bars change weight over the weight, with, & opsz axis, so they don’t fill the Oo counters. Do you mean the counter disappear?

**Comment by octaviopardo** [comment]
hi @sannorozco what I mean is that it was updated in the roman, also in our branch, but it was never updated in the files we ve been working on for the italic. As a consequence, we saw this issue in our QA process, when suddenly the bars we had in our base files were changing a lot in the italic axis. If you remember any other change of this kind that you ve introduced, let me know in case it skips our QA tests :)

**Comment by sannorozco** [comment]
@octaviopardo, I think if you copy the glyphs Oslash, oslash, Oslash-bar, oslash-bar  from Roman to Italic it should be fine, I’m not sure why they weren’t in the files you started working on.

I’ll let you know, cheers!
