### ISSUE TITLE
ae not rounded

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#584]
ae not rounded in master opsz18-wdth25-wght400-ROND100
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/9b6216da-ff02-4575-9fae-ec70517ec20c)

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
