### ISSUE TITLE
Dcroat and Eth have different bar placement in 6-151-400-R0

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#585]
Why not making one as component of the other one? The spacing values are also different
@MariannaPaszkowska
![Captura de pantalla 2023-06-25 a las 18 47 34](https://github.com/googlefonts/googlesans-flex/assets/2181684/13dda731-5bc2-4d4e-9be5-e254d0480cf9)

**Comment by sannorozco** [comment]
Hey @octaviopardo, updated in Roman.

**Comment by Txonliz** [comment]
Solved @octaviopardo @MariannaPaszkowska
