### ISSUE TITLE
euro.tf : euro component has different positions in sharp and rounded masters

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#586]
In the master opsz18-wdth25-wght1000-ROND100, euro component is 50 units further to the left than in its sharp partner. I assume the position in the sharp master is correct.
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/2ae240fe-bf59-4410-b81d-e3c100365a64)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
