### ISSUE TITLE
Spacing in seven.tf in sharp and round not consistent

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#588]
In masters -opsz18-wdth25-wght1000-ROND0 and -opsz18-wdth25-wght1000-ROND100 spacing is not consistent in **seven.tf**
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/05dc71e6-054c-4e2c-839a-229b295d0dde)
@octaviopardo

**Comment by Txonliz** [comment]
Same problem in this master with one.tf

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
