### ISSUE TITLE
j not rounded in master 18-50-1-100

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#589]
Lower ending of j (also jdotless) is not rounded at its lower ending in master 18-50-1-100. It also affects ij

![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/378cb97d-f281-496b-8598-480e5a418851)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
