### ISSUE TITLE
Bar too high in Hbar in 18-50-1-100

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#590]
Bar doesn not fit the placement of its sharp partner
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/aa30a7f1-bc2c-4e67-9836-dee07573e0a1)

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
