### ISSUE TITLE
Trademark not rounded in master 15-50-400-100

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#592]
trademark symbol is not rounded in master 15-50-400-100
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/a56877d6-46b4-47e4-ad8f-6fe3ad3f6b1d)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
