### ISSUE TITLE
Hbar not positioned

### ISSUE THREAD

**Issue by Bogidar** [googlefonts/googlesans-flex#593]
Master: 

opsz17.999-wdth25-wght400-ROND0.ufo

<img width="647" alt="Captura de pantalla 2023-06-27 a las 17 09 11" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/992e6994-7dde-4858-bece-209c9cfc7483">

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Bogidar, updated in Roman.
