### ISSUE TITLE
Spacing superscript & subscript

### ISSUE THREAD

**Issue by Bogidar** [googlefonts/googlesans-flex#595]
The spacing of master:

opsz17.999-wdth25-wght1-ROND0.ufo
opsz17.999-wdth25-wght400-ROND0.ufo

Have a non consistent spacing

<img width="1261" alt="Captura de pantalla 2023-06-27 a las 17 28 36" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/10d3b009-7325-4d77-b50c-e7ef5969efdd">
<img width="1263" alt="Captura de pantalla 2023-06-27 a las 17 29 30" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/e2e0ffdf-d832-49d2-a067-50e8753f806d">

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Bogidar, updated in Roman.

**Comment by Bogidar** [comment]
Gracias!
