### ISSUE TITLE
No rounded version for percent.tf

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#596]
On the master opsz144-wdth151-wght400-ROND100. 

The percent.tf doesn't have a rounded bar. And it looks like this. 

<img width="562" alt="Screenshot 2023-06-28 at 11 12 13" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/58236772-1c0d-4d3e-83d9-07ec08fc0417">

**Comment by sannorozco** [comment]
Hey @joanacorreiatype, updated in Roman.
