### ISSUE TITLE
Differing component placement in percent.tf master 18-25-1000-100

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#597]
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/247d3f57-0daa-4761-bf91-30d6e7ccd3e8)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco
