### ISSUE TITLE
Not centered glyphs tabular on rounded upright version

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#598]
On this master uprigth rounded- opsz144-wdth151-wght400-ROND100. 

The tabular glyphs are not centered. 

<img width="311" alt="Screenshot 2023-06-28 at 11 24 53" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/1e9d4d26-3fef-4e35-b82f-53ab8c936ca8">

**Comment by sannorozco** [comment]
Hey @joanacorreiatype, updated in Roman.
