### ISSUE TITLE
Different height on colon-time

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#599]
Colon-time has a different height on the rounded version upright than the sharp vertical. 

<img width="408" alt="Screenshot 2023-06-28 at 10 53 10" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/fbb2e2e9-ca38-47fd-bec4-fd9c7f9d7071">

**Comment by sannorozco** [comment]
Hey @joanacorreiatype, which source?

**Comment by joanacorreiatype** [comment]
Sorry @sannorozco it is happening in two sources, 144-100-400-ROND100 and 144-25-400-ROND100.

**Comment by sannorozco** [comment]
Hey @joanacorreiatype, updated in Roman.
