### ISSUE TITLE
Different height on colon.time in sharp and rounded 

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#600]
opsz144-wdth25-wght400-ROND0 - different height on colon.time in sharp and rounded on the upright version.

<img width="269" alt="Screenshot 2023-06-28 at 15 15 42" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/7cd26ef7-dd87-4210-9a77-77dc49aac0ee">
<img width="239" alt="Screenshot 2023-06-28 at 15 15 46" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/bc9d8ea8-e74b-4c26-a04a-1a370307ea9f">

**Comment by sannorozco** [comment]
Hey @joanacorreiatype, updated in Roman.
