### ISSUE TITLE
seven.tf not rounded

### ISSUE THREAD

**Issue by joanacorreiatype** [googlefonts/googlesans-flex#601]
in master 144-100-400-ROND100

seven.tf is not rounded. 

<img width="608" alt="Screenshot 2023-06-28 at 16 34 24" src="https://github.com/googlefonts/googlesans-flex/assets/9676919/d88db527-981e-4b51-a52d-d0fe48a3b672">

**Comment by sannorozco** [comment]
Hey @joanacorreiatype, updated in Roman.
