### ISSUE TITLE
Bar in percent.tf too heavy

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#603]
In masters 18-50-1-0, 18-50-1-100, 18-25-1-0 and 18-25-1-100
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/5f3b38f0-1545-4756-8cdf-d82d69ada236)
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/8ce14fe9-1706-4ab2-86f3-1f0ab2944fee)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco, updated in Italic.
