### ISSUE TITLE
ring not circular

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#604]
ring is not circular in masters 18-50-1-0 and 18-50-1-100 (also 18-85-1-0 and 18-85-1-100)
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/b7934020-22ea-4f6d-8702-06b947253c90)
@octaviopardo

**Comment by Txonliz** [comment]
same problen in zeropercent for masters 18-50-1-0 and 18-50-1-100  (18-85-1-0 and 18-85-1-100 seem ok)
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/76f72555-1d54-4526-99c9-e75dccce4c72)
@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.

**Comment by Txonliz** [comment]
Thanks @sannorozco, updated in Italic
