### ISSUE TITLE
zeropercent and ringcomb not circular

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#605]
In masters 18-25-400-0, 18-25-400-100, 18-25-1-0 and 18-25-1-100
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/5d868d9f-33ba-45cf-bf37-333c1d44df0b)
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/947bd197-2c60-48fa-a253-978e3eb8aee3)

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.
