### ISSUE TITLE
tabular numbers endings 

### ISSUE THREAD

**Issue by Bogidar** [googlefonts/googlesans-flex#606]
Master:
GoogleSansFlexItalic-opsz144-wdth85-wght400-ROND100.ufo

<img width="1229" alt="Captura de pantalla 2023-06-29 a las 14 26 53" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/df0267ae-7187-4c13-9633-48aeba8e3ba9">

@octaviopardo

**Comment by sannorozco** [comment]
Hey @Bogidar, updated in Roman.
