### ISSUE TITLE
Different placement of dots in question, questiondown, exclam and exclamdown

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/googlesans-flex#608]
Affects masters 18-85-1000-0 and 18-85-1000-100
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/0ccc2f29-920a-426c-ad14-72278382821a)
@octaviopardo

**Comment by MariannaPaszkowska** [comment]
CC @dberlow

**Comment by sannorozco** [comment]
Hey @Txonliz, updated in Roman.
