### ISSUE TITLE
Figure Approval?

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#61]
The first issue of the latest build is whether the figures are the final designs for all the design space so we can proceed with other figure sets required for this build.

Thanks.  

Edit:  would’ve been great since this issue was posted, to inform FB “there are No other figure sets required for this build.“

**Comment by dberlow** [comment]
(I am unable to "assign" anyone on this repo.)

**Comment by MariannaPaszkowska** [comment]
Thank you for the speedy delivery of this latest set of figure designs! @dberlow 
Before we can approve, here are some improvements we'd like to see in the next update:


- [x] `6` and `9` - Improve the balance of the skeletons of 6 and 9, mostly in the wdth-extended corner of the DS (example: opsz 44, wdth 141, wght 887, ROND 0). At the moment, they look leaning to the right or left. 

<img width="1034" alt="Screenshot 2022-11-30 at 7 58 37 PM" src="https://user-images.githubusercontent.com/22956348/204896819-3779aaad-893b-4cda-b4d7-af3c178ef1a7.png">
<img width="1070" alt="Screenshot 2022-11-30 at 10 08 52 PM" src="https://user-images.githubusercontent.com/22956348/204898982-a19db961-0f48-4e8d-9622-ad45b58ecc0e.png">

also visible here:
<img width="1072" alt="Screenshot 2022-11-30 at 10 37 57 PM" src="https://user-images.githubusercontent.com/22956348/204903124-ffe6584c-046d-4197-b1f2-e9e24abcb2d4.png">


- [x] `6` and `9` - Make legs even strokes. Strokes are concave. 

<img width="1085" alt="Screenshot 2022-11-30 at 10 30 07 PM" src="https://user-images.githubusercontent.com/22956348/204901718-878fbd05-440c-44db-b7aa-0971bb2c8afc.png">


- [x] `6` and `9` - General design refinements across all DS (contrast, color, point placement).
<img width="1068" alt="Screenshot 2022-11-30 at 10 35 16 PM" src="https://user-images.githubusercontent.com/22956348/204902566-bc308c9b-9d98-4fc6-afd9-004ed15b00fd.png">



- [ ] Fix interpolation in the `3` (in-stroke, see also #55):
<img width="1082" alt="Screenshot 2022-11-30 at 10 39 47 PM" src="https://user-images.githubusercontent.com/22956348/204903456-17da5660-aa06-4849-b975-4c45af4e5dd3.png">


- [x] Fix interpolation in the `4` (apex):
<img width="269" alt="Screenshot 2022-11-30 at 7 57 57 PM" src="https://user-images.githubusercontent.com/22956348/204899234-3ab0342c-d34a-4120-9972-b8172a30387b.png">
https://videoproof.graphicore.de/#2022-11-30T17:57:38Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;opsz44,wdth141,wght877;grid&World.Figures;0 



CC @davelab6 @chrissimpkins

**Comment by MariannaPaszkowska** [comment]
Hi @dberlow, I noticed that you removed the assignment. I assigned you here so you could report back to us about the progress on the improvements to 6 and 9. What's the status there? :) 
Do you have permissions to tick the boxes in this comment: https://github.com/googlefonts/googlesans-flex/issues/61#issuecomment-1332717967? Let me know if that's not the case, and I'll look into that.

**Comment by dberlow** [comment]
It’s your repo and strictly google’s decision that FB be excluded from as many permissions as possible there. 
Probably best if I both make and record the changes I make on our repo.

**Comment by MariannaPaszkowska** [comment]
Let's keep the conversation here for consistency and transparency for the whole team. I can help record the changes. 

What's the status of the tasks collected here: https://github.com/googlefonts/googlesans-flex/issues/61#issuecomment-1332717967?
