### ISSUE TITLE
Several source style names in the GoogleSansFlex.designspace do not always contain the "ROND100" (for the round 100 masters).

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#611]
Several source style names in the GoogleSansFlex.designspace do not always contain the "ROND100" (for the round 100 masters).

_Originally posted by @schriftgestalt in https://github.com/googlefonts/googlesans-flex/issues/520#issuecomment-1613424964_

**Comment by sannorozco** [comment]
Hi @MariannaPaszkowska Updated in Roman.

**Comment by octaviopardo** [comment]
This might have been fixed by @madig already when tweaking the designspace files?

**Comment by madig** [comment]
I copied the upright DS from the italics branch. If that fixed it, yes.
