### ISSUE TITLE
Fix issues in the master 17opsz, 1000wght, 25wdth ROND100 and ROND0

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#620]
- [ ] Outline issues:
 `ACcesr¢˘˛ ij `
<img width="1014" alt="Screenshot 2023-07-04 at 4 54 19 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/392b1915-dbf1-4690-9974-050f51eda8b0">

- [ ] Component positioning issue:
 `Čč `
<img width="183" alt="Screenshot 2023-07-04 at 4 57 13 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/3d6bc583-6ad3-42d2-af96-c1298bc85ffd">

- [ ] Anchor positioning issues:
 `ÅŮåů
ÄË Ï üÿä 
ĹĺŔŹúŕýśź
İċĊġĖė `
<img width="1078" alt="Screenshot 2023-07-04 at 4 57 00 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/d773d4f3-a988-4c13-a28a-87e853706406">

<img width="1044" alt="Screenshot 2023-07-04 at 4 54 34 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/b682e19e-36fc-462b-b872-39887bedccf6">

Tested font: local build from last Friday.

**Comment by Bogidar** [comment]
Its fixed on the QA we did this week! ;)
