### ISSUE TITLE
Master 6opsz, 1000wght, 100wdth, ROND100 is rounded and should be sharp in v1.002

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#622]
<img width="1531" alt="Screenshot 2023-07-04 at 5 22 44 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ddcb7ccd-faad-420c-9f84-8938698f5191">

**Comment by octaviopardo** [comment]
Ok, I think this got fixed with issue #611 although we will recheck it. What app is the one you are using in the screenshot?
