### ISSUE TITLE
Build error in it-ad-wip-italic-v1.002: Base master not found

### ISSUE THREAD

**Issue by casasin** [googlefonts/googlesans-flex#623]
We're getting this error when trying to build. It seems to come from "GoogleSansFlexItalic-opsz18-wdth85-wght1-ROND0.ufo" + "ROND100" (I might be wrong).
```sh
fontmake.errors.FontmakeError: In 'GoogleSansFlex-Full.designspace': Generating fonts from Designspace failed: Base master not found.
make: *** [build.stamp] Error 1
```

Any idea? Is there any way to get a more detailed error? (which _Base master_ is not found, p.e.)
It doesn't seem to come from anchors inconsistency.
Thanks!

**Comment by madig** [comment]
It's likely because the public.openTypeCategories key got out of sync in one UFO. I pushed a fix.

**Comment by octaviopardo** [comment]
and it works like a charm @madig thanks a lot

**Comment by schriftgestalt** [comment]
Can you check if you can improve the error message to make it easier to debug?

**Comment by madig** [comment]
I filed an issue at https://github.com/googlefonts/fontmake/issues/1014, maybe someone will fix it!
