### ISSUE TITLE
C anchor positioning issue opsz 18, wdth 25, wght 400

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#631]
<img width="554" alt="Screenshot 2023-07-18 at 5 49 25 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/366510ae-9d20-480e-aa14-00e3bd1d351c">

<img width="394" alt="Screenshot 2023-07-18 at 5 50 35 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/29c76fcc-bd10-4211-b41f-049068db00ec">

<img width="426" alt="Screenshot 2023-07-18 at 5 51 20 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/f652539e-df2d-47e4-b454-64a8cec9e7dc">

**Comment by Txonliz** [comment]
![image](https://github.com/googlefonts/googlesans-flex/assets/10536858/0d053949-319c-4b58-9d55-ced17a7d495d)
@MariannaPaszkowska @octaviopardo  Anchors in C are correctly placed now

**Comment by MariannaPaszkowska** [comment]
I confirm that this is fixed, thank you!
