### ISSUE TITLE
Ø - center the slash bar positioning at opsz 144, wdth 100, wght 400

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#632]
<img width="662" alt="Screenshot 2023-07-18 at 5 59 52 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/7ae954bb-a65d-45d8-9927-34f72f9992fc"> 

<img width="633" alt="Screenshot 2023-07-18 at 6 01 26 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/be50b85f-04dd-429c-af59-4853c046aad2">

**Comment by joanacorreiatype** [comment]
Done.

**Comment by MariannaPaszkowska** [comment]
Thank you for the quick update, I confirm this is fixed in the latest build.
