### ISSUE TITLE
harmonise outlines: master: 100 ROND, 400 wght, 151 wdth, 144 opsz 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#635]
**Harmonise outlines and balance curves**

A, improve rounded terminals:
<img width="894" alt="Screenshot 2023-07-19 at 9 19 20 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/202e2c5f-d1fe-4061-81a1-f6d848c7e716">
For comparison:
<img width="533" alt="Screenshot 2023-07-19 at 9 20 00 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/6b9d8ae1-8f79-4c56-b4e8-af1481dd23b7">

C:
<img width="868" alt="Screenshot 2023-07-19 at 9 18 08 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ce835df9-fce9-4b1a-b6f5-2390f19e9d7f">

G:
<img width="844" alt="Screenshot 2023-07-19 at 9 12 21 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/8c39a098-08bd-452b-9c42-ae85687df78e">
sharp is different:
<img width="847" alt="Screenshot 2023-07-19 at 9 12 29 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/b3920d56-544d-497f-82dc-3e857aa0be34">

g:
<img width="546" alt="Screenshot 2023-07-19 at 9 03 38 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/34306774-7694-46a5-bfbe-527f67c7ec95">
for comparison:
<img width="546" alt="Screenshot 2023-07-19 at 9 03 38 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a1ff392a-280b-4994-9cba-842c3af44cac">

X in ROND and sharp:
The left bottom terminal is thinning, and roundness could be improved.
<img width="950" alt="Screenshot 2023-07-19 at 9 00 51 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0c9edfee-8f44-4ae6-a1ea-3ae1bdc219cc">

y, the bottom terminal is thinning, and roundness could be improved.:
<img width="742" alt="Screenshot 2023-07-19 at 9 20 52 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0d6ae8e7-af6e-491d-b318-7638f96bc149">

ø, round terminals:
<img width="564" alt="Screenshot 2023-07-19 at 9 22 30 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/6efdf8af-b3e7-436d-a032-fe95a4dee522">

**even luminosity (colour)** 
1 is lighter, improve terminals of the 6, 7 and 9:
<img width="972" alt="Screenshot 2023-07-19 at 9 24 32 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ead790a0-9d24-40a6-ae5d-5da11b715399">

**Comment by joanacorreiatype** [comment]
It's done.

**Comment by MariannaPaszkowska** [comment]
Hi @joanacorreiatype, would it be possible to also refine the uppercase X? CC @octaviopardo  
<img width="727" alt="Screenshot 2023-07-25 at 4 16 32 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/3aed6458-cc30-41bf-bf70-ca20742f49e0">

**Comment by Bogidar** [comment]
Fixed Marianna!
