### ISSUE TITLE
ł: ROND100, opsz 18, wdth 100, wght 400

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#636]
ł: slash needs to be centred:
<img width="381" alt="Screenshot 2023-07-19 at 12 01 05 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/4bba194d-4a74-4c7b-863d-f72247e7792b">
comparison:
<img width="512" alt="Screenshot 2023-07-19 at 12 03 13 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9fa3fd99-5e24-4a09-9b51-c786821e3de5">

**Comment by MariannaPaszkowska** [comment]
also 'Ł ł' at: ROND 100, opsz 18, wdth 100, wght 1 <img width="509" alt="Screenshot 2023-07-19 at 12 09 26 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0c2c4c42-fc8e-4698-904b-b828ff13a80c">

**Comment by Bogidar** [comment]
Fixed! 

<img width="572" alt="Captura de pantalla 2023-07-19 a las 16 13 04" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/e9c694d3-f317-4397-be78-743b57eeae7b">
<img width="483" alt="Captura de pantalla 2023-07-19 a las 16 13 59" src="https://github.com/googlefonts/googlesans-flex/assets/134197382/8e8b0176-7539-4528-b2d7-48bd8262fa2e">

**Comment by MariannaPaszkowska** [comment]
Thank you for the quick updates, I confirm this is now fixed in the latest builds.
