### ISSUE TITLE
interpolation issues in dollar and cent: broken bars

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#637]
<img width="1064" alt="Screenshot 2023-07-19 at 2 42 03 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/5f763a55-896f-49e7-b3f5-206e2ef9a34a">
<img width="449" alt="Screenshot 2023-07-19 at 2 43 13 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/4d87e672-0ed9-414f-99bb-d155d0e3382f">
Please check if there is an intermediate master missing in Italic.

**Comment by octaviopardo** [comment]
Fixed!

![Captura de pantalla 2023-07-21 a las 8 49 08](https://github.com/googlefonts/googlesans-flex/assets/2181684/7beb1e73-aa1a-4517-9c5f-be2339eb7920)

**Comment by MariannaPaszkowska** [comment]
I confirm that this is fixed
