### ISSUE TITLE
interpolation issue in "9": opsz 144 wdth 151 wght 888

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#638]
Counter interpolation, it disappears when interpolating between
opsz 144, wdth 151, wght 1 
and
opsz 144, wdth 151, wght 1000:
<img width="383" alt="Screenshot 2023-07-19 at 2 49 16 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/283321c8-93b1-44b1-ac0f-5f8f7637478a">

**Comment by joanacorreiatype** [comment]
Corrected.

**Comment by MariannaPaszkowska** [comment]
I confirm that this is fixed in the latest build, thank you!
