### ISSUE TITLE
Add a custom GSF page to TypeRoof

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#64]
I'd like to use the commenting function of TypeRoof to perform reviews of Google Sans Flex and be able to share the URL easily. 

It would be helpful for the project to have a private, password-protected site with the latest version of the GSF embedded. 
Ideally, the latest version would be pulled from the repository, so the user shouldn't have to install the font.

**Comment by davelab6** [comment]
https://github.com/FontBureau/videoproof/issues/32

**Comment by MariannaPaszkowska** [comment]
Hi @graphicore, I hope you can help us with this!

**Comment by graphicore** [comment]
@MariannaPaszkowska 

Fonts are now put into local storage (indexedDB) which means they stay accessible once dropped.

I don't want to carry the burden of a password protected site which is used to distribute proprietary data.

With the local storage version, I think the workflow above can be established. People who have access to the required font will be asked to load it in a modal dialog in the app if they did not load it before. Please see https://github.com/FontBureau/videoproof/issues/32#issuecomment-1357703706 for a description and try it out.
