### ISSUE TITLE
Kerning improvements review GSF v1.002

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#640]
Kerning issue to address: 
ÞY MISÞYRMA
<img width="666" alt="Screenshot 2023-07-19 at 7 10 15 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/50a60c8a-fb90-49b4-8004-afc97f35b61d">

¿Y ¿YAY?
¿T ¿TÍA T?
<img width="614" alt="Screenshot 2023-07-19 at 7 12 38 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/8a9d524b-0450-4c3e-88b8-60220bdf0edf">

ľč topoľčiankach
ľž oceľželezo 
ľš boľševickej
ťš dvadsaťštyri
<img width="861" alt="Screenshot 2023-07-19 at 7 24 04 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/b9f3e7d8-ef32-4431-9755-557689cb8c3f">

ťš dvadsaťštyri
<img width="949" alt="Screenshot 2023-07-19 at 7 25 14 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/f10dff93-e35a-4610-ac16-b51a5cd26c83">

ľč topoľčiankach
<img width="812" alt="Screenshot 2023-07-19 at 7 29 47 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/aa5961bd-a16e-4fd8-ad14-fd807c797ead">

ĽV ĽVOV
ĽT VOĽTE
<img width="950" alt="Screenshot 2023-07-19 at 7 30 21 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ab9adc80-ba30-433d-b3fd-9ed5f51fd3dc">

<img width="1157" alt="Screenshot 2023-07-19 at 7 31 06 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/8306ee35-4077-4b12-8ed6-cd9bd480eb60">

¿Y ¿YAY? 
¿T ¿TÍA T?
<img width="956" alt="Screenshot 2023-07-19 at 7 32 59 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/04c78080-c15f-4bce-8867-94caa76205aa">

ĽV ĽVOV
<img width="1165" alt="Screenshot 2023-07-19 at 7 39 24 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/34251c84-0f27-4f3b-806d-1189c3eba6c0">
<img width="881" alt="Screenshot 2023-07-19 at 7 40 39 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/c0743e35-3a91-474a-8e66-28480e39fe57">

ĽV ĽVOV
<img width="1132" alt="Screenshot 2023-07-19 at 7 44 29 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/2c8775e6-69d2-43e7-a32e-f566f811227f">

‚Y
<img width="584" alt="Screenshot 2023-07-19 at 7 57 13 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/f099c476-dabd-4d50-ada2-93e7ffcdc0c8">

ĽV ĽVOV
<img width="677" alt="Screenshot 2023-07-19 at 7 58 52 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/1ca71467-c579-49a6-a36f-55ac0734d875">

**Comment by joanacorreiatype** [comment]
Corrected.
