### ISSUE TITLE
Tabular figures in upright: inconsistent sidebearings ROND vs sharp

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#641]
Issues with 1.tf in upright
<img width="1239" alt="Screenshot 2023-07-19 at 8 17 57 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/1f1471f3-34bd-486e-826b-1ca6f641818a">
<img width="1246" alt="Screenshot 2023-07-19 at 8 17 50 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/e7351be2-4612-47dc-8ca9-70e2151179c2">

Issues with 6.tf and 9.tf in upright

<img width="428" alt="Screenshot 2023-07-19 at 8 22 01 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a55ff8c1-a58c-4aea-9c5a-906832afc31f">

Issues with 7.tf (length of the horizontal bar)
<img width="1312" alt="Screenshot 2023-07-19 at 8 22 35 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/46e9f27a-10fa-4b0e-a18f-6c1cc9662e7b">
<img width="1314" alt="Screenshot 2023-07-19 at 8 22 30 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/e631b38b-7dc9-44ac-a6cb-3639506409dd">

Issues with 8.tf
<img width="1000" alt="Screenshot 2023-07-19 at 8 20 58 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/1edb30d0-f1ba-4601-a4af-330aa721f028">

, comma.tf
<img width="1300" alt="Screenshot 2023-07-19 at 8 24 38 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9026d74c-8b46-4f2e-b9e1-088785123a82">

, : ;  comma.tf colon.tf semicolon.tf
<img width="1304" alt="Screenshot 2023-07-19 at 8 25 16 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a0c43507-91e5-49d0-8f92-73a82289eb91">
<img width="1307" alt="Screenshot 2023-07-19 at 8 25 09 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/b0ae4241-e2d0-4d73-8ed7-0595575cbe7c">

Euro.tf
<img width="632" alt="Screenshot 2023-07-19 at 8 27 10 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/6efdf0c5-ffd1-4973-877a-e63c24a3d524">

<img width="660" alt="Screenshot 2023-07-19 at 8 27 14 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a0b517cd-560f-4b44-b331-f8b47fcaef73">

**Comment by joanacorreiatype** [comment]
Hi Marianna, it's not clear which of the masters the issues are from. If you can make it clearer I will correct them. Thank you @MariannaPaszkowska

**Comment by MariannaPaszkowska** [comment]
It's in the upright font only and it seems a global issue across masters. You need to make sure the metrics and side bearings are equal between sharp and round masters. Maybe @mekkablue or @casasin have an automatic solution to suggest?

**Comment by MariannaPaszkowska** [comment]
@octaviopardo are there any updates on this?

**Comment by octaviopardo** [comment]
fixed and pushed

**Comment by octaviopardo** [comment]
@MariannaPaszkowska  I ve been told that we might have not updated yet the opsz6 ROND (that are equal to the Sharp). We arre doing it this afternoon

**Comment by MariannaPaszkowska** [comment]
Excellent, this is now fixed in the latest builds. Thank you!
