### ISSUE TITLE
Fix FontBakery FAIL The dot of soft dotted characters                          

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#648]

**Comment by belluzj** [comment]
Hello Marianna, we had a designer working on the feature this morning and he spotted that the dot in the /i and /j are not at the same height at least in this particular UFO (he's working from the main branch)


![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/06d4e766-bd19-4fc2-8f67-0e2993f6aa0b)


![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/ddfc66cc-9753-4818-b9b2-d350e8f1f6ef)

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska this has been fixed in #659, all good to close this?

**Comment by MariannaPaszkowska** [comment]
correct, thanks @RickyDaMa!
