### ISSUE TITLE
[com.google.fonts/check/STAT/gf_axisregistry] Fix axis name FAIL 'Slanted' 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#649]
Files:   GoogleSansFlex-Full[ROND,opsz,slnt,wdth,wght].ttf

     
FAIL On the font variation axis 'slnt', the name 'Slanted'                 
          is not among the expected ones (Default) according to the Google Fonts
          Axis Registry. [code: invalid-name]                                   
    Result: 
FAIL

https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/slant.textproto

**Comment by MariannaPaszkowska** [comment]
This might be related to the Stat table. Let's try adding "Default" for slnt value: 0
https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/slant.textproto

**Comment by madig** [comment]
It's there already. The problem is the other entry for -10, which FB flags as an error. If I remove it, the check passes, but now com.adobe.fonts/check/stat_has_axis_value_tables fails because it wants there to be an entry for -10, too.

@felipesanches help? We need a slnt axis Slanted = -10 entry or equivalent in the STAT table, but the gfregistry check complains about it. Why? https://github.com/googlefonts/fontbakery/discussions/4214

**Comment by felipesanches** [comment]
I'm not sure.

The axisregistry documentation has this:

**fallback**

    Instance positions along the axis, such as wght 100,200,300,400,500,600,700,800,900.
    A cross-product of fallback positions along all supported axes is created to support legacy browsers that lack variable font support. For axes with CSS3 properties (such as [font-weight](https://drafts.csswg.org/css-fonts-3/#font-weight-prop)), the positions accessible to CSS3 should be specified. For axes lacking CSS3 properties a legacy browser is limited to a single position and that position must be at a fallback.
    In case an axis doesn't include predefined positions, it is mandatory to define at least one fallback position. It should be called Default and its value should correspond to the default_value position of the axis.

**fallback_only**
    Describes whether to only use fallback values when presenting to users in the UI. Currently, default to true, for continuous range axes should be set to **false**.



The slnt axis only has "Default" on the axisregistry and it also has `falback_only=false`. I am not sure but, perhaps the fontbakery check should only enforce fallback names when falback_only is **true**?

If that's the case, then we'll need to open an issue on fontbakery to change the behaviour of **com.google.fonts/check/STAT/gf_axisregistry**

I need someone else to review this. Maybe @m4rc1e knows better?

**Comment by MariannaPaszkowska** [comment]
@madig From Rosalie Wagner: "We usually only set a default value to 0 in the STAT and no fallback. Although if you want italic instances in the FVAR you would need to add an italic value also in the STAT and the test will fail (but in that case you ignore). if you have italic instances, the slant axis should be last in the axis order. And you would need to link 0 with the italic value. "

**Comment by m4rc1e** [comment]
Can you provide a link to a test font and I'll update fontbakery based on Rosa's comment.

**Comment by MariannaPaszkowska** [comment]
@m4rc1e there you go! https://github.com/googlefonts/googlesans-flex/actions/runs/5677375325

**Comment by madig** [comment]
I'll disable the check then.

**Comment by m4rc1e** [comment]
I opened up https://github.com/googlefonts/fontbakery/pull/4215 which should allow Italic AvisValues in the slnt axis.
