### ISSUE TITLE
Fix file name for the font with slant axis (Full)

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#650]
FAIL Expected                                                              
          "GoogleSansFlex[ROND,opsz,slnt,wdth,wght].ttf. Got                    
          GoogleSansFlex-Full[ROND,opsz,slnt,wdth,wght].ttf. [code:             
          bad-filename]                                                         
    Result: 
FAIL

**Comment by madig** [comment]
Fixed in main and the italics branch.
