### ISSUE TITLE
Unify kerning sharp vs ROND

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#651]
FAIL Kerning rules cause variation in horizontal advance                   
          on the ROND axis (e.g. ampersand/Y) [code: rond-kern-causes-reflow]   
    Result: 
FAIL

Reported here: https://github.com/googlefonts/googlesans-flex/actions/runs/5644349820/job/15287958961

**Comment by casasin** [comment]
@MariannaPaszkowska This has been fixed.
