### ISSUE TITLE
Fix j and thorn in ROND vs sharp

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#652]
Files:   GoogleSansFlex-Full[ROND,opsz,slnt,wdth,wght].ttf

     
FAIL The following glyphs have variation in horizontal                     
          advance due to the ROND axis: j and thorn [code: rond-causes-reflow]  

Reported here https://github.com/googlefonts/googlesans-flex/actions/runs/5644349820/job/15287958961

**Comment by casasin** [comment]
This has been fixed.
