### ISSUE TITLE
Request for contour point changes

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#654]
1. figure /4 simplification
2. /y overlap remove
3. Germandbls and /ß simplify
4. K,k and R additional diagonal points
5. The three off curve points in a row in the Google Logo's /e

Is there anyone else?

**Comment by dberlow** [comment]
Any comments or additions?

If not, and these changes are desired, please let us know which of these changes, who you want to make them, and when. Thanks.

**Comment by chrissimpkins** [comment]
I'm not current on what is going on in this thread and I've been assigned for feedback here.  Are these changes a request from Dave/Marianna, Octavio/team, or is this a recommendation from Font Bureau?

**Comment by dberlow** [comment]
Will document with pictures.

**Comment by dberlow** [comment]
1. The /4 was originally requested to have a top that separated (left). A request from @MariannaPaszkowska to simplify this as a result of artifacts appearing in interpolations would result in the contour on the right. 
<img width="1139" alt="Screen Shot 2023-08-03 at 6 55 06 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/44678b32-d068-4038-a060-ec52a87e56c9">
The glyph will not change visually except to correct above artifacts.


2. lowercase /y went through a series of changes to the contour. This ended up with an overlap (left), that is not what FB uses that capability of TT for and may create issues in future interpolations. The right contour is on the right. 
<img width="1103" alt="Screen Shot 2023-08-03 at 7 04 00 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/a0d0f97c-89aa-4258-b5f2-06ca4e3723d1">
 The glyph will not change visually except to correct the above.


3. Germandbls only, (and not /ß needs), to be simplified for points incorrectly included to round interior intersections. The two interior intersections, (highlighted in red on the right) are removed on the left. 
<img width="1268" alt="Screen Shot 2023-08-03 at 7 14 51 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/cdaa58ba-19e5-4bcb-86df-fe31f9101772">
 The glyph will not change visually except to make the top curve smoother


4. K,k and R additional diagonal points were kept from the original design that allowed a little step at the x max of the diagonal.  The has been co-positioned with other points until now to enable the ROND axis interpolation from 0 to 100 to go smoothly. Here's a detail from GoogleSans-Regular.ttf:
<img width="424" alt="Screen Shot 2023-08-03 at 7 25 20 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/d85c5539-fcdd-4b8a-9fa5-e8362f1104e1">
This and other similar point should be deleted, as shown below in the ROND001 before on the left, after on right.
<img width="1263" alt="Screen Shot 2023-08-03 at 7 33 03 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/4d31943e-b2dd-48a0-9320-2504b6791eb8">
 The glyph will not change visually


5. The three offcurve points in a row in the Google Logo's /e, are otherwise unique within the font. This crashes some of our software and the shape as it stands is poor. 
<img width="1162" alt="Screen Shot 2023-08-03 at 7 38 04 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/a55fca09-e8cc-4dd9-af5e-de8839b70c0c">
The glyph will get better.
