### ISSUE TITLE
Review release process

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#680]
I pushed the release tag, but it didn't seem to build fonts or trigger the release https://github.com/googlefonts/googlesans-flex/releases/tag/v1.002 
Here is the [release candidate](https://github.com/googlefonts/googlesans-flex/actions/runs/5685465927), and that's [the commit](https://github.com/googlefonts/googlesans-flex/actions/runs/5685450259) I tagged. 

CC @chrissimpkins

**Comment by MariannaPaszkowska** [comment]
My bad, I manually pushed the tag like in the GS, instead of following the steps described in the README

**Comment by chrissimpkins** [comment]
We moved the git tag up to the latest main branch commit to pull in the changelog updates and a couple of commits that seem to be fontinfo.plist update related.  The latest release @ https://github.com/googlefonts/googlesans-flex/releases/tag/v1.002 should build successfully based on our test of the last git tag push.  Let's confirm that we are at the proper release commit and have compiled our release files when we get together tomorrow.  Thanks all!
