### ISSUE TITLE
Latest GSF 2.0

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#681]
Please find font here: https://github.com/googlefonts/googlesans-flex/blob/FB-WIP2-2.0/fonts/GoogleSansFlex-2.0-A%5BGRAD%2CROND%2Copsz%2Cwdth%2Cwght%5D-VF.ttf

It is build of 2.0 with all axes and all glyphs to the existing specification. We will be reviewing it this week.

All of the sources for this build were ready the 29th of August and the build took until last night. 

We expect this to be about our last build, with Google and others taking over the designspace and build decisions.

Thanks.

**Comment by Lorp** [comment]
Edit this to 29 July for the record?

**Comment by dberlow** [comment]
The build is the recorded event i think.

**Comment by chrissimpkins** [comment]
> All of the sources for this build were ready the 29th of August and the build took until last night.

What is the approximate duration in hours?  It sounds like we are bumping into very significant compiler issues here.

**Comment by davelab6** [comment]
I found some vampire teeth :) 

<img width="1271" alt="Screenshot 2023-08-02 at 08 41 17" src="https://github.com/googlefonts/googlesans-flex/assets/261579/0579222e-0485-4646-a10c-638cd6fb29a2">

**Comment by dberlow** [comment]
This is a diagram of the styles, signed. 
<img width="1690" alt="Screen Shot 2023-08-01 at 11 36 02 AM" src="https://github.com/googlefonts/googlesans-flex/assets/1956494/8f1349d0-b889-4bc4-914f-4c8dc0bea534">

(the comment above is move to it's own issue)

**Comment by davelab6** [comment]
Thanks David - congratulations to you and @sannorozco on drawing and committing to the repo all those sources :) 

By hereby closing this issue, I accept this delivery. Any updates to fix vampire teeth will be gratefully received.
