### ISSUE TITLE
Extrapolation pattern?

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#682]
GSF Extrapolatelor routine v1.0

Note: each of 39 source locations currently are populated with designed widths and weights of ROND000, ROND001 and ROND100. All 13 source locations of opsz18 are fully populated with 9 sources including the Grades of Sharp and Round

From (sources designed manually)
OPSZ18-wdht100-wght400-rond000-grade00 and
OPSZ18-wdht100-wght400-rond000-grade50
OPSZ6-wdht100-wght400-rond000-grade00
To (sources to be extrapolated from the “From”s)
OPSZ6-wdht100-wght400-rond000-grade50

From
OPSZ18-wdht100-wght400-rond000-grade00 and
OPSZ18-wdht100-wght400-rond000-grade-50
OPSZ6-wdht100-wght400-rond000-grade00
To
OPSZ6-wdht100-wght400-rond000-grade-50

Loop replace ROND000 with ROND001
Loop replace ROND000 with ROND100

Loop all replacing opsz18 with opsz144

Note: this produces 27 complete sources

Loop all of all above replacing:
Wght400 with wght1
Wght400 with wght1000

Note: this produces 54 complete sources

Loop all of all of all the above replacing:
Wdth100 with wdth151
Wdth100 with wdth85
Wdth100 with wdth50 and then with
Wdth100 with wdth25

Note:  this produces 116 complete sources

Note of importance:  when extrapolating and GRAD-50 or +50
If wght = 400, use GRAD to -50 and +50 to extrapolate the respective +/- grades.
If wght = 100, use GRAD -0 and +50 to extrapolate the respective +/- grades.
If wght = 1000, use GRAD to -50 and use +0 to extrapolate the respective +/- grades.

That’s what I think.

**Comment by octaviopardo** [comment]
Hi David, thanks a lot. This is awesome. As you can imagine I have millions of questions, not so many related with the extrapolator but also about the things you ve been mentioning here that sneak peak your process. Apologies if I make you repeat info, but I m not sure I ve followed your process that close
- "39 source locations": Currently there are 42. Does that mean you are killing the 17.999? They are not needed anymore?
- "13 source locations of opsz18": aren't they 15? Which ones are you removing from the current designspace?
- Regarding the 9 sources of a location, Do you consider the italic (and its related styles) in this 9 sources? I remember in the turboglyphs presentation there was only one red square for the sharp in each location, but the sharp styles are two, upright and italic, right? Or do you mean that its required 9 sources for the upright and 9 sources for the italic?

Regarding the extrapolator I m not sure I follow yet what you mean but I think here 
Loop all of all of all the above replacing:
Wdth400 with wdth151
Wdth400 with wdth85
Wdth400 with wdth50 and then with
Wdth400 with wdth25

you mean
Loop all of all of all the above replacing:
Wdth100 with wdth151
Wdth100 with wdth85
Wdth100 with wdth50 and then with
Wdth100 with wdth25

I have many more questions but I need more information first to understand better this part :)

**Comment by MariannaPaszkowska** [comment]
outdated as we defined the source structure for v2.0
