### ISSUE TITLE
Define glyph list for v2/v2.1

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#684]
Following #587 "Define glyph list for v1.2) I'm starting a new issue to discuss the glyph list (+ feature list) for the following release, which I guess is v2 or even v2.1 :) 

In shifting to defining projects based on language support, we need to map those languages to glyph sets + feature sets, and shaperglot is the tool for this that all GS contributors should contribute to :) 

And these languages are in turn based on countries that Google sells devices in, which is publicly listed at https://support.google.com/store/answer/2462844 and lists 26 countries across all products:

1. Australia
2. Austria
3. Belgium
4. Brazil
5. Canada
6. Denmark
7. Finland
8. France
9. Germany
10. Ireland
11. Italy
12. Japan
13. Mexico
14. Netherlands
15. New Zealand
16. Norway
17. Portugal
18. Puerto Rico
19. Singapore
20. South Korea
21. Spain
22. Sweden
23. Switzerland
24. Taiwan
25. United Kingdom
26. United States

I believe this sorts into 2 groups, of Latin - (edit) where the only language missing I can see from the list in the comment above is **Maori** - and of Non-Latin, which is CJK and **Tamil**.

(I guess we might still be missing some secondary languages, like American indigenous ones, regional variants like American vs European English/Spanish/Portuguese, Norwegian/Sámi, although we do have Swiss German, etc.)

So! We have as a stretch goal for v2 at EOY an extended glyph set compared to v1, so I think it would be good when @MariannaPaszkowska is back (or @chrissimpkins if you have time to do it before) to confirm shaperglot profiles for everything (in both groups), and then list out any gap between v1 and those shaperglot results; and look into what I've missed off the top of my head in the list above.

**Comment by davelab6** [comment]
Latest info: 

What the fonts needed to support in v1.002, that shipped last week - if anything _isn't_ supported, we should identify that ASAP =)

* English
* Irish
* French
* German
* Dutch
* Norwegian
* Danish
* Swedish
* Italian
* Spanish
* Portuguese
* Dutch (Flemish)
* German (Austrian)
* German (Swiss)

These would the stretch goal targets:
* Polish
* Czech

And then those 2 and these:
* Slovakian
* Slovenian
* Romanian
* Hungarian
* Latvian
* Lithuanian
* Estonian
* Finnish
* Hungarian

Then:
* Greek
* Cyrillic (Bulgarian)

And then:
* Arabic (Gulf)
* Turkish (Latin)
* Hebrew

**Comment by MariannaPaszkowska** [comment]
Hey Dave! Good news, our v1.002 is compatible with all language requirements, including the ones planned for October and January 2024. That also includes Turkish (Latin), scheduled here for January 2025. 

Rest assured, by October 2024, we'll make sure to have Greek and Cyrillic (Bulgarian) ready. And by January 2025, we'll also have Arabic (Gulf) and Hebrew all set and good to go.

Currently, we support 271 of 533 languages that use Latin. Here are the languages that were included in our goal list for v1.002. The languages that are on your list are in bold @davelab6:
Basque	eus
Catalan	cat
Croatian	hrv
**Czech	ces**
**Danish	dan**
**Dutch	nld**
**Flemish nld** The Flemish alphabet is identical to the Dutch alphabet and has the same ISO 639-2 code
**English	eng**
**Estonian est**
**Finnish	fin**
**French	fra**
Galician	glg
**German	deu**
**German Austrian deu** The Austrian alphabet is identical to the German alphabet and has the same ISO 639-2 code
**Hungarian	hun**
Icelandic	isl
**Irish	gle**
**Italian	ita**
**Latvian lav**
**Lithuanian	lit**
Malaysian	zlm
**Norwegian	nor**
**Polish	pol**
**Portuguese	por**
**Romanian	ron**
**Slovak	slk**
**Slovenian	slv**
**Spanish	spa**
**Swedish	swe**
**Swiss German	gsw** 
**Turkish	tur**
Welsh	cym

**Comment by MariannaPaszkowska** [comment]
We also include Southern Sami (sma), but we should add Maori to the v2.0 goals.

**Comment by MariannaPaszkowska** [comment]
#693

**Comment by chrissimpkins** [comment]
@davelab6 Will you please expand on what you mean by "landing"?  My sense is that you are indicating annual (October) and quarterly releases (January?)?  I'd be happy to look into the schedule for font development deliveries to hit any targets.

**Comment by chrissimpkins** [comment]
@MariannaPaszkowska Great job on this lang support review!  It's good to hear how much we have covered already.  Before we commit to any landing schedules, let's understand what is currently funded, what requires annual budget decisions, and the timeframes required to ship into the target prod environments. We likely need to have font development wrapped by December 2023/early January 2024.  And there are a number of discussions in progress about capacity to roll out script-specific brand family updates.  Let's discuss these issues with Dave and then we'll come back to this thread to plan the release targets for other locales.

**Comment by davelab6** [comment]
I did more digging and there's internal localization prioritization.

**Comment by chrissimpkins** [comment]
Full set of v1.2 languages based on Hyperglot analysis:

- Acheron
- Achinese
- Afar
- Afrikaans
- Alekano
- Amahuaca
- Amarakaeri
- Amis
- Anaang
- Andaandi, Dongolawi
- Anuta
- Aragonese
- Arbëreshë Albanian
- Asháninka
- Ashéninka Perené
- Balinese
- Basque
- Batak Dairi
- Batak Karo
- Batak Mandailing
- Batak Simalungun
- Batak Toba
- Bemba (Zambia)
- Bena (Tanzania)
- Bikol
- Bislama
- Borana-Arsi-Guji Oromo
- Bosnian
- Breton
- Buginese
- Candoshi-Shapra
- Caquinte
- Caribbean Hindustani
- Cashibo-Cacataibo
- Catalan
- Cebuano
- Central Aymara
- Central Kurdish
- Chamorro
- Chavacano
- Chiga
- Chiltepec Chinantec
- Chokwe
- Chuukese
- Cimbrian
- Cofán
- Cook Islands Māori
- Cornish
- Corsican
- Creek
- Crimean Tatar
- Croatian
- Czech
- Danish
- Dehu
- Dutch
- Eastern Arrernte
- Eastern Oromo
- English
- Faroese
- Fijian
- Filipino
- Finnish
- French
- Friulian
- Gagauz
- Galician
- Garifuna
- German
- Gheg Albanian
- Gilbertese
- Gooniyandi
- Guadeloupean Creole French
- Gusii
- Haitian
- Hani
- Hiligaynon
- Hopi
- Huastec
- Hungarian
- Hän
- Icelandic
- Iloko
- Indonesian
- Irish
- Istro Romanian
- Italian
- Ixcatlán Mazatec
- Jamaican Creole English
- Javanese
- K'iche'
- Kabuverdianu
- Kalaallisut
- Kalenjin
- Kaonde
- Karelian
- Kashubian
- Kekchí
- Kenzi, Mattokki
- Khasi
- Kimbundu
- Kinyarwanda
- Kituba (DRC)
- Kongo
- Konzo
- Kven Finnish
- Kölsch
- Ladin
- Ladino
- Latgalian
- Lithuanian
- Lombard
- Low German
- Lower Sorbian
- Luba-Lulua
- Luo (Kenya and Tanzania)
- Luxembourgish
- Macedo-Romanian
- Makonde
- Malagasy
- Malaysian
- Maltese
- Manx
- Maore Comorian
- Maori
- Mapudungun
- Marshallese
- Matsés
- Mauritian Creole
- Meriam Mir
- Meru
- Minangkabau
- Mohawk
- Montenegrin
- Munsee
- Murrinh-Patha
- Mwani
- Mískito
- Naga Pidgin
- Ndonga
- Neapolitan
- Ngazidja Comorian
- Niuean
- Nobiin
- Nomatsiguenga
- North Ndebele
- Northern Kurdish
- Northern Qiandong Miao
- Northern Uzbek
- Norwegian
- Nyankole
- Occitan
- Ojitlán Chinantec
- Orma
- Oroqen
- Palauan
- Pampanga
- Papantla Totonac
- Papiamento
- Pedi
- Picard
- Pichis Ashéninka
- Piemontese
- Pijin
- Pintupi-Luritja
- Pipil
- Pohnpeian
- Polish
- Portuguese
- Potawatomi
- Purepecha
- Quechua
- Romanian
- Romansh
- Rotokas
- Rundi
- Samoan
- Sango
- Sangu (Tanzania)
- Saramaccan
- Sardinian
- Scots
- Scottish Gaelic
- Sena
- Seri
- Seselwa Creole French
- Shawnee
- Shipibo-Conibo
- Shona
- Sicilian
- Silesian
- Slovak
- Slovenian
- Soga
- Somali
- Soninke
- South Ndebele
- Southern Aymara
- Southern Qiandong Miao
- Southern Sami
- Southern Sotho
- Spanish
- Sranan Tongo
- Standard Estonian
- Standard Latvian
- Standard Malay
- Sundanese
- Swahili
- Swedish
- Swiss German
- Tagalog
- Tahitian
- Tedim Chin
- Tetum
- Tetun Dili
- Tok Pisin
- Tokelau
- Tonga (Tonga Islands)
- Tonga (Zambia)
- Tosk Albanian
- Tumbuka
- Turkish
- Turkmen
- Tzeltal
- Tzotzil
- Uab Meto
- Upper Guinea Crioulo
- Upper Sorbian
- Venetian
- Veps
- Võro
- Walloon
- Waray (Philippines)
- Warlpiri
- Wayuu
- Welsh
- West Central Oromo
- Western Abnaki
- Western Frisian
- Wiradjuri
- Xhosa
- Yanesha'
- Yao
- Yucateco
- Zapotec
- Zulu
- Záparo

**Comment by MariannaPaszkowska** [comment]
Updated targeted language list for : 

Basque | eu | eus 
Catalan | ca | cat
Croatian | hr | hrv
Czech | cs | ces
Danish | da | dan
Dutch and Flemish | nl | nld
English | en | eng
Estonian | et | est
Filipino | - | fil 
Finnish | fi | fin
French | fr | fra
Galician | gl | glg
German | de | deu
Hungarian | hu | hun
Icelandic | is | isl
Irish | ga | gle
Italian | it | ita
Indonesian | id | ind
Latvian | lv | lav
Lithuanian | lt | lit
Malaysian | ml |  zlm
Maori | mi | mri
Norwegian | no | nor
Polish | pl | pol
Portuguese | pt | por
Romanian | ro | ron
Slovak | sk | slk
Slovenian | sl | slv
Southern Sami | - | sma
Spanish | es | spa
Swedish | sv | swe
Swiss German | - | gsw
Turkish | tr | tur
Welsh | cy | cym

**Comment by MariannaPaszkowska** [comment]
I confirm that the font fully supports those language targets. Checked with Shaperglot and Hyperglot. Checked data: https://github.com/googlefonts/googlesans-flex/pull/813
