### ISSUE TITLE
[fontc] two glyphs with interpolation-incompatible paths

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#686]
Using patched fontc [here](https://github.com/RickyDaMa/fontc/tree/make-it-build), using unreleased norad v0.11 to allow missing instance/source names

Also using patched GS Flex [here](https://github.com/googlefonts/googlesans-flex/tree/make-fontc-build), with ROND sources moved into the same directory as others so that .fea files can be identical

---

```
[main fontc::workload ERROR] Be(GlyfFragment(eight.numerator)) failed 'eight.numerator' has interpolation-incompatible paths
[main fontc::workload ERROR] Be(GlyfFragment(nine.denominator)) failed 'nine.denominator' has interpolation-incompatible paths
```

**Comment by anthrotype** [comment]
I can build your GS Flex from `make-fontc-build` branch now using fontc from https://github.com/googlefonts/fontc/pull/385

**Comment by anthrotype** [comment]
but the fact that it builds doesn't mean that it works... In fact the gvar doesn't look good. It's almost twice as big, and doesn't behave correctly either. Will continue to investigate

**Comment by RickyDaMa** [comment]
Awesome, thanks Cosimo! I'll take a look shortly

**Comment by anthrotype** [comment]
btw I found the bug! When bulding the gvar Tuples we were appending the min/peak/max not in the correct order of fvar axes, but using the order given to us by BTreeMap<Tag, Tent>, which also explains why the deltas seemed correct but when moving the wrong slider 😄  Will file an issue/send a PR to fontc soon

**Comment by anthrotype** [comment]
also something is up with IUP optimization, I had to force disable that one as well. Would be nice to have a CLI option like fontmake/varLib have
