### ISSUE TITLE
Remove fontbakery reports from release zip archive

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#688]
Let's remove all of the data in the `out` directory from the release archive that is packaged for our GitHub repository releases.  We don't need this for distribution.

Includes the following sub-directories:

- `out/fontbakery`
- `out/proof`

IMO we could simply remove all sub-directories, including `fonts`, and package the variable font files at the root level of the zip archive.

Assigning to Jany to coordinate this on the DaMa team.  Not urgent.  We don't plan another release on this repository before late Q4.

**Comment by chrissimpkins** [comment]
Note: we *do* want to keep the QA data in our WIP commit-level build archives. This request only applies to the archives that land on the GH releases.

**Comment by belluzj** [comment]
Thanks Chris, @madig @RickyDaMa please look into this.
