### ISSUE TITLE
[fontc] use a single fea file

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/googlesans-flex#694]
```shell
$ rm -rf build/ && time target/release/fontc --source ../googlesans-flex/sources/GoogleSansFlex.designspace 
[2023-08-14T22:47:40.326681Z main fontc::workload ERROR] Fe(Features) failed Expected to match: "../googlesans-flex/sources/regular/GoogleSansFlex-opsz6-wdth25-wght1-ROND0.ufo/features.fea", "../googlesans-flex/sources/regular/ROND100/GoogleSansFlex-opsz6-wdth25-wght1-ROND100.ufo/features.fea"
Error: TasksFailed([(Fe(Features), "Expected to match: \"../googlesans-flex/sources/regular/GoogleSansFlex-opsz6-wdth25-wght1-ROND0.ufo/features.fea\", \"../googlesans-flex/sources/regular/ROND100/GoogleSansFlex-opsz6-wdth25-wght1-ROND100.ufo/features.fea\"")])
```

This occurs because GSF doesn't point to the same fea file everywhere. They are equivalent but you'd have to parse them to figure it out. Per IM with Chris lets make it use the same one.

https://github.com/googlefonts/googlesans-flex/compare/main...make-fontc-build has a fix for this, combined with some other change I'm less familiar with.

**Comment by RickyDaMa** [comment]
`make-fontc-build` only move the ROND around and adjusts feature files according, and doesn't contain any other changes. I have noticed however that there's a missing UFO / incorrect Designspace entry, so I'm looking into that now as currently it doesn't build through Python tooling 😅

**Comment by RickyDaMa** [comment]
> I have noticed however that there's a missing UFO / incorrect Designspace entry

Turns out I hadn't updated the smaller designspaces to the new UFO paths, which I've now done

**Comment by anthrotype** [comment]
> make-fontc-build only move the ROND around and adjusts feature files according, and doesn't contain any other changes.

then maybe you should open a PR to replace https://github.com/googlefonts/googlesans-flex/pull/695 ?

**Comment by RickyDaMa** [comment]
That's my intention once I've verified it works on CI :) https://github.com/googlefonts/googlesans-flex/actions/runs/5878131883
