### ISSUE TITLE
Document the build steps required to compile GS Flex fonts

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#696]
We are attempting to understand how much post-compile Python source will be required to get to the final font used for CI QA testing and releases as we begin to look into the replacement of fontmake with fontc.  Let's document the full end-to-end build process for GS Flex, including all of the steps that are required after the fontmake compile stage of the build.

Thanks!

cc @MariannaPaszkowska

**Comment by belluzj** [comment]
@RickyDaMa @madig Please look into this, thanks in avance!
