### ISSUE TITLE
tabular glyphs

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#713]
Hi, we are about to address the tabular glyphs. I would like to know if there is any specific strategy that we should be aware of. Are the tabular values synced with something else (space glyph for example or something I m missing?) How s the synced in between weights intended? I assume we cannot keep consitency along the entire weight axis due to brutal differences for example in the opsz144-wdth25 styles, but what about the rest of the font? Or are the tabular values simply harmonic for each weight and they are not synced in between the different weights?

**Comment by tiroj** [comment]
From a use perspective, maintaining a common tabular width between Regular and Bold weight instances is strongly desirable—necessary, I would say, considering the needs of documents like annual reports—, but beyond that you can probably get away with allowing it to flex to accommodate more extreme weights.

In terms of how wide the tabular width should be, this is best determined by the shape and weight of the Regular and Bold non-tabular numerals, such that medial width numerals like 3 5 6 require minimal adjustment to the tabular widths. If not already spec’d, I recommend inclusion of U+2007 FIGURE SPACE, which should be sync’d to the tabular numeral width.
