### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#720]
## Goals

- Update fontbakery, see:
  - #276
   - #716
- Use the latest toolchain for the v2 release

## Plan

1. Separate fontbakery from the rest of dependencies and always use the newest version:
    - Use f-actions/font-bakery for the CI (thanks @chrissimpkins 🤜🤛)
    - Use a separate venv in the local Makefile (or defer to the user-installed version?)
2. Update the build dependencies
3. Check failing tests
4. Regression test

**Comment by RickyDaMa** [comment]
Resolved by #722 & #721
