### ISSUE TITLE
Preferred axis order in fvar table

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#726]
What would be an ideal user-facing axis order in fvar table?

**Comment by Hoolean** [comment]
Precedent:

* **Google Sans v11.001**
  * opsz, wght, GRAD, ital*
* **Google Sans Flex v1.002**
  * wght, wdth, opsz, ROND, slnt

*only present in STAT, as there is no combined upright+italic TTF

---

@MariannaPaszkowska We will be swapping the order of opsz and wght for #731; shall we adopt:

> opsz, wdth, wght, GRAD, ROND, slnt

...for our pre-release V2 sources to see how different programs and deployment packaging behave? :)

**Comment by MariannaPaszkowska** [comment]
@Hoolean yes, let's try this out, many thanks!

**Comment by Hoolean** [comment]
@MariannaPaszkowska @chrissimpkins We have confirmed that the new order is in effect [in main](https://github.com/googlefonts/googlesans-flex/actions/runs/7196079980) for both `fvar` and `STAT`, and so this is ready for any application or deployment testing we may wish to do :)

> opsz, wdth, wght, GRAD, ROND, slnt
