### ISSUE TITLE
Create a ufoLib script for an automated burndown chart

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#73]
User story: The user gets a visual report of the progress of the font project at every new font build. It should be easy to understand which and how man glyphs are in-progress or finished. It should be in an easy-to-use format (could be a PDF).

The script will pull the UFO '[Mark Colors](https://robofont.com/documentation/tutorials/using-mark-colors/)' marks for color coding glyphs from editor sources and will report on progress using that data. 

@JeremieHornus and @justvanrossum created something like that for the GS CJK build CI (RoboCJK). Perhaps they could share their experience and offer advice? :)

CC @davelab6 @chrissimpkins

**Comment by belluzj** [comment]
Idea for implementation:
* target = when the project is done = sum(number of glyphs in each source)
* current progress for a given commit = sum(number of glyphs marked "green" in each source)

Then a script could check out each commit in turn, compute the current progress and plot a chart like so:
* x axis = time of commit
* y axis = target - current progress for the commit

The resulting curve should be going downwards and hit 0 when all glyphs are green.

@MariannaPaszkowska Is this what you have in mind?

**Comment by JeremieHornus** [comment]
Curve going downwards or upwards with the sum of glyphs actually finished could either work.
What we did previously was to include the deadline in the chart with a straight line from the begining to the goal so that the team knows if late or ahead of schedule.

**Comment by JeremieHornus** [comment]
we also included several 'status' colours (3 to 5 depending on projects) to be able to differentiate glyphs in-progress to finished ones.

**Comment by belluzj** [comment]
Sounds good, and the increases in status would count towards the goal? Like:

- target = when the project is done = sum(3 * number of glyphs in each source)
- current progress for a given commit = sum(3 if green, 2 if yellow, 1 if orange, 0 if red or no color for each glyph in each source)

**Comment by MariannaPaszkowska** [comment]
Thanks, @JeremieHornus! What was the color coding? Did you distinguish between different axes?

@belluzj What Jérémie is describing is what I think we need. We can ignore reporting for the specific glyphs for now. Can you extract deadlines from the milestones?

**Comment by JeremieHornus** [comment]
Color coding was:
- Red: started / in progress
- Orange: check 1
- Yellow: check 2
- Blue: check 3
- Green: validated

We distinguish each source, once a source is Green there is a lock mechanism that prevents further modification.

A glyph is considered finished (validated) if all its sources are Green.

**Comment by belluzj** [comment]
@MariannaPaszkowska is there a branch were there are already such colors, to help me prototype? If not I'll apply some colors myself to a couple glyphs to test a script.

**Comment by belluzj** [comment]
About getting deadlines from the milestones, maybe it's possible using a GitHub API to get the target dates, but I think it will be easier to put in a configuration file the finer details such as which glyph sets and sources (uprights/italics etc) are targeted by each milestone. I may as well put the dates in the same config file, if that's OK?

**Comment by JeremieHornus** [comment]
master branch on https://github.com/googlefonts/gs-cjk-rcjk
there is a `robocjk.status` key in the glyf's lib

**Comment by belluzj** [comment]
I don't have access to that repository. A lib key is conceptually neater than a mark color, but then do you need special editor support to set the status? Maybe you have a Robofont extension?

**Comment by JeremieHornus** [comment]
yes that's done through the robocjk extension

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins can we add @belluzj to that repository: https://github.com/googlefonts/gs-cjk-rcjk ?

**Comment by gorjious** [comment]
In case it might be useful, just wanted to share that there are Glyphs plugins by Hugo Jordan called [Color Flow](https://github.com/HugoJourdan/Color-Flow) and [Font Dashboard](https://github.com/HugoJourdan/Font-Dashboard) that make use of Layer Colors to mark progress. Hugo also has a prototype of producing an HTML progress report based on those colors.

**Comment by belluzj** [comment]
Do we want the same lib for GS Flex, or something simpler like a mark color? Because I don't know if Font Bureau are using the robocjk extension as well?

**Comment by MariannaPaszkowska** [comment]
@belluzj FB will use the color marks feature of RoboFont. Marks will be in the foreground of the glyphs.
Color code:
Green - design finished and ready for Google's review
Yellow - in progress
Red - not started
Blue - in progress and for v1.1 ()

**Comment by davelab6** [comment]
> @chrissimpkins can we add @belluzj to that repository: [googlefonts/gs-cjk-rcjk](https://github.com/googlefonts/gs-cjk-rcjk) ?

Added @madig @belluzj @gorjious 

> I don't know if Font Bureau are using the robocjk extension as well?

They are not, and while they have been using markColors already according to their own per-contributor adhoc/undefined semantics, they are ready (or will very soon be ready) to wipe the slate clean and adopt a new color scheme.

Also, I seems in RoboFont its possible to mark each layer with its own color, so a "status" layer that's empty and has a color associated may also work, if anyone has their own need for markColors with different semantics

**Comment by davelab6** [comment]
@gorjious good references, thanks! https://github.com/HugoJourdan/Color-Flow#how-it-work is insightful, indeed

![example](https://github.com/HugoJourdan/Font-Dashboard/raw/main/FontDashboard-preview.jpg)

This is a perfect example of the kind of things I'd like to have available to all projects

**Comment by davelab6** [comment]
I started a more public general discussion of this @ https://github.com/googlefonts/googlefonts.github.io/issues/63

**Comment by chrissimpkins** [comment]
@JeremieHornus do you have one of your old color coded burn up (?) charts that Marianna might see so that she understands how you tracked progress across your team?

**Comment by JeremieHornus** [comment]
[hanzi-progress.pdf](https://github.com/googlefonts/googlesans-flex/files/10183990/hanzi-progress.pdf)

**Comment by MariannaPaszkowska** [comment]
Thank you, @JeremieHornus!

**Comment by madig** [comment]
Should work as of https://github.com/googlefonts/googlesans-flex/issues/73

**Comment by RickyDaMa** [comment]
Closing this issue as #76 has been merged (along with some other improvements since: #146)
