### ISSUE TITLE
Reinstate overlap bits

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#737]
We [stopped setting overlap bits](https://github.com/googlefonts/googlesans-flex/blob/main/Makefile#L28-L31) in preparation for importing the V2 sources (owing to different TTF names, and potentially different overlapping glyphs). When the V2 sources are in `main`, we should restore them.

**Comment by Hoolean** [comment]
@MariannaPaszkowska As promised, here are the overlapping glyph lists we used for the v1.002 sources in [upright](https://github.com/googlefonts/googlesans-flex/blob/v1.002/sources/regular/glyphs-with-overlap.txt) and [italic](https://github.com/googlefonts/googlesans-flex/blob/v1.002/sources/italic/glyphs-with-overlap.txt) respectively 📝  (for extra context, from my understanding these were arrived at from discussion on #382)

**Comment by chrissimpkins** [comment]
@MariannaPaszkowska reminder that we need to do this as part of the prod work.  I added this to the v2 prod milestone

**Comment by MariannaPaszkowska** [comment]
@Hoolean for automated ways, we could look into the logic here: https://github.com/schriftgestalt/Glyphs-Google/tree/main/Georgs%20Flex/Cleanup

**Comment by belluzj** [comment]
(discussed in meeting) the idea from the logic there from Georg is to detect and remove points that are on top of each other.

Because these overlaid points are a common cause of false positives for setting the overlap bit, we could modify the process to set the overlap bit as such:
* first, remove overlaid points (using Georg's code)
* second, detect overlaps as usual (and we will only detect "real" overlaps as we're removed the causes for false positives).

However this idea is not the best solution, and @Hoolean will explain below why

**Comment by Hoolean** [comment]
Hello yes! We carried on the discussion a little :)

Having talked more, I think using the clean-up script will remove some of the false-positives but not all of them, as some overlapping points are necessary to keep. In the original thread, @anthrotype [suggested comparing by area](https://github.com/googlefonts/googlesans-flex/issues/382#issuecomment-1440268268) instead:

e.g. new pseudocode:

```python
for glyph in glyphs:
    for layer in layers:
        if layer.area() != layer.simplify().area():  # dependent on how library handles 'hidden' area
            glyph has overlapping area
```

...which would trim the false-positives from the previous approach:

```python
for glyph in glyphs:
    for layer in layers:
        if layer != layer.simplify():
            glyph has overlapping area OR POINTS
```

I need to re-read the issue in full though, as there may be a reason we did not pursue this before. It may be that we did not have full confidence that it would catch every issue with stroke, or that Skia could not measure 'hidden' area, or it may just be that we arrived at a manual list first.

**Comment by Hoolean** [comment]
Some extra thoughts:

- If we used the clean-up script to temporarily remove **every** overlapping point, ignoring compatibility, then we could use it to remove all false-positives in the previous approach
- Neither approach would catch overlaps that occur only when interpolating between sources; I am unsure how common this is

**Comment by anthrotype** [comment]
> 'hidden' area

what do you mean by that?

**Comment by Hoolean** [comment]
> what do you mean by that?

For the area to differ pre- and post- simplifying then the library we use for calculating it would need to count the overlapped area twice:

![Glyph with overlapping area highlighted](https://github.com/googlefonts/googlesans-flex/assets/2150762/a7c2e649-d834-4f91-9ce0-2dd7e4532309)

Maybe we do not need to worry about this if we sum per-contour areas though... I need to think it through in a bit more depth 🔎

**Comment by anthrotype** [comment]
it does not need to count it _twice_, the signed area of a closed path is calculated for each subpath individually

**Comment by anthrotype** [comment]
this is already the case, you don't need to do anything, pathops or even fonttools AreaPen already do what you think is right

**Comment by anthrotype** [comment]
on the other hand, only checking that the areas match before/after simplify may not be sufficient because you may incur in a false positive, e.g. if a glyph has two non overlapping contours each having different directions, because the formula computes the _signed_ area, contours with negative area will be subtracted; simplify() will "fix" the contour directions for the outer-most contours hence the total sum after simplify will be greater (comprise only additions of per-contour areas, no subtractions). While the original glyph didn't contain overlapping contours, the signed area did change after simplify.

However, as far as I know, fixing the contours direction can only be done safely after simplifying them (which is what skia-pathops does), so that you're left with either fully distinct sub-paths (same direction) or sub-paths that are fully inside others (with direction reversed).

**Comment by anthrotype** [comment]
> overlaps that occur only when interpolating between sources

there's no automatic solution for those, unless you want to try sampling the variation space at intervals but the combinations of all these axis steps gets unwieldy quickly as the number of axes increase

**Comment by anthrotype** [comment]
In case you weren't aware, ufo2ft now supports setting the overlap flags directly in the sources (via https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#publictruetypeoverlap) so you don't need the post-processing script if you wish to specify them manually.

**Comment by MariannaPaszkowska** [comment]
@schriftgestalt is it possible to set the overlap flags manually in the glyph sources?

**Comment by MariannaPaszkowska** [comment]
Meanwhile, here is my list of glyphs that need overlap:

```
numbersign
dollar
cent
currency
Euro
ampersand
plus
four
six
eight
nine
A
B
E
F
G
H
K
P
Q
R
T
X
Y
a
e
f
g
k
t
s
x
y
sterling
yen
section
ordfeminine 
registered
plusminus
onequarter
threequarters
Agrave
Aacute
Acircumflex
Atilde
Adieresis
Aring
AE
Ccedilla
Egrave
Eacute
Ecircumflex
Edieresis
Eth
multiply
Oslash
Yacute
Thorn
agrave
aacute
acircumflex
atilde
adieresis
aring
ae
ccedilla
egrave
eacute
ecircumflex
edieresis
eth
oslash
yacute
ydieresis
uni2074 / foursuperior 
f_i
f_f
f_f_i
f_f_l
OE
oe
Ecaron
ecaron
Rcaron
Tcaron
tcaron
Ydieresis
Edotaccent
edotaccent
Iogonek
iogonek
Uogonek
uogonek
Aogonek
aogonek
Eogonek
eogonek
Dcroat
dcroat
Emacron
emacron
Lslash
lslash
Abreve
abreve
uni0219 / scommaaccent
uni021A / Tcommaaccent
uni021B / tcommaaccent
uni0162 / Tcedilla
uni0163 / tcedilla
Scedilla
scedilla
Racute
racute
Ecaron
ecaron
Amacron
amacron
Emacron
emacron
uni0122 / Gcommaaccent
uni0123 / gcommaaccent
uni0136 / Kcommaaccent
uni0137 / kcommaaccent
Ycircumflex
ycircumflex
Gbreve
gbreve
Dcroat
dcroat
graterequal
lessequal
notequal
e.logo
Google.logo
l.logo
f_f
f_f_i
f_f_l
four.denominator
trademark
uni01CE / abreve  
uni01CD / Abreve  
gdotaccent
Gdotaccent
hbar
Hbar
uni0157 / Rcommaaccent
uni0156 / rcommaaccent
Ygrave
flig2
flig1
flig3
_registeredR
rcaron
sacute
scaron
ygrave
Acaron
acaron
section.tf
percent.tf
lessequal.tf
greaterequal.tf
plusminus.tf
notequal.tf
multiply.tf
plus.tf
divide.tf
sterling.tf
Euro.tf
dollar.tf
currency.tf
cent.tf
numbersign.tf
aogonek.alt
ae.alt
g.alt
gbreve.alt
gcommaaccent.alt
gdotaccent.alt
zeroslash
zeroslash.tf
foursubscript
foursuperscript
four.numerator
micro
mu
```

excluded: 
divide, colon, semicolon, superiors exempt four—this is because the design in the heavy styles changed and no longer overlaps

**Comment by behdad** [comment]
The area approach works best IMO. I suggest using `areaPen` instead of Skia-based area. Also, add room for some small tolerance.

**Comment by anthrotype** [comment]
> I suggest using areaPen instead of Skia-based area

when I added that, I literally ported to cython the fonttools' code from areaPen.py

https://github.com/fonttools/skia-pathops/blob/815070e964334ec6cdf453f2d859fe2db49d9b06/src/python/pathops/_pathops.pyx#L1024-L1077

**Comment by schriftgestalt** [comment]
> @schriftgestalt is it possible to set the overlap flags manually in the glyph sources?

not officially. But you can invent a userData/Lib key for it.

**Comment by anthrotype** [comment]
a lib key we already have, it's https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#publictruetypeoverlap
is it possible from Glyphs.app to set that? I suppose one could set it via some script.

**Comment by anthrotype** [comment]
I tried with a macro like this, where I select the glyphs I want to manually set the flag on and then run:

```python
for glyph in Glyphs.font.selection:
	glyph.userData["public.truetype.overlap"] = True
```

and after saving, I can see the .glyphs file contains `{"public.truetype.overlap" = 1;}` in the userData for the selected glyphs.
However when converting the .glyphs to UFOs the flags are lost and do not end up in the glyph `<lib>`, so the VF glyf table doesn't have them.
I think glyphsLib could be updated to preserve them.

**Comment by schriftgestalt** [comment]
If might work if you set it on each layer:
```
for glyph in Glyphs.font.selection:
	for layer in glyphs.layers:
		layer.userData["public.truetype.overlap"] = True
```
