### ISSUE TITLE
TD review of GS Flex Alpha1.0 Roman

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#74]
Here's the review of GSF Roman, GRAD0 and ROND0, ascii set. Font GoogleSansFlex-Alpha1.0[ROND,opsz,wdth,wght]-VF.ttf from [here.](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/fonts/GoogleSansFlex-Alpha1.0%5BROND%2Copsz%2Cwdth%2Cwght%5D-VF.ttf)

**Review request:** https://github.com/FontBureau/fb-GoogleSansFlex/issues/79 

- [x]  **opsz 6, wdth 100, wght 400**
<img width="548" alt="Screenshot 2022-12-07 at 5 41 45 PM" src="https://user-images.githubusercontent.com/22956348/206223899-9fdb1d5b-cfac-4f72-9153-7a6878b94116.png">

https://videoproof.graphicore.de/#2022-12-07T13:44:29Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;10;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6;1;6;0;l;;opsz6;1;6;0;l;;@v2:typespec

- [x]   **opsz 6, wdth 100, wght 1**
**Feedback:** the `comma ,` might be a touch too heavy; please double check. 
<img width="545" alt="Screenshot 2022-12-07 at 5 41 06 PM" src="https://user-images.githubusercontent.com/22956348/206223753-06eae77b-4460-4342-a045-49af9ac3be2a.png">

https://videoproof.graphicore.de/#2022-12-07T14:03:00Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;3;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wght1;1;6;0;l;;opsz6,wght1;1;6;0;l;;@v2:typespec

- [x] #81
**Feedback:** 
- Please revisit `5`, it needs a bit more space between the bowl and the horizontal bar. Perhaps the bar is too heavy. 
- `i` needs more space between the dot and the stem. 
- `G` - horizontal bar gets lost in small sizes. Needs optical correction. 
- `,` - comma looks too light. 
<img width="546" alt="Screenshot 2022-12-07 at 5 40 23 PM" src="https://user-images.githubusercontent.com/22956348/206223506-da127c7f-f36b-471b-95cc-199aeea6e017.png">

https://videoproof.graphicore.de/#2022-12-07T14:58:40Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wght1000;1;6;0;l;;opsz6,wght1000;1;6;0;l;;@v2:typespec

- [x]  **opsz 6, wdth 25, wght 400**

<img width="519" alt="Screenshot 2022-12-07 at 5 43 07 PM" src="https://user-images.githubusercontent.com/22956348/206224284-aa7394f8-dd05-4b28-872d-058d32fd149d.png">

https://videoproof.graphicore.de/#2022-12-07T15:01:48Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wdth25;1;6;0;l;;opsz6,wdth25;1;6;0;l;;@v2:typespec 

- [x]  **opsz 6, wdth 25, wght 1**
<img width="555" alt="Screenshot 2022-12-07 at 5 43 44 PM" src="https://user-images.githubusercontent.com/22956348/206224427-c43b54cd-60ea-40a0-91c8-21af7fbdca5a.png">

https://videoproof.graphicore.de/#2022-12-07T15:43:24Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;3;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wdth25,wght1;1;6;0;l;;opsz6,wdth25,wght1;1;6;0;l;;@v2:typespec

- [x] #82
**Feedback:** 
- `i` - dot and the stem are closing up, please revise.
- `2` `4` `5` - look too heavy; please review. 
- `3` - the contrast in the top bowl needs refinement
<img width="551" alt="Screenshot 2022-12-07 at 5 44 05 PM" src="https://user-images.githubusercontent.com/22956348/206224509-22dd49cd-0eb5-4db9-9954-30dfc23f0986.png">

https://videoproof.graphicore.de/#2022-12-07T15:33:38Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wdth25,wght1;1;6;0;l;;opsz6,wdth25,wght1000;1;6;0;l;;@v2:typespec

- [x] #83
Feedback:
- `z` - might be too slightly heavy; please check.
- `e` `c` - spacing might be too tight on the right; please check.
- `U` - spacing might be too loose; please check.
https://videoproof.graphicore.de/#2022-12-07T17:48:59Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;3;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wdth151;1;6;0;l;;opsz6,wdth151;1;6;0;l;;@v2:typespec 

<img width="707" alt="Screenshot 2022-12-07 at 7 49 26 PM" src="https://user-images.githubusercontent.com/22956348/206256741-e724ad49-8e4d-4289-8032-b9030e481f85.png">

- [x]  **opsz 6, wdth 151, wght 1**
https://videoproof.graphicore.de/#2022-12-07T17:49:56Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wdth151,wght1;1;6;0;l;;opsz6,wdth151,wght1;1;6;0;l;;@v2:typespec
<img width="716" alt="Screenshot 2022-12-07 at 7 50 04 PM" src="https://user-images.githubusercontent.com/22956348/206256941-5fad57ae-fe2d-4251-8a95-b33cd056e28b.png">

- [x] #84
- `O` `o` - contrast looks slightly reversed. Please check. 
- `a` - arch and the top of the bowl are closing up; please revise.  
https://videoproof.graphicore.de/#2022-12-07T17:50:54Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;40;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;opsz6,wdth151,wght1000;1;6;0;l;;opsz6,wdth151,wght1000;1;6;0;l;;@v2:typespec

<img width="670" alt="Screenshot 2022-12-07 at 7 51 07 PM" src="https://user-images.githubusercontent.com/22956348/206257367-ecce37ab-ffb4-43e2-9620-945d288ceddc.png">

- [x]  **opsz 18, wdth 100, wght 400**
<img width="1508" alt="Screenshot 2022-12-07 at 11 48 05 PM" src="https://user-images.githubusercontent.com/22956348/206303699-66f0ff5a-1e6b-449c-9a52-ad06bec77362.png">
https://videoproof.graphicore.de/#2022-12-07T21:47:43Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;90;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;;1;18;0;l;;;1;18;0;l;;@v2:typespec

- [x] #85
**Feedback** 
- Punctuation looks heavier than the rest of the characters: `,` `.` `:` `;` 
- the dot looks heavier in `i` and its siblings, 
- the dot looks heavier in `?` `!`
- `S``$` - needs to be a more continuous ogee curve. Perhaps the top and bottom need more balancing.
- <img width="42" alt="Screenshot 2022-12-08 at 2 38 18 PM" src="https://user-images.githubusercontent.com/22956348/206448355-ed7fdb5d-8821-4584-9aa7-4321b2ad95de.png">
<img width="58" alt="Screenshot 2022-12-08 at 2 46 59 PM" src="https://user-images.githubusercontent.com/22956348/206450194-dac3ed81-a466-4179-8a95-287f3a832875.png">

<img width="1504" alt="Screenshot 2022-12-07 at 11 48 59 PM" src="https://user-images.githubusercontent.com/22956348/206303831-2b42ced8-c5b4-4808-843a-0eff359f8b40.png">

- [x] #86
**Feedback** 
- `?` - dot and the stem might be slightly too close. Please revise.  
- Uppercase looks slightly too heavy. The difference is more visible than in the other weights. Please double-check.
<img width="1209" alt="Screenshot 2022-12-07 at 11 55 47 PM" src="https://user-images.githubusercontent.com/22956348/206305006-0a9fb8e8-5c35-4253-b564-7c5e31f58409.png">
<img width="1166" alt="Screenshot 2022-12-07 at 11 56 30 PM" src="https://user-images.githubusercontent.com/22956348/206305119-e7823c71-2538-4e29-b969-106d01073df6.png">

https://videoproof.graphicore.de/#2022-12-07T21:55:14Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;90;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;wght1000;1;18;0;l;;wght1000;1;18;0;l;;@v2:typespec

- [x] #87
**Feedback** 
- `M` and `N` might be slightly too heavy, please revisit.  
<img width="1011" alt="Screenshot 2022-12-07 at 11 58 58 PM" src="https://user-images.githubusercontent.com/22956348/206305561-7df7ceb3-b8d4-4fe8-90a1-1e2d41531ce8.png">

- [x] #88
**Feedback** 
- Punctuation looks heavier than the rest of the characters: `,` `.` `:` `;` 
- the dot looks heavier in `i` and its siblings, 
- the dot looks heavier in `?` `!`.
<img width="1002" alt="Screenshot 2022-12-08 at 12 02 45 AM" src="https://user-images.githubusercontent.com/22956348/206306203-88765c73-651e-4c7c-97df-6583252fb2e5.png">
https://videoproof.graphicore.de/#2022-12-07T22:02:19Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;90;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;wdth25,wght1;1;18;0;l;;wdth25,wght1;1;18;0;l;;@v2:typespec

- [x] #89
**Feedback** 
- `Z` looks slightly heavier than other characters.
- `2` looks slightly heavier than other characters.
<img width="1000" alt="Screenshot 2022-12-08 at 12 04 37 AM" src="https://user-images.githubusercontent.com/22956348/206306532-d5d653d2-8b96-44e5-b5ce-1d3760cedfb2.png">
<img width="1015" alt="Screenshot 2022-12-08 at 12 05 48 AM" src="https://user-images.githubusercontent.com/22956348/206306730-372072b0-3027-4e7c-9abe-386da6064dc0.png">

- [x] #90
- **Feedback** 
- `G` `O` `o` - look like those have a slightly reversed contrast. Please revisit. 
- `g` - the bottom half of the bowl looks thinner, and the contrast is slightly reversed
- `f` - bar looks short on the right side. Is this intentional? 
- `f` `t` - horizontal bar looks slightly too heavy. Please check. 
- `z` `Z` - looks slightly too heavy. Please check. 
- `a` `s` `S` `$` - contrast and shapes need refinement. Please revisit. 
<img width="88" alt="Screenshot 2022-12-08 at 2 15 38 PM" src="https://user-images.githubusercontent.com/22956348/206444219-f2ef0729-c45c-477d-97f9-2e3a766570f6.png">
<img width="49" alt="Screenshot 2022-12-08 at 2 20 04 PM" src="https://user-images.githubusercontent.com/22956348/206444933-c6854f72-5dff-4c7a-b11f-78de9eddacdb.png">
<img width="33" alt="Screenshot 2022-12-08 at 2 20 21 PM" src="https://user-images.githubusercontent.com/22956348/206444984-1caa8bc8-82b7-43bf-9cf7-ce01076f6491.png">
<img width="56" alt="Screenshot 2022-12-08 at 2 24 02 PM" src="https://user-images.githubusercontent.com/22956348/206445638-95cca142-b350-43b5-b02c-47d36163e8c2.png">

https://videoproof.graphicore.de/#2022-12-08T12:03:17Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;101;;11;5;4;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;wdth151;1;18;0;l;;wdth151;1;18;0;l;;@v2:typespec

<img width="1095" alt="Screenshot 2022-12-08 at 2 03 54 PM" src="https://user-images.githubusercontent.com/22956348/206442117-eadb529b-9011-4765-9224-1d57792171f1.png">
<img width="1188" alt="Screenshot 2022-12-08 at 2 05 50 PM" src="https://user-images.githubusercontent.com/22956348/206442439-5688f8c0-3538-471f-b91b-1ac05102c9e7.png">

- [x] #91
**Feedback** 
- Punctuation looks heavier than the rest of the characters: `,` `.` `:` `;` 
- the dot looks heavier in `i` and its siblings, 
- the dot looks heavier in `?` `!`.
- top of the vertical bar in `$` looks small. Please check. 
- `S` `$` - needs to be a more continuous ogee curve. Perhaps the top and bottom need more balancing.
<img width="83" alt="Screenshot 2022-12-08 at 2 37 02 PM" src="https://user-images.githubusercontent.com/22956348/206447968-771c4811-2306-4bcf-9b12-d1ffabfbb97b.png">
<img width="72" alt="Screenshot 2022-12-08 at 2 38 51 PM" src="https://user-images.githubusercontent.com/22956348/206448332-a6578471-0180-4fa8-b95d-5e59b8538e9f.png">

<img width="1014" alt="Screenshot 2022-12-08 at 2 33 28 PM" src="https://user-images.githubusercontent.com/22956348/206447472-bf2c7cb2-a4f1-4977-b23b-44482ed16561.png">

https://videoproof.graphicore.de/#2022-12-08T12:28:12Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;111;;11;5;3;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;wdth151,wght1;1;18;0;l;;wdth151,wght1;1;18;0;l;;@v2:typespec

- [x] #92
**Feedback** 
- `%` looks lighter than the other characters. 
- `5` top bar and the belly might be slightly too close.
- `ea` mismatch in colour, `a` looks slightly too light.
- `Y` - contrast is too high, looks lighter than the other characters. 
<img width="194" alt="Screenshot 2022-12-08 at 12 12 25 AM" src="https://user-images.githubusercontent.com/22956348/206307872-0d5162d6-9cf8-4c83-a636-9f9f0eb65c24.png">

- uppercase is heavier compared with lowercase. The difference is more visible than in the other weights. 
<img width="201" alt="Screenshot 2022-12-08 at 12 10 23 AM" src="https://user-images.githubusercontent.com/22956348/206307498-c39f6232-ecd1-457d-905d-adee72fbe742.png">

<img width="1122" alt="Screenshot 2022-12-07 at 10 41 40 PM" src="https://user-images.githubusercontent.com/22956348/206291118-941bf430-7c0a-4f1a-bfe8-d9478cbe702b.png">

https://videoproof.graphicore.de/#2022-12-07T20:41:18Z;GoogleSansFlex%20opsz18-wdth100-wght400-ROND0,Version%205.000;;;90;;11;5;3;opsz64;1;64;0;l;;opsz25;1;25;0;l;;;1;18;0;l;;wdth151,wght1000;1;18;0;l;;wght1000;1;18;0;l;;@v2:typespec

- [x] #93
**Feedback**
- `S` - please revise the contrast around the bottom and the outstroke.
<img width="164" alt="Screenshot 2022-12-08 at 4 04 26 PM" src="https://user-images.githubusercontent.com/22956348/206466173-af83d59b-f10d-44cf-b706-79a730c59310.png">
- `Y` - contrast looks slightly reversed (right arm). Please revise.
<img width="175" alt="Screenshot 2022-12-08 at 4 04 54 PM" src="https://user-images.githubusercontent.com/22956348/206466142-b0ba6b05-a625-4c93-86a8-695e16b4844b.png">
- `s` - please revise. Green arrow: slightly too square when compared with GS. 
<img width="300" alt="Screenshot 2022-12-08 at 4 15 09 PM" src="https://user-images.githubusercontent.com/22956348/206468718-7b887710-be28-4fc9-a76a-056ca6b1563b.png">
- `@` - please review the flattening on the top right of the ring. 
<img width="419" alt="Screenshot 2022-12-08 at 4 17 05 PM" src="https://user-images.githubusercontent.com/22956348/206469210-dbfc93c7-ba8e-4150-87be-6d315f00f787.png">

- [x] #103

Note for later: It seems that rasterizer (review done in Chrome v108.0.5359.94) has issues drawing the outlines so thin. The thinnest value of wght where I didn't see issues for opsz 144, wdth 100 was 20.
<img width="1131" alt="Screenshot 2022-12-08 at 4 23 38 PM" src="https://user-images.githubusercontent.com/22956348/206470914-580315ee-7df6-4e52-81fb-7835e2fc26d0.png">

- [x] #94
**Feedback**
- p - please revisit the roundness of the bowl.
<img width="234" alt="Screenshot 2022-12-08 at 4 52 44 PM" src="https://user-images.githubusercontent.com/22956348/206478092-cf7701f4-ae1c-498c-ac36-9fe45b84b8fd.png">
- `C` `G` `S` `a` `c` `e` : stroke endings look slightly flared (blue arrows), please refine 
- `C` `S` `a` `c` `e` `g`  - please refine the roundness (red arrows)
<img width="1075" alt="Screenshot 2022-12-08 at 5 17 24 PM" src="https://user-images.githubusercontent.com/22956348/206483724-a44c1bac-1de4-4974-b668-59440034efde.png">
- `5` - please refine the roundness of the bottom of the counter.
<img width="247" alt="Screenshot 2022-12-08 at 4 54 52 PM" src="https://user-images.githubusercontent.com/22956348/206478619-b766b154-80a1-4b0e-8ab2-6c3906604a9d.png">
- `6` - please refine the roundness of the bottom of the counter.
<img width="268" alt="Screenshot 2022-12-08 at 4 55 50 PM" src="https://user-images.githubusercontent.com/22956348/206478834-92e756a5-2dbb-4768-902c-b622b6a5e64b.png"> 
- `?` - please refine the roundness
<img width="120" alt="Screenshot 2022-12-08 at 5 21 35 PM" src="https://user-images.githubusercontent.com/22956348/206484667-0bebde24-a1a7-410d-8e25-38804210407c.png">

- [x] #100
**Feedback**
- `@` - please double-check the contrast in the ring.
<img width="130" alt="Screenshot 2022-12-08 at 5 24 54 PM" src="https://user-images.githubusercontent.com/22956348/206485477-f1a32abc-7e83-44dc-abdf-9329617d2d92.png">
- `f` - please revise the bar on the left side, is appears slightly too short. 
<img width="238" alt="Screenshot 2022-12-08 at 5 26 53 PM" src="https://user-images.githubusercontent.com/22956348/206485978-8a42820e-1233-4e81-a99b-d7b4e8072463.png">

- [x] #95
**Feedback**
- `@` - please double-check the ring. It appears backslanted. 
<img width="93" alt="Screenshot 2022-12-08 at 5 28 57 PM" src="https://user-images.githubusercontent.com/22956348/206486549-1d95a8a7-9a7b-4bc7-b777-fbc485c46e97.png">

- [x] #96
**Feedback**
- `@` - please double-check the contrast and roundness in the ring.

<img width="459" alt="Screenshot 2022-12-08 at 5 42 21 PM" src="https://user-images.githubusercontent.com/22956348/206490875-dfe7485a-2110-41d9-a408-0723b05e6fbf.png">

- `;` `,` - corner appears chipped. Please revise. 
<img width="198" alt="Screenshot 2022-12-08 at 5 31 22 PM" src="https://user-images.githubusercontent.com/22956348/206487176-032d921a-60eb-41da-a15e-fdb117966e3c.png">
<img width="174" alt="Screenshot 2022-12-08 at 5 33 09 PM" src="https://user-images.githubusercontent.com/22956348/206487761-05523aec-37b0-4015-ab79-e7e5c30b4d35.png">
- `?` `i` `j` - dot seems to be very close to the stem. Please confirm if that's intentional.
<img width="187" alt="Screenshot 2022-12-08 at 5 33 59 PM" src="https://user-images.githubusercontent.com/22956348/206488033-f32851b1-adb5-4323-968c-89a81db3cadb.png">
- `e` - revise roundness in the bottom half of the letter.
<img width="146" alt="Screenshot 2022-12-08 at 5 35 25 PM" src="https://user-images.githubusercontent.com/22956348/206488439-f53cee60-c9c5-4c04-b100-bfa9c3ef9abf.png">
- `g` - revise roundness.
<img width="277" alt="Screenshot 2022-12-08 at 5 42 00 PM" src="https://user-images.githubusercontent.com/22956348/206490742-07ee5af6-7f1b-487f-8b40-5c1d0c91c060.png">

- [x] #97
**Feedback** 
- `b` `c`  `d` `g` `h` `m` `n` `o` `p` `q` `C` `G` `O` `Q` `%` `2` `8`- have a slightly reversed contrast. 
<img width="725" alt="Screenshot 2022-12-09 at 3 41 07 PM" src="https://user-images.githubusercontent.com/22956348/206715259-c60a9f6d-0e04-49ce-93cb-100f16af54a3.png">

-  `5` `2` `3` - Please refine roundness. (`c` for reference)
<img width="589" alt="Screenshot 2022-12-09 at 3 30 18 PM" src="https://user-images.githubusercontent.com/22956348/206713255-86f2101f-1283-44d3-92c3-74fba2d5cc21.png">

-  `v` `w` `y` `V` `W` `Y` - have a slightly reversed contrast. Please revise.
<img width="428" alt="Screenshot 2022-12-09 at 2 14 21 PM" src="https://user-images.githubusercontent.com/22956348/206700334-2c85fc7f-7a3e-4192-b5c8-0044d07bd490.png">

- `S` - top is not as balanced as the bottom (`s` is only for reference)
<img width="373" alt="Screenshot 2022-12-09 at 3 23 22 PM" src="https://user-images.githubusercontent.com/22956348/206712084-240d0b94-d634-4074-9b13-c66af7e8cac2.png">

- [x] #98
**Feedback** 
- Roundness:
- `c` - Roundness, and bottom outstroke is slightly too far to the right:
<img width="152" alt="Screenshot 2022-12-08 at 6 55 11 PM" src="https://user-images.githubusercontent.com/22956348/206514818-a5666943-8333-4c6b-95e6-379d9b0e8b56.png">
- `e` - Roundness, and bottom outstroke is slightly too far to the right:
<img width="147" alt="Screenshot 2022-12-08 at 6 52 22 PM" src="https://user-images.githubusercontent.com/22956348/206514071-6c27abbb-f76f-4d55-b794-3d416a4e14ec.png">

- `S``s` `a` `$` - Please review roundness of the curves. (?23g are for reference)
<img width="1095" alt="Screenshot 2022-12-08 at 6 57 37 PM" src="https://user-images.githubusercontent.com/22956348/206515410-23743118-e319-4b3f-9fb1-b576b6e9d2cf.png">

- [x] #99
**Feedback**

`,` `;` - chipped corner, please fix:
<img width="127" alt="Screenshot 2022-12-08 at 10 03 05 PM" src="https://user-images.githubusercontent.com/22956348/206556497-7bd9cab4-c9a9-4ed7-823f-2783a4b69079.png">

- `@` - Please revise contrast in the ring.
<img width="176" alt="Screenshot 2022-12-08 at 10 03 48 PM" src="https://user-images.githubusercontent.com/22956348/206556617-b7e5a762-995e-4d3e-8c1f-2a05ebd75763.png">

- `9` - 
<img width="197" alt="Screenshot 2022-12-09 at 4 19 48 PM" src="https://user-images.githubusercontent.com/22956348/206723608-cda7d2f9-24c6-4467-9733-8bb7fc226b12.png">

- `G` - Please refine roundness of the curve in the top.
<img width="249" alt="Screenshot 2022-12-09 at 4 19 42 PM" src="https://user-images.githubusercontent.com/22956348/206723498-2e5b4982-5965-42b0-a0d0-a74ad062c9e5.png">

- `J` revise roundness in the inner counter (white space) 

<img width="279" alt="Screenshot 2022-12-09 at 4 19 29 PM" src="https://user-images.githubusercontent.com/22956348/206723319-59cb8584-9a3d-4c0e-ba90-429f556ca85d.png">

- `C`  overlapping terminals - is this intentional, is it possible we avid that here?
<img width="178" alt="Screenshot 2022-12-08 at 10 06 28 PM" src="https://user-images.githubusercontent.com/22956348/206557067-67172aad-ae07-43f0-b888-b548e999b6bd.png">

- `P`  roundness in the terminal:
<img width="198" alt="Screenshot 2022-12-08 at 10 07 20 PM" src="https://user-images.githubusercontent.com/22956348/206557210-5a957ac5-d7c4-4784-a8e9-5aa29c7dcde2.png">

- `?`
<img width="261" alt="Screenshot 2022-12-08 at 10 12 39 PM" src="https://user-images.githubusercontent.com/22956348/206558158-8f808061-8a9f-41d2-b7a3-35fff2a9eb71.png">

- `S` `a` `$` - top terminals overlap while they don't in the `s`. Is it possible to unify this for consistency? 
<img width="604" alt="Screenshot 2022-12-08 at 10 09 14 PM" src="https://user-images.githubusercontent.com/22956348/206557658-d851796d-c660-4eed-a198-b21f8df14df4.png">

-`S`  roundness
<img width="218" alt="Screenshot 2022-12-09 at 4 19 37 PM" src="https://user-images.githubusercontent.com/22956348/206723395-39f79106-24d6-406a-9d23-d46f6367448c.png">

- `a`  - roundness
<img width="299" alt="Screenshot 2022-12-09 at 4 21 57 PM" src="https://user-images.githubusercontent.com/22956348/206723437-2951f402-86c8-4961-8da2-394939f5700a.png">

- `$` - top vertical bar is shorter, please double check
<img width="164" alt="Screenshot 2022-12-08 at 10 10 52 PM" src="https://user-images.githubusercontent.com/22956348/206557867-9ef7533c-2fa9-4c84-83e3-5a2da0dad476.png">

**Sample texts:** 
```
!	"	#	$	%	&	'	(	)	*	+	,	-	.	/	0	1	2	3	4	5	6	7	8	9	:	;	<	=	>	?	@	A	B	C	D	E	F	G	H	I	J	K	L	M	N	O	P	Q	R	S	T	U	V	W	X	Y	Z	[	\	]	^	_	`	a	b	c	d	e	f	g	h	i	j	k	l	m	n	o	p	q	r	s	t	u	v	w	x	y	z	{	|	}	~
(ASCII character set)

The five boxing wizards jump quickly. Google Fonts! 
Our font catalog places typography front and center, inviting users to explore, sort, and test fonts for use in more than 135 languages. We showcase individual type designers and foundries, giving you valuable information about the typographers and their process, as well as analytics on usage and demographics. Our series of thematic collections helps you discover new fonts that have been vetted and organized by our team of designers, engineers, and collaborators, and our default sort organizes fonts based on popularity, trends, and your geographic location. 489 You can also create your own highly customized collections by filtering families, weights, and scripts, plus test color themes, and review sample copy. Collections can be shared, making it easy to collaborate on projects and ensure typography is optimized and streamlined throughout the design and engineering process. In 2021, we added icons to our Google Fonts catalog, expanding expressive capability for our users. Our first set was the Material icons—delightful, beautifully crafted symbols for common communication needs. Download them on desktop to use them in your digital products for Android, iOS, and web.
(https://fonts.google.com/about)

HOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOHOH
nonononononononononononononononononononononononoononononononononon
H!H"H#H$H%H&H'H(H)H*H+H,H-H.H/H0H1H2H3H4H5H6H7H8H H9H:H;H<H=H>H?H H@HAHBHCHDHEHFHGHHHIHJHKHLHMHNHOHPHQHRHSHTHUHVHWHXHYHZH[H\H] H^H_H`HaHbHcHdHeHfHgHhHiHjHkHlHmHnHoHpHqHrHsHtHuHvHwHxHyHzH{H|H}H~H
O!O"O#O$O%O&O'O(O)O*O+O,O-O.O/O0O1O2O3O4O5O6O7O8O O9O:O;O<O=O>O?O O@OAOBOCODOEOFOGOHOIOJOKOLOMONOOOPOQOROSOTOUOVOWOXOYOZO[O\O]O O^O_O`OaObOcOdOeOfOgOhOiOjOkOlOmOnOoOpOqOrOsOtOuOvOwOxOyOzO{O|O}O~O
oaobocodoeofogohoiojokolomonooopoqorosotouovowoxoyozo{o|o}o~o

Whereas recognition of the inherent dignity and of the equal and inalienable rights of all members of the
human family is the foundation of freedom, justice and peace in the world, Whereas disregard and contempt
for human rights have resulted in barbarous acts which have outraged the conscience of mankind, and the
advent of a world in which human beings shall enjoy freedom of speech and belief and freedom from fear
and want has been proclaimed as the highest aspiration of the common people, Whereas it is essential,
if man is not to be compelled to have recourse, as a last resort, to rebellion against tyranny and oppression,
that human rights should be protected by the rule of law, Whereas it is essential to promote the development
of friendly relations between nations, Whereas the peoples of the United Nations have in the Charter reaffirmed their faith in fundamental human rights, in the dignity and worth of the human person and in the equal
rights of men and women and have determined to promote social progress and better standards of life
in larger freedom, Whereas Member States have pledged themselves to achieve, in cooperation with the
United Nations, the promotion of universal respect for and observance of human rights and fundamental
freedoms, Whereas a common understanding of these rights and freedoms is of the greatest importance
for the full realization of this pledge, Now, therefore, The General Assembly, Proclaims this Universal Declaration of Human Rights as a common standard of achievement for all peoples and all nations, to the end
that every individual and every organ of society, keeping this Declaration constantly in mind, shall strive by
teaching and education to promote respect for these rights and freedoms and by progressive measures,
national and international, to secure their universal and effective recognition and observance, both among the
peoples of Member States themselves and among the peoples of territories under their jurisdiction.
```

**Comment by dberlow** [comment]
‘’opsz 6, wdth 100, wght 1
Feedback: the comma , might be a touch too heavy; please double check.’’
We’ve checked this in normal and dark mode and feel this is the best weight, size and shape to remain distinct from /.

**Comment by dberlow** [comment]
‘’opsz 6, wdth 100, wght 1000’’
‘’Feedback:’’
In sum, there are counters of this location are on the very edge of legibility. I’ll take a second look at these.
The /i and /j are not a problem if I lower the top of the strike to end below the x-height? 
doing so has visual repercussions if opsz6 is used larger, and also it must be controlled along the wght axis, to realign to the x-height when the space is large enough, via one or more intermediates.

**Comment by dberlow** [comment]
No issue # 
"opsz 144, wdth 100, wght 1
Note for later: It seems that rasterizer (review done in Chrome v108.0.5359.94) has issues drawing the outlines so thin. The thinnest value of wght where I didn't see issues for opsz 144, wdth 100 was 20."

See also: https://github.com/FontBureau/fb-GoogleSansFlex/issues/42

**Comment by MariannaPaszkowska** [comment]
@dberlow I added #103, thank you!
