### ISSUE TITLE
Fix interpolation of the "8" on opsz axis

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#741]
Hi @octaviopardo, I was testing out the latest imported fonts and noticed an issue with the "8". It seems to have an interpolation error. Would you mind taking a look and fixing it when you have a chance? Thanks so much!

<img width="625" alt="Screenshot 2023-12-05 at 8 10 49 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/bc1b8eb3-ea33-4246-8471-b4ef3ab155c1">

**Comment by octaviopardo** [comment]
Good catch. I think it's fixed now.

**Comment by MariannaPaszkowska** [comment]
Many thanks!
