### ISSUE TITLE
Build upright-only and italic-only VFs from V2 sources

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#747]
Having discussed, we want to keep building all three target VFs from V1 with the V2 sources:

1. Full designspace
2. Upright-only
3. Italic-only

The current pipeline builds (1), and so this issue tracks the approach of building (2), and then later (3) when we have italic sources.

## Approaches

There are two main ways we can build sub-VFs:

1. #748
2. #749

We will open a draft PR for each to compare their output and ergonomics.

**Comment by madig** [comment]
Slicing is most elegant, but you'll probably run into the usual problems of slicing requiring fixups because not all metadata is set as expected.

**Comment by MariannaPaszkowska** [comment]
Decision: only make one font with a slant axis.
