### ISSUE TITLE
Add Grade axis support to the 'Build Font and Specimen' workflow 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#750]
Hi team, 
we noticed that the Build Font workflow doesn't support creating a grade axis. Can we add this functionality? 
Import workflow supports grade already. 
Many thanks, @octaviopardo, for bringing this to my attention!

**Comment by Hoolean** [comment]
## Notes from meeting earlier:

### At Present

These two approaches should produce consistently correct TTFs:
  - For building `main`:
    1. Run the 'Build font and specimen' action: from `main`, importing from `main`
  - For building `it-ad-wip-v2.0`:
    1. Delete any pre-existing import branch
    2. Run the 'Update from sources' action: from `main`, importing from `it-ad-wip-v2.0`

Other combinations have known defects:
  - e.g. 'Build' actions targeting `it-ad-wip-v2.0` build the V1 sources, omitting Grade and originating this GitHub issue
  
### Next Steps

DaMa will restructure the workflows into the following, re-using actions in their implementation to avoid build differences:

* Build UFOs
  * Used for building `main`, releases, and PRs
* Build Glyphs
  * Used for building Glyphs-based branches in place
* Import Glyphs
  * Used for importing Glyphs-based branches into main

**Comment by Hoolean** [comment]
cc @schriftgestalt @MariannaPaszkowska @chrissimpkins

Following up from earlier: these are the processing steps we wrap around glyphsLib in addition to fontmake:
* [On the .glyphs input](https://github.com/googlefonts/googlesans-flex/blob/66b886d4/scripts/glyphs_to_ds.py#L38-L72)
* [On the designspace output](https://github.com/googlefonts/googlesans-flex/blob/66b886d4/scripts/glyphs_to_ds.py#L102-L137)

Some adjustments are for building the in-development sources while others are for glyphsLib bugs, as documented for each inline. Altogether, there is potential to reduce these both as the V2 sources progress (e.g. when full kerning is added) and as glyphsLib development continues upstream :)
