### ISSUE TITLE
Harmonise the ROND design in accents, diagonals, K. Fix ogoneks 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#760]
Many thanks for the fantastic work over last few days @octaviopardo !

For other reviewers: Please note that grade and slant axes will be added in the later stage of this project. 

A few things are left to iron out:

- [ ]  S, caron, grave, circumflex and acute:

<img width="1074" alt="Screenshot 2023-12-18 at 6 34 54 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/462ae3f3-94ba-4627-9796-c905b3cb1199">

- [ ]  Diagonal glyphs (v w x y) need improvement in the interpolation, there is slight kink in the middle of the design space: 

<img width="1191" alt="Screenshot 2023-12-18 at 3 56 26 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0b9d6d36-321b-4646-9bf9-c66ca5ec32ff">

- [ ] Other small interpolation issues:

[FlexRoundReport.pdf](https://github.com/googlefonts/googlesans-flex/files/13706954/FlexRoundReport.pdf)

- [x] ogoneks need repositioning and slight redesign—this will be done later in the project.
<img width="611" alt="Screenshot 2023-12-13 at 4 09 28 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ca8d45ce-f0b0-43a9-9cd0-2cd4bba5eb0d">

**Comment by davelab6** [comment]
I wonder if the stem to arm contour could be smooth at ROUND max + WDTH min (+ opsz 144 + wght 1000)

<img width="131" alt="Screenshot 2023-12-18 at 12 05 56" src="https://github.com/googlefonts/googlesans-flex/assets/261579/a3fa496c-d752-4321-8dea-9c37fa2b91bb">

The WDTH min WGHT max K also looks a bit odd without rounding overall

**Comment by MariannaPaszkowska** [comment]
@octaviopardo I have checked the latest sources and found that the issues are still present. I am reporting it again so that we don't lose track of it: 

- [ ] **accents**



<img width="775" alt="Screenshot 2024-01-18 at 6 08 06 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/4439fbdf-3308-49ee-b511-6132baea5d1d">



- [ ] **diagonals**



<img width="845" alt="Screenshot 2024-01-18 at 6 06 46 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a2f25001-e201-4f9e-9e7c-894a3d5aea20">



- [ ] **K**



<img width="804" alt="Screenshot 2024-01-18 at 6 09 32 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/667dc587-9d93-4a21-b189-50e7c0e757df">



- [ ] **ogoneks**

<img width="744" alt="Screenshot 2024-01-18 at 6 11 59 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/eb1fa6c3-0669-4539-b9c1-8821de689f4d">

**Comment by Txonliz** [comment]
@MariannaPaszkowska, characters with ogoneks have been reworked during the past days. We found several problems in different locations of the interpolation space and fixed them by repositioning anchors and tweaking the design of the ogoneks in some masters. This video shows how it works now in the mentioned locations. These characters will be added soon to the prototype.

https://github.com/googlefonts/googlesans-flex/assets/10536858/79c35440-e279-4465-8418-26614abc258a

**Comment by MariannaPaszkowska** [comment]
@Txonliz Fantastic work! Many thanks!

**Comment by MariannaPaszkowska** [comment]
remaining tasks were moved here: #803
