### ISSUE TITLE
Review excluded 'googlefonts' QA checks

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#762]
We excluded [some checks](https://github.com/googlefonts/googlesans-flex/blob/1c5e8840/qa/check-googlesans.py#L46-L64) in the 'googlefonts' QA profile for the V1 release because of bugs in FontBakery. Now that we have updated (#721), we should review the excluded tests in each profile to see if they can be restored.

**Comment by MariannaPaszkowska** [comment]
Can we check if those checks have been fixed: 
```
"com.google.fonts/check/varfont/regular_wght_coord",  # Buggy in 0.8.9
"com.google.fonts/check/varfont/bold_wght_coord
"com.google.fonts/check/STAT/gf_axisregistry", # Buggy in 0.8.13
```
