### ISSUE TITLE
Axis tagged opsz has name Optical size but should be named Optical Size

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#768]
Can we please adjust the opsz axis name? Is `Optical size` but should be `Optical Size`.

Reported by Fontbakery here: https://github.com/googlefonts/googlesans-flex/actions/runs/7396121971 

```
Section: Google Sans Flex Custom Checks
🔥
Confirms that axes have the expected names.
Check ID: com.google.fonts/check/googlesansflex/vf/axis_names
🔥 GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf
🔥 FAIL
Axis tagged opsz has name Optical size but should be named Optical Size
```

**Comment by RickyDaMa** [comment]
This needs be be changed in the Glyphs sources, and an import will then see this being renamed. @octaviopardo please 🙏

**Comment by schriftgestalt** [comment]
The opentype spec spells it "Optical size": https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz

**Comment by MariannaPaszkowska** [comment]
@octaviopardo just a note that this hasn't been addressed yet in this build: https://github.com/googlefonts/googlesans-flex/actions/runs/7570040538

**Comment by MariannaPaszkowska** [comment]
Fixed in import: https://github.com/googlefonts/googlesans-flex/actions/runs/7586243257
