### ISSUE TITLE
Font Bakery GRAD,ROND reflow fail 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#773]
Full results: https://github.com/googlefonts/googlesans-flex/actions/runs/7396121971

I think some of those might be on purpose, and we might need to skip or modify this check, if possible. We decided not to keep the metrics identical for ROND, but for GRAD axis, they should be identical.

```
Ensure VFs with duplexed axes do not vary horizontal advance.
Check ID: com.google.fonts/check/varfont/duplexed_axis_reflow
🔥 GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf
🔥 FAIL
The following glyphs have variation in horizontal advance due to duplexed axes (ROND or GRAD): Lslash, Dcaron, Ldot, less, d, multiply, ae, divide, guilsinglleft, racute and 42 more.

Use -F or --full-lists to disable shortening of long lists. [code: duplexed-causes-reflow]
```

UPDATE: the team is implementing custom parameters in Glyphs to ensure full glyph width compatibility in between sharp and round.

**Comment by RickyDaMa** [comment]
Started looking into this, see https://github.com/fonttools/fontbakery/pull/4400

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa after discussing the issue with Octavio, we will fix the sources and keep the metrics between sharp/ROND identical. 
CC @octaviopardo

**Comment by MariannaPaszkowska** [comment]
Hi @octaviopardo 
In the latest import, I see big improvement, many thanks! Only a few glyphs still reflow:
`dollar, eth and cent` 

Tested build: https://github.com/googlefonts/googlesans-flex/actions/runs/7570040538
```
Ensure VFs with duplexed axes do not vary horizontal advance.
Check ID: com.google.fonts/check/varfont/duplexed_axis_reflow
🔥 GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf
🔥 FAIL
The following glyphs have variation in horizontal advance due to duplexed axes (ROND or GRAD): dollar, eth and cent [code: duplexed-causes-reflow]
```

**Comment by octaviopardo** [comment]
yesss, working on them right now. I ll keep you updated when they are ready

**Comment by MariannaPaszkowska** [comment]
related #788

**Comment by MariannaPaszkowska** [comment]
Fixed in import: https://github.com/googlefonts/googlesans-flex/actions/runs/7586243257
