### ISSUE TITLE
Restore V1 feature code

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#776]
See #769, #771

When importing V2, the V1 feature code was cleared; we should restore this before release. This requires two steps:

1. Stop [clearing features](https://github.com/googlefonts/googlesans-flex/blob/e0be6426720f0e9b89d48e103e752bf114f9e8de/scripts/glyphs_to_ds.py#L70-L72) on import
    - This was a workaround for glyphsLib exporting features that were not enabled, but the sources now no longer require this
2. Retrieve V1 feature code from git history and add to Glyphs sources (if it does not require re-engineering for the new sources)

**Comment by MariannaPaszkowska** [comment]
I confirm that features now are importing, many thanks 🚀
