### ISSUE TITLE
GSF v1.2 vs. v2.0 OpenType table size comparisons

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#782]
Some size comparisons to show the progress that Octavio's team has made in the v2 work.  

Caveats: this is not a production grade and the v2.0 builds represent estimates at this stage.  The builds were developed for the purposes of these estimates.  We feel that this should be a representative estimate of the gvar data in the final delivery next month.  GSF 2.0 with grade is the build that Octavio delivered. GSF 2.0 instanced grade is a build with the grade axis instanced at 0 to determine the impact of the grade axis on the gvar deltas.

_**tl;dr**: significant improvement in our pre-grade v2 prototype gvar sizes that more than offsets both the kerning pair definition expansion (nearly 3.5-fold increase in GPOS size since v1.2) and the addition of a new positive range only grade axis._

### Per Total Encoded + Unencoded Glyph Size Ratios

508 total encoded and unencoded glyphs in each build.  Byte (B) size units.

| **GSF 1.2** | **GSF 2.0 instanced grade** | **GSF 2.0 with grade** |
|-------------|-----------------------------|------------------------|
|  7300 B/glyph |    3143 B/glyph       |       6716 B/glyph   |

### Size in Bytes by OpenType table

|          | **GSF 1.2** | **GSF 2.0 instanced grade** | **GSF 2.0 with grade** |
|----------|-------------|-----------------------------|------------------------|
| **GDEF** |      153808 |          137648             |       296546           |
| **GPOS** |       36746 |          121358             |       124914           |
| **GSUB** |        3686 |            3770             |         3770           |
| **HVAR** |       34310 |           24487             |        44312           |
| **MVAR** |        4930 |             306             |         1992           |
| **OS/2** |          96 |              96             |           96           |
| **STAT** |         628 |              68             |           68           |
| **cmap** |         750 |             782             |          782           |
| **fvar** |         548 |             140             |          164           |
| **gasp** |           8 |        not implemented      |     not implemented    |
| **glyf** |       29686 |           24870             |        24870           |
| **gvar** |     3433838 |         1274556             |      2905768           |
| **head** |          54 |              54             |           54           |
| **hhea** |          36 |              36             |           36           |
| **hmtx** |        2032 |            2032             |         2032           |
| **loca** |        1018 |            1018             |         1018           |
| **maxp** |          32 |              32             |           32           |
| **name** |        2516 |            1498             |         1610           |
| **post** |        3635 |            3806             |         3806           |
| **prep** |           7 |         not implemented     |     not implemented    |
| **TOTAL (B)** |**3708716** |         **1596876**         |     **3412188**        |

**Comment by chrissimpkins** [comment]
@MariannaPaszkowska @octaviopardo 

A couple of file size-unrelated notes:

The encoded glyph number dropped from 391 in v1.2 to 376 in v2.0 prototype.  Suggest that we look into that.  Octavio mentioned four brace layer glyphs that were excluded from the build at this stage.  But it looks like there are 11 other, unexpected codepoint position differences.

It looks like we don't have gasp/prep definitions yet.  We'll need to make sure that those are implemented in the build pipeline.  This might have been an external fontmake build from Octavio? These definitions should already be implemented in the repository pipeline.

MVAR size decreased fairly significantly in the v2 builds.  Thoughts about why that might be happening?  Do we have metrics that vary in v1.2 and are not in v2.0?  Intentional or a bug? Related: https://github.com/googlefonts/googlesans-flex/issues/246

STAT table is missing in Octavio's builds. Full fvar definitions likely too.

**Comment by octaviopardo** [comment]
Seen, here is the explanation
5 glyphs were removed to simplify the exporting process of the prototype

Regarding the other 10
v1.2 features 5 sets of small numbers: denominators, numerators, scientific inferiors, subscripts, and superiors. The scientific inferiors and the subscripts are virtually the same glyphs, but the subscripts have unicode value. 
For the v2.0, apparently we got rid of one set of numerals (to be honest it must have been very early in the process and I don t recall it) and we removed the ones with the unicode. Bringin them back is a matter of seconds. More important it would be to decide if we really want them back and we leave the set as it was in v1.2, or on the contrary we bring the subscripts back and we remove the scientific inferiors, making a total of four sets of small numbers, which is the standard. I defenetly advise for this option

and yes it was an external build

**Comment by MariannaPaszkowska** [comment]
I checked MVAR in this build https://github.com/googlefonts/googlesans-flex/actions/runs/7477650009 and is also small: 0.35 kB (354 bytes) compared to 4.81 kB (4930 bytes) from the release. 
It seems that previously, we had deltas related to those metric tags:
'hcrn'	horizontal caret run	hhea.caretSlopeRun
'hcrs'	horizontal caret rise	hhea.caretSlopeRise
'sbxo'	subscript em x offset	OS/2.ySubscriptXOffset
'spxo'	superscript em x offset 	OS/2.ySuperscriptXOffset
'xhgt'	x height	OS/2.sxHeight

It the new version it is only:
'xhgt'	x height	OS/2.sxHeight
that varies. 

We need to investigate to make sure all this is intentional. 


prep and gasp table are being added when building on the repo.

**Comment by chrissimpkins** [comment]
> Seen, here is the explanation 5 glyphs were removed to simplify the exporting process of the prototype
> 
> Regarding the other 10 v1.2 features 5 sets of small numbers: denominators, numerators, scientific inferiors, subscripts, and superiors. The scientific inferiors and the subscripts are virtually the same glyphs, but the subscripts have unicode value. For the v2.0, apparently we got rid of one set of numerals (to be honest it must have been very early in the process and I don t recall it) and we removed the ones with the unicode. Bringin them back is a matter of seconds. More important it would be to decide if we really want them back and we leave the set as it was in v1.2, or on the contrary we bring the subscripts back and we remove the scientific inferiors, making a total of four sets of small numbers, which is the standard. I defenetly advise for this option
> 
> and yes it was an external build

I recommend that we keep all encodings that we shipped in v1.2, particularly if this is a simple / quick process to add them back.  It isn't clear to me if any team is using these codepoints, but they could be if we've previously shipped them into production and it would be a regression to revert at this stage unless we have strong evidence to do so.  Open to more info if you have any to justify removal.

**Comment by chrissimpkins** [comment]
> I checked MVAR in this build https://github.com/googlefonts/googlesans-flex/actions/runs/7477650009 and is also small: 0.35 kB (354 bytes) compared to 4.81 kB (4930 bytes) from the release. It seems that previously, we had deltas related to those metric tags: 'hcrn' horizontal caret run hhea.caretSlopeRun 'hcrs' horizontal caret rise hhea.caretSlopeRise 'sbxo' subscript em x offset OS/2.ySubscriptXOffset 'spxo' superscript em x offset OS/2.ySuperscriptXOffset 'xhgt' x height OS/2.sxHeight
> 
> It the new version it is only: 'xhgt' x height OS/2.sxHeight that varies.
> 
> We need to investigate to make sure all this is intentional.
> 
> prep and gasp table are being added when building on the repo.

I chatted with Marianna about the MVAR data today. She is going to continue the review to determine if we need to keep any previous MVAR definitions that are not in the current beta/prototype builds.  

Also, good to hear prep/gasp is already implemented.  We determined that Octavio compiled outside of our repo pipeline so the test fonts didn't include those table definitions.  We'll need them in the prod release builds.

**Comment by octaviopardo** [comment]
> I recommend that we keep all encodings that we shipped in v1.2, particularly if this is a simple / quick process to add them back. It isn't clear to me if any team is using these codepoints, but they could be if we've previously shipped them into production and it would be a regression to revert at this stage unless we have strong evidence to do so. Open to more info if you have any to justify removal.

Yup, I definetely think that the encodings should be back, and they will. My comment is more oriented to removing one of the other sets of small numerals. Let me illustrate it with an image that I think will clarify my point :)

![Captura de pantalla 2024-01-17 a las 8 55 16](https://github.com/googlefonts/googlesans-flex/assets/2181684/617a2de8-ab84-4c03-9661-dfbbaae53a47)

As you see here in v1.2 there are five sets of small numbers, with two of them being encoded, the subscript (in red) and the superior (the line of numbers right below the red one). The line in blue is identical to the red one, but without encoding. It makes no sense for that set of numerals to exist, and even if you want to keep the sinf OT feature, it s a matter of pointing the feature to the subscripts, instead of to the sinf numbers.
My advise: recover the encoding to the subscript numbers and delete the scientific inferiors. To be honest, I do not see any drawback

**Comment by chrissimpkins** [comment]
The unencoded set use the encoded set as components?  How does our fea code handle the two different sets?  I assume that removal of the unencoded forms means that we will need to update GSUB fea code?  Or have they already been completely abandoned as duplicates in favor of the encoded forms?

**Comment by MariannaPaszkowska** [comment]
In Google Sans there are four sets of figures:
1. superior
2. inferior 
3. denominator
4. numerator

Both sinf and subs are using inferior figures:

feature sinf {
    # automatic
    sub zero by zeroinferior;
    sub one by oneinferior;
    sub two by twoinferior;
    sub three by threeinferior;
    sub four by fourinferior;
    sub five by fiveinferior;
    sub six by sixinferior;
    sub seven by seveninferior;
    sub eight by eightinferior;
    sub nine by nineinferior;
} sinf;

feature subs {
    # automatic
    sub zero by zeroinferior;
    sub one by oneinferior;
    sub two by twoinferior;
    sub three by threeinferior;
    sub four by fourinferior;
    sub five by fiveinferior;
    sub six by sixinferior;
    sub seven by seveninferior;
    sub eight by eightinferior;
    sub nine by nineinferior;
} subs;

if in v1.2 subs inf figures are on the same vertical position, one set - subs, can be removed and we would use inferiors for sinf feature.

**Comment by MariannaPaszkowska** [comment]
STAT Table Size in v1.2 for the font with slant axis was 0.61 kB (628 bytes). If we would keep the same instances, this will likely be the same.

**Comment by octaviopardo** [comment]
sinf moved to "non-export" status, sinf OT feature was already pointing to the inferiors, that have been reencoded

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins 
In the latest import: https://github.com/googlefonts/googlesans-flex/actions/runs/7781836863 
```
MVAR Table Size: 478 bytes, 0.47 kB,
Value Tags in MVAR Table:
hcrn mnemonic: horizontal caret run, value represented: hhea.caretSlopeRun
hcrs mnemonic: horizontal caret rise, value represented: hhea.caretSlopeRise
sbxs mnemonic: subscript em x size, value represented: OS/2.ySubscriptXSize
sbyo mnemonic: subscript em y offset, value represented: OS/2.ySubscriptYOffset
sbys mnemonic: subscript em y size, value represented: OS/2.ySubscriptYSize
spxs mnemonic: superscript em x size, value represented: OS/2.ySuperscriptXSize
spys mnemonic: superscript em y size, value represented: OS/2.ySuperscriptYSize
xhgt mnemonic: x height, value represented: OS/2.sxHeight
```
