### ISSUE TITLE
uni000D and uni00A0

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#783]
Question!
uni00A0 or NoBreak Space, must have same glyph width as space, correct? there is a bit of figure jump in our file currently

uni000D or Carriage Return, also must have the same glyph width as space, right? currently and also in v1.2 it has value 0

**Comment by MariannaPaszkowska** [comment]
Hi Octavio,
yes, both CR u+000D, and nbspace u_00A0 should have identical width as space u+0020.
Thanks for pointing that out, let's fix it!

**Comment by schriftgestalt** [comment]
Why not double (triple) encode them?

**Comment by MariannaPaszkowska** [comment]
related: https://github.com/googlefonts/googlesans-flex/issues/770

**Comment by octaviopardo** [comment]
unless you want to follow george's advise we are done here :)

**Comment by schriftgestalt** [comment]
At least add a width metrics key.

**Comment by MariannaPaszkowska** [comment]
We can investigate if adding multiple encodings to a control character is not creating any issues in a later stage; for now, let's leave them as separate characters. Adding width metrics keys is good idea.
