### ISSUE TITLE
Why is wdth max 151, not 150?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#784]
@dberlow, I am curious, why is wdth max 151, not 150? :)

**Comment by MariannaPaszkowska** [comment]
We intended to match the Roboto Flex wdth value, but I am not aware of why this was 151 instead of 150. Thanks @chrissimpkins

**Comment by davelab6** [comment]
DB said offline, 

> This can be 150, 151 was mostly a caution not to go any wider.

Since we shipped 151 in the GSF in the API, I think we'll want to use avar1 in GSF v2 to warp the space so that 151 = 150; or, we'll want to redo the axis max to 150 and update the font in the API, if there's no traffic to API URLs with a width 151

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins, could you check the traffic to API URLs with a width of 151? We could easily adjust the wdth max value to 150.

**Comment by MariannaPaszkowska** [comment]
Related https://github.com/googlefonts/roboto-flex/issues/54
