### ISSUE TITLE
review Bluezones

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#789]
We need to make sure that the bluezones are correct and scaled to 2000 UPM.
Are there tools to review them? Or is this a manual check?

**Comment by schriftgestalt** [comment]
The glyphs sources are almost properly set up. The default zones seem to match the outlines, now. But there is a `Height for .denominator` zone. And it is only set in very few masters, most simply set it to zero. When generating alignment zones (are those even needed for a TT based variable font?) this one should probably be ignored (as it has a filter).
