### ISSUE TITLE
Refine `w v x y` in extended masters

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#799]
Currently: 
<img width="738" alt="Screenshot 2024-01-25 at 5 49 07 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/475d6601-0a53-4daf-ae70-ffddb71170ac">
<img width="734" alt="Screenshot 2024-01-25 at 5 50 42 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/4096872a-0395-4e66-b365-35b350452020">
<img width="758" alt="Screenshot 2024-01-25 at 5 51 15 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/e4716f8a-10f8-4eb4-917d-56ea4d70027e">
<img width="736" alt="Screenshot 2024-01-25 at 5 51 03 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/ee11311d-5943-49f5-bf8c-90d84ffe926c">

**Comment by Bogidar** [comment]
Current diagonal shapes adjusted from the previous versions.

Opsz6-100-1000
![Captura de pantalla 2024-01-25 a las 18 04 05](https://github.com/googlefonts/googlesans-flex/assets/134197382/22b2e8d5-f60a-472d-ae52-5fcedcfd0393)

Opsz18-151-1000
![Captura de pantalla 2024-01-25 a las 18 05 58](https://github.com/googlefonts/googlesans-flex/assets/134197382/50f6bbfe-3c11-4507-bc0d-c3117f845e6d)

Opsz144-100-1000
![Captura de pantalla 2024-01-25 a las 18 06 53](https://github.com/googlefonts/googlesans-flex/assets/134197382/f78eb080-2242-4104-856a-49d74787be23)

Opsz144-151-1000
![Captura de pantalla 2024-01-25 a las 18 07 55](https://github.com/googlefonts/googlesans-flex/assets/134197382/88c3e616-75a6-4bc4-b4d6-3de1124943df)

**Comment by MariannaPaszkowska** [comment]
Many thanks! As discussed with @octaviopardo during our meeting, let's work a little more on balancing those forms in those masters: Opsz18-151-1000, Opsz144-151-1000

**Comment by octaviopardo** [comment]
opsz18-400-151
![Captura de pantalla 2024-02-06 a las 16 24 45](https://github.com/googlefonts/googlesans-flex/assets/2181684/9a968218-9db8-44f3-ab05-31cef409c194)

opsz18-1000-151
![Captura de pantalla 2024-02-06 a las 15 54 55](https://github.com/googlefonts/googlesans-flex/assets/2181684/23370b18-b7b5-4858-9b54-21513d209cc5)

![Captura de pantalla 2024-02-06 a las 16 14 19](https://github.com/googlefonts/googlesans-flex/assets/2181684/a5851de8-ed9c-4261-aae9-71f6c939d85e)

opsz144-400-151
![Captura de pantalla 2024-02-06 a las 16 29 37](https://github.com/googlefonts/googlesans-flex/assets/2181684/13a49e7c-e9cc-472e-bbee-277b1b72d0c2)

opsz144-1000-151
![Captura de pantalla 2024-02-06 a las 16 03 39](https://github.com/googlefonts/googlesans-flex/assets/2181684/c798e786-9d2b-4405-9dfe-cf4db48fe73d)

![Captura de pantalla 2024-02-06 a las 16 15 55](https://github.com/googlefonts/googlesans-flex/assets/2181684/df7f066c-a5f4-43ff-95d5-7a56e4a90e2f)

**Comment by davelab6** [comment]
LGTM

**Comment by MariannaPaszkowska** [comment]
imported in #844 

<img width="684" alt="Screenshot 2024-02-06 at 11 47 42 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9140d1b3-5e46-46b9-ab60-2adfbe9707b4">
<img width="630" alt="Screenshot 2024-02-06 at 11 49 06 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/2e9dfdda-ed1c-455c-aac2-0b92d0b449ca">
