### ISSUE TITLE
Address FontBakery errors

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#802]
https://github.com/googlefonts/googlesans-flex/actions/runs/7643147176/job/20824720478 
```
Error: The following Fontbakery profiles had fails/errors: check-sources check-googlesans check-fea
Error: Process completed with exit code 1.
```

**Comment by RickyDaMa** [comment]
This is intended: the pipeline fails if any of the tests fail. That message just summarises which check profiles had errors/fails

If all Fontbakery checks pass/warn, this error will no longer be generated
