### ISSUE TITLE
Known interpolation issues in v2.0

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#803]
There is a kink in:

- [x] Acute 
- [x] Hungarian umlaut 

and a very slight in:

- [x] Eth italic 
- [x] five.tf italic

[GSF-latest14Feb.pdf](https://github.com/googlefonts/googlesans-flex/files/14279646/GSF-latest14Feb.pdf)

<img width="703" alt="Screenshot 2024-02-14 at 2 56 07 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/b7c7c88f-996c-4b10-a854-f8b593c67b7a">
<img width="700" alt="Screenshot 2024-02-14 at 2 56 14 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/e2cc3e22-110e-47e1-9ca0-6f36a0ed76ab">
<img width="698" alt="Screenshot 2024-02-14 at 2 57 23 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/c5161d59-ae5d-4d75-ac6a-36c057ec8dbd">
<img width="684" alt="Screenshot 2024-02-14 at 2 57 42 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/235fc7ac-a54a-4443-b25b-e34e9ea8a318">

**Comment by schriftgestalt** [comment]
The point structure screams for kinks. From experience, I don't think they are 100% avoidable. 

I had a look at hungarumlautcomb (0x030B): Some round outlines do not match the sharps. Partially that seems to be on purpose. But some of the rounds do not look very round:

<img width="906" alt="Bildschirmfoto 2024-01-26 um 00 57 58" src="https://github.com/googlefonts/googlesans-flex/assets/174660/f58d96d9-9796-4b22-9c8a-76a7d5761326">

But that probably has nothing to do with the kinks.

**Comment by MariannaPaszkowska** [comment]
moved from https://github.com/googlefonts/googlesans-flex/issues/810 
kink:
- [x] `eth`
- [x] `five`
- [x] `five.tf`
- [x] `s`
- [x] `section`
- [x] `uni1E9E ẞ`

[GSF-latest18.pdf](https://github.com/googlefonts/googlesans-flex/files/14186202/GSF-latest18.pdf)
