### ISSUE TITLE
Review MVAR table in v2.0 vs v1.002

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#807]
Related: https://github.com/googlefonts/googlesans-flex/issues/782#issuecomment-1893741500 

make sure if the slnt axis is present to vary:
'hcrn' horizontal caret run hhea.caretSlopeRun
'hcrs' horizontal caret rise hhea.caretSlopeRise

**Comment by MariannaPaszkowska** [comment]
related #821 #820 #822

**Comment by MariannaPaszkowska** [comment]
QQ @belluzj @RickyDaMa @Hoolean does import process/fontmake need a custom parameter 
or does it use the italic angle to calculate MVAR entries: 'hcrn' horizontal caret run hhea.caretSlopeRun and 'hcrs' horizontal caret rise hhea.caretSlopeRise
Currently, we do not have it yet set correctly in the sources @octaviopardo . will be done in #820 
cc @schriftgestalt

**Comment by anthrotype** [comment]
ufo2ft uses the italicAngle to compute the caret slope rise/run unless the latter are also explicitly set. in Glyphs.app I think you can only control the italic angle, which determines the caret slope, but not the caret slope run/rise directly (UFO has distinct fontinfo attributes for the latter two as well)

**Comment by schriftgestalt** [comment]
There was openTypeHheaCaretSlopeRise/Run parameters on the font level i the glyphs file. I removed them (6f93284e9eb8ed3aff19350488f8ec0970d6e9a5) as of #820

**Comment by MariannaPaszkowska** [comment]
Many thanks! In the latest import: https://github.com/googlefonts/googlesans-flex/actions/runs/7781836863 
```
MVAR Table Size: 478 bytes, 0.47 kB,
Value Tags in MVAR Table:
hcrn mnemonic: horizontal caret run, value represented: hhea.caretSlopeRun
hcrs mnemonic: horizontal caret rise, value represented: hhea.caretSlopeRise
sbxs mnemonic: subscript em x size, value represented: OS/2.ySubscriptXSize
sbyo mnemonic: subscript em y offset, value represented: OS/2.ySubscriptYOffset
sbys mnemonic: subscript em y size, value represented: OS/2.ySubscriptYSize
spxs mnemonic: superscript em x size, value represented: OS/2.ySuperscriptXSize
spys mnemonic: superscript em y size, value represented: OS/2.ySuperscriptYSize
xhgt mnemonic: x height, value represented: OS/2.sxHeight
```
