### ISSUE TITLE
Disable http://namecheck.fontdata.com/ FB check

### ISSUE THREAD

**Issue by belluzj** [googlefonts/googlesans-flex#815]
I'm seeing an error on Google Sans Flex saying that http://namecheck.fontdata.com/ doesn't work, and indeed it doesn't. 
We should probably disable that check for the Google Sans fonts.

 @Marianna Paszkowska FYI

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/0d135682-9406-4cdf-af63-a418efa62de8)

**Comment by RickyDaMa** [comment]
Upstream tracking issue: https://github.com/fonttools/fontbakery/issues/2719

Seems like this isn't the first time the website has gone down
