### ISSUE TITLE
Fix ss03 feature

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#818]
Hi, I noticed that the ss03 feature maps to the same `g` that is referenced is the ss02 - `g.alt`

**Comment by MariannaPaszkowska** [comment]
<img width="1538" alt="Screenshot 2024-01-29 at 6 39 35 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0f144041-bfce-41cf-b374-24a38a10b866">

**Comment by MariannaPaszkowska** [comment]
I noticed that the g.ss03 is not being imported. Do we still use an import glyph list @RickyDaMa ?

**Comment by RickyDaMa** [comment]
There is no import list, everything should come through. We'll look into it

**Comment by RickyDaMa** [comment]
![image](https://github.com/googlefonts/googlesans-flex/assets/113340856/9b70d302-5342-4f19-9b19-ca9d8a78d18a)

Looks like it was an issue in the sources, as doing a fresh import built the right font for me. It looks like on `main` the feature code isn't there to sub in `g.ss03`

**Comment by MariannaPaszkowska** [comment]
Many thanks! I confirm it is fixed in #825
