### ISSUE TITLE
Review positions of subscript and superscript and their metrics

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#821]
Tasks:

- [x] Review the positions across the design space (subscript and superscript)

- [x] Script for unifying positions of all the small numbers within the master. It will check positions within the overshoots. It will align the numerators to the cap height.  It will automatically assign the same vertical shift for the duplexed axes (GRAD or ROND) and Italic, as it has the same height.
- [x] Script for computing the metrics numbers for the OS/2 table (will be stored as a custom parameter in the masters' tab in the font info panel)

**Comment by octaviopardo** [comment]
Ok, so here is my proposal 
Numerators: as we said, they stick to the uppercase height
Denominators: baseline

and now the tricky part. 
Subscripts: 
opsz6-> do not touch them: base sits at Y-467; top raises to Y450
opsz18 -> do not touch them: base sits at Y-410; top raises to Y450
opsz144 -> base sits at -344; top raises to Y450

Superscripts
opsz6 -> do not touch them: base sits at Y954; top raises to 1868
opsz18 -> base sits at Y954; top raises to 1813
opsz144 -> base sits at 954; top raises to 1748

let me know what you think

**Comment by schriftgestalt** [comment]
This is a bit more tricky. The height of the figures are different. So the bottom and top bound will be different in different weights. 

I see this options (explanation for the subscripts, the superscripts work the same):

1) Pick the top for all masters (Y450). That will move up the bolder weights a bit. 
2) Use bottom for each optical size. That is the most complicated to get right (what about intermediate sources?). 
3) Use a generic method that used a percentage of the figure height.

I tend to the third option.

**Comment by schriftgestalt** [comment]
I updated the script to be easier to customize. It has a parameter at the top of the file. Can you play around and check all weights.

**Comment by schriftgestalt** [comment]
I added another script. It uses the height of a key glyphs to sync all components. It shows a lot existing inconsistencies.

**Comment by MariannaPaszkowska** [comment]
Notes from a meeting with Georg: 
The script should work as is; the height actually differs between the optical sizes.

**Comment by MariannaPaszkowska** [comment]
@octaviopardo I will close it after you finish your review, many thanks!

**Comment by MariannaPaszkowska** [comment]
Note to self: we are now getting an error:
``` 
Check that global font unit attributes match GS v10.001 (taking upM into consideration).
Check ID: com.google.fonts/check/googlesansflex/opentype/global_fu_attributes
🔥 GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf
🔥 FAIL
OS/2.ySubscriptXSize should be 1300 but is 1200

🔥 FAIL
OS/2.ySubscriptYOffset should be 150 but is 409

🔥 FAIL
OS/2.ySuperscriptXSize should be 1300 but is 1200

🔥 FAIL
OS/2.ySuperscriptYOffset should be 700 but is 954
``` 
We need to make sure those values are intentional and we are moving from the 10.001 values on purpose.
