### ISSUE TITLE
Halfkern Kerning Review: default master on language priorities

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#826]
The top image is the suggestion; bottom is what is in the font. 

Here is a full list of pairs that need review or fix: `jj gj kx fí ïb ïl iï ïk īj dî îl Vī Vä Vă Vš Vř Tà Tâ Tā Tă Ță Tä Tå Tō Tě  Tö Tõ Tř ñT ÍÏ ÎÏ ÏÎ ťt LV`
Please review those pairs on all masters. 

PDF with selected pages: 
[GSFv2kerned.pdf](https://github.com/googlefonts/googlesans-flex/files/14113277/GSFv2kerned.pdf)

- [x] `ÍÏ   ÎÏ  ÏÎ ` - too close, needs kerning
<img width="358" alt="Screenshot 2024-01-31 at 4 36 06 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a89a10ed-01ce-4d6d-ae49-c1cadd08932f">

- [ ] ` ťt `- consider no kerning; maybe it's not needed here? The top line shows no kerning, the second is the tool's suggestion, and the third is kerning from the font. 
<img width="386" alt="Screenshot 2024-01-31 at 4 44 45 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/127673f6-9404-420e-a6f5-25b60cd2612f">

- [x] `jj` - collision, needs kerning
<img width="335" alt="Screenshot 2024-01-31 at 4 18 19 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/c38e89d1-c150-4f74-b1f8-746af3bde65b">

- [x] `gj` - too close, needs kerning

- [x] `kx` - too close, needs kerning
<img width="400" alt="Screenshot 2024-01-31 at 4 17 45 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9500b875-c443-4470-a8d8-ecda42a10abd">

- [x] `fí ` - too lose
<img width="378" alt="Screenshot 2024-01-31 at 4 17 20 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/1170dc5b-2354-4481-b84a-c0ba475bcaaf">

- [x] `ïb` - too close, needs kerning
<img width="395" alt="Screenshot 2024-01-31 at 4 17 12 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/1c35c4f7-4351-4d97-8e19-b376286b42ae">

- [x] ` ïl `- too close, needs kerning
<img width="354" alt="Screenshot 2024-01-31 at 4 17 08 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/4ef69a9f-a1b1-424a-bf0f-5601d99c3ef0">

- [x] `iï ` - too close, needs kerning
<img width="349" alt="Screenshot 2024-01-31 at 4 23 12 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a479be74-eff0-4021-af58-4ebb7e72a95d">

- [x] `ïk` - too close, needs kerning
<img width="379" alt="Screenshot 2024-01-31 at 4 24 25 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/cb9b0830-fc07-46ba-a1de-7ad886214660">

- [x]  `īj` - too close, needs kerning
<img width="365" alt="Screenshot 2024-01-31 at 4 29 52 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/5f9006dd-4f8a-49fa-b509-3b0799e91c86">

- [x] `dî` - too close, needs kerning
- [x] `îl` - too close, needs kerning

- [x] `Vī ` - too close, needs kerning
<img width="366" alt="Screenshot 2024-01-31 at 4 32 43 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/a8788a3e-f6e2-4928-87e9-a47d6a8c8cb8">

- [x] `Vä  Vă ` - too tight
<img width="416" alt="Screenshot 2024-01-31 at 4 27 15 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/d8dfafef-90b8-4eae-a14e-03af16415d8e">

- [x] `Tà` - too tight
<img width="406" alt="Screenshot 2024-01-31 at 4 17 02 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9beb1aa2-dfa9-4148-ad6e-2ab620a0e3be">

- [x] `Tâ ` - too tight
<img width="390" alt="Screenshot 2024-01-31 at 4 25 14 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/89d43db5-95cf-4f23-a8fe-bdfcbee856fb">

- [x] `Tā Tă Ță Tä Tå ` - too tight, slightly
<img width="385" alt="Screenshot 2024-01-31 at 4 33 14 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/dceb3c0b-436f-41f0-88fe-a7233cddd04e">

- [x] `Tō Tě ` - too tight, slightly
<img width="393" alt="Screenshot 2024-01-31 at 4 27 32 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/7735c3ba-65da-46ca-bead-96af0a3c9a08">

- [x] `Tö ` - too tight
<img width="384" alt="Screenshot 2024-01-31 at 4 28 41 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/64d35386-075d-4bfa-9370-335a3771f67a">

- [x] `Tõ ` - too tight
<img width="405" alt="Screenshot 2024-01-31 at 4 29 10 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/abfe731c-8a63-401c-ae60-0f89bda98b64">

- [x] `Tř ` - too tight
<img width="371" alt="Screenshot 2024-01-31 at 4 38 03 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/35e6b976-588b-45ad-8c61-84145d50af29">

- [x] ` ñT  ` - too tight
<img width="384" alt="Screenshot 2024-01-31 at 4 35 30 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/d8da01af-0e71-47bb-9a86-d8ecad2a0fa0">

- [x] `Vš ` - too tight, slightly
<img width="416" alt="Screenshot 2024-01-31 at 4 39 29 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/59aabfe6-7de7-493f-b473-af2b1975797b">

- [x] `Vř ` - too tight
<img width="386" alt="Screenshot 2024-01-31 at 4 40 33 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/e16fa614-6f8b-44fc-aad1-f971e04ff53d">

- [x] LV - could be slightly tighter

**Comment by davelab6** [comment]
> The top image is the suggestion; bottom is what is in the font.

A small nit, but, that order seems inverse of normal expectations so if the images are output by the tool, it would be good to change the tool :)

**Comment by MariannaPaszkowska** [comment]
@davelab6 yes, I agree! Since then we added labels, but I agree that the order you suggest is better, cc @behdad

**Comment by behdad** [comment]
Okay. So: unkerned, font kerned, tool kerned?

**Comment by MariannaPaszkowska** [comment]
@davelab6  I posted this issue: https://github.com/behdad/halfkern/issues/16 
I was thinking: 

1. font kerned
2. tool kerned
3. unkerned

Sounds good?

**Comment by behdad** [comment]
Done.

**Comment by MariannaPaszkowska** [comment]
@octaviopardo New report: 
[halfkern-reportGSF-v2.pdf](https://github.com/googlefonts/googlesans-flex/files/14251841/halfkern-reportGSF-v2.pdf)

**Comment by MariannaPaszkowska** [comment]
@octaviopardo Latest report, as discussed in the meeting. 
Many thanks!
[kerned-1502.pdf](https://github.com/googlefonts/googlesans-flex/files/14296453/kerned-1502.pdf)
