### ISSUE TITLE
Grade bugs

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#829]
Grade issues with interpolation:

- [x] ligatures: ﬁﬂﬃﬄ
- [x] $¢
- [x] ð
- [x] Q

<img width="584" alt="Screenshot 2024-01-31 at 6 31 29 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/0dc0e085-7645-42d4-9248-cafd24ac764c">

**Comment by MariannaPaszkowska** [comment]
@octaviopardo, the `$ ¢ ð` and `Q` are fixed; many thanks! However, the ligatures still misbehave, this time I saw it in the narrow corners: <img width="855" alt="Screenshot 2024-02-06 at 11 42 03 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/13c71024-0758-458a-8276-b3e9f8f41d8f">

**Comment by octaviopardo** [comment]
Noted, i still saw a couple of glitches in the Q in a couple of locations, though. I started fixing it today, I ll finish it tomorrow. I ll look at the ligas as well

**Comment by octaviopardo** [comment]
Screenshot from the last build using the Grader in G4

<img width="1552" alt="Captura de pantalla 2024-02-13 a las 17 51 40" src="https://github.com/googlefonts/googlesans-flex/assets/2181684/6a386690-5389-42ce-b088-11a1d1ce5b78">

**Comment by MariannaPaszkowska** [comment]
ligatures fixed in #860 
Top fixed:
<img width="354" alt="Screenshot 2024-02-13 at 7 45 44 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/67d8e26e-2a9a-424d-ae7b-b2821e8215a9">
