### ISSUE TITLE
Refine K at ROUND max + WDTH min (+ opsz 144 + wght 1000)

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#830]
I wonder if the stem to arm contour could be smooth at ROUND max + WDTH min (+ opsz 144 + wght 1000)

<img width="131" alt="Screenshot 2023-12-18 at 12 05 56" src="https://github.com/googlefonts/googlesans-flex/assets/261579/a3fa496c-d752-4321-8dea-9c37fa2b91bb">

The WDTH min WGHT max K also looks a bit odd without rounding overall

_Originally posted by @davelab6 in https://github.com/googlefonts/googlesans-flex/issues/760#issuecomment-1861364934_

**Comment by schriftgestalt** [comment]
Or do the opposite and rotate the top arm a few degrees CW? That would make the transition more intentionally sharp?

**Comment by octaviopardo** [comment]
0) Current; 1) Proposal 1 (smooth connection); 2) Proposal 2 (bringing the connection higher)

Although 1) might look nice(r?) I would go for 2 for the simple reason that this kind of smooth connection is not going to be present anywhere else than just that master, and in terms of design space, as soon as you move any slider away from this position we will be loosing it too

![Captura de pantalla 2024-02-06 a las 15 19 59](https://github.com/googlefonts/googlesans-flex/assets/2181684/4c1d42c1-b238-4aef-8ff9-9b0b5a8e69ab)

**Comment by davelab6** [comment]
(2) is fine with me. (1) should be used in the "final v2 delivery" deck as a concept for the future, which may require HOI tooling to achieve properly.

**Comment by octaviopardo** [comment]
This one should be fixed in the last push
