### ISSUE TITLE
FB check FAIL: STAT table contains compulsory Axis Values.

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#835]
Potential solutions:

- We could adjust the 151 wdth max to be 150, (in fvar and STAT)
- Add also an entry for 151 (probably needs to be different)
- Can we use ranges flag and set 150 and 151? Would this address that FB issue?
- Decide that we keet 151 and ignore the FAIL

```
Check a font's STAT table contains compulsory Axis Values.

Check ID: com.google.fonts/check/STAT
🔥 GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf
🔥 FAIL
Compulsory STAT Axis Values are incorrect:

Name	Axis	Current Value	Current Flags	Current LinkedValue	Expected Value	Expected Flags	Expected LinkedValue
(...)
ExtraExpanded	wdth	151.0	0	None	150.0	0	None
(...)				
```

**Comment by RickyDaMa** [comment]
Related: #784

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa OK, many thanks for the updates! Now, we still get a fail on this check `Check a font's STAT table contains compulsory Axis Values.`
Let's deactivate it.
