### ISSUE TITLE
Glyphslib workaround Workflow

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#848]
In anticipation to the avar1 work:
Change the import script to:
If the avar table is not there, then add avar with empty mappings

**Comment by Hoolean** [comment]
### Notes from meeting:

We have an automated workaround in our import process that adds a 1-to-1 avar mapping prior to glyphsLib to ensure that every source is exported:

https://github.com/googlefonts/googlesans-flex/blob/476cad496df03b60d2bd22e8db2799c061e5dc9b/scripts/glyphs_to_ds.py#L50-L60

If we define a custom avar mapping for GRAD (that also covers the minimum and maximum), then we should adjust this script to only add entries for the other axes.
