### ISSUE TITLE
GRAD: even out the interpolation

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#850]
I noticed that on the 144 opsz between 200 and 650 weight axis the visual difference is bigger then 100 points.

We need to fix that either on the source level or using the avar1:

<img width="1011" alt="Screenshot 2024-02-12 at 6 44 38 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/940586da-610c-4e75-86c4-4d106bf3c5d2">

**Comment by schriftgestalt** [comment]
I got the Grader to work in Glyphs 4 (that can batter handle the big designspaces). It produces much more even grades. So avar1 might not be needed.

**Comment by MariannaPaszkowska** [comment]
fixed in #860 
<img width="807" alt="Screenshot 2024-02-13 at 7 44 16 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9fdd6cfa-067c-4e21-a4d5-848d0f73b9ec">
