### ISSUE TITLE
Improve interpolation

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#853]
Target to fix in 2.0. 
kink, mostly in Italic:
- [x] `s` - italic
- [x] `five` - upright and i
- [x] italic, very slight
- [x] `uni1E9E ẞ`  - italic
- [ ] `eth` - italic
- [x] `section`- italic
- [x] `five.tf` - upright and 
- [ ]  `five.tf` italic, very slight

[GSF-latest18.pdf](https://github.com/googlefonts/googlesans-flex/files/14186202/GSF-latest18.pdf)

_Originally posted by @MariannaPaszkowska in https://github.com/googlefonts/googlesans-flex/issues/803#issuecomment-1930781239_

**Comment by MariannaPaszkowska** [comment]
Latest report: [GSF-latest16.pdf](https://github.com/googlefonts/googlesans-flex/files/14259329/GSF-latest16.pdf)

**Comment by MariannaPaszkowska** [comment]
Locations of the bug in "s":
<img width="386" alt="Screenshot 2024-02-13 at 12 37 26 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/d3d90318-4172-4bb1-bf44-663e3f503b37">

<img width="388" alt="Screenshot 2024-02-13 at 12 39 00 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/8a7df9c5-5a94-45d8-ab9d-493bbedfc0d1">

**Comment by octaviopardo** [comment]
Top, lookign at it right now. The bugs seen in five are some of them located in the GRAD axis, but I haven t really see them in the same location in the weight+100, so before addressing them, I think we should wait to see if the new grader actually manages to solve the issue

**Comment by MariannaPaszkowska** [comment]
Many thanks! All bigger issues are resolved; there are very slight issues in "5.tf" and "eth", but it's ok to address them in the next version. Great work!

**Comment by MariannaPaszkowska** [comment]
Here is the latest interpolatable report: [GSF-latest14Feb.pdf](https://github.com/googlefonts/googlesans-flex/files/14279598/GSF-latest14Feb.pdf)

**Comment by MariannaPaszkowska** [comment]
closing because it is a duplicate of #803
