### ISSUE TITLE
Fix component positioning - small numbers on two masters

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#858]
- [x] 'opsz' 6, 'wdth' 25, 'wght' 1, 'GRAD' 0, 'ROND' 0, 'slnt' 0
- [x] 'opsz' 6, 'wdth' 25, 'wght' 1, 'GRAD' 100, 'ROND' 0, 'slnt' 0

<img width="738" alt="Screenshot 2024-02-13 at 5 33 17 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/1440df65-32c4-4c46-b467-3d5de1cc65e4">
<img width="743" alt="Screenshot 2024-02-13 at 5 41 50 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/cef2aa3d-da81-45b2-bc13-22d917fb72b4">

**Comment by octaviopardo** [comment]
this should be fixed in the last build, but it s a problem produced by the software. George is looking into a solution, so we can leave it open here as a reminder until is solved
