### ISSUE TITLE
Post v2 planning/forecasting 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#888]
Once v2.0 is done and everyone has taken the rest needed to get back into the project with full energy, the first step will be to assess timelines for extending the glyph set, and, ha ha, redrawing everything to change the way the Rounded axis interpolates.

This will mean picking a handful of key demo glyphs that have various different terminal directions/shapes, and drawing new ways for how the Round axis could handle them differently. 

Material Design team designers do want to be able to animate along the Rounded axis, and want particular care of the design at the 25/50/75/100 points. There is now also interest in the axis range from 0 to 25, and currently they see that this doesn’t look the way they want at large optical sizes and bolder weights. They are happier with the 75..100 range today than the other parts of the axis.

(They acknowledge they previously fully approved the current design :)

**Comment by schriftgestalt** [comment]
> Material Design team designers do want to be able to animate along the Rounded axis, and want particular care of the design at the 25/50/75/100 points. There is now also interest in the axis range from 0 to 25, and currently they see that this doesn’t look the way they want at large optical sizes and bolder weights. They are happier with the 75..100 range today than the other parts of the axis.

Changing the rounding approach means starting from scratch. It means substantially touching all sources and probably even adding a lot more of them. That would be a version 2.5 or probably more a 3. So another 6 month for all of us.

**Comment by MariannaPaszkowska** [comment]
Hi @davelab6 , I am working with Octavio and the teams on the estimates already. We have a brainstorming meeting planned for this Monday to discuss that.
Btw: I added a milestone for v3 https://github.com/googlefonts/googlesans-flex/milestone/11 , and we have some items collected in the backlog here: https://github.com/googlefonts/googlesans-flex/milestone/17  
We also have #804 open to discuss the language target.

**Comment by davelab6** [comment]
@schriftgestalt yuuuuuup ;)

@MariannaPaszkowska excellent thanks, i posted this so the notes i took on details from an internal meeting are captured and shared out :)

**Comment by schriftgestalt** [comment]
I’m happy to admit that I was wrong. I worked out the point structure for most of the "a" and it works very well.

**Comment by MariannaPaszkowska** [comment]
@schriftgestalt Do you mean about the rounding? Do we have a prototype that I could test? CC @octaviopardo

**Comment by schriftgestalt** [comment]
Keep it in Optical Size 18, upright and grade 0. The weight, width and rounding, should work. 
[GoogleSansFlexaVF.ttf.zip](https://github.com/googlefonts/googlesans-flex/files/14424405/GoogleSansFlexaVF.ttf.zip)

I needed to add an self overlap to avoid a kink:
<img width="652" alt="Bildschirmfoto 2024-02-27 um 19 52 05" src="https://github.com/googlefonts/googlesans-flex/assets/174660/9468106b-afb1-45c4-a65e-26a10d90a60a">

And here the file if someone likes to have a look:
[GSF-full a.glyphspackage.zip](https://github.com/googlefonts/googlesans-flex/files/14424447/GSF-full.a.glyphspackage.zip)

**Comment by chrissimpkins** [comment]
What is v3.0 release actionable in this issue report?

**Comment by MariannaPaszkowska** [comment]
Reopening as we actually still need to approve the round designs and this issue will be used for QA to check against the request.
