### ISSUE TITLE
Fix tt ligature crossbar to be pixel perfect on Android

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#901]
An internal user [reported an issue](https://b.corp.google.com/issues/200611569) with GS (not Flex) `tt` ligature glyph rendering on Android, where there is an expected perfect pixel alignment of the crossbar, and yet it doesn't render that way:

![tt ligature pixel unalignment](https://github.com/googlefonts/googlesans-flex/assets/261579/3e017dea-c9a0-42be-9f3e-dff674f1f20c)

I downloaded go/fonts/specimen/Google+Sans and go/fonts/specimen/Google+Sans+Flex land looked at the roman TTFs in https://www.axis-praxis.org/samsa/ and see:

<img width="602" alt="tt ligature vectors in GSF" src="https://github.com/googlefonts/googlesans-flex/assets/261579/0acdb857-a50e-427f-a4e9-ce5d3d41326c">

The crossbar of the ligature is made of 2 overlapping components. 

It is possible to 'transform' components, so I propose removing one rectangle and stretching the other to have the same area and position as the previous combination. This should produce zero change in ink in most scenarios, and remove the double-printing where it is seen.

**Comment by davelab6** [comment]
I also posted this as a FB check proposal @ https://github.com/fonttools/fontbakery/issues/4593

**Comment by MariannaPaszkowska** [comment]
Hi Dave, which version of the font was that?

**Comment by MariannaPaszkowska** [comment]
note to self: we should also check the overlap settings for this glyph

**Comment by simoncozens** [comment]
Overlap settings look good - is there any chance the rasterizer has been fixed, because on a Pixel 8 all looks well:
![PHOTO-2024-03-14-14-58-23](https://github.com/googlefonts/googlesans-flex/assets/106728/2faf4221-be0d-40b4-86b3-75c91f64bd57)

**Comment by MariannaPaszkowska** [comment]
@davelab6 shared that the reporter says it's a current issue. 
I posted other glyphs that might have similar issues in the same environments and a suggested solution here: https://github.com/googlefonts/googlesans/issues/624#issuecomment-1999349332

**Comment by MariannaPaszkowska** [comment]
@simoncozens did you check both GS and GSF?

**Comment by davelab6** [comment]
Curious! The user said last week,

> I still observe the issue on my up-to-date Android 14 with default font and font size.

**Comment by davelab6** [comment]
@MariannaPaszkowska, @simoncozens and I discussed this with a small group today, and Marianna is going to check in with @chrissimpkins about it and perhaps she and DaMa can supply 2 test files with her and my proposed solutions to see if those change anything. 

@MariannaPaszkowska also noted that v12 release was due at the end of this month, so was expecting to wrap DaMa effort next week; I'm not sure when v13 might happen so my guess is that it will be ok to delay v12 by 1-2 weeks to fix this, but I defer to @chrissimpkins :)

@simoncozens how did you test? I think we don't have a good font testing rig for this kind of issue; @chrissimpkins worked on an Android font testing app in 2018 or 2019, but I don't know we can spare his dedicated time to pick that back up... but perhaps @simoncozens can.

**Comment by simoncozens** [comment]
I have an intern who would very much like to work on this.

**Comment by chrissimpkins** [comment]
How did we end up approaching this?

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins We updated all of the ligatures that had overlapping crossbars and took similar approach like in GS: https://github.com/googlefonts/googlesans/issues/624
