### ISSUE TITLE
Review PANOSE values across masters

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#903]
Off the back of last meeting, I was wanting to look at how our PANOSE values varied across masters to try and work out what I should be setting the values to for our static generation

What I found was that all our PANOSE values are the same across all masters currently: `2, 11, 5, 3, 3, 5, 2, 4, 2, 4`

From my limited understanding of PANOSE, some of these values should vary as we move along axes (e.g. `bWeight`). Maybe we should look into updating this?

**Comment by MariannaPaszkowska** [comment]
Yes, indeed, we should update those for the statics. 
`bWeight` should change as the weight changes, `bProportion` should change as the width changes, 
then `bSerifStyle` should switch between Sans Serif and Rounded, and `bLetterform`  (`Normal/Boxed` to `Oblique/Boxed`) should vary depending on if the font is Italic. 
@octaviopardo we should update the panose settings for the next release.

**Comment by MariannaPaszkowska** [comment]
Panose values per location:

Google Sans Flex 144-opsz 100-wdth 0-ROND `bProportion=3`, `bSerifStyle=11`
Google Sans Flex UltraCondensed 144-opsz 50-wdth 0-ROND `bProportion=7`, `bSerifStyle=11`
Google Sans Flex SuperCondensed 144-opsz 25-wdth 0-ROND `bProportion=8`, `bSerifStyle=11`
Google Sans Flex Rounded 144-opsz 100-wdth 100-ROND `bProportion=3`, `bSerifStyle=15`
Google Sans Flex Text 12-opsz 100-wdth 0-ROND `bProportion=3`, `bSerifStyle=11`
Google Sans Flex ExtraExpanded 144-opsz 150-wdth 0-ROND `bProportion=5`, `bSerifStyle=11`

Italics: `4 Normal/Boxed` changes to `11 Oblique/Boxed`

`bWeight` for weights:
100 `bWeight=2`
200 `bWeight=3`
300 `bWeight=4`
400 `bWeight=5`
500 `bWeight=6`
600 `bWeight=7`
700 `bWeight=8`
800 `bWeight=9`
900 `bWeight=10`

**Comment by RickyDaMa** [comment]
Just double checking as I'm writing the logic, anything you've not specified in the previous message I'll leave the same as it currently set

That is:
- `bFamilyType` is 2
- `bContrast` is 3
- `bStrokeVariation` is 5
- `bArmStyle` is 2
- `bMidline` is 2
- `bXHeight` is 4

All good?

**Comment by belluzj** [comment]
Merged as part of https://github.com/googlefonts/googlesans-flex/pull/900
