### ISSUE TITLE
check "do not export" setting support

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#904]
_Originally posted by @MariannaPaszkowska in https://github.com/googlefonts/googlesans-flex/issues/902#issuecomment-2015291388_

From @octaviopardo 

_those two marks are actually bars we created to build components but in the glyphs file they are set as " do not export". They are the stroke short comb (used for glyphs like hbar or eth) and the slash short comb, for lslash. The only reason why we created them was to ensure that we compose those glyphs using components with automatic alignment. However stroke short comb was eventually decomposed in hbar and eth, before production, since the base glyphs (h and d) were also decomposed to slightly adjust their height and visually compensate the additional dark area on top._

It seems that we don't need those two glyphs in the fonts. Those should be decomposed and excluded.
Does it mean that something goes wrong during the conversion from .glyphspackage to UFOs? Does our pipeline ignore "do not export" settings? 
If so we need to think about how to address this.

Can we subset those in the statics?

**Comment by belluzj** [comment]
We'll need to review these two steps:
* decomposing of components -> being investigated by @RickyDaMa in https://github.com/googlefonts/googlesans-flex/pull/902#issuecomment-2015291388
* exclusion of "do not export" glyphs by glyphsLib -> TODO check that it happens
* pruning of un-needed glyphs from the font binaries, which is already implemented in the pipeline for both VF and instances, using the script `prune_font_binary.py` that calls the fontTools subsetter -> TODO check if the useless glyphs remain in the font despite these build steps

**Comment by RickyDaMa** [comment]
> exclusion of "do not export" glyphs by glyphsLib -> TODO check that it happens

This has also been updated/fixed/discussed in #902 (48df175f80381de84eb33ca9fe6cee12176f5fc5)

The only work left here is the final point of checking for useless glyphs despite pruning efforts

**Comment by RickyDaMa** [comment]
Fontbakery testifies we have no unreachable glyphs in latest builds
