### ISSUE TITLE
edit Rounding

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#905]
An issue to discuss the rounding refactor planned for the GSF v3.0

**Comment by davelab6** [comment]
Feedback from MD team on the first `a` concept of the New Rounding approach: 

> Overall, we're really liking the new approach! 
>
> I just called out a few small things that I want to ask about, where there's a little pinch or wobbliness in the transition. (I'm assuming this is probably because it's more of a  quick test.) 
>
> For the next review, please could we test a few additional characters to form a word to play around with.”
> 
> ![unnamed (2)](https://github.com/googlefonts/googlesans-flex/assets/261579/561872ba-576d-4d6a-a4f3-475353a1f7f1)
> ![unnamed (3)](https://github.com/googlefonts/googlesans-flex/assets/261579/10581dda-da68-4936-8cba-a613b1090889)
> ![unnamed (4)](https://github.com/googlefonts/googlesans-flex/assets/261579/de647739-3208-4494-9659-8cfe94d78f30)
> ![unnamed (5)](https://github.com/googlefonts/googlesans-flex/assets/261579/f176bc1a-8e52-4dcd-9f96-2528b1f20df1)

(Same info also made as [google slides](https://docs.google.com/presentation/d/1UdqN8JOYCChKPZ5VRASKqvHJP79PGj8J4w7m7hvO2X4) form)

**Comment by chrissimpkins** [comment]
Requested axis settings to reproduce this

**Comment by davelab6** [comment]
ROUND at 30, 60, 100; Weight at 300, 600, 800

**Comment by MariannaPaszkowska** [comment]
@schriftgestalt Do you think that we could do better with the current interpolation model? Would we need intermediate masters?

**Comment by schriftgestalt** [comment]
I improved the top left round corner slightly (18, 400, 100):
<img width="304" alt="Screen Shot 2024-04-19 at 19 11 04" src="https://github.com/googlefonts/googlesans-flex/assets/174660/0ff320b8-0837-4caa-a789-9abe5bf90f66">

what is wrong with the second to last image?

The last image is the round master. That can be drawn whoever we like. That just needs some fiddling.

**Comment by MariannaPaszkowska** [comment]
The second to last seems correct to me. It seems like an inktrap. Would that be correct @octaviopardo ?

**Comment by octaviopardo** [comment]
Yes, That is an inktrap. Nothing to change there

**Comment by chrissimpkins** [comment]
@octaviopardo Will you please update this thread with a summary of the rounding changes that we will land in v3.0.  I'd like to record this for posterity.  Let's link the script used to achieve the new rounding, what changes in the outlines, and if there is going to be a file size impact as a result of those changes.  Thanks!

**Comment by chrissimpkins** [comment]
Recording here also that we need a final rounding revision deliverable presentation deck from Octavio to put this in front of Material UX for review before we release.
