### ISSUE TITLE
Release v2.1 as wght axis fonts instead of static fonts, and rename the default width family

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#932]
Following #897 and https://github.com/googlefonts/googlesans-flex/releases/tag/v2.001 there was internal discussion at [b/333400350](https://b.corp.google.com/issues/333400350) on how to onboard these, and 2 requests have come back

-  [ ] Append ` Normal` to the family name of the static family previously released as `Google Sans Flex`, due to a CSS API namespace collision with the current VF. The complete set of family names is thus now:

```
Google Sans Flex ExtraExpanded
Google Sans Flex Normal
Google Sans Flex Rounded
Google Sans Flex SuperCondensed
Google Sans Flex Text
Google Sans Flex UltraCondensed
```

- [ ] Subspace the VF to a 100..900 wght axis only, instead of fully instancing the VF to all the statics, for Roman and Italic. While Workspace doesn't use the VF, the API will instance the API wght axis 100..900 and ital 0..1 into 9x2 statics for Workspace, like all other VF families, and will auto upgrade to VFs as they are supported by Workspace in time. 

- [ ] Include a README.md file in the release suitable for google3 that explains these families should be hidden from catalog surfaces and only shown in Workspace, a link to the build script used to make them, this issue & #897, etc :)

**Comment by chrissimpkins** [comment]
These remain Workspace-only build targets and should continue to be packaged as a separate Workspace-specific zip archive on the releases.

**Comment by chrissimpkins** [comment]
Optical size instances for the families that Dave listed above:

## 144pt

- Google Sans Flex ExtraExpanded
- Google Sans Flex Normal
- Google Sans Flex Rounded
- Google Sans Flex SuperCondensed
- Google Sans Flex UltraCondensed

## 12pt

- Google Sans Flex Text

**Comment by chrissimpkins** [comment]
How will fvar and STAT table definitions need to be revised in the new Workspace VF builds?

**Comment by davelab6** [comment]
> How will fvar and STAT table definitions need to be revised in the new Workspace VF builds?

They will need the normal wght axis entries :) Should be straightforward

**Comment by RickyDaMa** [comment]
> Subspace the VF to a 100..900 wght axis only, instead of fully instancing the VF to all the statics, for Roman and Italic. While Workspace doesn't use the VF, the API will instance the API wght axis 100..900 and ital 0..1

Hey @davelab6, I've started poking at these changes and will hopefully open up a draft PR this week. Just wanting to confirm, which are you wanting:

- VF on just the weight axis, with italic and upright separate TTFs
- VF on weight & slant (-10..=0)
- VF on weight & italic (0..=1)

Thanks!

**Comment by MariannaPaszkowska** [comment]
Hi @RickyDaMa We will not do slant/italic axis but instead separate upright and italic fonts.
So the first option.

CC @davelab6

**Comment by MariannaPaszkowska** [comment]
QQ: does the fontTools subsetter subsets STAT tables?

STAT should contain only the weight axis entried, identical to fvar. and it will be different then GSF, because we only will support 100-900 range.

**Comment by RickyDaMa** [comment]
> QQ: does the fontTools subsetter subsets STAT tables?

Yes, seems so. Hairline and UltraBlack aren't present here but are in the main VF

![image](https://github.com/googlefonts/googlesans-flex/assets/113340856/692a5465-2fdd-453e-863b-158530a7bbb4)
