### ISSUE TITLE
tnum: tabular space (space.tf) advance width in Google Sans Flex vs. Google Sans

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#937]
There has been some product team interest in the GS + GSF tabular figure support.  As I was looking into how we support tnum across the families, I noticed that we made different decisions about how to approach the advance width for the space character in GS and GSF.

### Google Sans approach

space.tf is half of the tabular width

![6BNkzx2Ckqp9hVe](https://github.com/googlefonts/googlesans-flex/assets/4249591/51564fae-dd82-47bb-b2d7-791957c05a84)

### Google Sans Flex approach

space.tf is the full tabular width

![93yQLfGFwJ6BDii](https://github.com/googlefonts/googlesans-flex/assets/4249591/c4a2de43-8660-4747-90aa-f292bbc9d3b0)

---

Full tabular width spaces feel really wide.  Is there a target use case where we want spacing this wide when tnum is toggled on?  

Let's decide the best approach to use in the GS families, and decide if and how to make it consistent across GS and GSF.

**Comment by octaviopardo** [comment]
The reason why this happened is a mix of several factors, but I agree that a full tf width space is not very nice looking. I already changed it in the 2.3 version to imitate the GS approach

**Comment by chrissimpkins** [comment]
Perfect!

**Comment by chrissimpkins** [comment]
It looks like we also have tabular punctuation in GSF that does not exist in GS.  @MariannaPaszkowska Why don't we chat about the need to develop the same set of tabular designs in the GS family on a GS repo tracker.

**Comment by chrissimpkins** [comment]
@octaviopardo if these changes already landed in main, please feel free to close this issue. Ty!

**Comment by MariannaPaszkowska** [comment]
Notes from the meetings: we will change the space.tf to half tabular width in 2.003. In progress
