### ISSUE TITLE
Disable `cu2qu` and remove `EraseOpenCorners` filter

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans-flex#942]
As discussed in the meeting, we are okay to disable cu2qu and EraseOpenCorners, and hopefully enjoy some build speed-up

Tasks:

- [x] Write a Fontbakery sources check that validates that all our sources are quadratic
- [x] Write a Fontbakery sources check that validates all our sources have no open corners (they shouldn't due to the constraints rounding puts on the design)
- [x] Update `glyphs_to_ds.py` to remove the lib key that causes `EraseOpenCorners` to be run
- [ ] #945
- [ ] ~~Discuss with gftools configuration support for quadratic sources and/or fontmake automatically detecting source time and disabling `cu2qu` when appropriate~~

---

Potential performance improvement raised by @anthrotype in https://github.com/googlefonts/googlesans-flex/pull/902#issuecomment-2098211319:

> By the way, don't know if you know, if your sources only contain TrueType quadratic curves and no cubic beziers, you can tell fontmake to skip cu2qu step altogether. There's a --ttf-curves option that controls this:
>
> https://github.com/googlefonts/fontmake/blob/8305773a3a495750832b2f1929eeb83c9cefdae5/Lib/fontmake/__main__.py#L449-L459
>
> basically fontmake by default runs cu2qu to convert all cubics to quads; if there are only quads like in your case it's no-op but still may take some time to process all glyphs. If you set it to --ttf-curves=keep-quad it will attempt to compile the curves as is (and potentially fail with an error if they actually aren't as told).

---

In theory the cu2qu pass the compiler performs now is redundant, as our sources are already quadratic, although we would still need to be careful when removing it:

- Correct outline direction must be preserved
- Open corners must be removed on the correct side
  - See https://github.com/googlefonts/googlesans-flex/pull/902#issuecomment-2088552652
- Compatibility checking must be kept as strict
  - See googlefonts/fontmake#1091

Prior to checking these details of the end result, we could do a test build without cu2qu to see if the compilation time reduction is significant.

**Comment by RickyDaMa** [comment]
Update - I benchmarked the performance numbers to see what gains we might stand to make here. The short version is everything is within margin of error

|                                     | **With cu2qu** | **Without cu2qu** |
|------------------------------------:|----------------|-------------------|
|    **With EraseOpenCorners filter** | Baseline       | Kinda same        |
| **Without EraseOpenCorners filter** | Kinda same     | Kinda same        |

On my dev machine:

![image](https://github.com/googlefonts/googlesans-flex/assets/113340856/8c6d76c1-68ed-42f7-a3ba-dbf1126e0eb7)

![image](https://github.com/googlefonts/googlesans-flex/assets/113340856/8cd26da5-b23f-4af7-bbf4-a3fe78f952de)


Tested with the following invocation:

```shell
hyperfine -w 1 -r 5 \
    -n "With cu2qu" 'venv/bin/fontmake -m sources/GoogleSansFlex.designspace -o variable --output-path /dev/null' \
    -n "Without cu2qu" 'venv/bin/fontmake --ttf-curves=keep-quad -m sources/GoogleSansFlex.designspace -o variable --output-path /dev/null'
```

In English: 1 warm-up, then 5 runs of building the VF with fontmake. To test without the filter, I just find+replaced all the lib keys and re-ran the above

**Comment by anthrotype** [comment]
thanks for the benchmarks! yeah, probably not worth it after all
