### ISSUE TITLE
`zero` & `tnum` features not working in combination

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#957]
@MariannaPaszkowska tiny bug confirmed about `zero` vs `tnum` features:

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/9b052880-2f9f-4cbe-b376-a68299fbbd93)

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/3ca9901d-f8b7-491f-a837-cedc0521cb93)

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/aeb1d8e7-fda8-4eb7-8dc5-3aac7b951851)

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/2e569b1d-4d79-4ae4-b2db-f619e9979435)

_Originally posted by @belluzj in https://github.com/googlefonts/googlesans-flex/pull/953#discussion_r1660795910_

---

Marianna prefers option 1

**Comment by octaviopardo** [comment]
Option 1 applied in the next build. TOp!

**Comment by MariannaPaszkowska** [comment]
Let's close this issue after it is imported and merged into main.

**Comment by m4rc1e** [comment]
Can confirm this has been fixed

<img width="1278" alt="Screenshot 2024-07-18 at 09 23 11" src="https://github.com/user-attachments/assets/b1558914-d0a0-4beb-a1d5-0583f762932a">


@MariannaPaszkowska @RickyDaMa Should I be writing unit tests so we don't get regressions?

**Comment by RickyDaMa** [comment]
> Should I be writing unit tests so we don't get regressions?

This is what #953 covers, I'll get that updated now the import has been merged to lock in feature behaviour

**Comment by m4rc1e** [comment]
Awesome. Thank you very much!

**Comment by RickyDaMa** [comment]
> Let's close this issue after it is imported and merged into main.

Looking good here :)
