### ISSUE TITLE
Dead code: `case` feature

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#958]
@MariannaPaszkowska very minor, the automatic `case` feature is not needed, as the glyphs `periodcentered.loclCAT` and `periodcentered.loclCAT.case` are only used as components in `ldot` and `Ldot`, but are not produced by features, so they shouldn't appear in the glyph stream on their own. It's not really a bug though, just extra feature code that is not needed (and so, not testable, since it's not possible to reach it).

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/4f04d575-34b9-4ba7-866c-77e168a1fa18)

_Originally posted by @belluzj in https://github.com/googlefonts/googlesans-flex/pull/953#discussion_r1660809295_

**Comment by octaviopardo** [comment]
Top, fixed in the next build

**Comment by MariannaPaszkowska** [comment]
Let's close this issue after it is imported and merged into main.

**Comment by MariannaPaszkowska** [comment]
@octaviopardo In the future could you please label issues that are done in a branch ad "-ready for review"?

**Comment by m4rc1e** [comment]
Just checked the latest merge, which happened yesterday and the code is still in the .fea files.

<img width="581" alt="Screenshot 2024-07-18 at 09 17 16" src="https://github.com/user-attachments/assets/63b5a604-dbdb-4e83-be78-99ef45ea1fe4">

**Comment by RickyDaMa** [comment]
Just noticed this again today, fontmake is warning about references to the `case` feature in `aalt` blocks when the feature isn't otherwise defined:

https://github.com/googlefonts/googlesans-flex/blob/8fdf84be01338ef3888925cd4ceeb1805dee0c50/sources/GoogleSansFlex-wg1000-wd25-oz18-GD100-RD0-sl0.ufo/features.fea#L57-L74

(line 72)

**Comment by RickyDaMa** [comment]
Discussed in meeting: it's not the code in the red box that needs removing, it's the lookup referring to `/periodcentred.loclCAT` in `case`. Because `case` only has this one rule in it, it can be removed entirely

@octaviopardo

**Comment by MariannaPaszkowska** [comment]
#1102
