### ISSUE TITLE
GitHub Actions custom googlefonts org runner environments are not functioning correctly

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#961]
The custom GitHub Actions workflow runner environments began hanging without a timeout in the last week.  Reported by Octavio in the last 24 hours.  Reported by @justvanrossum beginning ~ Thursday on our CJK development repo.

e.g., https://github.com/googlefonts/googlesans-flex/actions/runs/9815702771

**Comment by chrissimpkins** [comment]
@RickyDaMa @octaviopardo mind pointing me to a commit run where we experienced the issue?  It is that the runner never builds the font files and continues to run without a time out?

**Comment by chrissimpkins** [comment]
As a first step to see if it fixes the issue, let's modify the previous configuration approach:

```
runs-on: [linux, googlefonts-64cores-256GB]
```

as defined in https://github.com/googlefonts/googlesans-flex/blob/6c421734c091c3a5c1a3d0128f71e8663cd451f4/.github/workflows/build-glyphs.yml#L12

to the following:

```
runs-on: googlefonts-64cores-256GB
```

This is the current configuration documentation for how we define the use of this runner environment

![C8P3mjgsvxPyKwv](https://github.com/googlefonts/googlesans-flex/assets/4249591/6658a0f2-f2a5-4a2f-8fdf-37ac3ab6e883)

**Comment by RickyDaMa** [comment]
Example job that's hanging / given up with no runner available: https://github.com/googlefonts/googlesans-flex/actions/runs/9815702771

**Comment by chrissimpkins** [comment]
Thanks!  Mind changing the configuration to the one defined in https://github.com/googlefonts/googlesans-flex/issues/961#issuecomment-2217884584 so that we can confirm that they are not working with the latest approach that GitHub defines to use custom runners?  If that does not fix it, I'll reach out to GH support.

**Comment by RickyDaMa** [comment]
> Mind changing the configuration...?

See #962 and it's current build attempt [here](https://github.com/googlefonts/googlesans-flex/actions/runs/9858983266?pr=962). Looks to be experiencing the same issue

**Comment by chrissimpkins** [comment]
Seems to be running

![9j3TbhteG8enRPg](https://github.com/googlefonts/googlesans-flex/assets/4249591/2e0fbe2b-797d-4ccb-b48e-47c19079b7ba)

**Comment by RickyDaMa** [comment]
Well that'll be a nice relatively easy fix if so, feel free to merge it

**Comment by chrissimpkins** [comment]
No errors being reported on the admin panel during the run.  We have an allotment of up to 99 concurrent jobs.  Not bumping into that issue.

![tJaBH8bmNPhWsNi](https://github.com/googlefonts/googlesans-flex/assets/4249591/aa55ea33-0e97-43f7-a201-e63c0a9b52f0)

**Comment by chrissimpkins** [comment]
@justvanrossum mind changing your CJK repo workflow configuration to the one described in https://github.com/googlefonts/googlesans-flex/issues/961#issuecomment-2217884584 so that we can verify the fix on your repo too?

**Comment by chrissimpkins** [comment]
We merged https://github.com/googlefonts/googlesans-flex/pull/962

We still need to confirm that the test/tests workflow completes succesfully.  Test run in https://github.com/googlefonts/googlesans-flex/actions/runs/9859595289

**Comment by RickyDaMa** [comment]
Aha, I think this has pointed to our issue (from the link above):

![image](https://github.com/googlefonts/googlesans-flex/assets/113340856/5262fa13-d941-4f82-aa05-56c983d7b65b)

**Comment by chrissimpkins** [comment]
Yep.  We missed a deprecation warning.  OK that is good to know. We have a fix confirmed. Thanks for your help troubleshooting this Ricky.

https://github.com/googlefonts/googlesans-flex/actions/runs/9859595289/job/27223972874 ran without issues.

We should update our custom GHA runner configs on all repos where they are used.

**Comment by RickyDaMa** [comment]
> We should update our custom GHA runner configs on all repos where they are used.

I'll look into it this afternoon & tomorrow 👍

**Comment by RickyDaMa** [comment]
Opened https://github.com/googlefonts/googlesans/pull/635

Of all the private Google font repos I'm in, Google Sans is the only other one that uses the custom runners, most are using the GitHub provided ones. Maybe you can check a billing statement or something for the high-end runners to see if there are any more repositories using them?

**Comment by chrissimpkins** [comment]
Our GS CJK repos definitely use the custom runners. I reached out to Just today to test the change there.  He moved over to the default runner last week when he identified the issue.  I'm not aware of any other repositories where they are in use.  I'll see if I can track down some run logs.  No need to look into or address anything other than the ones that you've set up across the GS families.  Thanks Ricky!

**Comment by chrissimpkins** [comment]
I filed a GitHub support issue.  The problem is fixed on this repository.  Let's leave this tracker open until Just has a chance to test on the CJK repo.

**Comment by justvanrossum** [comment]
We were using one of the lower (the lowest?) specced googlefonts runners, and it turns out the current regular runners perform equally well (the running times don't differ significantly), so for us it currently makes no sense to even use the googlefonts runner.

I understand the problem was caused by the deprecated runner label syntax (we also completely missed a warning for that), and am confident we can use it again once we have a need for it again.

**Comment by chrissimpkins** [comment]
Thanks Just.  Ok we will close this as fixed then.  If you run into any issues if you transition back down the road, please let me know.

**Comment by chrissimpkins** [comment]
GitHub support responded and there is no issue with billing.  The bills will not reflect the actual runner execution time recorded in the commits over the last week.  All good.  Thanks all for your help troubleshooting and fixing the issue here.
