### ISSUE TITLE
Test smaller GitHub Actions runner performance

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#963]
Opening this issue following our investigation into #961.  We're using the largest googlefonts org GitHub Actions runners to build and CI test the Flex project.  This might be more metal than we really need and it is the most expensive runner environment, billed on per minute use.  Let's test the memory / CPU requirements to confirm that we need the 256GB + 64 core environment.

Other supported options include:

![6gKNHbvZgZpvewe](https://github.com/googlefonts/googlesans-flex/assets/4249591/8f6ee675-fbeb-4715-a424-1a4d8165f3ba)

I also suggest that we throw the higher performance environments at the most computationally intensive tasks.  We could use an approach to throw more computation power at compiles and less at CI tests or vice versa based on actual requirements, rather than a one size fits all approach across everything that we run in the GitHub Actions environment.

Not urgent. But let's look into it during Q3. We want to be able to support fast compiles and fast tests.  There is no intent to slow development times to reduce cost.  Let's attempt to avoid unnecessary costs if they are truly unnecessary and our development time is not impacted by the change.  Thanks.

**Comment by MariannaPaszkowska** [comment]
We will look into that!

**Comment by RickyDaMa** [comment]
Marianna to confirm with Chris how in-depth we want to test. Something like 3 runs of each would be a baseline for reliable results, the more the merrier naturally (but also more expensive)

Will take some extra work to make tests get updated without using main directly due to how workflows are configured currently. Marianna happy to give me temporary push rights to `main` if needed

**Comment by chrissimpkins** [comment]
Let's please make this happen. It should not be diffcult.  I suggest that we simply edit all of the configuration files to use the 8core-32GB runner and use it.  If we run into problems, let's scale up to the next available larger size.  Thanks
