### ISSUE TITLE
Review the timeout settings for the runners

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#964]
Let's see if we can improve the timeout settings. more details TBD

**Comment by RickyDaMa** [comment]
The timeout settings are already relatively conservative. I'd warn against trying to reduce them further as if we start getting builds that are running without issue getting stopped by the timeout, the resulting process to increase that timeout is going to incur more billable costs than you potentially stand to save. Especially as the scope of Flex increases, this situation would become increasingly likely, and we may even run up against the time limits we have in place now.

**Comment by MariannaPaszkowska** [comment]
Thanks, @RickyDaMa This was following the situation from last week: https://github.com/googlefonts/googlesans-flex/issues/961 Are there any ways we can prevent builds hanging when they cannot locate the runner (like in this example of the deprecated runner label syntax)?

**Comment by RickyDaMa** [comment]
I don't believe so, no. I can't see anything in documentation. It's not billable time though so it needn't be a concern. I would be happy to close the issue on this repository as I don't think any further work is needed

I'll open a related issue on Google Sans later today, as that doesn't have explicit timeout periods for the workflow runs (i.e. billable time) and it would be good to have that in place

**Comment by RickyDaMa** [comment]
Opened https://github.com/googlefonts/googlesans/issues/636, which I'll try and get to soon

**Comment by RickyDaMa** [comment]
Closing this as I don't think there's anything further we can do here, and there's a tracking issue for Google Sans
