### ISSUE TITLE
review the height of the accents in uppercase across the designspace

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#967]
context #965

**Comment by octaviopardo** [comment]
it will be a good chance also to review the size of quotes and comma in the opsz144-wght1 styles; and then reasses if we can replace okina by the quoteleft component

**Comment by chrissimpkins** [comment]
This is only about changes to support Hawaiian? If so, low priority for v3.0 but we'll take it if there is time for it.  If this is about a wider objective to review UC marks, please document the rationale so that we can decide the priority level here.

**Comment by octaviopardo** [comment]
partially. CJ dunn made an obseration about the position of accents in certain parts of the design space (extreme masters like osz144-151-1000) and I tended to agree with him. Reviewing he height meant in all cases bringing them down, so I think it should be a great chance to address also the current android issue we have with accents

**Comment by octaviopardo** [comment]
Changes introduced:
6-25-400: adjustment of dieresis
6-25-1000: only lower macron, dieresis, tilde
6-100-1: lower all
6-100-400: lower all
6-151-1: lower all / dieresis macron dot accent
6-151-400: only lower macron, dieresis, breve, caron


18-25-1: lower breve
18-25-1000: lower breve and hungarmlaut
18-100-1: lower all
18-100-1000: lower all
18-151-1: lower all / breve
18-151-400: only lower acute, grave, circumflex, hungarumlaut. Hungarumlaut more separated and slanted round fixed, deeper angle
18-151-1000: all lower / circumflex narroer / dieresis, slightly smaller dots / hungarumlaut more separated

144-25-1: hungarumlaut thinner
144-25-1000: hunagumlaut base of the stroke thinner
144-100-1: all accents lower / circumflex a bit thicker / hook smoother curve
144-100-400: all accents lower
144-100-1000: hook wider
144-151-1: all accents lower / hungarumlaut more separated / acute and grave less inclined
144-151-400: all accents lower /  acute and grave less inclined / circumf narrower / macron & tilde narrower / hungarumlaut less inclined
144-151-1000: all accents lower / dieresis narrower and smaller dots / hungarumlaut, better centered
