### ISSUE TITLE
Customise mismatching-tabular-widths FB check

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#973]
Can we modify the test to exclude the space.tf character? This is intentional https://github.com/googlefonts/googlesans-flex/issues/937 

🔥 GoogleSansFlex-wg1000-wd25-oz144-GD100-RD100-sl-10.ufo
🔥 FAIL
layer 'public.default':

- space.tf (455) has different width than zero.tf (910)
[code: mismatching-tabular-widths]

**Comment by RickyDaMa** [comment]
I'll work on this now. It's a private check so we can quickly get this one fixed
