### ISSUE TITLE
Benchmark / Compare build & test times with different GitHub Action runners

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#978]
Currently we're using the fastest & bestest `googlefonts-64cores-256GB` just because we know Flex is monstrous, however given the eagerness to reduce CI costs, we should do some experimentation and see if there's a better value-for-speed proposition to be found elsewhere, given Python isn't renouned for being parallel.

Note: testing will have to be done on the runners and higher quality results will cost more for things like repeated runs & more granular testing

cc @chrissimpkins for suggesting we try this out at some point

TODO: decide on a test approach and get the thumbs up for giving it a go

**Comment by chrissimpkins** [comment]
Related https://github.com/googlefonts/googlesans-flex/issues/963

**Comment by RickyDaMa** [comment]
Ah shoot, didn't realise this was a duplicate, my bad
