### ISSUE TITLE
Review of Adjusted Hooked Letters by Mark and Neil from Jamra-Patel

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#984]
Review of Adjusted Hooked Letters by @MarkJamra and @NeilSureshPatel 

"Observations
Overall, the revised hooks are greatly improved. The ɓ and ƙ look good across all instances.

The decision to flatten the exit of the hooks on the diagonal strokes of Ƙ, Ƴ and ƴ is a good one as it harmo-
nizes them to hooks on the ɓ, ɗ and ƙ. However, this has made them harder to distinguish from their un-
hooked counterparts particularly for the wght=1 instances. Though this is arguably less of a concern for the

opsz=144 instances we have been given to the review, it will be a concern for the equivalent opsz=6 and 18
instances which are in the design space.

The Ƙ and Ƴ in the rest of the opsz=144 instances are okay though the hook on the ƴ seems to be consist-
ently more abrupt as compared to the Ƴ. Again less of a problem at 144pt, but there would be some benefit to

making adjustments.
Probably we are reviewing too many opsz=144 instances which are less susceptible to legibility concerns.
Looking at the opsz=144 instances at 18pt suggests that there could be legibility problems with the ƴ at
smaller optical sizes.
Distinguishing between Ƙ, Ƴ and ƴ and their unhooked counterparts in the opsz=18/wdth=25 instances is
really difficult though there is a limit to the improvements that can be made.
Recommendations
We believe the priority is modifying the wght=1 instances.
opsz=144 wdth=100 wght=1 GRAD=0 ROND=0 slnt=0
opsz=144 wdth=100 wght=1 GRAD=0 ROND=0 slnt=-10
opsz=144 wdth=25 wght=1 GRAD=0 ROND=0 slnt=0
opsz=144 wdth=25 wght=1 GRAD=0 ROND=0 slnt=-10
The best solution is to steepen the diagonals and start the curvature much earlier. on the following page we
show how this would work on a single instance to demonstrate how the hook can be made more prominent
without adding/removing nodes or changing side bearings. The exit of the hook also remains unchanged.
(See pg 2)
Reducing the abruptness of the hook on the ƴ in remaining instances would make an improvement though
this is a lesser priority. The solution for folowing instances is the same as as above. This method can also be
used to control the wifth of the Ƴ for these instances. (See pg 2)
opsz=144 wdth=151 wght=400 GRAD=0 ROND=0 slnt=0
opsz=144 wdth=151 wght=400 GRAD=0 ROND=0 slnt=-10
For the following instances the ƴ can be improved byt reducing the weight in the upper left corner of the
hook. (See pg 3)
opsz=144 wdth=25 wght=1000 GRAD=0 ROND=0 slnt=0
opsz=144 wdth=25 wght=1000 GRAD=0 ROND=0 slnt=-10
opsz=144 wdth=25 wght=1000 GRAD=0 ROND=0 slnt=0
opsz=144 wdth=25 wght=1000 GRAD=0 ROND=0 slnt=0
"

<img width="746" alt="Screenshot 2024-07-18 at 6 36 12 PM" src="https://github.com/user-attachments/assets/6ec3e41c-83bf-4d86-91e0-512f9053526a">

<img width="751" alt="Screenshot 2024-07-18 at 6 36 36 PM" src="https://github.com/user-attachments/assets/478a0412-1348-4989-ab16-e0ded813dec8">

<img width="777" alt="Screenshot 2024-07-18 at 6 36 50 PM" src="https://github.com/user-attachments/assets/6f65b68b-8e43-474a-92b5-49f6e5baefda">

<img width="786" alt="Screenshot 2024-07-18 at 6 37 04 PM" src="https://github.com/user-attachments/assets/d32c3435-465d-48db-9be1-57ed1e9e90df">

See the full document with more proofs here: 
[Revised Hooks Review 071124.pdf](https://github.com/user-attachments/files/16285547/Revised.Hooks.Review.071124.pdf)

**Comment by moyogo** [comment]
The hooks of capitals Ƙ and Ƴ should harmonize with those of capitals Ɓ and Ɗ first, or even that of capital J. They can be flatter but should be as salient. Making the letters confusable with hookless letters should be avoided.

**Comment by moyogo** [comment]
For context, ƘƳƴ were as they were based on 1930s-1990s designs of Ƙ:
<img width="328" alt="Ƙoƙi - 10 1017:S0041977X0012419X_" src="https://github.com/user-attachments/assets/f7b49dcb-47c8-4326-96d8-06634f75f920">
<img width="115" alt="Screenshot 2024-07-19 at 12 44 08" src="https://github.com/user-attachments/assets/8f0cb898-e3a0-45c2-a383-f0a838b7e0ff">

Similar designs are used in some fonts like BBC Reith fonts, for example https://x.com/bbchausa/status/1813944991544172844
<img width="544" alt="Screenshot 2024-07-19 at 13 33 05" src="https://github.com/user-attachments/assets/f898f57c-8381-4f19-9156-3d688b1c28b5">

**Comment by chrissimpkins** [comment]
Low priority for v3.0 but we will definitely take this if we can fit it in.

**Comment by MariannaPaszkowska** [comment]
From @NeilSureshPatel on Jul 30th: _"The short of it is the hooks look good now and I don't think any more design changes are required. I am still seeing some issues with anchors and kerning. Otherwise, things are looking good."_
@octaviopardo will review the anchors and kerning to double check that it's been fixed since.

**Comment by octaviopardo** [comment]
The issue with anchors that Neil mentions there is being discussed in #1060 (https://github.com/googlefonts/googlesans-flex/issues/1060) . 

Regarding kerning, he refers mostly to the yhook in opsz144 weight 1. I suspect they were not informed that that specific style is a super display style because one of his comments is that he struggles to see the differenc in between yhook and y (image attached, I think at 144 size are different enough), and in their report they display the glyph in multiple sizes. So they propose kerning to increase this difference and make it more obvious. In my opinion, not many changes are required. Still I have reviewed the kerning in that specific style and some of the surrounding ones.

![Image](https://github.com/user-attachments/assets/b7b80c9c-1493-4901-8447-50c0690390cb)
