### ISSUE TITLE
Review the bar of cent and dollar

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#997]
in opsz18 near weight 700 width 25 Grad 100
and also in the opsz144, wdth25, wght 1 Grad100

**Comment by chrissimpkins** [comment]
What is there to review?  Why are we reviewing it?

**Comment by octaviopardo** [comment]
pretty sure Marianna asked me to write down the coordinates here of an issue we spotted. it was corrected in the previous delivery

**Comment by MariannaPaszkowska** [comment]
It was dues to small interpolation bugs. Reviewed, fixed and merged in #1073

**Comment by MariannaPaszkowska** [comment]
Deltas changed in the `dollar` sign on GRAD masters: 

opsz 6_0; wght 520_01; wdth 25; GRAD 100; ROND 100, slnt 0
opsz 6_0; wght 699_01; _wdth 25; GRAD 100; ROND 100, slnt 0
opsz 6_0; wght 700_0; wdth 25; GRAD 100; ROND 100, slnt 0

opsz 18; wght 1; wdth 25; GRAD 100; ROND 0; slnt  10
opsz 18; wght 1; wdth 25; GRAD 100; ROND 0; slnt 0
opsz 18; wght 1; wdth 25; GRAD 100; ROND 100; slnt  10
