### ISSUE TITLE
Integrate shaping tests

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#998]
More details to follow...

Android UI strings, cover features in GSF, 

We should see fail on the CI.

**Comment by chrissimpkins** [comment]
Please follow with the additional details so that we can discuss this as part of v3.0. Ty!

**Comment by MariannaPaszkowska** [comment]
@Hoolean "Let's add them to the diffenator2 user strings" 
 - I agree that it is a good idea! 
@chrissimpkins qq: should we add those strings upstream to the diffenator2? Are there any licensing issues preventing us from adding them there?

**Comment by RickyDaMa** [comment]
Opened https://github.com/googlefonts/diffenator2/issues/163 to gather thoughts/feelings from maintainers

**Comment by MariannaPaszkowska** [comment]
We already have the shaping tests in place. Closing since the suggestion is made in the diffenator2 repo.
